[quote.epigraph, , Luke 10:16]
____
He who hears you hears Me, he who rejects you rejects Me,
and he who rejects Me rejects Him who sent Me.
____

== Journal of John Richardson

I was not above thirteen years of age when my father died,
yet the Lord was at work by His light, grace, and Holy Spirit in my heart.
I did not then know what it was which inwardly disquieted my
mind when anything that was evil prevailed over the good in me,
which it oftentimes did, for lack of taking heed to the Spirit of God in my heart.
I desired ease and peace some other way,
without taking up the cross of Christ to my own corrupt will,
and so I strove for some time (as no doubt many do) to
make merry over the just witness of God in my heart,
until for a season He seemed to be slain, or to have disappeared.
Then I took liberty, but not in gross evils which many ran into,
being preserved religiously inclined.
I sought after professors of Christianity and inquired
of them for my information and satisfaction,
seeking to find, if I could, anything that was safe to rest in,
or any true and solid comfort to my poor disconsolate and bewildered soul.
But I was afraid lest I should be deceived,
or take up a false rest in anything that was wrong or unsafe--
which fear was the great love and mercy of God to me.

I searched and inquired many times among those who were
but in the written letter and outward court,
where the veil remains over the understanding,
and the eye of the mind is not truly opened to see into
things that are hidden from all carnal-minded men.
So my state and afflictions were hidden from these,
along with the various deceitful workings of Satan,
and the strong temptations which I met with.
These blind guides could not see,
nor did they know how to direct me to the true Shepherd of Israel,
the Law-giver coming out of Zion,
who turns away ungodliness from Jacob and transgression from Israel;
for these had not truly experienced deliverance wrought in themselves out of the cloudy,
bewildered, and tempted state which I was in.

Oh that people would come to Him that has the eye salve,
with which if the eye be truly anointed, it will see things clearly as they are,
and not darkly, mistaking trees for men, and things terrestrial for things celestial!
Oh that they would buy gold, tried by the fire of Him who is called the Tried Stone,
elect and precious, laid in Zion for a foundation!
This is Christ whom the true church believes in and builds upon,
and so is enriched with His love, power, and virtue, which is better than outward gold.
Indeed, this is the anointing, which the true church has, and receives from Christ,
the Holy One.
And such as do truly put on His righteousness, purity, and holiness,
their clothing is better than that of fine linen outwardly.
Oh that all the inhabitants of the earth might be thus anointed, enriched,
and truly clothed,
that no more inward blindness or poverty may be found in the children of men,
nor the shame of their nakedness be seen any more!
Receive and learn these things, you that can,
of Him that is the faithful and true witness,
who always witnesses against the evil in man,
but always gives witness to the Father for the good in men which they say and think.
This is the Spirit of Him that was dead, and is alive,
no more to be known after the flesh (as the apostle gave testimony),
but is to be known inwardly and spiritually by the children of men.

It is He alone that opens the blind eye, and unstops the deaf ear,
and pierces into the soul that has been clouded and captivated, imprisoned,
and misguided, even in a wilderness state, seeing no way for deliverance,
like Israel in the land of Egypt, when the Lord Jehovah sent Moses,
a lively type of Christ,
and employed him in that great work of pleading
with and plaguing Pharaoh and the Egyptians.
For a time their burdens were increased, and their exercises more bitter,
until their deliverance was in a good degree accomplished,
which was not until the first-born of man and
beast was slain throughout all the land of Egypt.
The clear opening I had in the light of what is
to be understood and gathered from this is:
not the slaying of the outward man,
but a putting off or slaying the body of the sins of the flesh,
crucifying or putting off the old man with his deeds.
And as to the beast, all cruelty, lust, pushing, tearing, devouring, and savageness,
is to be slain or put away.
The corrupt or strong will of man, as well as what is bestial,
must be slain before man can come out from under the power of
him who is called the prince of the power of the air,
the spirit that rules in the hearts of the children of disobedience.
These things must be experienced before the children of
men can go forth rightly qualified to glorify God,
and to follow His dear Son,
whom He has appointed to be a leader and a commander of His people.
This is He, as Moses declared, who is to be heard in all things,
under the penalty of being cut off from the people,
or of having their names blotted out of the book of life,
or being deprived of the comforts of the Lord`'s holy presence.
Read this, you who have heard and understood what the Spirit says unto the churches.
These things I saw, after the true witness revived and arose in me,
and the light shone which had for a time disappeared or been clouded.

After much searching without,
amongst those who proved to me physicians of no value and miserable comforters,
I committed myself to a lonesome and retired life, breathing after,
and seeking the Lord in fields and private places,
beseeching Him that He would bring me to the saving knowledge of His truth.
And blessed be the name of the Lord now and forever,
I had not sought Him long with all my heart,
before I met with His inward appearance to me, in and by His Holy Spirit, light,
and grace.
But when the true Light did begin to shine more clearly,
and the living witness arose in my inward man, oh then my undone, bewildered,
and miserable condition began to appear,
and great and unutterable were my conflicts and distress!
I thought no man`'s condition upon the face of the earth was like mine.
I thought I was not fit to die, neither did I know how to live.
I thought in the evening, "`Oh that it was morning!`" and in the morning,
"`Oh that it was evening!`"
I had many solitary walks in the fields, and other places,
in which I poured out my complaints and cries before the Lord,
with fervent supplications to Him,
that He would look upon my affliction and the strong temptations I was under,
and that He would rebuke the adversary of my soul, and deliver it;
for I thought my soul was in the jaws of a devouring lion, and amongst the fiery spirits,
and under the weight of the mountains.
Read and understand the afflictions of your brother,
you who have come through great tribulations,
and have washed and made your garments white in the blood of the Lamb.
This is the beginning of that baptism which does save,
and of that washing of regeneration and renewing of the Holy
Ghost which the Lord sheds upon believers in abundance.
This is the blood which sprinkles the heart from an evil conscience,
so that the children of men, thus changed, may serve the living and true God.
This is the life which converts the world, even as many as are converted.
This is the virtue, life, and blood which makes clean the saints`' garments,
and inwardly washes them from all filthiness, both of flesh and spirit.
I found this was and is He of whom it is said,
"`By Him were all things made, and He is Lord of all.`"
Indeed, a man ought to be servant to Him, and all things in man subservient to Him,
who commands and comprehends all things,
and in whom all the types and shadows end and are fulfilled.
Read this, you virgin daughter, or clean church of Christ, the Rock of your strength,
whose name to you is as precious ointment poured forth;
for because of the savor of His ointments the virgins love Him,
and are under great obligations to obey and follow the Lamb of God wheresoever He leads.

Although I had seen many things, and had various openings, still great were my trials,
and many were the temptations I met with in those days.
I lived at a distance from Friends and meetings,
which made my exercises the more difficult, as will more fully appear hereafter.
Indeed,
some of the trials I met with in the course of my travels and
pilgrimage through this vale of tears and troubles were not common;
but the Lord helped me through them all, blessed be His name forever!

I now came to witness that Scripture fulfilled which says,
"`When the Lord`'s judgments are in the earth,`" or in the earthly hearts of men,
"`the inhabitants learn righteousness.`"
There was an aversion in my wild nature to the people in scorn called Quakers,
as also to the name itself;
yet when the afflicting hand of the Lord was upon me for my disobedience,
and when (like Ephraim and Judah), I saw my hurt and my wound in the light,
I bemoaned myself,
and mourned over that just Seed of light and grace in
me which I had pierced with my sins and disobedience.
Although that ministration of condemnation worked within and was glorious in its time,^
footnote:[In 2 Corinthians 3,
Paul describes the old covenant as "`the ministration of condemnation,`" and
the new covenant as "`the ministration of the Spirit.`"
Early Friends believed that,
just as the one ministration gave way to the other with
the coming of Christ in the fullness of time,
so this same process or change takes place in the heart of the believer.
First, the righteous law of God shines as a light upon the
transgressing nature and all of its fruits in man.
Then, as the root, branches,
and fruits of the fleshly man are yielded up to death on the cross,
the ministration of the Spirit comes to be progressively experienced,
wherein the Lord reigns in increasing freedom in and over the circumcised heart.]
yet great were my troubles,
which humbled my mind and made me willing to deny myself of
everything which the light made me know to be evil.

I was in great distress, and lacked peace and assurance of the love of God to my soul.
The weight of this greatly humbled my mind, and I knew not of any calling, people,
practice, or principle, that was lawful and right, which I could embrace or fall in with.
This was surely like the day of Jacob`'s troubles, and David`'s fears,
and I saw that "`the filth of Zion needed to be purged away by the Spirit of
judgment and the Spirit of burning`" (Isa. 4:4).
This is the way of the
deliverance and recovery of poor men out of the fall,
and the way whereby God restores the kingdom to His true Israel.
Read, you that can, and understand.
This was the day of my baptism into the love of God,
and into a true faith in His beloved Son, as also into a feeling of,
or a sympathy with Him in His sufferings, which were unutterable.
Then I found that the ministration changed;
for that which had been unto death was now unto life.
Yes, the ministration which was for condemnation unto the first birth,
when that was slain and in a good degree nailed or fastened to
the cross of Christ (which is the power of God),
then the good prevailed over the evil, and worked out the evil in the mind,
and also in the members, making all good and holy.
Indeed, the Lord`'s living power and consuming Word, when it works and prevails,
brings all into subjection, and makes holy the very heart or ground in men.

As there had been an aversion in me to the people in scorn called Quakers,
and also to their strict living, demeanor, plainness of habit and language,
so I learned none of these things from them.
But when the Lord changed my heart, He also changed my thoughts, words, and ways,
and there became an aversion in me to vice, sin, and vanity,
even as there had before been to the ways of virtue.
Having tasted the terrors and judgments of God because of sin,
I was warned to flee from such things as occasioned Christ`'s coming
"`not to bring peace upon the earth, but a sword;`"
oh, a sword indeed, yes, His heart-penetrating, searching Word,
which is sharper than any two-edged sword,
that pierces to the dividing asunder between flesh and spirit, joints and marrow.

Thus I came to see and abhor the evil in myself.
And when those who had been my companions in vanity now reviled me, or came in my way,
I was often moved to warn and reprove them.
Having tasted of the terrors of the Lord for sin,
I could not well forbear to warn others to flee such things as I had been judged for.
Then I came clearly to be convinced about the hat-honor, bowing the knee,
and the corrupt language, as well as finery in clothing;^
footnote:[See Introduction, pg. 10-11]
all of which, for conscience-sake, and the peace thereof,
I came to deny and take up the cross to, and I had great peace in so doing.

Though the blessed truth thus prevailed in me,
I was still not without great conflicts of spirit, temptations,
and trials of various kinds.
Nevertheless, my mind was resigned to the Lord, and my prayers were fervent to Him.
Truly He kept me and opened my understanding,
for I was afraid of being misled in anything, especially things relating to my salvation.
I came to be weaned from all my companions and lovers in whom I had taken delight.
All things in this world were little to me,
for my mind was much redeemed out of the world,
not only the corrupt and evil part thereof, but even from the lawful part.
So I became much given up to seek the Lord,
waiting upon Him to feel His presence and peace, and to know His will,
and receive power to do the same.

As my mind came to be thus brought into a dependent and waiting frame upon the Lord,
and to be stayed in the light,
and to experientially and feelingly partake of His love
and grace (which helped me against my weaknesses),
I found it to be sufficient for me, as I kept to it in all trials and temptations;
blessed be His name.
Then I came to see that all outward performances in matters of
religion do not avail nor render man acceptable to God,
but only as the heart comes to be truly given up to Him,
that He might not only purge it from defilement,
but also keep it clean through the indwelling of His Holy Spirit.
As nearly as I remember,
I saw clearly through these things before the sixteenth year of my age.

Between the death of my father and this time,
I took liberty to go among whatever people I would, my mother giving us great liberty,
and I began to attend the meetings of the Lord`'s people called
Quakers as diligently as my circumstances would well admit.
My mother was a woman well accounted among all who knew her for her
industry and fair dealing concerning the things of this world.
When my father died, she was left with five children,
the youngest being about three years old.
My father left but little of this world`'s goods to bring us up,
though my parents always had as much as kept them above contempt,
and nobody lost by them.
So I found myself under a necessity to work hard for my own support,
for the help of my mother, and for the education of my brothers,
especially since my only sister died soon after.
But being left on a grazing farm, part of which was tilled,
we did well as to the things of this world.

I cannot well omit mentioning one thing which became a great exercise to me,
which was this: My mother married one who was zealous for the Presbytery.
I was much against the marriage,
and told my mother I was afraid that she had too much an eye to what he had,
for he was considered rich as to this world.
And if she thought to augment our portion by so marrying,
then the hand of the Lord would be against her,
and a blasting or mildew would come upon even that
which we had gotten through industry and hard labor.
But if we kept faithful to the truth, and contented ourselves with our present condition,
then the Lord would bless us.
My mother confessed that, as to the worldly enjoyments,
it had never been better with her than now.
I must write with great caution; she was my mother, and a tender mother over me,
unwilling to offend me.
She had promised, as far as she well dared,
not to marry anyone with whom I was not satisfied.
But of their procedure in courtship and marriage, from this time forward,
I was entirely ignorant until it was accomplished.
And then, when my poor mother was married, her cry was, "`My son,
how shall I ever be able to look him in the face any more?
It will be such a trouble to him, he who has not at any time disobliged me;
for if I bid him go, he ran, and if I bid him do anything,
he did it with all his might,`" or to this effect, as several told me who heard her.
Having now married, what we had was mixed with my step-father`'s goods.
In time, my mother died first, and my step-father married again, made his will,
and when dying, left me five shillings for all my part.
As nearly as I remember, this marriage was in the eighteenth year of my age,
so that what I foresaw about the blast and mildew, came to pass.

I return to my account concerning the troubles that
attended me while in my step-father and mother`'s house.
After their marriage, we and what we had were removed to his house,
except for part of the livestock left on the ground.
I foresaw that I was likely to come to a great trial,
and was brought very low about the marriage,
and into exercise of mind concerning my own condition,
having so many conflicts of spirit that I was almost in despair.
Had not the Lord, in whom I believed,
risen in His power to rebuke the adversary of my soul,
I would have been overthrown and swallowed up in this day of trouble and
travail by the temptations that were cast out of the dragon`'s mouth.
But in an acceptable time, the God of love and pity saw me and helped me in my distress.
He who heard poor Ishmael when he cried from under the shrub,
giving relief to him and his mother when they had gone out from Abraham`'s house,
saw me in this great strait.

When I came to my step-father`'s house,
I found he was a man much given to religious duties,
such as saying grace before and after meals,
but I could comply with none of these things unless I
evidently felt the Spirit of Truth to attend therein,
and to open both the heart and mouth in such things.
For I had come to see clearly that there could be no true and acceptable
worship performed to God except what was in the Spirit and in the Truth;
nor could any pray aright,
except as the Spirit helped them and taught them how to pray and what to pray for,
and rightly prepared the mind,
guiding it in the performance of every service
which the Lord calls for from His children.
The first day I came to the house,
being called to the table with all or most of the family, I thought,
"`Is it now come to this? I must either displease my heavenly or my earthly father!`"
Then oh, the awfulness and deep exercise which was upon my spirit!
Strong were the cries that ascended to the Lord for
help and preservation that I might not offend Him.
My step-father sat with his hat partly off, and with his eyes fixed on me,
as mine were fixed on him in much fear.
He continued as long or longer than he used to be in saying grace (as they call it),
but said nothing that we heard.
At length he put on his hat again, to the wonder of the family; but he did not then,
nor ever after, ask me why I did not put off my hat.
Neither did he ever perform that ceremony again all the time I stayed with him,
which was above one year.
Thus the Lord helped me, renowned be His great name now and forever.

My step-father seemed for age, spirit, and understanding,
to be much more than a match for me (a poor shrub),
but the Lord--who caused the pillar of cloud to give light to Israel,
and brought darkness upon the Egyptians, and fought against them,
and for Israel--I believe smote my poor step-father,
so that he could not rise up against the power with which the Lord helped me.
Truly, it was not mine but the Lord`'s doing; to Him be given the attributes of praise,
salvation, and strength, now and forever.

I found my step-father was much displeased with my going to meetings,
yet I could not see a way to appease his displeasure,
except in perhaps being very diligent in his business, which I was,
even beyond my ability, working very hard.
It is almost incredible what my poor, little, weak body went through in those days,
but all would not gain his love.
Indeed, the longer I stayed with him, the more his love declined from me,
although I told him he need not be uneasy about my wages,
for I would leave that entirely to him.
I could not see what he could have against me, except my going to meetings,
and that was all he alleged.

When other strategies failed,
he offered me a horse to ride on if I would but go with him to his place of worship.
This I declined,
and so met with many a snub and sour countenance
from him upon my return on foot from meetings
(though I always returned as punctually as my body was capable of doing).
On first-day mornings,
my step-father commonly sent me a mile or two on foot into the fields to look at beasts,
horses and sheep,
I suppose with a design to weary me and make me incapable of going to meetings.
All of this I bore patiently,
and never (that I remember) complained that it was hard usage.
Then, after his errands, and to the great grief of my poor mother, I had to walk two,
three, four, five, and sometimes six miles to Friends`' meetings.
After walking fast, or running with my shoes under my arms for lack of time,
I have seen many Friends weep when they saw me come
into the meeting very hot and in a great sweat.
They could not forbear tears, being in part sensible of the hard task I had to undergo.
But the Lord`'s mighty power bore me up, and He gave me (as it were) hinds`' feet,
and enabled me to go through these exercises,
and to bear the burden in the heat of the day of my trials, both inwardly and outwardly,
which were many and various.

Now the last stratagem my step-father used to hinder my going to meetings was this:
he took me in his arms in a great show of kindness,
and said that if I would be as a son to him, I should find he would be a father to me,
also expressing something about his having no near kindred.
He said something to the same effect to my brother Daniel as well, who was an innocent,
wise, and clean-spirited lad.
I replied to him, "`If in making me your son,
you intend to hinder me from going to meetings,
or to oblige me to go with you to the Presbyterian meetings,
or anything that is against my conscience, I cannot, upon this foundation, be your son.`"
And, for the same reasons, I also refused to be his hired servant,
though he offered to hire me and give me wages if I would cease from meetings.
So when he saw that neither frowns, threatenings, hardships,
nor great promises of kindness could prevail with me,
he told me bluntly and roughly that I could stay no longer in his house.
I innocently answered that I could not help it if it must be so,
as all I could do would not give him content without hurting my conscience,
and the peace of my mind, which I valued above all mutable things of this world.
My poor mother heard my pleading with him, and how I offered to do my utmost for him,
by night or day, as I always had done, if he would be easy,
and let me have his acceptance.
But this was his reply: No, I should not stay in the house.

This troubled my mother so, that I was forced to leave my step-father, go to her,
and endeavor to alleviate her great sorrow by telling her that, if I was but faithful,
the Lord, I believed, would take care of me so that I would not lack.
And in order to more fully discharge myself,
I reminded her that she had entered into a marriage covenant with her husband,
and so she should endeavor to perform it,
and in everything to faithfully discharge herself as a wife ought to do to a husband,
and to leave me and all else, and cleave to him,
and to make her life as easy as she could.
I also told her never to send me anything that my step-father did not know of,
for I would not be free to receive it.

I write this partly that all who marry may take
special heed that it be done with great caution,
and under due consideration, and that the Lord be sought after diligently in it.
All must be done in His counsel, and not in name only, but truly in His fear,
and then it will doubtless be well with both husband and wife.
For these, being equally yoked,
will not only be true helpers in all things belonging to this life,
but more especially in things pertaining to the world that is to come,
and the good of the immortal soul.
Oh, how happily and peaceably do such live together in the Lord,
as they keep to that which thus joined them!

One remarkable event comes to mind, which hap­pened in this way: My step-father,
having come home from the Presbyterian meeting,
put my brother upon reading aloud the priest`'s text (as was his custom),
which that day had been from Daniel,
concerning his being cast into the den of lions for not regarding the king`'s decree.
Contrary to the king`'s command,
Daniel prayed to the God of heaven with his windows open toward Jerusalem,
according to his customary manner.
My step-father made his observations as my brother read, and very much magnified Daniel,
and said that the Spirit of God was in him,
but that there were none such as him in our days.
I acknowledged that Daniel was indeed an extraordinary man,
but in that there were none endowed with a measure of the same Spirit in our day,
I dissented from him.
I then gave my step-father a brief account of the many sufferings of
our Friends for the word of God and the testimony of Jesus,
some of which were past, and some present.
I especially mentioned the great sufferings of our dear Friends in New England,
where they met with hard imprisonments, cruel whippings, cutting off ears,
and banishment if they returned into New England anymore.
I likewise showed him how they put to death Marmaduke Stevenson, William Robinson,
William Leddra and Mary Dyer,
for no other cause but laboring to turn people from darkness to light,
and from the power of Satan to the living power of God, to His light, grace,
and Holy Spirit in their hearts, and laboring to bring the people from persecution,
pride, and every evil work and way, to live a self-denying, humble life,
agreeable to the Christianity they professed.^
footnote:[These four Quakers were put to death in Boston in 1659, 1660,
and 1661 by a Puritan government who had made just _being_ a Quaker a banishable offense.
Friends at this time suffered greatly under the
persecuting priests and magistrates of New England,
but most especially at the hands of Boston`'s governor, the infamous John Endecott.
Many were imprisoned, put in stocks, had ears cut off, or were stripped to the waist,
tied to carts, and whipped from town to town before being banished.
Returning to the Massachusetts Bay Colony after banishment was a capital offense.
For a full relation of these events, see William Sewel`'s
_The History of the Rise, Increase, and Progress of that Christian People Called Quakers._]
This was the service they were called to, and for it they deeply suffered.
And from this I inferred that there was something of
the Spirit of God in man in these days,
even as there was in Daniel and many more formerly,
which helped them and bore them up in their great sufferings.
My step-father confessed it was true that some suffered for good, and some for evil.
Then he said he had now lived to the age of about sixty-five years,
and although he heard us speaking of a Seed or light within, yet he knew not what it was.
I replied very meekly,
"`If you will hear me, I will tell you what it is,`"
which I did in the following words:
"`When at any time you have been under a temptation to put forth your hand to steal,
or to lie for advantage, or by provocation to swear, or allow any evil work or word,
have you not found something in you that has
shown you that you ought not to say or do so?
And when you have taken heed to this, and not said or done wrong,
have you not found great peace and inward comfort in your mind?
But if you have said or done wrong,
have you not found great disquietness and trouble of mind?
This is the inward Seed, light, or grace,
that God has placed in man to help and direct him,
which we the people of God called Quakers, do hold agreeably to the Holy Scriptures.`"
My step-father then struck his hands together, and confessed it was true.

A little time before the marriage of my mother,
I was brought into the public work of the ministry.
Concerning this I had many reasonings, being young (scarcely eighteen years old),
and naturally of a stammering tongue, which I could not overcome,
though I used all endeavors that lay in my power as a man;
all would not do until the Truth helped me.
But after my many conflicts, troubles, and temptations, the worst trial I ever met with,
and the most piercing sorrow I had been in since I came
to the knowledge of the blessed Truth was when,
through reasonings, disobedience,
and an unwillingness to comply with the Lord`'s requirings,
He in displeasure took away from me the comfort
of His holy presence for several months together.
Oh, the tribulations I met with in this condition!
No tongue is able to express,
nor any creature able to conceive the depth of the heart-piercing sorrow I was in.
I thought my state was as bad as Jonah`'s, for surely if there be a hell upon earth,
I was in it.
What greater hell can there be to a quickened soul and an enlightened understanding,
who has tasted of the goodness of God, and in measure of the powers of the world to come,
than to be deprived thereof, and to think they are fallen away from this state?
I could scarcely believe I should ever have repentance granted to me,
or be restored to the love and favor of God,
for I found that river of life dried up which before did make both me,
and the whole city of God, truly glad.

Being left under an apprehension of the Lord`'s displeasure,
and in part a partaker of the terrors of His wrath, I thought,
"`Oh, surely the very mountains and hills are not sufficient,
if they could be put into the balance and weighed
against the weight of my troubles and afflictions!`"
But as the Lord, by His judgments,
had brought me in a good degree out from the vice and vanity of this world,
so now by His judgments He made me willing to give up to His requirings.
And in my obedience to Him I began again to feel some comfort of love,
and the fellowship of the Spirit of the Lord in myself,
and in His people who were partakers of the like fellowship.

Now I return to the matter of my being turned out of my step-father`'s house.
When I saw I must go out, I thought it expedient to acquaint some worthy Friends with it,
lest any undue reflections should be cast upon the Truth, or Friends, or myself,
that if so, these Friends might be able to contradict them.
So I acquainted Sebastian Euethorp, and that worthy minister of the Gospel,
Ben­jamin Padley, two of the chief Friends in Ellington Monthly Meeting.
These men came to my step-father`'s house, and inquired the reasons why I went away,
and if my step-father had anything against me concerning the business he employed me in,
and whether I was not faithful and diligent in all his affairs he sent me about.
He confessed I was, and thought none could exceed me.
They said, "`Well then, what is the reason of the conflict between you and your step-son?
Is it about his going to meetings?`"
And when they understood his reasons (which it was not hard to do),
they expressed pity towards me that I could have no more liberty.
And they thought, as I was so diligent in his business,
if he perhaps would give me a little more liberty to go to meetings,
it would be an encouragement to me.
At this my step-father took offense and gave the good men rough language,
and asked what they had to do with him and his son.
He then bid them go home, and mind their own business, and said, in short,
that there was no abiding for me there.
At this the Friends were troubled, especially for my sake,
and then wondered how I had lived with him so long.
But Sebastian Euethorp told me, which was greatly to my comfort,
that my step-father had nothing against me, except concerning the law of my God.
This is the sense, if not the words, of these wise and good men,
which passed between them and my step-father, as they later expressed them to me;
for I was not there when they were together.

Though I pleaded with my step-father to let me
stay until I could hear of a place of employment,
he would not have it--though I was scarcely fit for any kind of service,
being almost skin and bones, as the saying is,
so that most who knew me said I would pine away in a consumption.
But turn out I must, and I did, though I was weak, poor, and low in body, mind, pocket,
and clothes; for I think I had but twelve pence in my pocket,
and very ordinary clothes upon my back.
Thus I took my solemn leave of the family, with my heart full,
but I kept inwardly turned to the Lord, and under Truth`'s government.
Many tears were shed when I left them, especially by my poor mother.
My step-father said little,
but appeared like one struck with wonder to see so much
love manifested towards me by the others in the family,
and so much wishing that I might not go away.

I came out upon the great fields before-mentioned, where I had had many solitary walks,
but none had been like this, for now I knew not where to go.
I then thought of Abraham, who was called out of Ur in the land of the Chaldeans;
but this was the difference between us--he was called, and I was forced out.
I had many friends, but I did not feel free to go to them,
not believing any had employment for me; for I was not of a forward,
but rather of a backward and shy disposition.
As I was walking in the fields, not knowing where to go or where to lay my head,
the sense of my weak condition came over me to such a degree
that it seemed as though my way was hedged in on every side,
inwardly and outwardly.
I thought myself like a pelican in the wilderness, or like an owl in the desert,
there seeming to me scarcely a man in all the earth in my condition.
In the sense and deep consideration of my present wilderness state,
I felt myself under a great oppression of spirit, and my heart seemed full,
like a bottle that needed vent.
I looked round about me to make sure none were near to see my tears or hear my cries,
and in the very anguish and bitterness of my soul, I poured forth my complaints, cries,
and tears, to the Judge of all the earth.
The Lord comforted me in this my deplorable state, and said to me,
as if a man had spoken,
"`Seek first the kingdom of heaven, and the righteousness thereof,
and all these things that you stand in need of shall be given unto you.`"
I then desired He would be pleased to show me the place I should go to,
and the Lord opened my way,
and showed me the house where I should go and abide for a time.
I said, "`Good is the word of the Lord.`"
I believed, and it was a great means to stay my mind, and to settle it in the Truth,
with full purpose of heart to follow the Lord and obey His requirings,
according to the knowledge and ability given me.

I went to this Friend`'s house in South Cliff (William Allon by name),
and I soon bound myself to him to learn his trade of a weaver.
After I was bound, I found this good man loved me,
and I loved him to the day of his death.
He often said he was blessed for my sake, and all that pertained to him;
for he was very poor, but he increased very considerably after I went to live with him.

Three things stood in my way of answering the Lord`'s
commands as fully as I sometimes should have done:
first, a painful disorder came upon one of my legs soon after I was bound apprentice,
which I (and others) thought was much occasioned by hard usage,
heats and colds in excess, even from my infancy.
The lameness held me about two years, and it much discouraged and disabled me.
The second hindrance was my low circumstances in the world, of which very few knew,
because the common thought was that I had rich
parents (which was not without some truth).
Few knew the difficulties I met with.
And yet, my truly religious master,
if he understood anything was upon my mind with
respect to visiting any meeting or meetings,
would say, "`Take my mare and go your way,
and be not uneasy either about the mare or the business; and do not hasten yourself.`"
Such acts of kindness made me often wonder how I might return sufficient acknowledgments,
and be duly grateful for his love.

I was diligent in my master`'s business, not serving him with eye-service, but faithfully,
believing it good and acceptable in the sight of God, and I had great peace in it.
My master never found fault with me for doing too little, but often for doing too much,
and would sometimes say, "`I think you will cleave to the weaver`'s beam!
Come off and let us walk into the fields and see how things are there.`"
The healing of my leg, I attribute to the great and good providence of God;
for in a short time after I gave up freely and
cheerfully to answer the Lord`'s requirings,
the Lord healed me of my lameness.

The third hindrance was my stammering tongue, and I cried unto the Lord,
believing that He was able to take away this impediment,
even as He had stopped the violent disorder in my body.
Several learned men had given their advice, and showed their skill,
which all proved ineffectual.
But I came to believe in Jesus Christ, and to press through all unto Him,
and to touch the skirt of His garment--that is,
the lowest appearance of His blessed truth and power--
in which I found true healing virtue to my soul,
and also to my body and tongue, even to my admiration.
I then came to speak plainly, not only in the testimony the Lord gave me to bear,
but also in my common interactions with men.

In those days I was under the dispensation of openings and visions, and thought myself,
as it were, upon Mount Pisgah, and saw into the Holy Land,
and into things relating to God and His heavenly kingdom.
I saw clearly into God`'s work and way of bringing man
out of the fall and alienation unto Himself again,
and into a heavenly state in Christ,
as man yields true obedience to the leadings and operation of
His blessed grace and Holy Spirit in the heart.
But under such dispensations it is of absolute
necessity that man be brought into true self-denial,
into a dependent frame of mind, and a resignation of his will to the will of God,
daily sitting as in the dust with respect to the motions and workings of the creature.
For all that is of man`'s working does but hinder the spiritual work of God in the heart.
And we must come truly to know all fleshly motions,
and the workings in man`'s own will and spirit, to be silenced,
in order to hear the voice of God, which is a still small voice.
Indeed, His voice is not to be heard in the noise and hurries of the world,
nor when the mind is busied with things agreeable to
our own corrupt wills and depraved nature.

Although I had clear sights into many heavenly things,
and also at times had comfortable enjoyments of the living presence of God,
yet I was in need of being more established in the unchangeable Truth.
In crying out to the Lord, I found that He inclined unto me and heard my cries, and,
as David said,
plucked my feet out of the mire and clay and set them upon a rock that was
higher than I. He established my goings and put a new song in my mouth,
even high praises unto the Lord for all His tender mercies to me in those trying times.
And now, being more crucified to the world and to the spirit of it,
I witnessed a more constant indwelling of His heavenly power and living presence, light,
and grace.
I came to be brought into stillness,
and found it was most agreeable to my condition to keep much in silence,
waiting upon the Lord for the renewing of strength,
that I might thereby surmount all temptations and trials with
which I might be tried (which were not a few).
These things are worthy of commemoration,
and proved great confirmations to me in the Truth in
those days of tribulation and great trials.
Read and believe, you that can, for they are faithful and true sayings.

After the Lord had healed me, He sent me forth in the work of the ministry,
and the first journey I took was southward into Lincolnshire, Nottinghamshire,
and through Coventry, and so to Warwick, to see William Dewsbury.^
footnote:[William Dewsbury (1621-1688) was one of the
earliest ministers in the Society of Friends,
and though he spent much of his adult life imprisoned for the testimony of Jesus,
he was considered by all to be a pillar and an elder in the house of God.]
He inquired which way I had come,
and I gave him an account of the particular towns and places I had passed through,
mentioning that Coventry was the last and the worst.
For at Coventry some of the rude people flung stones at
me with great violence as I was speaking in the meeting,
and had the Lord allowed them to hit me, they would surely have spoiled me.
But my faith in the Lord, and the strength of the Truth,
bore up my mind above the fear of what wicked men could do to me.
After William had heard my account, he fixed his eyes on me and said,
"`You must go back again to Coventry.`"
I appeared unwilling for two reasons: first,
because I thought I had cleared myself of that people; and secondly,
because I thought it not safe to run back into danger
unless I was satisfied the Lord required it of me.
But William was positive and said I must go, for there was a service for me to do there.
Upon a deliberate consideration, and seeking the Lord to know His will in the matter,
I felt my way clear to go back.
And indeed, I found that there was some service for me there,
for there had been a misunderstanding among some Friends in that city,
and so I was able to leave them nearer to one another than when I first met with them,
much to my satisfaction.

When I returned home from this, and indeed from all my journeys,
I took care (as far as my weak body was able) to give myself to business,
and not to loiter away my time, neither abroad nor at home.
My weak constitution would not well bear the weaving trade,
therefore I left it much against my will, and took up clock and watch work,
and many other things, in order to supply my necessities.
The Lord always allowed me as much time at home
as put me in a condition fit for traveling,
and then I was inclined to go and visit Friends.
Many things I omit, because I am not willing to swell my account too much.
But I traveled through most parts of England four times,
and twice through most parts of Wales,
between the twentieth and twenty-eighth year of my age.

After the Lord had opened my heart,
I came (in measure) to understand the Holy Scriptures,
and to have experience of that Holy Spirit in which the holy penmen had written them,
and a sympathy with the spirits and exercises of the righteous mentioned therein.
I took great delight in reading them, and having a good memory,
I could thereby better deal with opposing
priests and professors of several denominations,
with whom I had several disputes and reasonings,
both in Yorkshire and in other parts in my travels.
But through these disputes, and through much reading,
my mind came to be too much in the written letter,
and not altogether as much in Spirit and in power as it should have been.
Because of this, I met with a gentle caution from the Lord, which was thus:
I heard a voice from the Lord, as plain as if one had spoken to my outward ear, saying,
"`The fowls of the air lodge in the branches.`"
This being repeated to me,
I sought the Lord to show me what was the meaning of that voice which I heard.
Then the Lord, the mighty God, showed me (in His condescending love),
that the Scriptures, which were written as holy men were moved of the Holy Spirit,
sprung from the living root; yet those who rested only in the letter,
and came not to be acquainted with, and live in, and minister from, the same Holy Spirit,
are outward, dead, dry, airy, and foolish.

This gentle check was of great service to me,
not so as to make me decline from reading the Scriptures,
but that I should not have too much dependency upon them,
and to caution me against a neglect of waiting for the help of the Holy Spirit.
For indeed, the Spirit is the root and pure spring of all right and living ministry,
which alone can reach the heart and carry the true evidence to
believers that it is of God--which the written letter,
of itself, cannot do.
I tenderly desire that all concerned in the great work
of the ministry may not be ministers of the letter only,
but of the Spirit also, and may speak in the demonstration of the Spirit and of power.
"`Let him who speaks, speak as the oracle of God, and he that ministers,
do it as of the ability that God gives`" (1 Pet. 4:11).
This is the last and lasting ministry,
which is after the order of Melchizedek, and not after the order of Aaron.
This ministry is in Jesus Christ, the High Priest, the one offering,
who makes perfect forever all who come to Him through the drawings of the Father.
He is the one Lord, and there is but one true faith in Him,
and but one true and saving baptism into Him, or into the likeness of His death.
And as Christ died for sin, so we may truly die to sin;
and as He was raised by the glory of the Father, so we may walk in newness of life.
He is the heavenly High Priest, holy, harmless, separate from sinners, who was tempted,
and knows how to succor those who are tempted.
He is the advocate with the Father, the propitiation for the sins of all,
the true guide and comforter, the leader of them into all truth who obey and follow Him.
Though to the world,
He is a reprover and a swift witness against all ungodliness and unrighteousness of men.

My writing in this way,
from this gentle check from the Lord concerning the fowls and the branches,
is not with the least intention either to lessen the Holy Scriptures,
or to discourage any from reading them;
for I encourage all true Christians to be more conversant in them.
Yet my advice, kind reader, from your well-wisher and true friend,
is that you breathe unto,
and truly seek after the Lord for a measure of His holy and blessed Spirit,
who is the only key and the best expositor to open and truly expound them to you.
And it is by this same Holy Spirit that your mind and
understanding comes to be fitted and enlightened.
Indeed,
the whole vessel must be brought into a preparation to hold the heavenly treasure,
and not to mix the pure with the corrupt and impure.
For without the enlightening, preparing, opening,
and sanctifying gift of God`'s holy grace and Spirit,
man can neither know the heavenly power of God,
nor can he know the Holy Scriptures as he ought to know them.
And for this reason it has seemed good to God to hide these things from the learned,
wise, and prudent of this world, that they should not pry into,
nor find out the mysteries contained therein, unless they are sanctified,
and called of God thereto.
As no man knows the things of a man except the spirit of a man that is in him,
likewise the things of God are not perceivable by man
without the help of the Holy Spirit of God in man.

Thus the Lord opened to me the true meaning of the parable of the mustard seed,
in this time of my infancy in the ministry, with which He sent me forth into the world,
that my faith might stand in the Lord alone, who is the author and finisher,
as well as the giver of true and saving faith--even that faith
which "`works by love,`" and "`gives victory over the world.`"
It was by and through the power and efficacy of true faith
(which is the gift of God)
that many in former ages,
and many now, obtain a good report.
It was through this gift that worthy Abel, with his offering, was accepted of God,
although he was envied by his evil-minded brother Cain, and also by him slain.
The ever-memorable Enoch, through the virtue of this holy gift, walked with God,
and God Himself bore witness that Enoch pleased Him.
This man walked in faith and obedience even to the end,
so that he died not as men commonly do, but was translated,
or changed in a peculiar manner.
Come, read, you that can, and understand,
you that are redeemed out of the power of the first nature, and have overcome the flesh,
the world, and the devil in a great measure.
For you know that it is by the operation of this gift that the dead in old
Adam are raised to a new life and a new way of living in the new man,
through the power of the heavenly Adam, who is known to these to be a life-giving Spirit,
agreeably to Scripture.
Through faith the violence of fire was quenched, the mouths of lions stopped,
the sword turned back, and armies put to flight,
even those armies who were aliens or strangers to God,
and who fought outwardly against the Lord`'s people in that day.
And indeed, this sets before us, as in a mirror or figure,
how and what we are to overcome in this gospel day.
For in the gospel day we are not to fight with men, but with our lusts,
and to overcome sin and Satan,
which is as great a victory as that which overcame ravenous lions.
For it is sin and Satan that have power and
dominion over the wicked and ungodly to this day.

Consider now while there is time, you who read these lines,
whether Christ or antichrist does predominate in you,
whether grace or sin most abound in your mortal body.
Consider whether the Spirit of Truth, that leads into all truth, or the spirit of error,
that leads into all error and untruth, is the most prevalent,
and has the greatest place in your heart.
For to him to whom you are the most subject, and yield your members as servants,
his servant you are.
And to him to whom you give way and subject yourself,
his servant you will fully come to be in time,
and the wages due to his servants you shall have given to you at the end of your work.
Therefore consider in due time, while the day of your visitation continues unto you,
and while the Lord follows and calls you by His secret checks and reproofs,
by which He disquiets your mind.
For although you may take some pleasure in vanity and wrong ways when
you can get over the just witness of God in your own soul,
yet while it strives with you to convert and
gather you out of earthly and fading pleasures,
to set your mind upon heavenly things and take pleasure in them,
you will have no true comfort in all your lower enjoyments,
but rather condemnation and anguish of soul will attend
you until you either get over the witness in your heart,
or leave the evil.
This is the experience of the Lord`'s people,
who have been acquainted with the true inward warfare, and with the saints`' victory.
Learn to follow Christ by the footsteps of the flocks of His companions,
although it be through great tribulations,
for it is the way to have your garments washed and made white
in the mystical blood of the immaculate Lamb of God.
This is He, as John the Baptist said, that takes away the sins of the world.
Happy is everyone that truly puts on His lamb-like nature, His humility, righteousness,
and purity, and is covered with His Holy Spirit,
and lives and walks in and under the influence and direction thereof to the end of time.

[.asterism]
'''

[.emphasized]
John Richardson`'s long and fruitful life was truly a "`fragrance of Christ
among those who are being saved and among those who are perishing.`"
He remained a traveling minister as long as physical strength permitted,
passing several times through most parts of England, Scotland, and Ireland,
and crossing the seas twice to minister among the colonies in America.
He lived to be 86 years old, and even in his declining years,
his friends bore this testimony of him:
"`When his natural faculties were somewhat impaired,
and he was confined at home through old age and infirmities,
he appeared more and more heavenly-minded, and seemed to grow in the life of religion.`"

[.emphasized]
In 1740, when John Richardson was 73 years old, Samuel Fothergill
(then a young minister in the Society)
stayed a night in Richardson`'s home,
and communicated the following to his wife in a letter:
"`In the afternoon I rode ten miles to the house where the ark rests, i.e.,
John Richardson`'s, who went with me next day to Pickering.
The life of Truth arose wonderfully +++[+++in the meeting],
and then that Father in Israel took me home, where we sat up until almost daylight.
We then repaired to our respective lodgings,
but soon after five in the morning he came and sat by my bedside,
and though weak and very poorly, said he would accompany me ten miles to Malton.`"
