[quote.epigraph, , Luke 10:16]
____
He who hears you hears Me, he who rejects you rejects Me,
and he who rejects Me rejects Him who sent Me.
____

== Chapter I. A Brief Relation of William Richardson

It has been repeatedly revived in my mind,
to leave the following account concerning my dear father, William Richardson,
having seen something of his own in manuscript, concerning his convincement,
with remarks on some other things; but I being young when he died,
did not then much heed it, and when I would gladly have seen it for my own satisfaction,
I could not, nor as yet can meet with it.

As my father was early convinced of the Truth, a sufferer for it,
and bore a public testimony to it, I found it my duty,
as nearly as I could remember the contents thereof,
to leave this short account concerning him.
He was born at North Cave, in the eastern part of Yorkshire, in the year 1624,
of honest parents, and of good repute, and was educated in the Episcopal way,
being soberly inclined from his childhood; a lover and seeker after purity and virtue.
I have heard him say he gave his mind much to retirement, reading the Holy Scriptures,
and seeking after the Lord, especially in the fields, being by calling a shepherd;
and it pleased the Lord to open his understanding so clearly,
that he saw and longed for a more excellent dispensation to come.
He also saw that the priests were wrong, and generally proud and covetous,
so that he was weary of following them, and much weaned from them and all company,
except two or three men who met with him,
and spoke one to another concerning their inward conditions,
and what they had experienced of the Lord`'s dealings with them.
This was before they had heard of the name Quaker,
as it was in a short time after given to a people which the
Lord raised up to give testimony of the notable and ancient,
yet newly revived and blessed, dispensation of Christ`'s coming,
and manifestation by the Holy Spirit in the hearts of the children of men,
in order to enlighten, quicken, sanctify, and save them from darkness, death,
ignorance and sin, that they might be made capable of obeying,
worshipping and glorifying the great God and sanctifier of them.

As my father was thus waiting and looking for a
more general breaking forth of this glorious,
powerful, and Gospel day, which had in a good degree sprung up in his heart, he had not,
as yet, seen that worthy and good man, George Fox,
although he passed through those parts about that time;
but soon after came William Dewsbury, and at the sound of his voice,
I have heard my father say, he was exceedingly glad,
in hearing him declare the way to find the lost piece of silver,
the pearl of great price within, a Savior near,
who had been held forth by men to be at a distance.
But having left the dark watchmen, of whom they used to inquire,
they now met with their beloved at home, in their own bosoms;
renowned be the name of the Lord, now and forever.

Thus the hearing and receiving the ever blessed Truth, was as the seed,
or word of the kingdom, sown in the good ground, or honest hearts of men,
which took root downward and sprang upward, and brought forth fruit, in some thirty,
in some sixty, and in others a hundred fold,
to the praise of the great and good Husbandman.

My father was early raised to bear a public testimony,
which was living and acceptable to Friends,
but was so much attended with weakness of body for many years,
that he went little abroad in the work of the ministry.
He suffered patiently the spoiling of his goods, and imprisonment of his weakly body,
in the great and more general imprisonment; and not only believed in Jesus Christ,
but suffered for him.
He was a good neighbor, a loving husband, and a tender father over all that was good,
but severe to all that which was wrong, and was for judgment, without respect of persons,
and spared not even his own children; especially he was much concerned for me,
for he said I was the wildest of them.
As he lived well, and believed in Jesus Christ,
I doubt not that he has finished his course in the love and favor of God,
is entered into a mansion of glory, and is at rest with all the faithful,
who "`loved not their lives unto death,`" but rather hated them in
comparison of that endeared and unfeigned love they bore to God the Father,
and to Jesus Christ his dear and well-beloved Son, who died for them,
and also for the whole world.

He departed this life in 1679, aged about fifty-five years,
and was decently buried in Friends`' burying-place at Hotham, near Cave,
where he was born.
