== Chapter II

[.chapter-subtitle--blurb]
An Account of His First Visit to Friends in America.

Now the time came for my going into America,
having had a sight of it about ten years before.
I acquainted my wife therewith about a year before she died,
and found it was likely to be a very near trial to her.
She was a virtuous good woman, but was taken away, and left me three small children,
the eldest not above four years old, the youngest not much above one month old.
Having but little of this world, I reasoned much about going,
thinking my circumstances at present might excuse me: my intentions were good in it,
that I might not leave things in any way to the dishonour of the truth.
My youngest child was taken away when about a year old; and soon after, wherever I went,
while I was awake, it sounded in my ears several days and nights.
Now is the time, now is the time.
Providence so ordered it,
that my other two children were placed to mine and Friends`' satisfaction.

I went through many provings that no man knew of, but I believe,
when I am gathered to my place, I shall leave many brethren behind me in mutability,
who will read my lines in their own experience.
I would not have any to misunderstand me, for as to my outward circumstances,
I left no debt, neither was I in a way of going backward in the world;
for after I received the knowledge of the Truth,
I could not see what pretence I could have to religion, if any should lose by me.
I have often said, and been hearty in my intentions,
that rather than truth should suffer on that score, I would live upon bread and water,
and wear very mean clothes, and work very hard if I were able, and upon any mean,
but lawful calling.
It has been matter of wonder to me, how persons who carry any pretensions to religion,
dare run such great ventures, sometimes beyond their own bottom or abilities;
which to me has always appeared an unwarrantable risk,
and I apprehend pride and ostentation are much the occasion of it,
which are against truth, and men are no better for their greatness; for the more plain,
and the more humble we are, the more we resemble humble Jesus and his religion,
which he laboured to inculcate.
If any are lifted up, or aspire above their places,
let them consider well the foregoing paragraph.

Now I must leave my little children, and my very near friends, and native country,
and all for Christ and the Gospel`'s sake, without any sinister end or view.
I appealed to the Lord, in the simplicity of my heart,
that he knew I was willing to be at his disposal, and what he had favoured me with,
I could leave to him;
yet whether what I had was sufficient to defray mine
and my two little ones necessary charges,
was somewhat in my way; and to satisfy me in this doubt,
the Lord`'s voice sounded exceedingly clear to that sensation I was then endued with,
saying, "`Go, and be faithful, and I will bless you every way.`"
Oh! my heart seemed to melt, and my spirit to dissolve within me, and I said,
Good is the word of the Lord,
you have not failed me in any of my great straits and trials to this day;
I have great cause to trust in you; renowned be your most excellent name,
now and forever.

I parted from my friends with much brokenness of heart,
and set forward on my journey towards London, in order to take shipping there,
the 11th of the eighth month, 1700.
With my companions, Thomas Thompson, Josiah Langdale, John Estaugh,
and some other Friends, I went on board a ship in the river Thames,
and we had not been long there, considering our freedom about going in the ship,
when it opened clearly in my mind, in the light, That I must not go in that vessel;
and I said to the Friends, I could not go in her,
for I saw nothing but death and darkness there.
The account of what afterwards happened to the ship I had from two particular Friends,
in two letters from London to America,
wherein they expressed a thankfulness for our deliverance,
and magnified that hand which wrought it, and preserved us from going in that ship,
which was lost near the island of either Jersey or Guernsey, and, as it was said,
about seventy people were drowned.

I have seen a Divine Providence attend terrestrial affairs;
and I may mention some things that appear to be of but little importance to some;
and such as do not duly consider these things, may make a wrong application;
yet my travels have afforded a variety of trials and transactions,
which are in some things very peculiar,
and there is a willingness in my mind to favour some who
have been desirous I should leave a journal of my life,
as far as I can see my way clear in the Truth.

We went on board another ship called the Arundel, Splenden Rand, master,
in which we embarked the 17th of the ninth month, 1700, and after many storms,
and much sea sickness, not without some conflicts of spirit,
more than I am free to express, and a long passage,
being nearly sixteen weeks upon the sea, we arrived in the river Patuxent, in Maryland,
as near as I remember, the 5th or 6th of the first month, 1701, and my heart was glad,
and filled with acknowledgments and praises to the Lord,
for bringing us safely over the mighty waters.

We left the ship and master, who was a churlish, ill-natured man.
I was very weak and low, both in body and mind, when I landed, but the Lord helped me,
and made my journey and labours comfortable to many, as well as to my own soul.
After the first or second meeting we were at, John Estaugh being my companion,
as we came near a great house in Maryland, I espied a little white horse,
the sight of which put me in mind of a dream I had on board the ship before I landed,
in which I thought I got a little white horse, which carried me well, and many miles.
I said to the Friends with me.
Let us call at this house, which we did, and upon inquiry about a horse,
the man said he had none but a little white young galloway, as he called it,
which he was willing to sell, and told us, it carried him one day forty miles.
He asked eight pounds sterling for it, and I bade him five pounds sterling;
the man`'s wife coming up the passage, heard what I had offered,
and she said to her husband.
It is enough: so I had him, and a good horse he proved, and carried me,
by a moderate computation, four thousand miles.
I took this, according to the nature of it,
to be a favour from that great Hand which led me forth,
and till now has preserved me in the land of the living, to praise his ever-worthy name.

We set forward towards Virginia and North Carolina,
and found great openness in these two provinces among the people,
and a tender-hearted remnant of Friends scattered in these wilderness countries.
Although, as I said before, I was brought very low, yet the Lord, in whom I did,
and yet do believe and put my trust, raised me,
and many times filled my heart with his word and testimony,
so that sometimes it went forth as a flame of fire among the loose libertines,
who were proud and unfaithful, yet professors of the Truth;
and we had many large and good meetings.

One thing is worthy of notice; as I was speaking in a meeting in Virginia,
a sudden stop came upon me, and occasioned me to say, I cannot go forward,
whatsoever the matter may be, I know not; but giving over immediately, a Friend,
whose name was Edward Thomas, began to preach, who was but young in the ministry,
though an elderly man, and apt to be attended with reasonings.
He said after the meeting, he had sought to the Lord with prayers,
that he would condescend so far to his request, as to give me a sense of him,
and in so doing he would take that as a great strength and confirmation to his ministry,
in this day of many exercises and great fears; or much to the same effect.
Thus we see the Lord in his great mercy condescends to the low, weak, and as it were,
infant states of his children, like a tender father, and being our heavenly high priest,
is touched with a feeling of the infirmities of his people;
thanksgiving and honour be given to his most excellent name, now and forever.

During our stay in Virginia, being at a Friend`'s house, an ancient widow,
I observed several persons of note come into the yard, a store-house being near, to make,
as appeared afterwards, a seizure for rates for the government and priest.
Not being distinctly charged, but a mixed rate,
it occasioned Friends to be straitened about the payment of them.
Observing the priest to be there, and very busy, I asked what he was come about:
the Friend replied, they were come to make distress for the forty pounds per poll,
as they phrase it, which is forty pounds of tobacco, payable for every taxable head,
i+++.+++ e. all above sixteen years old.
There were along with the priest, the sheriff and constable for the government,
and several merchants of note as spectators.
Understanding the reason of their coming, I stepped out to the priest,
who seemed a topping brisk man, his temper in this case not unsuitable to his name,
which was Sharp; and desired him to be careful how he devoured widows`' houses;
he briskly replied, he did not; to which I as closely returned, that I found he did.
He denied my assertion, and said, the government gave him what he demanded and took;
to which I gave the following answer: Inasmuch as he did not anything for the widow,
for which he reasonably might require a reward,
I believed the government would not insist upon it for him,
if he would be willing to drop it, which in common equity I thought he should.
The priest, displeased with this modest reply, tartly answered, you are no Christians.
I told him, the charge was high and false, and he might more easily affirm than prove it;
wherefore I put the question, and asked him, why we were so charged by him;
to which he returned this insignificant answer,
that we denied part of the divinity of Christ.
I told him, he was a novice, and differed in his opinion from most of his brethren,
seeing it was a general reflection cast on us by most of his fraternity,
that we owned the divinity of Christ, but denied his manhood, which was false also;
therefore I demanded of him, to prove what part of the divinity of Christ we denied;
in which if he failed, I should look upon him as a false accuser,
and those present would, I hoped, be my witnesses.
He shuffled and declined answering, though I urged him as much as possible;
and to cut the matter off, he asked from where I came.
The sheriff bid him give me a verse in Greek; I told them,
I mattered not meddling in that,
for as the English tongue was best understood by those present,
I thought it would be best to keep by it.
I told him, I was of Old England; but still reminded him of proving his assertion,
which I looked for from him; but instead of that, he asked,
what part of Old England I came from: I told him Yorkshire;
and bid him produce his proofs, as before urged, but still evading the matter,
he desired to know from what place.
I told him, I was born at North Cave; and, said he, I was born at South Cave,
and my father was minister there many years, his name was Sharp,
and there is but a mile difference between those places: I said it was a long one.
No sooner was this over, but the priest, transported with my being his countryman,
began hugging me to such a degree, that I was quite ashamed of him.

When I had got clear of his embraces, though not without some difficulty, I asked him,
if he esteemed himself a minister of Christ: he answered, yes,
and lawfully called thereto.
I told him, if he was a Gospel minister, as the Gospel was free,
so should his ministry be free; and turning to the people there present,
I told them I would not have them deceived,
for they might understand he only possessed his place
by virtue of a law in that case provided,
and his call and ordination was only such as had been conferred upon him for a fee,
which made him require pay for what he did, and indeed where he did nothing,
which was highly unfair;
wherefore they might upon consideration find he was but a minister of the letter,
which was dead, and not a minister of the Spirit and Divine Power;
from which he did not offer to clear himself, though I urged him thereto.
Then I asked him,
from which of those odious characteristics that the
false ministers were branded with in the New Testament,
he would clear himself: which I then enumerated to him; The sheriff said it was so;
and then said, Mr. Sharp, answer the man, for the question is very rational,
and you ought to answer him, and for honour-sake clear yourself of those odiums,
if you can.
But he would not offer to meddle with it; wherefore I told him, to mind for the future,
not to charge any man or people with more than he could be sure to prove;
for it was highly scandalous.
It being now meeting time, I asked him to go there; but he refusing, said he dared not;
so we parted.

Having visited Friends here, we returned back for Maryland and Pennsylvania,
and we found a great many who loved to hear the testimony and doctrines of Truth,
but too few who took up the cross daily, and followed Christ in the way of self-denial,
and knew the thorough work of regeneration,
so as to have their garments washed and made white in the mystical blood of the Lamb.
These are not polluted with the sins and iniquities of the world,
who have experienced this blood to sprinkle the heart from an evil conscience:
these are capable of serving the living God;
and coming from the laver or pool that truly washes, there is none unfruitful,
but every one bearing twain, and they are inwardly clean and fruitful to God,
and walk with him,
whose bright and shining lives are also fruitful to the world that will receive them.
Read this, you that have known something of the work of conversion,
and consider the great difference there is between the bright lives of the virtuous,
and the dull and cloudy lives of the vicious, and be sure you look well,
which of these you most resemble in yours.

When we came into Pennsylvania, my companion before mentioned, whom I loved well,
told me he must go back to Virginia.
It became an exercise to us both, for I could not see my way clear to go back,
having been twice through that province.
When no other way appeared, but that we must part,
for my way appeared clear for the Jerseys, Long Island, Rhode Island and New England,
I held it needful that we should call the Friends
and elders of Philadelphia and thereabouts together,
to let them know how we parted, for we parted in much love and tender-heartedness;
that if any reflections should be cast upon the Friends there concerning us,
because of our parting, they might set those things in their proper light;
so taking our leave of our dear friends in these parts,
I travelled without any constant companion.
Sometimes I fell into company with Elizabeth Webb and Sarah Clement,
who were virtuous women, and lived near the kingdom,
and were of good service in their travels, and grew in the Truth, of which,
while with them, I was sensible.
We travelled under great care and circumspection,
both for our own good and avoiding offence, as became our places and holy profession,
that in all things we might adorn the Gospel of the kingdom,
a dispensation of which was committed to us to preach to others.
I had good service for the Lord, and great satisfaction in my own mind in these parts,
the Lord helping me by his mighty power through all my trials,
as my heart was devoted and resigned to answer his requirings.

I had great openings in several places in New England, and it appeared clear to me,
and sometimes I spoke openly of it,
that the Lord would gather a great people to the
saving knowledge of the Truth in his time,
notwithstanding what many of our Friends had suffered in
these parts from the predecessors of the present inhabitants,
for the name of the Lord and the testimony which they held.
The view of the state of these things,
especially the great sufferings of many of our faithful Friends,
put me in mind of this saying, The blood of the martyrs is the seed of the church;
and in this case, I believe it will be fulfilled in its season.

One passage happened, which I think not fit to pass over in silence.
A man who was brother to a Presbyterian priest,
came into a meeting in the eastern parts of New England, in order to oppose Friends.
He had often been very troublesome, as Friends said,
and in the beginning of the meeting he desired to have liberty to ask some questions.
Being a stranger, and not having so much as heard of the man,
and none making reply to him,
I felt a liberty in the Truth to return the following answer in behalf of the meeting.
That I did apprehend it was the desire of Friends,
inasmuch as the meeting was appointed for the worship of God,
and not for asking questions, or for controversies,
that the chief part should first be answered;
and I also thought the meeting would be willing, in the conclusion,
to give him liberty to ask the questions,
if his intent therein was for information or satisfaction, and not for contention.
Friends were silent, and the man submitted to what was proposed,
and a good meeting we had, the Lord`'s heavenly power and living presence being with us,
and the substance was felt among us, and exalted over all the shadows and types;
and Christ the true bread and living water, the light and life of the world,
was exalted that day; and the mighty God and Father, with his beloved Son,
through the help of the Holy Spirit, was glorified, who is worthy forever.
Near the conclusion of the meeting, the man began to speak well of what he had heard,
particularly touching water baptism, which he said, he had nothing to object against;
but as to the sacrament, as he called it,
because little or nothing had been said about it, therefore he concluded,
we either denied or disused it; or words to the same purport.
I stood up and said, I did not remember that the word sacrament was in all the Bible;
but supposed he meant the bread and wine; he answered he did.
I asked him whether he was of the same mind as the Episcopal church;
if not of the same mind, he might say so; for they say,
the bread and wine is an outward and visible sign of an inward and spiritual grace, etc.;
what said he to it?
He was some time silent; then I asked him, how long he thought that sign was to continue?
He replied, to the end of the world.
I answered, he did not read in all the Bible,
that the Lord had appointed any figure or sign but what was to end in the substance,
which is to be witnessed and enjoyed in this world,
and not put off to the end or conclusion thereof, as his argument seemed to declare,
by his urging,
that the sign of that divine substance must remain till the end of this world.
I asked him what he could answer to that: he turned off with only saying,
I was too great a scholar for him, and so he would not meddle with me.
He was then silent, and there being many people,
I had a fine opportunity to open to the tender-hearted and Friends present,
how that was at best but a sign, which the people eat and drank outwardly,
in remembrance of Christ`'s death until he came;
but that I could now prove plenteously from the New Testament, that the substance,
the grace, was come, and urged many proofs out of the Scriptures to the same purpose.
What I said so reached a good-like old man, a Presbyterian, that he confessed with tears,
he had heard much said upon that subject, but had never heard it so opened before;
and said he believed I was in the right.
The meeting broke up in a good frame, and Friends rejoiced that Truth came over all,
and the contentious man was silenced.

When the meeting was over, the goodly old man took me to the door,
and asked me what a man should do in case of a solemn league and covenant,
he being entered into it.
I told him I needed not to direct him,
for he had that in himself which would show him what he should do;
for if one should make an agreement or covenant with hell and death,
in the time of ignorance and darkness, and now the true light discovered it to be so;
the same light which discovered and manifested it to be wrong,
as he was faithful to the same, would show him how and when to break it,
and every other wrong thing; to which light I recommended him,
and bid him take heed to it; which, he said he hoped he should;
and so I left him with tears on his cheeks, and passed on.

I omitted one thing which happened in that part of New England,
near New York and Long Island, although I was twice backward and forward,
yet to be brief in my travels through those countries,
intended to make one account serve.
As I was speaking in a meeting, there came a great damp over my spirit,
and in that time came into the meeting several men,
occasioned by a topping and great man in the world,
who had given them an expectation that they should hear how he would oppose the Quakers;
but in a short time Truth rose, and Friends generally heard a man say to this disputant.
Why do you not speak?
He hushed him with saying, The man is upon the subject which I intend to oppose them with.

After some time the man was urged again to speak to me, with a Why do you not speak?
We heard him say, The man has opened the thing so as I never heard it before,
and I have nothing to say; and to his own, and the wonder of his neighbours,
he sat down upon a seat near the door, and wept tenderly;
so it was a good time to him and many more, for the Lord`'s mighty power was among us.
In my return from my journey in the eastern parts of New England,
the same man desired me to have a meeting at his house;
and after due consideration and the approbation of Friends, who desired it might be so,
when they knew it was his request, a meeting was appointed,
and I heard there were likely to be at it a great many of
the higher sort of Presbyterians of his neighbourhood.

I went to the meeting under no small concern of mind,
but when I was come into the great house,
I was very much affected with the wise conduct of the man,
to see in what excellent order he had placed everything,
so that I could not find wherein anything could be amended;
and a heavenly meeting it was, without any opposition.
At the breaking up of the meeting, this tender man,
whose heart was broken and opened by the power of Truth, said audibly,
his heart and house were open to receive me, and such as me,
let all say what they would to the contrary.
But what the subject matter was at the first meeting when he came in, I have forgotten;
it was enough and that we remembered we had a good heavenly meeting,
and were truly thankful for the same to Him who was the author thereof.

I and some other Friends being in our passage by water in a vessel bound for Rhode Island,
and meeting with high and contrary winds,
we put into a creek some miles distant from Rhode Island,
and desired the people to procure us some horses to ride on,
and we would pay them anything that was reasonable,
but hoped they would not make a prey of us, for we were strangers,
and they ought to do to us as they would be done by, if they were in a strange land,
as we were.
There came up to us a goodly old man, and asked us what people we were,
if we were not Quakers?
I told him we were in scorn so called, but we did not much mind names,
for there was but little in them.
He was a brisk talking man, and said,
There was a man here lately who said he was a Quaker, and borrowed a horse,
and when he was gone some miles from this place, he offered to sell the horse;
I know not, said the man, but you are such.
I returned this answer to the reflection;
That that was a great proof we were an honest and reputable people where we were known,
for when a man is so wicked as to become a notorious cheat,
he will cover himself under the best name he can think of,
otherwise he might have said he was a Baptist, or a Presbyterian, or an Episcopalian,
and desired you to lend him a horse; but you mind not these names,
neither does the wicked man think he can pass so well under any of these last,
but under the first; and the reason of it I leave you to judge.
The old man asked no more questions, but used his endeavours to get us horses,
and a man and horse to go with us, to have the horses back again,
and we were well mounted; but before we set forward,
he took me to his house and was very courteous,
for though we had reserved some food in as short a time as well might be,
he invited me to drink, and brought of his apples and beer,
which he would have my friends to partake of, for he said, and we found it true,
it was but a poor inn.
The old man and I parted very lovingly,
and I gave him a piece of money to show my gratitude
for his civility and good service to us.
The people looked upon us as some great wonder, for I heard one say, Are these Quakers?
Well, said he, they look like other people.
How we had been represented, and by whom, it is not hard to gather,
for it is very apparent,
that the same spirit and the same enmity continues
in some of the inhabitants of that country,
of which our Friends formerly felt the severe effects.
They are since somewhat moderated by the government there,
which is of a more mild and Christian disposition; although I am well assured,
that many of the more conscientious and thinking
people in those parts of the world begin to see,
and many will see and understand in time, that hanging and taking away lives,
for the sake of religion, is opposite to Christ,
and the nature of the true religion which is wrought in man by the operation,
quickenings, and indwellings of the Holy Spirit.
As it is regarded and followed,
it leavens and brings the soul of man in some degree to put on the purity,
heavenly image, and nature of Christ, which is love, praying for enemies,
and is not for destroying, but saving lives;
how far the reverse will agree with that religion taught by Christ,
and practised by him and the apostles, I would have all seriously consider in time.

While we were in Boston,
when one of the afore-mentioned worthy women was declaring excellently,
both with good utterance and voice, and good matter,
as the manner of the inhabitants of Boston had been for many years to encourage,
or at least permit a rude mob to bawl and make a noise, so they did now,
that it was hard to hear so as to understand distinctly what the Friend said,
although she spoke plainly and intelligibly.
It did very much grieve me to see the ignorance and
darkness of those high professors of religion,
and when the Friend had done, observing there appeared men of some note in the world,
I requested them to hush the rabble, for I had something to say,
which I desired them to make known to the governor and chief men of the town;
so they soon quelled the noise.
Then I told them, that in case we were as erroneous as some might insinuate we were,
that was not the way to convince us of our errors, neither to bring us out of them,
but rather to establish us in them; and that was not the way for them to gain proselytes,
but the way to lose many from them, and increase dissenters;
for what convincement could there be by noise and clamour, and hooting,
as if they would split their own lungs.
I had come a great way to see them, and what character could I give of them.
I never thought to have seen so much folly among
a wise and religious people as I now saw:
tell the governor and chief men of the town, what the Englishman says;
for I am ashamed of such doings.
It had a good effect, for when I came after, we had quiet meetings;
and I understood by a letter from Daniel Zachary, of Boston, to Old England,
that the governor said I was in the right,
and ordered that peace should be kept in Friends`' meetings there;
and I never heard to the contrary but it is well yet as to that.
We had great reason to be truly thankful to the Lord for these and all other mercies,
that He, the fountain of all good, is pleased to favour us with.
As an instance of the Lord`'s mercy to many poor sufferers,
and to show the implacable envy of these people to Friends, the case of Thomas Maulham,
of Salem, may suffice, in some measure,
who was a great sufferer in the time of hot persecution.
When the persecutors had stripped him of almost all he had; not content with that,
they came with axes, and hewed down all the apple trees in his orchard,
which was a large one, and left the stumps about the height of a man`'s knee.
As Thomas Maulham said, they took the way, as they thought, to ruin him,
but the Lord turned it into a blessing, for the trees grew to admiration,
and came to bear fruit abundantly, and a finer orchard I have not seen in all my travels,
for the size of it; let the Lord be sanctified by all his people,
and admired by all them that believe.

I went with several other Friends from Salem Yearly Meeting,
which was a large and good meeting, towards Dover, and coming to a river,
a Friend took my horse, with two more, into the boat,
and by the time I came to the river side, the boat was sinking,
and the ferryman made a lamentable cry, saying.
The boat is sunk, and we shall be all drowned.
It was so ordered, that there was but one Friend in the boat with the boatman,
and I do not remember that ever before now my horse was in any boat and I not there;
which I looked on as the mercy of a kind Providence to me,
and to several other Friends in company.
Hearing the noise and the floundering of the horses when tumbling into the water,
I called to the men to be sure to take care to free
themselves of all the tackling of the horses,
as bridles, stirrups, etc., and catch hold of my horse`'s tail,
and he would bring them both on shore; but if they trusted to the tackling,
when the horses swam, they would fail them, unless very strong;
and to hold by the bridle was the way to drown both horse and man.
This advice was given while they had the horses in their hands;
and the boatman being a lively youth, took my advice, caught hold of my horse`'s tail,
it being long, which I ever approved of among rivers, and calling to my horse,
he came quickly with the man ashore, but left the honest old Friend, Ezekiel Waring,
to whose house M`'e intended to go that night, in the river floating to the neck,
a hundred yards from the shore by computation, yet watchful Providence did so attend,
that his life was preserved to a wonder.

He missed taking my advice, and caught hold of the stirrup, and the girth broke,
as they are apt to do if they be when the horse begins to swim,
which brought off the saddle and pillion, and the oar of the boat and his hat,
which with the pillion-seat being in his arms,
just bore up his head above water for some time.
His poor wife seeing the danger to which her husband was exposed,
fell into a fainting fit; there being neither house, man, or boat,
to be seen on this side of the river but ourselves and the boatman,
and the stem and stern of the sunk boat full of water.
There was a house on the other side of the river, which was half a mile over.
The ferryman did his best to get a boat or canoe, and although it began to be dark,
yet he found a canoe, which is made of a fine piece of timber,
hollowed in the form of a boat, and generally will carry but two or three or four men.

Coming to us, he asked if Ezekiel was alive: I told him he was, but very weak,
for I had often heard him blubber in the water; I encouraged him,
that he might not faint in his mind, for I told him,
I yet believed his life would be preserved; he would very faintly say, Unless help came,
he could not hold it long.
I went on by the waterside, and laid me down often on the land,
not much regarding wet or dirt, sometimes tumbling over logs of wood and limbs of trees,
for so it is in these uncultivated places,
and I directed the man with his canoe where the poor Friend was,
as nearly as I could tell by my last observation,
and desired he would turn the stern of his canoe to him,
as he could not lift him into the canoe;
neither to let him lay his hand upon the broad side of it, but upon the stern,
lest he should overset it, and they be both drowned: he did so,
and brought him gently on shore, to the great joy of his loving wife and of us all.
The boatman, as he owned, had found my counsel good,
and therefore would have me tell him what he must do now.
I bid him fetch the boat to shore by the fowler or rope,
and then go and carry Ezekiel in the canoe to the inn on the other side of the water,
that he might dry, warm, and refresh himself until we came;
in the mean time we cleared the boat of water, which, when done,
we put two horses into it, and I towed my horse at the boat`'s stern,
to make room for several, especially the good women before mentioned,
who were at this time in my company, and not without their exercise any more than myself.
We got well over, and then the ferryman and Friend on the other side,
brought the horses that were left, being three, which were enough for the boat,
and proved too many the first time.
We found the good old Friend finely and well recruited,
and got to his house about midnight, where we were glad,
and our hearts were full of praises to the Lord for
this great and eminent deliverance and preservation.

In this first visit, while in Rhode Island, I met with something worthy of your notice,
if you are such a reader as I wish you may be, which was thus: Being in Rhode Island,
several Friends came to me in some of the intervals of the Yearly Meeting,
for it held several days, both for worship and discipline,
to inquire whether it was usual in our part of the world to let the young,
and such as had appeared but little in testimony,
come into the meetings of public Friends: I said, "`Yes, if they were of clean lives,
and what they had to say, approved;
and it was very likely such might need advice as much as those
who were come to more experience in the work of the ministry,
if not more:`" this was some means of enlarging the
said meetings of ministers now coming on.
When I came into the meeting, several of the elders desired me to go into the gallery,
which I refused, the concern upon my mind being so great,
I thought it was enough that I could but get into the house,
and sit down among the lowest rank.

This meeting was one not to be forgotten,
because of the eminent visitation from the Lord that was upon us in it.
I have not often seen the like.
I question if there were any dry cheeks for some time in it;
and the manner of the working of the heavenly power was remarkable,
in order to the sanctifying and preparing vessels for the Lord`'s use.
He broke us down by his judgments from following flattering flesh,
and the pleasing vanities of the world, and the subtle baits of Satan,
and by the tenders of his love, engaged us to follow the heavenly and inward calls,
knocks and reproofs of his Holy Spirit, and to obey the dictates of the same.
When the Lord prepares in a good degree for this work of the ministry,
many have been unwilling to give up and obey,
until they have tasted of the Lord`'s displeasure, and in part of his judgments,
which have brought them into submission; after which they went out,
sometimes with their lives in their hands, and became a wonder to men,
bearing their reproach, and sometimes appeared in great congregations,
sometimes in noises and tumults, and sometimes were in watchings and fastings,
in weariness, hunger, and in cold, with much more,
for the name of the Lord and his testimony, and for the enjoyment of peace,
and his internal presence, who separated us to this work by the Holy Spirit.
And it is by our abiding faithful to the same,
that we are preserved in a capacity of persevering through all to the end,
to the mutual help and comfort one of another, and renown of the name of the Lord,
who is worthy now and forever.

We also had a very large meeting on this island in an orchard,
where I had good service for the Lord:
I remember I was much concerned about the two ministrations, namely,
John`'s baptism with water, and Christ`'s with the Holy Spirit,
it being clear from John`'s words,
that he saw to the end of his own dispensation when he declared, he must decrease,
but Christ must increase;
which is generally understood to relate to their differing dispensations.
The first was to baptize unto repentance, the other to the purging of the floor,
and burning up of that which was combustible, i.e. the chaff and stubble,
which the Lord`'s baptism burns up inwardly, and which no elementary thing can do;
for if all the eatings, washings, observations, and ceremonies under the law,
although commanded and enjoined to Israel by the Lord,
could not make the comers thereunto perfect,
how should these or any of them now perfect the Gentile world when not commanded,
as they never were to us?
What I had upon my mind, as I received I went through with, and showed the beginning,
use and end of the watery dispensation,
and the use and continuance of Christ`'s spiritual baptism to the end of the world.
The meeting broke up, and Friends went into an upper room in an inn;
but I felt such an exercise upon my spirit that I could not eat,
but desired Friends to be easy, and I would cat as soon as I could;
and while I was walking over the large chamber alone,
there came up three men whom I knew not, or what they were,
but it sprang livingly in my heart to set my eyes on them in the Lord`'s dread,
and so I did.
They passed away, and I was told afterwards,
that they were three Baptist preachers who had been at the meeting, and came to see me,
with a design to have a dispute with me; but, they said, I looked so sharply,
they dared not meddle with me.
Thus the Lord in a good degree wrought for me, blessed be his worthy name forever.

Now I leave the account of my travels in those parts, and enter upon my second,
with my honest companion, James Bates, who was born in Virginia,
and travelled much with me through many provinces, and some islands,
and we had good service together.
It was much with me, when on Rhode Island, to visit Nantucket,
where there were but very few Friends; Peleg Slocum, an honest public Friend,
near Rhode Island, intending to carry us in his sloop to Nantucket that night.
He thought we had been close in with our desired landing place, but we fell short,
and night coming on, and having but one small canoe to put us on shore,
which would carry but three people at once, we went on shore at twice,
and left the sloop at an anchor.
It being dark, we thought we were going up into the island among the inhabitants,
but soon found that we were upon a beach of sand and rubbish,
where was neither grass nor tree, neither could we find the sloop that night,
though we sought it carefully, and hallowed one to another till we were weary,
so that we were forced to settle upon our little island, from the centre of which,
one might cast a stone into the sea on every side.
Here we stayed that night, not knowing but the sea, when at the height,
would have swept us all away, but it did not; there I walked, and sometimes sat,
until morning, but slept none; at last the morning came, and the mist went away,
and we got on board again, and reached the island about the ninth or tenth hour.

The master was willing, at our request, to land three of us, namely, me, my companion,
and Susanna Freborn, a public Friend, who had had a concern upon her mind for some time,
as she signified to Friends in Rhode Island, where she lived,
to visit the few Friends in Nantucket,
and Friends thought this was a proper season to pay that visit.
She was a woman well beloved, and in good unity with Friends.

We landed safely, and as we went up an ascent,
we saw a great many people looking towards the sea, for great fear had possessed them,
that our sloop was a French sloop loaded with men and arms,
who were coming to invade the island.
I held out my arms and told them, I knew not of any worse arms than these on board.
They said, they were glad it was no worse, for they had intended to alarm the island,
it being a time of war.
I told the good-like people, for so they appeared to me, that Peleg Slocum,
near Rhode Island, was master of the sloop,
and that we came to visit them in the love of God,
if they would be willing to let us have some meetings among them.
They behaved themselves very courteously towards us, and said, they thought we might.

We then inquired for Nathaniel Starbuck, who,
we understood was in some degree convinced of the truth,
and having directions to his house, we went there.
I told him, we made bold to come to his house, and if he was free to receive us,
we should stay a little with him, but if not, we should go elsewhere;
for we heard he was a seeking religious man, and such chiefly we were come to visit:
he said, we were very welcome.
By this time came in his mother Mary Starbuck,
whom the islanders esteemed as a judge among them,
for little of importance was done there without her, as I understood.

At the first sight of her it sprang in my heart.
To this woman is the everlasting love of God.
I looked upon her as a woman that bore some sway in the island, and so I said,
and that truly, we are come in the love of God to visit you,
if you are willing to let us have some meetings among you.
She said, she thought we might; and further said,
there was a Non-conformist minister who was to have a meeting, and they were going to it,
and she thought it would be the best way for us to go with them to the meeting.
I showed my dislike to that for these reasons; first,
we did not need to hear what that minister had to say,
because some of us had tried them before we came there,
meaning the Non-conformists of several sorts, and if we should go,
and could not be clear without speaking something in the meeting, he might take it ill.
But as we understand there is another meeting appointed
at the second hour for the same man,
and as we look upon ourselves to stand upon equal
ground in a religious capacity with other dissenters,
if we should appoint our meeting at the same hour,
then the people will be left to their choice to which meeting they will go.
The woman approved of the proposal, and said, Indeed that was the best way.
The next consideration was, Where shall the meeting be?
She paused awhile, and then said, I think at our house.
I from there gathered she had a husband,
for I thought the word our carried in it some power besides her own,
and I presently found he was with us.
I then made my observation on him, and he appeared not a man of low abilities,
but she far exceeded him in soundness of judgment, clearness of understanding,
and an elegant way of expressing herself, and that not in an affected strain,
but very natural to her.

The meeting being agreed on, and care taken as to the appointment of it, we parted,
and I lay down to try if I could get any sleep,
for I have showed before what sort of a night the last was with us;
but sleep vanished from me,
and I got up and walked to and fro in the woods until the meeting was mostly gathered.

I was under a very great load in my spirit; the occasion of which was hid from me,
but I saw it my place to go to meeting, the order of which was such,
in all the parts thereof, that I had not seen the like before;
the large and bright rubbed room was set with suitable seats or chairs,
the glass windows taken out of the frames, and many chairs placed without,
very conveniently, so that I did not see anything lacking, according to the place,
but something to stand on, for I was not free to set my feet upon the fine cane chair,
lest I should break it.

I am the more particular in this exact and exemplary order than in some other things,
for the seats both within and without doors were so placed,
that the faces of the people were towards where the public Friends sat, and when so set,
they did not look or gaze in our faces, as some I think are too apt to do,
which in my thoughts bespeaks an unconcerned mind.
The meeting being thus gathered, and set down in this orderly manner,
although there were but very few bearing our name in it,
it was not long before the mighty power of the Lord began to work,
and in it my companion did appear in testimony in the forepart thereof.
While he was speaking, a priest, not the one before mentioned, but another,
threw out some reflections upon him, and the people for his sake,
which I did not see the least occasion for; after which he went away.

I sat a considerable time in the meeting before I could see my way clear to say anything,
until the Lord`'s heavenly power raised me,
and set me upon my feet as if one had lifted me up;
and what I had first in commission to speak, was in the words of Christ to Nicodemus:
"`Except a man be born again, he cannot see the kingdom of God;`" with these words.
No, the natural and unregenerate man cannot so much as
see the heavenly and spiritual kingdom of Christ,
which stands not only in power but also in righteousness,
joy and peace in the Holy Spirit.
I told them that to be born again, was not to be done unperceivably,
no more than the natural birth could be brought forth without trouble;
and to pretend to be in Christ and not to be new creatures, is preposterous;
and to pretend to be new creatures,
and yet not be able to render any account how it was performed, was unreasonable;
it could not be, as I urged before, without our knowledge; for to be born again,
signified to be quickened and raised into a spiritual and new life,
by which the body of the sins of the flesh is mortified,
and we come to live a self-denying life.
Those who are crucified with Christ, are crucified to their sins,
that as he died for sin, we might die to sin: in this state we live not after the flesh,
although we live, as the apostle said, in the flesh; but the life which these live,
is through faith in the Son of God: and to have all this, and much more wrought in us,
and we know nothing of it, is unaccountable.

As I was thus opened, and delivering these things, with much more than I can remember,
the woman +++[+++Mary Starbuck]
I felt, for most of an hour together, fought and strove against the testimony,
sometimes looking up in my face with a pale, and then with a more ruddy complexion;
but the strength of the truth increased,
and the Lord`'s mighty power began to shake the people within and without doors;
but she who was looked upon as a Deborah by these people,
was reluctant to lose her outside religion, or the appearance thereof.
When she could no longer contain, she submitted to the power of Truth,
and the doctrines thereof, and lifted up her voice and wept.
Oh! then the universal cry and brokenness of heart and tears were wonderful!
From this time I do not remember one word that I spoke in testimony,
it was enough that I could keep upon the true bottom,
and not be carried away with the stream above my measure.

I might add much more concerning this day`'s work,
but I intend not to say anything to the praise of the creature,
but to the renown of the mighty name of the Lord of Hosts,
and let all flesh lie as in the dust forever.
While I continued speaking in this state, as before mentioned,
and thus swallowed up in the internal presence of Christ,
where there was no lack of power, wisdom, or utterance,
I spoke but a sentence and stopped, and so on for some time:
I have since thought of John`'s being in the spirit on the Lord`'s day.
If it had been a state to be continued in,
I am of the mind I should not have been sensible of weariness,
neither of hunger nor pain.
This is a mystery to many, yet these are faithful and true sayings,
you may read that can; but there are none who can know the white stone and new name,
but they who have it;
there are none who stand upon mount Zion with harps of God in their hands,
but only such as have come through great tribulations,
and have washed their garments and made them white in the blood of the Lamb.
To these are the seals of the book of the mysteries of the glorious kingdom opened;
these are called out of nations, kindreds, tongues and people;
these are redeemed out of the fallen and earthly state of old Adam, into the living,
heavenly and spiritual state in Christ the second Adam; these cry holy;
the other part of the children of men cry unholy,
because they are not willing to cast down their crowns at
the feet or appearance of Christ in their own souls.
Although such with the four beasts may cry,
"`Come and see,`" yet are they not properly qualified
to worship the Lord God and the Lamb before his throne,
as the four and twenty elders did, and as all do, and will do,
who worship God in his holy temple in spirit and in truth,
according to his own appointment; who are not tied up to the canons, creeds, systems,
and dictates of men, much of which is beaten out of the wisdom, abilities,
and natural comprehensions of earthly fallen man.

I return from this, which may seem a mysterious digression,
to the other part of what did happen concerning the meeting,
and come now to the breaking up thereof.
As extreme heats oft end in extreme cold, and as great heights frequently centre,
as to man in this capacity, in great depths, and great plenty in great poverty,
which I have often seen to be good, in order to keep the creature low,
in fear and in a dependance upon the Lord,
I soon fell into such a condition that I was likely to die away.
When it was so, I with my companion made a motion to break up the meeting,
but could not for some time, for they sat weeping universally; then I told the meeting,
especially such as were near me, that if I should faint away,
I would not have them to be surprised at it;
for I was much concerned lest that should hurt these tender people;
my life was not dear to me in comparison of the worth
of the souls of the children of men;
but all this did not break up the meeting.
After some time Mary Starbuck stood up, and held out her hand,
and spoke tremblingly and said, All that ever we have been building,
and all that ever we have done, is pulled down this day;
and this is the everlasting truth; or very nearly these words.
Then she arose, and I observed that she, and as many as could well be seen,
were wet with tears from their faces to the fore-skirts of their garments,
and the floor was as though there had been a shower of rain upon it; but Mary,
that worthy woman, said to me,
when a little come to consider the poor state that I was in, Dear child,
what shall I do for you?
I said, A little would do for me;
if you can get me something to drink that is not strong, but rather warm, it may do well:
so she did, and I went unto her son`'s, where my clothes were, that I might shift me,
for I felt sweat in my shoes as I walked.

I mention this partly for the sake of such of my brethren,
who may be at any time in the like case, to take care to keep out of the cold,
and beware of drinking that which is cold, neither is brandy good,
for it feeds too much upon the weakened vitals;
but in all things endeavour to possess your vessels in sanctification and honour.
As it is not in man`'s power to make the vessel clean nor prepare it,
therefore if the Lord does,
with your obedience through the work of his grace and Holy Spirit,
fit your vessel for his work and service, take this caution,
see that you neither destroy, defile, nor hurt the same.
But it may be, some have done all these, some one way and some another.

I remember Peleg Slocum said after this meeting, that the like he was never at;
for he thought the inhabitants of the island were shaken,
and most of the people convinced of the Truth: however,
a great convincement there was that day, Mary Starbuck was one of the number,
and in a short time after received a public testimony, as did also her son Nathaniel.

After I was somewhat revived, my companion having a mind to speak to the priest,
to know why he did so reflect on him, desired me to go with him,
which I did with several more, and coming to his door, where he was set upon a bench,
James Bates asked him, Why he did so reflect]
He replied, he was in a passion, and had nothing against him: James forgave him,
and they fell into some debate concerning faith;
my friend urged the apostle James`' words, which are these,
"`As the body without the spirit is dead, so is faith without works, dead also.`"
The priest said, Dead faith was nothing, and that it had no being in the world.
I thought he appeared to be in the craft; and after they had tugged at it a while,
I said, I found something in my mind to interpose, if they would hear me;
they both showed a willingness to hear what I had to say, and then I asked,
What belief or faith that was the devils had; for I did not understand,
but that although they believed there was a God, they remained devils still;
therefore the word dead is a proper word,
and properly adapted to that which any may call faith, and is not operative,
but a notion that may be received by education, by hearing or reading,
and not that faith which works by love and overcomes the world:
and because of its not working, being inactive and useless, it is fitly called dead:
what do you say to that?
He said I was too great a scholar for him.
I replied, there was no great scholarship in that.
He then invited me to stay all night,
and said I should be as welcome as his own children,
and he and I would dispute about that between ourselves.
I declined it, and showed these reasons for so doing; if he declined the debate publicly,
I would not debate it privately,
for then these neighbours of his would not have the benefit of it;
and so we parted with my saying, as it immediately sprang up in my heart.
You have been a man in your young years that the Lord has been near,
and favoured with many openings, and if you had been faithful to the gift of God,
you might have been serviceable; but you have been unfaithful,
and a cloud is come over you, and you are laid aside as useless.

I was altogether a stranger to the state of the priest, nor had I heard anything of him,
nor indeed of the state of the inhabitants of the island, but what I heard afterwards,
mostly from Mary Starbuck.
As we walked from the priest`'s house towards our quarters, she said,
Everything she now met with, did confirm her in the Truth;
for she knew this was the state of the priest, as I had said,
being acquainted with him in his best state,
and then he had fine openings and a living ministry among them,
but of late a cloud was come over him, and, as I said, he was laid by and useless.
She also put me in mind of something I had said in the meeting about election,
which as near as I can remember was thus: I had endeavoured to make one in the election,
and one born again, much the same;
for I had laid waste all claim to election without being born again;
for as Christ was the chosen or elect of God, who never fell,
could such who were in the fall be the branches of Christ, the pure heavenly vine?
Or such who were found in the impure slate, and in the degeneracy,
by reason of sin and wicked works?
Or would Christ be married to a people, and become as their husband,
who were in an unconverted state?
Could this be the true church of Christ?
Could this be the Lamb`'s bride, who had departed from his spirit,
and was in the pollutions of the world through lust,
and running after the pleasures and fineries of the world, depending upon ceremonies,
and outside things and elements, which appear not to be essential to our salvation,
neither do we find life in them, nor conversion through them?
I was of the apostle`'s mind,
that "`Neither circumcision nor uncircumcision avails anything,
but a new creature:`" and what man in the world can say, that water,
although he may have been baptized or dipped into the same, has converted him,
or changed his state from a natural to a spiritual,
or from a dead to a living state in Christ?
Or, who that have gone through the most celebrated ceremonies, as some may account them,
had thereby got dominion over sin and Satan?

Having thus treated of these things among them, I said to Mary,
that she warred and strove against the testimony for a time: and as nearly as I remember,
she said their principle was.
That such who believed once in Christ, were always in him,
without a possibility of falling away; and whom he had once loved, he loved to the end:
it was a distinction they had given to their church, to be called Electarians;
and as I said, or near it, she had no mind to be pulled out of her strong hold.
But when she saw the glory of Christ and the true church,
as the queen of the south saw Solomon`'s, and the glory of his house;
and as she had her questions and doubts answered, she had no more spirit in her,
or doubts or questions, but openly owned.
This is the Truth, this is the glory I have heard so much of:
that spirit of doubting and questioning was swallowed up now,
by hearing and beholding for herself this greater than Solomon, his wisdom and glory,
and the great house that he had built.
The servants, the attendance, the excellent order, with the ascent to the house of God,
which were all wonderful in Solomon`'s house,
carried in them a lively resemblance of Christ, his power, glory and wisdom,
as also that order and mien which is seen among his faithful servants,
his church and people,
even such as our spiritual Solomon rules in and over by his spirit and power.
Here is Solomon or Man of Peace, elsewhere called the Prince of Peace;
and as Solomon ruled in Jerusalem, formerly called Salem, or City of Peace,
and indeed over all Judah, and over all his tribes,
so does Christ in his kingdom everywhere upon the face of the whole earth.
Learn this, see and know in and for yourself,
that you are truly translated out of the kingdom
of death and darkness into the kingdom of Christ,
which is a kingdom of power, life, light, peace and joy in the Holy Spirit.
I was much bowed down in my spirit, and in weakness, fasting,
and in much fear, for the more Truth appears,
the more it brings the creature into self-abasement.

A passage is here revived to my mind, which was thus: After a large Yearly Meeting,
where were many able ministers, worthy William Penn, who was one of them,
taking me aside, said,
The main part of the service of this day`'s work went on your side, and we saw it,
and were willing and easy to give way to the Truth, though it was through you,
who appears but like a shrub;
and it is but reasonable the Lord should make use of whom he pleases: now, I think,
you may be cheerful.
From which I gathered, that he thought I was too much inclined to be cast down;
therefore I gave him this true answer, I endeavour to keep in a medium,
out of all extremes, as believing it to be most agreeable to my station;
with this remark, the worst of my times rather embitter the best to me.
William shook his head, and said with much respect,
"`There are many who steer in this course besides you,
and it is the safest path for us to walk in;`" with
several other expressions which bespoke affection.

This worthy man, and minister of the Gospel,
notwithstanding his great endowments and excellent qualifications,
yet thought it his place to give way to the Truth,
and let the holy testimony go through whom it might
please the Lord to empower and employ in his work,
although it might be through contemptible instruments.
I sincerely desire this may prove profitable to those whom it may concern,
and into whose hands it may come, that the Lord`'s work maybe truly minded,
and given way to, when it is opened; for seeing no man can open it,
let not any strive in the man`'s part to shut the same.
I have at times seen something of this, which has not been altogether to my satisfaction.
A word to the wise may serve, I hope, and be sufficient for a caution,
for what I have written is in the love of God,
and under a concern that has been upon my mind at times, for some years,
to leave behind me a gentle caution to my tender friends of both sexes,
to have an especial care in all things to recommend not only their gifts,
but their demeanour in them, as also their conduct after them,
to every man`'s conscience in the sight of God;
so that you may build up the Lord`'s house, and always have a great care,
that nothing you say or do may in any way tend to the hindrance of the Lord`'s work,
or to discourage the weakest in the flock of Christ, but labour to fasten every stake,
and strengthen every cord of Zion, and as much as you are capable,
build up the tabernacle in Jerusalem.
As God is a spirit, and the soul of man is a spiritual existence,
and as the soul and body of man become sanctified and prepared,
as a temple for the Lord by his Holy Spirit to tabernacle in,
the Lord is to such as a sanctuary to flee to, and rest in, from heats and from storms:
here is the Rock of the true church, and her place of defence, namely:
the name and power of the mighty God.
Oh! that all the inhabitants of the earth were acquainted with this name,
and rock of defence! they would not then be so much overcome, as they are,
with the power of the enemy of the soul, but would live above his region,
which is in the earth, or rather in the earthly hearts of men.
All you who have escaped the pollutions of the world, keep in your tents,
until the Lord moves and leads forward, and opens the way, sometimes as in a wilderness.

Read and understand from where these things have their rise,
for there is the church`'s safety, and its comeliness too in abiding in the Truth.
This is your place of safety, where the enemy has no power,
where the wiles of Satan and inventions of man cannot reach;
no enchantment has power over these,
renowned be the great name of the Lord now and forever.

How comfortable, how easy and pleasant are even all the books and testimonies,
and exhortations, that are given forth in the spirit, love and life of Christ! yes,
the very company and conversation of such who are preserved in the life,
becomes a sweet savour of Divine life to the living.
There is comfort and consolation,
a strengthening and building up one of another in the most holy and precious faith,
so that I find the truly quickened soul takes great delight to resort to,
and as much as may be,
converse with the awakened and truly quickened souls
who take up the cross of Christ daily,
and follow him in the way of self-denial,
although it be a way that is much spoken against,
by such who know not the nature and discipline of the holy cross,
and despise those who are the true followers of Christ.
To feel this essential virtue, seed or leaven of the kingdom, or salt of the covenant,
Christ, to work so effectually to the restoring of the powers and faculties of the soul,
into the first rectitude and purity, that all the malignity may be thoroughly purged out,
with all the dross or tin, which defiles the man,
and makes him unfit for the kingdom and for the service of God, is a great work.
Neither is the vessel preserved clean, when it is in degree cleansed,
but through great care, watchfulness,
and diligence in attending upon the Lord with great devotedness,
and resignation to his mind and will in all things.
Experience has taught us, as well as what we read in the Holy Scriptures,
that there are many combats to go through for such as are engaged in this warfare,
before the above-said states, deliverance from sin and Satan,
and a sabbatical or peaceful rest in Christ, can be obtained to the soul.

Come, you that love the light, and bring your deeds to the light,
and believe in the light, and have your body full of light,
by keeping your eye single to God,
and in and to all things that may tend to his glory and your duty;
you will become a child of the light, and receive the whole armour of light.
This is that which will arm you on the right hand and on the left.
Put off your own righteousness,
with which it may be your breast has been too much possessed,
and put on Christ`'s righteousness as a breast plate,
for it much emboldens in imminent dangers, and also at approaching death.
Wait upon him who has power,
that your feet may be shod with the preparation of the Gospel of peace;
so that as the Gospel power and Gospel ministry all tend
to gather into the ways of the Gospel and of virtue,
you may not fail to be a preacher of righteousness
in your walking and in your whole conduct;
for this is one of the good ends for which the Gospel
power has reached and visited your soul,
namely: to purge it, and make it clean.
Take care to have upon your head the helmet of salvation,
which will be a strength and as a crown to you, not only in the many encounters,
but more especially m your last encounter with death;
and that you may have faith as a shield to put on, that you may overcome the world;
and above all things, take to yourself the sword of the spirit, which is the word of God,
that through this excellent armour of proof,
you may be able to quench all the fiery darts and temptations of the devil.

If you are a soldier of Christ, this is your armour;
these are your accoutrements which fit you for your vocation,
as a follower of the Lamb through many encounters with your enemies,
which armour will give you the victory, and bring you through many tribulations,
which is the way to the kingdom of heaven.

Now leaving the eastern parts of New England,
and these tender people on Nantucket Island,
with fervent supplications and prayers to the Lord of heaven and earth,
that he will prosper his blessed work of conversion which he has begun among them,
and in all such upon the face of the whole earth; in the next place I came to Lynn,
to Samuel Collings`', where I had not been long before I met with an unusual exercise,
which I had expected for some time would fall upon me.

Having heard of George Keith`'s intention of being at Lynn Monthly Meeting the next day,
which as near as I remember, lies between Salem and Boston, the evening coming on,
as I was writing to some Friends in Old England,
one came in haste to desire me to come down, for George Keith was come to the door,
and a great number of people and a priest with him,
and was railing against Friends exceedingly.
I said, Inasmuch as I understand this Lynn meeting is, although large,
mostly a newly convinced people, I advise you to be swift to hear, but slow to speak,
for George Keith has a life in argument; and let us, as a people,
seek unto and cry mightily to the Lord, to look down upon us,
and help us for his name`'s sake, for our preservation, that none may be hurt.

The country was much alarmed; for, as Friends said,
George Keith had given notice two weeks beforehand,
that he intended to be at this Monthly Meeting,
and the people were in great expectation to hear the Quakers run down,
for George Keith had boasted much of what he would prove against Friends.
Soon after some pause, retirement,
and fervent seeking to the Lord for direction and counsel in this important affair,
I went to the rails, and leaned my arms on them near George Keith`'s horse`'s head,
as he sat on his back, and many people were with him; but the few Friends who were come,
stood With me in the yard.
My fervent prayers were to the Lord, that if he gave me anything to speak to George,
it might go forth in that power and wisdom which was able
to wound that wicked spirit in which he appeared,
and boasted over Friends after the following manner, crying,
"`Is here a man that is a scholar?
Is here a man that understands the languages among you?
If so, I will dispute with him.`"
I told him,
it was probable the English tongue was most generally
understood and used among that people,
and therefore I thought it was the best to keep to it.
He went on and said,
that he was "`come in the Queen`'s name to gather the Quakers from Quakerism,
to the mother church,
the good old Church of England,`" and that he intended to exhibit
in our meeting on the morrow these charges following against us,
which, he said, he could prove we were guilty of out of our Friends`' books, namely:
Errors, heresies, damnable doctrines and blasphemies.
"`Look,`" said he, "`to answer for yourselves, for if you do not,
the auditory will conclude that what I exhibit against you is true.`"

I was roused up in my spirit in a holy zeal against his wicked insults and great threatenings,
and said to him, That it was the fruit of malice and envy,
and that he was to us but as a heathen man and a publican.
Then he began to cast what odium he could upon Friends,
with such bitter invectives as his malice could invent.
I stood with an attentive ear and a watchful mind; for as I stood leaning upon the rails,
with no small concern upon my mind, I felt the Lord`'s power arise,
and by it my strength was renewed in the inner man, and faith, wisdom,
and courage with it, so that the fear of man,
with all his abilities and learning was taken from me;
and in this state George Keith appeared to me but as a little child, or as nothing:
renowned be the most excellent name of the Lord, now and forever.
But this great champion, Goliath-like, at least in his mind,
I supposed feared not any there; he overlooked us all,
and in the pride of his heart disdained us;
but the Lord of heaven and earth looked down upon us in a very acceptable time,
and helped us for his name`'s sake, and covered our heads in the day of battle:
glorified be his great name forever.

I have sometimes thought to omit some part of this account concerning George Keith,
but remember it opened clearly in my mind then, and I said to him,
That the hand of the Lord was against him,
and that he would pour forth contempt upon him for his disobedience and wickedness.

But to return to his reflections: he said,
The Quakers pretend to be against all ceremonies,
but he could prove that they used many ceremonies, as taking one another by the hand,
and men saluting one another, and women doing so to one another, and he said,
that women did salute men; yes, they had done it to him;
as it was generally understood by those who heard him,
which I thought not worthy my notice.
He went on and said, the Quakers pretended to be against all persecution,
but they were not clear,
for the Quakers in Pennsylvania and the Jerseys had persecuted him,
and would have hanged him, but that there was some alteration in the government.

Then came out one of my arrows, which cut and wounded him deeply: I said, George,
that is not true.
Upon that the priest drew near, and appeared very brisk,
and said I had as good as charged Mr. Keith, as he called him, with a lie.
I replied, Give me time, and I will prove that which George said, is not true,
and then you and he may take your advantage to rescue him from that epithet of a liar,
if you can.
The priest said I knew not Mr. Keith: I replied, If he knew him as well as I did,
he would be ashamed to be there as an abettor of him.
The priest got away,
and troubled me no more in all the engagements that George and I had afterwards,
although the said priest was with him.
Then I demanded of George, What way our friends proceeded against him,
and what measures they took, as he would insinuate, to bring him to the gallows.
But I perceived fear began to surprise the hypocrite,
and he thinking by my boldness I was an inhabitant in those parts,
and knew his abuse to Friends in these provinces,
and their peaceable behaviour towards him, was willing to let the matter drop,
and demanded my name, which was told him.

I then asked,
How he could have a face to urge such a notorious untruth
in the view of that people who were much strangers to,
and ignorant of the troubles and differences, chiefly created by him,
among Friends in these parts.
The members of this meeting being generally newly convinced of the truth,
I urged him to come to the particulars of Friends`' proceedings against him,
that among those strangers he would set forth as far as he could in truth,
the steps Friends had taken in persecuting him, as he pretended;
but he would not meddle in the least with it.
Then I showed him, and the people, the falsity of his charge,
and the wickedness of his spirit,
and the peaceableness of Friends`' behaviour towards him,
and what great affronts and provocations they had put up with at his hand,
as I had it from those who were eye and ear witnesses of it.
For, as I showed George Keith, I had searched into the bottom of these matters,
and heard that when he stood before governors and assembly-men in their courts of judicature,
when they were met about the affairs of the three provinces,
he had torn open his buttons and told them, His back tickled for a whipping,
and could they not cut him into collops, and fry and eat them with salt;
and that he scorned they should wipe his shoes: all which, with much more,
I told him I could prove against him.
And when he saw he could not provoke Friends to give him some condign punishment,
which I thought, as I said to him, none but Friends would have spared,
especially when his back tickled so much for a whipping; but they,
like men of peace and religion, overlooked it all; he, like a man full of malice,
rather than go without something to slur and blacken Friends with, wrote a letter,
I know not where, but dated it from Bridlington prison, in West Jersey.
It must have been dated on the outside of the prison, the doors being locked,
so that he could not get into it; yet this went current far off,
that George Keith was in prison; consequently by Friends`' procurement,
they being chiefly at the helm of government in those three provinces.

I asked, What he had to say to all this, for it was all provable:
he did not object one word against what I had said,
but vainly hoping for belter success in Old England, relating to his undertaking,
and finding me, as he might suppose, so well versed in the American affairs, hoped,
no doubt, that I had been more ignorant of the affairs of Britain: but, poor man,
he sped as illy there also.
For he boastingly said,
Since it pleased God to open his eyes to see into the worst of the Quakers`' errors,
although, he said,
charity did oblige him to construe everything at the best while in fellowship with them,
but since they were so opened; he had been instrumental to bring from Quakerism,
to the good old mother church, in Old England, five hundred people.
I replied, That is not true: if he rightly considered what he had done in Old England,
he had little cause to boast; for, I said,
I thought about as many persons as he spoke of hundreds, would make up the number there;
and if there was occasion, I could name all or most of them; and told him,
that some of those few, while among us,
were grown to be neither honourable nor comfortable to us.
I urged George, if he could, to name or make appear more in number than I had mentioned,
that he had so gathered, as he had falsely said.
This was a very great stroke, and put him to a stand.

He then began to ask of my country, and from where I came;
with the account of which I humoured him; yet I put him in mind of his great brag,
and importuned him to make something appear towards
that great matter he had done in Old England;
for I was ashamed for him, that a man of his learning, talents, and pretensions,
should so expose himself; but he went no farther about it.
Then I showed the people what sort of a man he was, as they themselves could not but see,
who were impartial, and that he was not worthy of our notice,
for he cared not what he said, so that he could but calumniate and abuse us.

By this time he appeared somewhat glutted with the
sharp sword and keen arrow the Lord gave me,
which cut and wounded deeply, so that I did not find in our after encounters,
he appeared at any time so bold and desperately hardy, but rather expressed himself,
though very wickedly, yet in a softer tone.
He was now for being gone, threatening us with what he would do on the morrow;
but I reminded him, that he was to us as a heathen man or a publican,
and that what he exhibited against us, being but the fruits of wrath and envy,
as such we slighted and trod it under our feet as dirt,
and rather desired his absence than his company: so away he went, only telling us,
he would be with us in the morning.
We understood by it, that he intended to be with us at the Friend`'s house,
the meeting- house being about a quarter of a mile from our lodgings.

The evening coming on,
the neighbouring Presbyterian women fell hard upon
our women Friends about their saluting men,
which George Keith had charged upon them, as was generally understood in the plural,
and this appeared as a confirmation, as they alleged, because when charged,
I made no reply to it, as I had done to all or most other charges,
and had overthrown Mr. Keith, as they said, so that he was not able to stand before me.
They ought to have said, before the Lord in the first place.
But how the women might clear themselves of that reflection was the present business.
I said, I thought it would be the best, at a suitable time in the morning,
when George Keith was come, that by handsomely bringing the matter over him,
they might learn what women they were who saluted him,
and so clear themselves from the reflection cast upon them; for, I said,
perhaps he will limit it to some of his near kindred, as wife, mother, sister, daughter,
which may serve him for a salvo in this present case;
for I did not know of any such general practice in any place where I had been,
and I had visited most of the meetings in England, Scotland, and Wales.
So in the morning, when George, with two priests, and many people were come,
with some Friends, who filled the house, a woman Friend stood up,
and brought the matter discreetly over George Keith.
But when she put the question in the plural, women, he shifted the term, and said,
He did not say women.
I desired the Friend to call to her neighbours who
heard what George Keith had said the last evening,
and were now present, how they understood the word.
One, like a wise and just man, said, He would do justice to every man;
and he understood that George said women; and many said to the same purpose,
but none to the contrary.
The Friends asked me, How I understood the word: as being a north countryman,
I might know better the north or Scotch dialect than they.
I replied, They had a broad way of expressing the word woman,
rather sounding it like the plural, but I understood it women,
as the above-mentioned discreet man had said.

The next question she put to him was.
What woman?
He answered, A good old motherly woman that was gone to heaven many years ago.
Then she asked, What countrywoman?
He replied, A Scotch woman.
The Friend said, It was very well that he had cleared all the world of that fault,
if it might be so termed, but Scotland, and one woman dead many years ago.
The women Friends were greatly satisfied,
and glad they were so finely discharged of that which some counted a reflection,
and especially before their zealous neighbours the Presbyterians; who,
as the Friends said, might probably have twitted them with it,
whether the matter was true or false, if it had not been cleared up; but,
as I said to George, it was a reflection for reflection`'s sake:
for I was willing to set everything that was wrong, as far as I was capable,
in its proper light, that Friends and others, of all persuasions who were present,
might see things as they really were, and not be deceived;
and I had much satisfaction in so doing.
As I was engaged in the defence of the truth,
it appeared most clear to me to load him with his own lies, mistakes, and wickedness,
and to do what we did, as much as in us lay, in the Lord`'s mighty power;
for he appeared to me like the angels who kept not their first state.

Matters being thus far gone through, and the meeting time drawing on,
I was in some concern of mind,
lest any should be hurt by either hearing or answering George Keith,
he having a great propensity to jangling;
it therefore opened in my mind to ask him a question.
Reminding him, that he was but to us as a heathen man or a publican, yet he might,
if he pleased, answer me the question, which was:
Whether he was always sound in the fundamental doctrines of Christianity, yes or no?
Upon which he sat a considerable time in silence, of which I was truly glad,
my spirit being much bowed under the apprehension I had of the
weighty exercise that was likely to attend the approaching meeting.
But before we parted, George stood up, and taking his staff in his hand by the middle,
said, While he was a Quaker, he thought as Paul thought, that he had the Spirit of God,
and when he had the Spirit of God, then he wrote sound things, but when he had it not,
then he wrote unsound things.
I asked, whether these unsound things he wrote were in fundamentals, yes or no:
if not in fundamentals, then my question remained firm and untouched.
He would have gone from the matter, but I reminded him of it again,
as I supposed he foresaw that he could not answer it,
but by bringing a stroke upon himself, for if he had owned his being unsound,
I had it under his own hand, in a book written after he left Friends,
that he was always sound, etc.
And if he had said, he was always sound in the fundamentals, as before,
then I intended to have asked, why he left us:
for he advocated the same orthodox principles which we believed and taught;
but we ended quietly, and prepared to go to the great meeting,
for by this time many Friends and people were come, and coming from every quarter,
to see and hear how matters would go between the poor Quakers,
and this great champion in his heart, George Keith,
for I thought he most resembled the great Goliath of Gath,
who defied the armies of the living God, of any I had seen in all my travels,
in a religious respect.

Now to the meeting we went; George Keith,
with two priests and a great many people of several professions
and qualities gathered together into one body,
and Friends and some friendly people into another body;
and as we came near to the meeting-house, I stood still, and took a view of the people,
and it appeared to me as if two armies were going to engage in battle.
There appeared with George Keith men of considerable estates, talents, and learning,
and we appeared like poor shrubs; and, under a sense of our present state,
I had like to have been dismayed, and my faith even to have failed me.
But I cried mightily to the God and Fountain of all our tender mercies,
that he would look down upon us,
and help us in this time of great exercise,`' which was not hid from him;
but his penetrating eye saw, and his watchful providence attended us,
blessed be his name forever.
I continued my fervent prayers and intercessions to the Lord of Hosts,
that he would arise for his great name`'s sake, and work for us that day,
that the enemies of truth might not triumph or vaunt over us,
and that none of these tender plants,
whom he had brought to the saving knowledge of the Truth, might be hurt.

I had no sooner thus heartily sought the Lord, but I felt renewed strength come upon me,
and the fear of man was taken away from me,
and I saw evidently that Truth would have the victory that day,
and my faith and confidence were greatly strengthened in the Lord.
These breathings forth of my spirit to the Lord were in secret,
without words to be heard by men,
but the Lord hears and knows the distress and language of the spirit.

Being thus encouraged in myself,
it arose in my heart to speak to Friends before we went into the meeting-house;
and I advised them to be swift to hear, and slow to speak,
that what was spoken might be in the Lord`'s power, for that wounds George the most,
and slays that wicked and ranting spirit in him,
more than all the wisdom of words without it:
let us maintain our testimony of denial against him,
and endeavour to get together into one body,
that we may be a help and strength one to another; and let every one who knows the Lord,
cry mightily to him, that his living power and presence may be among us,
and I believe the Lord will not allow any to be hurt.
So the meeting gathered, and immediately after, George stood up to tell us, as before,
that he was come in the Queen`'s name, to gather Quakers from Quakerism,
to the good old mother church, the Church of England, as he called it,
and that he could prove out of our own books, that we held errors, heresies,
damnable doctrines, and blasphemies; with a threat to look to ourselves to answer,
or else the auditory would conclude, that what he exhibited against us was true.
I expected some of the elder Friends would say something to him, but none did;
and having a deep concern upon my mind, lest Truth, or the friends of Truth,
should suffer through our mismanagement,
and such as waited for occasion might have it administered by us against ourselves;
under this concern I stood up,
and signified to the people what manner of man George Keith was.
Notwithstanding he had walked many years among us,
yet towards the latter end of his so walking with us, he grew very troublesome,
by reason of a contentious spirit which did possess him;
and after much labour and exercising of patience, and extending of love towards him,
in order to recover and reclaim him,
all that labour of love and much forbearance would not avail,
but he still persisted in the work of contention and disturbance;
then he was publicly disowned, and testified against by us,
as a person with whom we had no unity or fellowship.
Being thus cast out, he became to us, agreeably to the sayings of Jesus Christ,
as a heathen man or a publican; and did what lay in his power,
to expose us to all sorts of people, printing against us; wherein he has much abused us,
in leaving out the explanatory parts of sentences,
and coining words to make the meaning appear different from what was designed,
and indeed, from what was most fair and genuine.

Therefore, some of our Friends found themselves concerned to follow him in print,
for the clearing us from what he, through envy, would have willingly fastened upon us,
and to return his self-contradictions, misinterpretations,
and misapplications of our writings upon himself, and to clear our own innocency,
and manifest the perverseness and wickedness of his spirit.
Neither do we, as a people,
hold ourselves under any obligation to follow him into foreign parts of the world,
to answer his charges,
not being conscious that we hold anything contrary to sound and orthodox doctrine.
And knowing that what he exhibits against us, is the fruit of envy and malice,
as such we reject it, and trample it under our feet; and were it not for your sakes,
who are strangers to these things, we should take no further notice of George Keith,
than to slight and reject him as a man that cares not what he says,
nor is he worthy of our notice.

Then pausing a little, George being quiet, a Friend stood up with a short,
but living testimony, and then my companion; all this in much weight,
and with good demonstration.
After them it pleased the Lord to open my mouth, I think in as much strength,
clearness and demonstration as ever, beginning with the following words:
In that way you call heresy do we worship the God of our fathers,
believing all things that are written concerning Jesus Christ,
both as to his Godhead and manhood; giving a summary account of his birth,
working of miracles, some of his doctrine, sufferings and death,
ascension and glorification, the coming of the Spirit of Truth, or Comforter,
to lead all those who receive, believe and obey it, into all truth:
having great openings concerning the law and prophets, and the beginning,
service and end of the ministration of John the Baptist.
The people appeared very attentive,
for the Lord`'s heavenly baptizing power was among us that day:
it was thought many were there who had not been at any of our meetings of worship before,
and the presence of the priests there, opened a door for all the rest.

Being clear, I left them to the grace of God, and to their free teacher Christ,
whose heavenly power in the appearance of his spirit, the last and lasting dispensation,
was exalted that day above all the shadowy and typical
things that ever had been in the world:
a good meeting it was,
and Friends were mutually comforted and edified in the eternal presence of the Lord.

The priest of this place, whose name was Sheppard,
before my mouth was opened in testimony, made preparation to write;
and when I began to speak, he had his hat upon his knee, and his paper upon its crown,
and pen and ink in his hands, and made many motions to write, but wrote nothing;
as he began, so he ended, without writing at all.
As Friends entered the meeting-house, the Lord`'s power,
even that power which cut Rahab and wounded the Dragon, which had been at work,
kept down in a good degree the wrong spirit in George, for he appeared much down;
but this busy priest called to him several times to make his reply to what I had spoken.
After some time, I said to the priest, in behalf of the meeting,
That he might have liberty to make reply.
He proposed to have another day appointed for a dispute; to which I said,
If he did make a voluntary challenge, which he should not say we put him upon, we,
or some of us, meaning Friends, if a day and place were agreed upon,
should find it our concern to answer him as well as we could.
He said he would have Mr. Keith to be with him.
I told him if he should, and meddled in the dispute, if I was there,
I should reject him for reasons before assigned.
When the priest had said this and somewhat more,
an elder of the Presbyterian congregation clapped him on the shoulder,
and bid him sit down; so he was quiet, and then stood up George Keith,
and owned he had been refreshed among us that day,
and had heard a great many sound truths, with some errors,
but that it was not the common doctrine which the Quakers preached.

I then stood up and said,
I had something to say to obviate what George Keith would insinuate;
for his drift was to infuse an opinion into them,
that the Quakers did not commonly preach up faith in the manhood of Christ,
as I had done that day.
I appealed to the auditory,
whether any thought there was a necessity frequently to
press a matter so universally received among Christians,
as faith in the manhood of Christ was: yet we, as a people,
had so often and clearly demonstrated our faith in the manhood of Christ,
both in our testimonies and writings, as might satisfy any unbiassed person,
or such who were not prejudiced against us;
and we know not of any people who believe more scripturally
in the manhood of Christ than we do.
But inasmuch as the grace, light, and Holy Spirit,
is highly concerned in the work of man`'s salvation,
as well as what Christ did for us without us,
and this being yet much a mystery to many called Christians, it pleases God to open,
in the course of our ministry, into the meaning and mystery thereof,
and to press the latter more than the former.
To which George made no reply, but began to exhibit his charges against us,
and said he could prove them out of our Friends`' books,
naming George Fox and Edward Burrough, etc.
He had in a paper a great many quotations out of Friends`' books,
and a young man with him had many books in a bag, out of which,
he said he would prove the charges he was about to exhibit against us.

He was now crowded up into the gallery between me and the rail, with a paper in his hand;
and I standing over him, and being taller, could see his quotations,
and his paraphrases upon them, on which I told him loudly,
that all the meeting might hear,
That he offered violence to that sense and understanding which God had given him,
and he knew in his conscience, we were not that people,
neither were our Friends`' writings either damnable or blasphemous,
as he through envy endeavoured to make the world believe,
and that he would not have peace in so doing,
but trouble from the Lord in his conscience.
I spoke in the Lord`'s dreadful power,
and George trembled so much as I seldom ever saw any man do.
I pitied him in my heart, yet as Moses said once concerning Israel,
I felt the wrath of the Lord go forth against him.
George said, Do not judge me; I replied, The Lord judges,
and all who are truly one in spirit with the Lord, cannot but judge you.
So he gave over, and it appearing a suitable time to break up the meeting,
Friends parted in great love, tenderness, and brokenness of heart;
for the Lord`'s mighty power had been in and over
the meeting from the beginning to the end thereof;
glorified and renowned be his most excellent name, now and forever,
for his mercies are many to those that love and fear him, who is the fulness of all good.

This meeting was not only for worship, but also for business,
as I said to the people at our parting; it was Friends`' Monthly Meeting,
in which their poor, fatherless and widows, were taken care of,
and such other things as concern them as a people.
Two Friends were desired to stay, to hear what George had to say to them who remained,
which said two Friends gave us an account,
that George said to the people after we were gone,
the Quakers had left none to dispute with him but an ass and a fool; when I heard it,
I said, could you not have replied,
An ass was once made sufficient to reprove the madness of the prophet.

George called to see me the next day, and said, "`You had the advantage of me yesterday,
for you persuaded me to be quiet until you had done,
and then you would not stay to hear me;`" neither
indeed were we under any obligation so to do.
I told him, I hoped that Truth would always have the advantage over those who opposed it;
and so we parted, but met again upon Rhode Island; the governor of which place,
who was a friendly man, having heard of my intention of coming there,
ordered the deputy-governor, when I came, to bring me to him, which he did.
When he saw me at the door, and after inquiry heard my name, he took me by the hand,
and led me like a brother, or rather more like a tender father, into a room,
setting me down by him, and then began to say, I have heard much of you,
and I desired to see you long, and am glad you are here.
Finding him near me in spirit, I was very open in my mind to him,
and answered him with much clearness and satisfaction.
I remember he asked,
whether I thought the sourness in the minds of the Presbyterians against us,
was not rather abated?
I told him, I did believe it was; and if our Friends did but observe to walk wisely,
and live up to what they professed, they would overcome it all.
He said that was the way, and there was not another comparable to it; and as he said,
and I believe it was so, he had no other view in sending for me,
but to manifest his respect to me, and to do me any service that lay in his power.
I told him I was sensible of his love,
and wished I could be capable of returning that which
in gratitude his kindness to me called for:
he said he desired no more than when I came that way, I would visit him,
if he was living.
I told him I intended so to do, if it was my lot to come there again.
I then desired he would be at the meeting next day, George Keith proposing to be there,
in all likelihood it would be very large; which he promised he would,
and accordingly came.

George made little disturbance in the beginning of the meeting,
but commanded the governor to quiet the Quakers.
A priest said, Mr. Keith, you ought not to command the governor, but entreat him;
well then, he entreated the governor to quiet the Quakers, that he might be heard;
whereupon the governor, like a man of justice and wisdom, stood up and said,
It was not in his power to quiet the Quakers; inasmuch as the house is theirs,
and they have appointed the meeting, it is but reasonable they should have their liberty,
and if they be willing when they have done,
you have your liberty to say what you have to say to those who will stay to hear you:
so the governor being next me, leaned his hand upon me, and went away in a sober manner.
George was quiet, and we had a good meeting, and so parted.

After most of the Friends were gone, a Friend and I went to the meeting-house door,
to hear what George said: he held his Bible in his hand,
and said it was promised that the Gospel should be
preached unto every creature under heaven;
but if it was truly translated, it would be in every creature, not in every creature,
as horse, cow, etc., but in every rational creature of mankind:
and then their meeting broke up in confusion.

My next remove was to Long Island, where I met with Thomas Story and John Rodman;
John desired Thomas and me to be assistant to him
in preparing a writing against George Keith,
when he came to Flushing meeting upon the aforesaid island,
which writing was to this effect:

[.embedded-content-document.legal]
--

Colonel West, an inhabitant in these parts, who died and made Miles Forster a trustee,
gave by Will a considerable sum of money to poor Friends of London,
which money was ordered by the testator to be put into the hands
of some faithful Friends of the aforesaid city of London,
to distribute as above.

--

A true copy of which Will we obtained,
and at the meeting made it fairly appear to George Keith`'s face,
that he had wronged the poor in receiving fifty pounds
of the aforesaid money of Miles Forster,
as appeared under Miles`'s own hand;
which George did not deny when he was charged with it in the meeting,
as knowingly to have robbed the poor; it being made fairly to appear,
that George Keith had no right to meddle with the money, neither as a faithful Friend,
nor yet as a poor Friend of London, because he was then in America.
And what made him more incapable of claiming any part of it,
was his being got into the spirit of strife and enmity against Friends, and therefore,
before they could hear his charges, he ought first to lay down the money,
or give such security as Friends approved of; neither of which he was capable of doing.
He was slighted by all or most of the people, as well as by Friends,
and this blocked up his way so much that we had little
or no trouble with him in that part of the world.
The Lord wrought for his name`'s sake, and the preservation of his tender people,
praises and honour be given to his great name, now and forever.

Thus ended this engagement between a poor servant of Christ, and a grand apostate,
who appeared to fight against reason, sense and conscience.
Think not, my friends, the account too long, for it has seemed to me, for some time,
a debt due to my brethren, and a piece of justice due to the memory of George Keith,
for his wickedness, revolting and sad apostasy.
Few there are who can believe how great the power of darkness
and wickedness of that mind and spirit was,
which possessed and breathed through him; so great it was,
that even the considerate and sober people said,
they did not think that George Keith had been so
wicked a man as they found he was upon trial.
Courteous friend and reader, hold fast that which you have received,
that none may take your crown, for it is laid up in store for the righteous only,
and such who hold out to the end, in the same pure righteousness which is of Christ,
wrought and continued in man, by the operation and indwelling of his Holy Spirit,
as man abides in subjection and obedience to the leadings and dictates thereof.

I told George, that I was much ashamed of his complimenting great people;
for I observed he sometimes said thee and thou, and sometimes you and sir;
sometimes put his hat off, and sometimes kept it on,
and that before I would be so unhandy, if I intended to be ceremonious,
I would go to school a while, and not shame myself as he had done.
If I have not written the very words, in all my accounts in the preceding pages,
I have the substance: and for a conclusion, I had to say to George Keith,
the hand of the Lord was against him, and would follow him, unless he repented.

This account carries in it an admonition to us, and to Friends in future ages,
into whose hands it may come, to beware of letting in the spirit of envy,
prejudice and pride of heart, which I clearly saw was that which,
with too much leaning to his natural abilities and learning, was his overthrow,
he not keeping to the Lord`'s Holy Spirit, the life and strength of his faithful people,
and the key of true knowledge, the good remembrancer, and leader into all truth,
which the Lord sees fit in his wisdom to open and lead us into.
Without the help of this anointing and Holy Spirit,
we are apt to be cold and forgetful in our duties towards God,
and also in our love and duties one to another;
but as the measure of this spirit is faithfully kept to and improved,
we grow more and more fruitful in every good work and word,
to the glory of God and comfort of our souls, and, as the salt of the earth,
help to season those who are not seasoned.
