== Chapter III. First Visit to Friends in America

Now the time came for my going into America,
having had a sight of it about ten years before.
I acquainted my wife therewith about a year before she died,
and found it was likely to be a very near trial to her.
She was a virtuous good woman, but was taken away, and left me three small children,
the eldest not above four years old, the youngest not much above one month old.
Having but little of this world, I reasoned much about going,
thinking my circumstances at present might excuse me: my intentions were good in it,
that I might not leave things in any way to the dishonor of the truth.
My youngest child was taken away when about a year old; and soon after, wherever I went,
while I was awake, it sounded in my ears several days and nights.
Now is the time, now is the time.
Providence so ordered it,
that my other two children were placed to mine and Friends`' satisfaction.
I went through many provings that no man knew of, but I believe,
when I am gathered to my place, I shall leave many brethren behind me in mutability,
who will read my lines in their own experience.
I would not have any to misunderstand me, for as to my outward circumstances,
I left no debt, neither was I in a way of going backward in the world;
for after I received the knowledge of the Truth,
I could not see what presence I could have to religion, if any should lose by me.
I have often said, and been hearty in my intentions,
that rather than truth should suffer on that score, I would live upon bread and water,
and wear very mean clothes, and work very hard if I were able, and upon any mean,
but lawful calling.
It has been matter of wonder to me, how persons who carry any pretensions to religion,
dare run such great ventures, sometimes beyond their own bottom or abilities;
which to me has always appeared an unwarrantable risk,
and I apprehend pride and ostentation are much the occasion of it,
which are against truth, and men are no better for their greatness; for the more plain,
and the more humble we are, the more we resemble humble Jesus and his religion,
which he labored to inculcate.
If any are lifted up, or aspire above their places,
let them consider well the foregoing paragraph.

Now I must leave my little children, and my very near friends, and native country,
and all for Christ and the Gospel`'s sake, without any sinister end or view.
I appealed to the Lord, in the simplicity of my heart,
that he knew I was willing to be at his disposal, and what he had favored me with,
I could leave to him;
yet whether what I had was sufficient to defray
mine and my two little ones necessary charges,
was somewhat in my way; and to satisfy me in this doubt,
the Lord`'s voice sounded exceedingly clear to that sensation I was then endued with,
saying, "`Go, and be faithful, and I will bless you every way.`"
Oh! my heart seemed to melt, and my spirit to dissolve within me, and I said,
"`Good is the word of the Lord,
you have not failed me in any of my great straits and trials to this day;
I have great cause to trust in you; renowned be your most excellent name,
now and forever.`"

I parted from my friends with much brokenness of heart,
and set forward on my journey towards London, in order to take shipping there,
the 11th of the eighth month, 1700.
With my companions, Thomas Thompson, Josiah Langdale, John Estaugh,
and some other Friends, I went on board a ship in the river Thames,
and we had not been long there, considering our freedom about going in the ship,
when it opened clearly in my mind, in the light, That I must not go in that vessel;
and I said to the Friends, I could not go in her,
for I saw nothing but death and darkness there.
The account of what afterwards happened to the ship I had from two particular Friends,
in two letters from London to America,
wherein they expressed a thankfulness for our deliverance,
and magnified that hand which wrought it, and preserved us from going in that ship,
which was lost near the island of either Jersey or Guernsey, and, as it was said,
about seventy people were drowned.

I have seen a Divine Providence attend earthly affairs;
and I may mention some things that appear to be of but little importance to some;
and such as do not duly consider these things, may make a wrong application;
yet my travels have afforded a variety of trials and transactions,
which are in some things very peculiar,
and there is a willingness in my mind to favor some who
have been desirous I should leave a journal of my life,
as far as I can see my way clear in the Truth.

We went on board another ship called the Arundel, Splenden Rand, master,
in which we embarked the 17th of the ninth month, 1700, and after many storms,
and much sea sickness, not without some conflicts of spirit,
more than I am free to express, and a long passage,
being nearly sixteen weeks upon the sea, we arrived in the river Patuxent, in Maryland,
as near as I remember, the 5th or 6th of the first month, 1701, and my heart was glad,
and filled with acknowledgments and praises to the Lord,
for bringing us safely over the mighty waters.

We left the ship and master, who was a churlish, ill-natured man.
I was very weak and low, both in body and mind, when I landed, but the Lord helped me,
and made my journey and labor comfortable to many, as well as to my own soul.
After the first or second meeting we were at, John Estaugh being my companion,
as we came near a great house in Maryland, I espied a little white horse,
the sight of which put me in mind of a dream I had on board the ship before I landed,
in which I thought I got a little white horse, which carried me well, and many miles.
I said to the Friends with me.
Let us call at this house, which we did, and upon inquiry about a horse,
the man said he had none but a little white young galloway, as he called it,
which he was willing to sell, and told us, it carried him one day forty miles.
He asked eight pounds sterling for it, and I bade him five pounds sterling;
the man`'s wife coming up the passage, heard what I had offered,
and she said to her husband.
It is enough: so I had him, and a good horse he proved, and carried me,
by a moderate computation, four thousand miles.
I took this, according to the nature of it,
to be a favor from that great Hand which led me forth,
and hitherto has preserved me in the land of the living, to praise his ever worthy name.

We set forward towards Virginia and North Carolina,
and found great openness in these two provinces amongst the people,
and a tender-hearted remnant of Friends scattered in these wilderness countries.
Although, as I said before, I was brought very low, yet the Lord, in whom I did,
and yet do believe and put my trust, raised me,
and many times filled my heart with his word and testimony,
so that sometimes it went forth as a flame of fire amongst the loose libertines,
who were proud and unfaithful, yet professors of the Truth;
and we had many large and good meetings.
One thing is worthy of notice; as I was speaking in a meeting in Virginia,
a sudden stop came upon me, and occasioned me to say, I cannot go forward,
whatsoever the matter may be, I know not; but giving over immediately, a Friend,
whose name was Edward Thomas, began to preach, who was but young in the ministry,
though an elderly man, and apt to be attended with reasonings.
He said after the meeting, he had sought to the Lord with prayers,
that he would condescend so far to his request, as to give me a sense of him,
and in so doing he would take that as a great strength and confirmation to his ministry,
in this day of many exercises and great fears; or much to the same effect.
Thus we see the Lord in his great mercy condescends to the low, weak, and as it were,
infant states of his children, like a tender father, and being our heavenly high priest,
is touched with a feeling of the infirmities of his people;
thanksgiving and honor be given to his most excellent name, now and forever.

During our stay in Virginia, being at a Friend`'s house, an ancient widow,
I observed several persons of note come into the yard, a store-house being near, to make,
as appeared afterwards, a seizure for rates for the government and priest.
Not being distinctly charged, but a mixed rate,
it occasioned Friends to be straitened about the payment of them.
Observing the priest to be there, and very busy, I asked what he was come about:
the Friend replied they were come to make distress for the forty pounds per poll,
as they phrase it, which is forty pounds of tobacco, payable for every taxable head,
i.e. all above sixteen years old.
There were along with the priest, the sheriff and constable for the government,
and several merchants of note as spectators.
Understanding the reason of their coming, I stepped out to the priest,
who seemed a topping brisk man, his temper in this case not unsuitable to his name,
which was Sharp; and desired him to be careful how he devoured widows`' houses;
he briskly replied, he did not; to which I as closely returned, that I found he did.
He denied my assertion, and said the government gave him what he demanded and took;
to which I gave the following answer: Inasmuch as he did not anything for the widow,
for which he reasonably might require a reward,
I believed the government would not insist upon it for him,
if he would be willing to drop it, which in common equity I thought he should.
The priest, displeased with this modest reply, tartly answered, you are no Christians.
I told him, the charge was high and false, and he might more easily affirm than prove it;
wherefore I put the question, and asked him, why we were so charged by him;
to which he returned this insignificant answer,
that we denied part of the divinity of Christ.
I told him, he was a novice, and differed in his opinion from most of his brethren,
seeing it was a general reflection cast on us by most of his fraternity,
that we acknowledged the divinity of Christ, but denied his manhood,
which was false also; therefore I demanded of him,
to prove what part of the divinity of Christ we denied; in which if he failed,
I should look upon him as a false accuser, and those present would, I hoped,
be my witnesses.
He shuffled and declined answering, though I urged him as much as possible;
and to cut the matter off, he asked, from where I came.
The sheriff bid him give me a verse in Greek; I told them,
I mattered not meddling in that,
for as the English tongue was best understood by those present,
I thought it would be best to keep by it.
I told him, I was of Old England; but still reminded him of proving his assertion,
which I looked for from him; but instead of that, he asked,
what part of Old England I came from: I told him Yorkshire;
and bid him produce his proofs, as before urged, but still evading the matter,
he desired to know from what place.
I told him, I was born at North Cave; and, said he, I was born at South Cave,
and my father was minister there many years, his name was Sharp,
and there is but a mile difference between those places: I said it was a long one.
No sooner was this over, but the priest, transported with my being his countryman,
began hugging me to such a degree, that I was quite ashamed of him.
When I had got clear of his embraces, though not without some difficulty, I asked him,
if he esteemed himself a minister of Christ: he answered, yes,
and lawfully called thereto.
I told him, if he was a Gospel minister, as the Gospel was free,
so should his ministry be free; and turning to the people there present,
I told them I would not have them deceived,
for they might understand he only possessed his
place by virtue of a law in that case provided,
and his call and ordination was only such as had been conferred upon him for a fee,
which made him require pay for what he did, and indeed where he did nothing,
which was highly unfair;
wherefore they might upon consideration find he was but a minister of the letter,
which was dead, and not a minister of the Spirit and Divine Power;
from which he did not offer to clear himself, though I urged him thereto.
Then I asked him,
from which of those odious characteristics that the
false ministers were branded with in the New Testament,
he would clear himself: which I then enumerated to him; The sheriff said it was so;
and said, "`Mr. Sharp, answer the man, for the question is very rational,
and you ought to answer him, and for honor-sake clear yourself of those odiums,
if you can.`"
But he would not offer to meddle with it; wherefore I told him, to mind for the future,
not to charge any man or people with more than he could be sure to prove;
for it was highly scandalous.
It being now meeting time, I asked him to go there; but he refusing, said he dared not;
so we parted.

Having visited Friends here, we returned back for Maryland and Pennsylvania,
and we found a great many who loved to hear the testimony and doctrines of Truth,
but too few who took up the cross daily, and followed Christ in the way of self-denial,
and knew the thorough work of regeneration,
so as to have their garments washed and made white in the mystical blood of the Lamb.
These are not polluted with the sins and iniquities of the world,
who have experienced this blood to sprinkle the heart from an evil conscience:
these are capable of serving the living God;
and coming from the laver or pool that truly washes, there is none unfruitful,
but every one bearing twain, and they are inwardly clean and fruitful to God,
and walk with him,
whose bright and shining lives are also fruitful to the world that will receive them.
Read this, you that have known something of the work of conversion,
and consider the great difference there is between the bright lives of the virtuous,
and the dull and cloudy lives of the vicious, and be sure you look well,
which of these you most resemble in yours.

When we came into Pennsylvania, my companion before mentioned, whom I loved well,
told me he must go back to Virginia.
It became an exercise to us both, for I could not see my way clear to go back,
having been twice through that province.
When no other way appeared, but that we must part,
for my way appeared clear for the Jerseys, Long Island, Rhode Island and New England,
I held it needful that we should call the Friends and
elders of Philadelphia and thereabouts together,
to let them know how we parted, for we parted in much love and tender-heartedness;
that if any reflections should be cast upon the Friends there concerning us,
because of our parting, they might set those things in their proper light;
so taking our leave of our dear friends in these parts,
I traveled without any constant companion.
Sometimes I fell into company with Elizabeth Webb and Sarah Clement,
who were virtuous women, and lived near the kingdom,
and were of good service in their travels, and grew in the Truth, of which,
while with them, I was sensible.
We traveled under great care and circumspection,
both for our own good and avoiding offense, as became our places and holy profession,
that in all things we might adorn the Gospel of the kingdom,
a dispensation of which was committed to us to preach to others.
I had good service for the Lord, and great satisfaction in my own mind in these parts,
the Lord helping me by his mighty power through all my trials,
as my heart was devoted and resigned to answer his requirings.

I had great openings in several places in New England, and it appeared clear to me,
and sometimes I spoke openly of it,
that the Lord would gather a great people to the
saving knowledge of the Truth in his time,
notwithstanding what many of our Friends had suffered in these
parts from the predecessors of the present inhabitants,
for the name of the Lord and the testimony which they held.
The view of the state of these things,
especially the great sufferings of many of our faithful Friends,
put me in mind of this saying, The blood of the martyrs is the seed of the church;
and in this case, I believe it will be fulfilled in its season.

One passage happened, which I think not fit to pass over in silence.
A man who was brother to a Presbyterian priest,
came into a meeting in the eastern parts of New England, in order to oppose Friends.
He had often been very troublesome, as Friends said,
and in the beginning of the meeting he desired to have liberty to ask some questions.
Being a stranger, and not having so much as heard of the man,
and none making reply to him,
I felt a liberty in the Truth to return the following answer in behalf of the meeting.
That I did apprehend it was the desire of Friends,
inasmuch as the meeting was appointed for the worship of God,
and not for asking questions, or for controversies,
that the chief part should first be answered;
and I also thought the meeting would be willing, in the conclusion,
to give him liberty to ask the questions,
if his intent therein was for information or satisfaction, and not for contention.
Friends were silent, and the man submitted to what was proposed,
and a good meeting we had, the Lord`'s heavenly power and living presence being with us,
and the substance was felt among us, and exalted over all the shadows and types;
and Christ the true bread and living water, the light and life of the world,
was exalted that day; and the mighty God and Father, with his beloved Son,
through the help of the Holy Spirit, was glorified, who is worthy forever.

Near the conclusion of the meeting, the man began to speak well of what he had heard,
particularly touching water baptism, which he said, he had nothing to object against;
but as to the sacrament, as he called it,
because little or nothing had been said about it, therefore he concluded,
we either denied or disused it; or words to the same purport.
I stood up and said I did not remember that the word sacrament was used in all the Bible;
but I supposed he meant the bread and wine; he answered he did.
I asked him whether he was of the same mind as the Episcopal church;
if not of the same mind, he might say so; for they say,
the bread and wine is an outward and visible sign of an inward and spiritual grace, etc.;
what said he to it?
He was some time silent; then I asked him, how long he thought that sign was to continue?
He replied, to the end of the world.
I answered, he did not read in all the Bible,
that the Lord had appointed any figure or sign but what was to end in the substance,
which is to be witnessed and enjoyed in this world,
and not put off to the end or conclusion thereof, as his argument seemed to declare,
by his urging,
that the sign of that divine substance must remain till the end of this world.
I asked him what he could answer to that: he turned off with only saying,
I was too great a scholar for him, and so he would not meddle with me.
He was then silent, and there being many people,
I had a fine opportunity to open to the tender-hearted and Friends present,
how that was at best but a sign, which the people eat and drank outwardly,
in remembrance of Christ`'s death until he came;
but that I could now prove plenteously from the New Testament, that the substance,
the grace, was come and urged many proofs out of the Scriptures to the same purpose.
What I said so reached a good-like old man, a Presbyterian, that he confessed with tears,
he had heard much said upon that subject, but had never heard it so opened before;
and said he believed I was in the right.
The meeting broke up in a good frame, and Friends rejoiced that Truth came over all,
and the contentious man was silenced.

When the meeting was over, the goodly old man took me to the door,
and asked me what a man should do in case of a solemn league and covenant,
he being entered into it.
I told him I needed not to direct him,
for he had that in himself which would show him what he should do;
for if one should make an agreement or covenant with hell and death,
in the time of ignorance and darkness, and now the true light discovered it to be so;
the same light which discovered and manifested it to be wrong,
as he was faithful to the same, would show him how and when to break it,
and every other wrong thing; to which light I recommended him,
and bid him take heed to it; which, he said he hoped he should;
and so I left him with tears on his cheeks, and passed on.

I omitted one thing which happened in that part of New England,
near New York and Long Island, although I was twice backward and forward,
yet to be brief in my travels through those countries,
intended to make one account serve.
As I was speaking in a meeting, there came a great damp over my spirit,
and in that time came into the meeting several men,
occasioned by a topping and great man in the world,
who had given them an expectation that they should hear how he would oppose the Quakers;
but in a short time Truth rose, and Friends generally heard a man say to this disputant.
Why do you not speak?
He hushed him with saying, The man is upon the subject which I intend to oppose them with.
After some time the man was urged again to speak to me, with a Why do you not speak?
We heard him say.
The man has opened the thing so as I never heard it before, and I have nothing to say;
and to his own, and the wonder of his neighbors, he sat down upon a seat near the door,
and wept tenderly; so it was a good time to him and many more,
for the Lord`'s mighty power was amongst us.
In my return from my journey in the eastern parts of New England,
the same man desired me to have a meeting at his house;
and after due consideration and the approbation of Friends, who desired it might be so,
when they knew it was his request, a meeting was appointed,
and I heard there were likely to be at it a great many
of the higher sort of Presbyterians of his neighborhood.

I went to the meeting under no small concern of mind,
but when I was come into the great house,
I was very much affected with the wise conduct of the man,
to see in what excellent order he had placed everything,
so that I could not find wherein anything could be amended;
and a heavenly meeting it was, without any opposition.
At the breaking up of the meeting, this tender man,
whose heart was broken and opened by the power of Truth, said audibly,
his heart and house were open to receive me, and such as me,
let all say what they would to the contrary.
But what the subject matter was at the first meeting when he came in, I have forgotten;
it was enough and that we remembered we had a good heavenly meeting,
and were truly thankful for the same to Him who was the author thereof.

I and some other Friends being in our passage by
water in a vessel bound for Rhode Island,
and meeting with high and contrary winds,
we put into a creek some miles distant from Rhode Island,
and desired the people to procure us some horses to ride on,
and we would pay them anything that was reasonable,
but hoped they would not make a prey of us, for we were strangers,
and they ought to do to us as they would be done by, if they were in a strange land,
as we were.
There came up to us a goodly old man, and asked us what people we were,
if we were not Quakers?
I told him we were in scorn so called, but we did not much mind names,
for there was but little in them.
He was a brisk talking man, and said,
"`There was a man here lately who said he was a Quaker, and borrowed a horse,
and when he was gone some miles from this place, he offered to sell the horse;
I know not,`" said the man, "`but you are such as he.`"
I returned this answer to the reflection:
That this was a great proof we were an honest and reputable people where we were known,
for when a man is so wicked as to become a notorious cheat,
he will cover himself under the best name he can think of,
otherwise he might have said he was a Baptist, or a Presbyterian, or an Episcopalian,
and desired you to lend him a horse; but you mind not these names,
neither does the wicked man think he can pass so well under any of these last,
but under the first; and the reason of it I leave you to judge.
The old man asked no more questions, but used his endeavors to get us horses,
and a man and horse to go with us, to have the horses back again,
and we were well mounted; but before we set forward,
he took me to his house and was very courteous,
for though we had spoken for some victuals in as short a time as well might be,
he invited me to drink, and brought of his apples and beer,
which he would have my friends to partake of, for he said, and we found it true,
it was but a poor inn.
The old man and I parted very lovingly,
and I gave him a piece of money to show my gratitude
for his civility and good service to us.

The people looked upon us as some great wonder, for I heard one say, Are these Quakers?
Well, said he, they look like other people.
How we had been represented, and by whom, it is not hard to gather,
for it is very apparent,
that the same spirit and the same enmity continues in
some of the inhabitants of that country,
of which our Friends formerly felt the severe effects.
They are since somewhat moderated by the government there,
which is of a more mild and Christian disposition; although I am well assured,
that many of the more conscientious and thinking
people in those parts of the world begin to see,
and many will see and understand in time, that hanging and taking away lives,
for the sake of religion, is opposite to Christ,
and the nature of the true religion which is wrought in man by the operation,
quickenings, and in dwellings of the Holy Spirit.
As it is regarded and followed,
it leavens and brings the soul of man in some degree to put on the purity,
heavenly image, and nature of Christ, which is love, praying for enemies,
and is not for destroying, but saving lives;
how far the reverse will agree with that religion taught by Christ,
and practiced by him and the apostles, I would have all seriously consider in time.

While we were in Boston,
when one of the aforementioned worthy women was declaring excellently,
both with good utterance and voice, and good matter,
as the manner of the inhabitants of Boston had been for many years to encourage,
or at least allow a rude mob to bawl and make a noise, so they did now,
that it was hard to hear so as to understand distinctly what the Friend said,
although she spoke plainly and intelligibly.
It did very much grieve me to see the ignorance and
darkness of those high professors of religion,
and when the Friend had done, observing there appeared men of some note in the world,
I requested them to hush the rabble, for I had something to say,
which I desired them to make known to the governor and chief men of the town;
so they soon quelled the noise.
Then I told them, that in case we were as erroneous as some might insinuate we were,
that was not the way to convince us of our errors, neither to bring us out of them,
but rather to establish us in them; and that was not the way for them to gain proselytes,
but the way to lose many from them, and increase dissenters;
for what convincement could there be by noise and clamor, and hooting,
as if they would split their own lungs.
I had come a great way to see them, and what character could I give of them.
I never thought to have seen so much folly
amongst a wise and religious people as I now saw:
tell the governor and chief men of the town, what the Englishman says;
for I am ashamed of such doings.
It had a good effect, for when I came after, we had quiet meetings;
and I understood by a letter from Daniel Zachary, of Boston, to Old England,
that the governor said I was in the right,
and ordered that peace should be kept in Friends`' meetings there;
and I never heard to the contrary but it is well yet as to that.
We had great reason to be truly thankful to the Lord for these and all other mercies,
that He, the fountain of all good, is pleased to favor us with.
As an instance of the Lord`'s mercy to many poor sufferers,
and to show the implacable envy of these people to Friends, the case of Thomas Maulham,
of Salem, may suffice, in some measure,
who was a great sufferer in the time of hot persecution.
When the persecutors had stripped him of almost all he had; not content with that,
they came with axes, and hewed down all the apple trees in his orchard,
which was a large one, and left the stumps about the height of a man`'s knee.
As Thomas Maulham said, they took the way, as they thought, to ruin him,
but the Lord turned it into a blessing, for the trees grew to admiration,
and came to bear fruit abundantly, and a finer orchard I have not seen in all my travels,
for the size of it; let the Lord be sanctified by all his people,
and admired by all them that believe.

I went with several other Friends from Salem Yearly Meeting,
which was a large and good meeting, towards Dover, and coming to a river,
a Friend took my horse, with two more, into the boat,
and by the time I came to the river side, the boat was sinking,
and the ferryman made a lamentable cry, saying, The boat is sunk,
and we shall be all drowned.
It was so ordered, that there was but one Friend in the boat with the boatman,
and I do not remember that ever before now my horse was in any boat and I not there;
which I looked on as the mercy of a kind Providence to me,
and to several other Friends in company.
Hearing the noise and the floundering of the horses when tumbling into the water,
I called to the men to be sure to take care to free
themselves of all the tackling of the horses,
as bridles, stirrups, etc., and catch hold of my horse`'s tail,
and he would bring them both on shore; but if they trusted to the tackling,
when the horses swam, they would fail them, unless very strong;
and to hold by the bridle was the way to drown both horse and man.
This advice was given while they had the horses in their hands;
and the boatman being a lively youth, took my advice, caught hold of my horse`'s tail,
it being long, which I ever approved of among rivers, and calling to my horse,
he came quickly with the man ashore, but left the honest old Friend, Ezekiel Waring,
to whose house we intended to go that night, in the river floating to the neck,
a hundred yards from the shore by computation, yet watchful Providence did so attend,
that his life was preserved to a wonder.
He missed taking my advice, and caught hold of the stirrup, and the girth broke,
as they are apt to do if they be tight when the horse begins to swim,
which brought off the saddle and pillion, and the oar of the boat and his hat,
which with the pillion-seat being in his arms,
just bore up his head above water for some time.
His poor wife seeing the danger to which her husband was exposed,
fell into a fainting fit; there being neither house, man, or boat,
to be seen on this side of the river but ourselves and the boatman,
and the stem and stern of the sunk boat full of water.

There was a house on the other side of the river, which was half a mile over.
The ferryman did his best to get a boat or canoe, and although it began to be dark,
yet he found a canoe, which is made of a fine piece of timber,
hollowed in the form of a boat, and generally will carry but two or three or four men.
Coming to us, he asked if Ezekiel was alive: I told him he was, but very weak,
for I had often heard him blubber in the water; I encouraged him,
that he might not faint in his mind, for I told him,
I yet believed his life would be preserved; he would very faintly say.
Unless help came, he could not hold it long.
I went on by the waterside, and laid me down often on the land,
not much regarding wet or dirt, sometimes tumbling over logs of wood and limbs of trees,
for so it is in these uncultivated places,
and I directed the man with his canoe where the poor Friend was,
as nearly as I could tell by my last observation,
and desired he would turn the stern of his canoe to him,
as he could not lift him into the canoe;
neither to let him lay his hand upon the broad side of it, but upon the stern,
lest he should overset it, and they be both drowned: he did so,
and brought him gently on shore, to the great joy of his loving wife and of us all.
The boatman, as he acknowledged, had found my counsel good,
and therefore would have me tell him what he must do now.
I bid him fetch the boat to shore by the fowler or rope,
and then go and carry Ezekiel in the canoe to the inn on the other side of the water,
that he might dry, warm, and refresh himself until we came;
in the mean time we cleared the boat of water, which, when done,
we put two horses into it, and I towed my horse at the boat`'s stern,
to make room for several, especially the good women before mentioned,
who were at this time in my company, and not without their exercise any more than myself.
We got well over, and then the ferryman and Friend on the other side,
brought the horses that were left, being three, which were enough for the boat,
and proved too many the first time.
We found the good old Friend finely and well recruited,
and got to his house about midnight, where we were glad,
and our hearts were full of praises to the Lord for
this great and eminent deliverance and preservation.

In this first visit, while in Rhode Island, I met with something worthy of your notice,
if you are such a reader as I wish you may be, which was thus: Being in Rhode Island,
several Friends came to me in some of the intervals of the Yearly Meeting,
for it held several days, both for worship and discipline,
to inquire whether it was usual in our part of the world to let the young,
and such as had appeared but little in testimony,
come into the meetings of public Friends.
I said, yes, if they were of clean lives, and what they had to say was approved;
and it was very likely such might need advice as much as those
who were come to more experience in the work of the ministry,
if not more.
This was some means of enlarging the said meetings of ministers now coming on.
When I came into the meeting, several of the elders desired me to go into the gallery,
which I refused, the concern upon my mind being so great,
I thought it was enough that I could but get into the house,
and sit down amongst the lowest rank.

This meeting was one not to be forgotten,
because of the eminent visitation from the Lord that was upon us in it.
I have not often seen the like.
I question if there were any dry cheeks for some time in it;
and the manner of the working of the heavenly power was remarkable,
in order to the sanctifying and preparing vessels for the Lord`'s use.
He broke us down by his judgments from following flattering flesh,
and the pleasing vanities of the world, and the subtle baits of Satan,
and by the tenders of his love, engaged us to follow the heavenly and inward calls,
knocks and reproofs of his Holy Spirit, and to obey the dictates of the same.
When the Lord prepares in a good degree for this work of the ministry,
many have been unwilling to give up and obey,
until they have tasted of the Lord`'s displeasure, and in part of his judgments,
which have brought them into submission; after which they went out,
sometimes with their lives in their hands, and became a wonder to men,
bearing their reproach, and sometimes appeared in great congregations,
sometimes in noises and tumults, and sometimes were in watchings and fastings,
in weariness, hunger, and in cold, with much more,
for the name of the Lord and his testimony, and for the enjoyment of peace,
and his internal presence, who separated us to this work by the Holy Ghost.
And it is by our abiding faithful to the same,
that we are preserved in a capacity of persevering through all to the end,
to the mutual help and comfort one of another, and renown of the name of the Lord,
who is worthy now and forever.

We also had a very large meeting on this island in an orchard,
where I had good service for the Lord:
I remember I was much concerned about the two ministrations, namely,
John`'s baptism with water, and Christ`'s with the Holy Ghost,
it being clear from John`'s words,
that he saw to the end of his own dispensation when he declared, he must decrease,
but Christ must increase;
which is generally understood to relate to their differing dispensations.
The first was to baptize unto repentance, the other to the purging of the floor,
and burning up of that which was combustible, namely, the chaff and stubble,
which the Lord`'s baptism burns up inwardly, and which no elementary thing can do;
for if all the eatings, washings, observations, and ceremonies under the law,
although commanded and enjoined to Israel by the Lord,
could not make the comers thereunto perfect,
how should these or any of them now perfect the Gentile world when not commanded,
as they never were to us?
What I had upon my mind, as I received I went through with, and showed the beginning,
use and end of the watery dispensation,
and the use and continuance of Christ`'s spiritual baptism to the end of the world.
The meeting broke up, and Friends went into an upper room in an inn;
but I felt such an exercise upon my spirit that I could not eat,
but desired Friends to be easy, and I would eat as soon as I could;
and while I was walking over the large chamber alone,
there came up three men whom I knew not, or what they were,
but it sprang livingly in my heart to set my eyes on them in the Lord`'s dread,
and so I did.
They passed away, and I was told afterwards,
that they were three Baptist preachers who had been at the meeting, and came to see me,
with a design to have a dispute with me; but, they said I looked so sharply,
they dared not meddle with me.
Thus the Lord in a good degree wrought for me, blessed be his worthy name forever.

Now I leave the account of my travels in those parts, and enter upon my second,
with my honest companion, James Bates, who was born in Virginia,
and traveled much with me through many provinces, and some islands,
and we had good service together.
It was much with me, when on Rhode Island, to visit Nantucket,
where there were but very few Friends; Peleg Slocum, an honest public Friend,
near Rhode Island, intending to carry us in his sloop to Nantucket that night.
He thought we had been close in with our desired landing place, but we fell short,
and night coming on, and having but one small canoe to put us on shore,
which would carry but three people at once, we went on shore at twice,
and left the sloop at an anchor.
It being dark, we thought we were going up into the island among the inhabitants,
but soon found that we were upon a beach of sand and rubbish,
where was neither grass nor tree, neither could we find the sloop that night,
though we sought it carefully, and hallowed one to another till we were weary,
so that we were forced to settle upon our little island, from the center of which,
one might cast a stone into the sea on every side.
Here we stayed that night, not knowing but the sea, when at the height,
would have swept us all away, but it did not; there I walked, and sometimes sat,
until morning, but slept none; at last the morning came, and the mist went away,
and we got on board again, and reached the island about the ninth or tenth hour.

The master was willing, at our request, to land three of us, namely, myself,
my companion, and Susanna Freborn, a public Friend,
who had had a concern upon her mind for some time,
as she signified to Friends in Rhode Island, where she lived,
to visit the few Friends in Nantucket,
and Friends thought this was a proper season to pay that visit.
She was a woman well beloved, and in good unity with Friends.
We landed safely, and as we went up an ascent,
we saw a great many people looking towards the sea, for great fear had possessed them,
that our sloop was a French sloop loaded with men and arms,
who were coming to invade the island.
I held out my arms and told them, I knew not of any worse arms than these on board.
They said they were glad it was no worse, for they had intended to alarm the island,
it being a time of war.
I told the good-like people, for so they appeared to me, that Peleg Slocum,
near Rhode Island, was master of the sloop,
and that we came to visit them in the love of God,
if they would be willing to let us have some meetings amongst them.
They behaved themselves very courteously towards us, and said they thought we might.

We then inquired for Nathaniel Starbuck, who,
we understood was in some degree convinced of the truth,
and having directions to his house, we went there.
I told him, we made bold to come to his house, and if he was free to receive us,
we should stay a little with him, but if not, we should go elsewhere;
for we heard he was a seeking religious man, and such chiefly we were come to visit:
he said we were very welcome.
By this time came in his mother Mary Starbuck,
whom the islanders esteemed as a judge among them,
for little of importance was done there without her, as I understood.

At the first sight of her it sprang in my heart.
To this woman is the everlasting love of God.
I looked upon her as a woman that bore some sway in the island, and so I said,
and that truly, we are come in the love of God to visit you,
if you are willing to let us have some meetings among you.
She said she thought we might;
and further said that there was a Non-conformist minister who was to have a meeting,
and they were going to it,
and she thought it would be the best way for us to go with them to the meeting.
I showed my dislike to that for these reasons; first,
we did not need to hear what that minister had to say,
because some of us had tried them before we came there,
meaning the Non-conformists of several sorts, and if we should go,
and could not be clear without speaking something in the meeting, he might take it ill.
But as we understand there is another meeting
appointed at the second hour for the same man,
and as we look upon ourselves to stand upon equal
ground in a religious capacity with other dissenters,
if we should appoint our meeting at the same hour,
then the people will be left to their choice to which meeting they will go.
The woman approved of the proposal, and said, "`Indeed that was the best way.`"
The next consideration was, where shall the meeting be?
She paused awhile, and then said, "`I think at our house.`"
I from this gathered she had a husband,
for I thought the word our carried in it some power besides her own,
and I presently found he was with us.
I then made my observation on him, and he appeared not a man of poor abilities,
but she far exceeded him in soundness of judgment, clearness of understanding,
and an elegant way of expressing herself, and that not in an affected strain,
but very natural to her.

The meeting being agreed on, and care taken as to the appointment of it, we parted,
and I lay down to try if I could get any sleep,
for I have showed before what sort of a night the last was with us;
but sleep vanished from me,
and I got up and walked to and fro in the woods until the meeting was mostly gathered.
I was under a very great load in my spirit; the occasion of which was hid from me,
but I saw it my place to go to meeting, the order of which was such,
in all the parts thereof, that I had not seen the like before;
the large and bright rubbed room was set with suitable seats or chairs,
the glass windows taken out of the frames, and many chairs placed without,
very conveniently, so that I did not see anything lacking, according to the place,
but something to stand on, for I was not free to set my feet upon the fine cane chair,
lest I should break it.

I am the more particular in this exact and exemplary order than in some other things,
for the seats both within and without doors were so placed,
that the faces of the people were towards where the public Friends sat, and when so set,
they did not look or gaze in our faces, as some I think are too apt to do,
which in my thoughts bespeaks an unconcerned mind.
The meeting being thus gathered, and set down in this orderly manner,
although there were but very few bearing our name in it,
it was not long before the mighty power of the Lord began to work,
and in it my companion did appear in testimony in the forepart thereof.
While he was speaking, a priest, not the one before mentioned, but another,
threw out some reflections upon him, and the people for his sake,
which I did not see the least occasion for; after which he went away.

I sat a considerable time in the meeting before I could see my way clear to say anything,
until the Lord`'s heavenly power raised me,
and set me upon my feet as if one had lifted me up;
and what I had first in commission to speak, was in the words of Christ to Nicodemus:
"`Except a man be born again, he cannot see the kingdom of God;`" with these words.
No, the natural and unregenerate man cannot so much as see
the heavenly and spiritual kingdom of Christ,
which stands not only in power but also in righteousness,
joy and peace in the Holy Spirit.
I told them that to be born again, was not to be done unperceivably,
no more than the natural birth could be brought forth without trouble;
and to pretend to be in Christ and not to be new creatures, is preposterous;
and to pretend to be new creatures,
and yet not be able to render any account how it was performed, was unreasonable;
it could not be, as I urged before, without our knowledge; for to be born again,
signified to be quickened and raised into a spiritual and new life,
by which the body of the sins of the flesh is mortified,
and we come to live a self-denying life.
Those who are crucified with Christ, are crucified to their sins,
that as he died for sin, we might die to sin: in this state we live not after the flesh,
although we live, as the apostle said, in the flesh; but the life which these live,
is through faith in the Son of God: and to have all this, and much more wrought in us,
and we know nothing of it, is unaccountable.

As I was thus opened, and delivering these things, with much more than I can remember,
the woman +++[+++Mary Starbuck]
I felt, for most of an hour together, fought and strove against the testimony,
sometimes looking up in my face with a pale, and then with a more ruddy complexion;
but the strength of the truth increased,
and the Lord`'s mighty power began to shake the people within and without doors;
but she who was looked upon as a Deborah by these people,
was unwilling to lose her outside religion,
or the appearance thereof When she could no longer contain,
she submitted to the power of Truth, and the doctrines thereof,
and lifted up her voice and wept.
Oh! then the universal cry and brokenness of heart and tears were wonderful!
From this time I do not remember one word that I spoke in testimony,
it was enough that I could keep upon the true bottom,
and not be carried away with the stream above my measure.

I might add much more concerning this day`'s work,
but I intend not to say anything to the praise of the creature,
but to the renown of the mighty name of the Lord of Hosts,
and let all flesh lie as in the dust forever.
While I continued speaking in this state, as before mentioned,
and thus swallowed up in the internal presence of Christ,
where there was no lack of power, wisdom, or utterance,
I spoke but a sentence and stopped, and so on for some time:
I have since thought of John`'s being in the spirit on the Lord`'s day.
If it had been a state to be continued in,
I am of the mind I should not have been sensible of weariness,
neither of hunger nor pain.
This is a mystery to many, yet these are faithful and true sayings,
you may read that can; but there are none who can know the white stone and new name,
but they who have it;
there are none who stand upon mount Zion with harps of God in their hands,
but only such as have come through great tribulations,
and have washed their garments and made them white in the blood of the Lamb.
To these are the seals of the book of the mysteries of the glorious kingdom opened;
these are called out of nations, kindreds, tongues and people;
these are redeemed out of the fallen and earthly state of old Adam, into the living,
heavenly and spiritual state in Christ the second Adam; these cry holy;
the other part of the children of men cry unholy,
because they are not willing to cast down their crowns
at the feet or appearance of Christ in their own souls.
Although such with the four beasts may cry,
"`Come and see,`" yet are they not properly qualified
to worship the Lord God and the Lamb before his throne,
as the four and twenty elders did, and as all do, and will do,
who worship God in his holy temple in spirit and in truth,
according to his own appointment; who are not tied up to the canons, creeds, systems,
and dictates of men, much of which is beaten out of the wisdom, parts,
and natural comprehensions of earthly fallen man.

I return from this, which may seem a mysterious digression,
to the other part of what did happen concerning the meeting,
and come now to the breaking up thereof.
As extreme heats oft end in extreme cold, and as great heights frequently center,
as to man in this capacity, in great depths, and great plenty in great poverty,
which I have often seen to be good, in order to keep the creature low,
in fear and in a dependance upon the Lord,
I soon fell into such a condition that I was likely to die away.
When it was so, I with my companion made a motion to break up the meeting,
but could not for some time, for they sat weeping universally; then I told the meeting,
especially such as were near me, that if I should faint away,
I would not have them to be surprised at it;
for I was much concerned lest that should hurt these tender people;
my life was not dear to me in comparison of the
worth of the souls of the children of men;
but all this did not break up the meeting.
After some time Mary Starbuck stood up, and held out her hand,
and spoke tremblingly and said, "`All that ever we have been building,
and all that ever we have done, is pulled down this day;
and this is the everlasting truth;`" or very nearly these words.
Then she arose and I observed that she, and as many as could well be seen,
were wet with tears from their faces to the fore-skirts of their garments,
and the floor was as though there had been a shower of rain upon it; but Mary,
that worthy woman, said to me,
when a little come to consider the poor state that I was in,
"`Dear child, what shall I do for you?`"
I said, "`A little would do for me;
if you can get me something to drink that is not strong, but rather warm,
it may do well.`"
So she did, and I went unto her son`'s, where my clothes were, that I might shift me,
for I felt sweat in my shoes as I walked.

I mention this partly for the sake of such of my brethren,
who may be at any time in the like case, to take care to keep out of the cold,
and beware of drinking that which is cold, neither is brandy good,
for it feeds too much upon the weakened vitals;
but in all things endeavor to possess your vessels in sanctification and honor.
As it is not in man`'s power to make the vessel clean nor prepare it,
therefore if the Lord does,
with your obedience through the work of his grace and Holy Spirit,
fit your vessel for his work and service, take this caution,
see that you neither destroy, defile, nor hurt the same.
But it may be, some have done all these, some one way and some another.

I remember Peleg Slocum said after this meeting, that the like he was never at;
for he thought the inhabitants of the island were shaken,
and most of the people convinced of the Truth: however,
a great convincement there was that day, Mary Starbuck was one of the number,
and in a short time after received a public testimony, as did also her son Nathaniel.

After I was somewhat revived, my companion having a mind to speak to the priest,
to know why he did so reflect on him, desired me to go with him,
which I did with several more, and coming to his door, where he was set upon a bench,
James Bates asked him, Why he did so reflect?
He replied, he was in a passion, and had nothing against him: James forgave him,
and they fell into some debate concerning faith;
my friend urged the apostle James`' words, which are these,
"`As the body without the spirit is dead, so is faith without works, dead also.`"
The priest said, "`Dead faith is nothing, and has no being in the world.`"
I thought he appeared to be in the craft; and after they had tugged at it a while,
I said I found something in my mind to interpose, if they would hear me;
they both showed a willingness to hear what I had to say, and then I asked,
What belief or faith that was the devils had; for I did not understand,
but that although they believed there was a God, they remained devils still;
therefore the word dead is a proper word,
and properly adapted to that which any may call faith, and is not operative,
but a notion that may be received by education, by hearing or reading,
and not that faith which works by love and overcomes the world:
and because of its not working, being inactive and useless, it is fitly called dead:
what do you say to that?
He said I was too great a scholar for him.
I replied, there was no great scholarship in that.
He then invited me to stay all night,
and said I should be as welcome as his own children,
and he and I would dispute about that between ourselves.
I declined it, and showed these reasons for so doing; if he declined the debate publicly,
I would not debate it privately,
for then these neighbors of his would lack the benefit of it;
and so we parted with my saying, as it immediately sprang up in my heart.
You have been a man in your young years that the Lord has been near,
and favored with many openings, and if you had been faithful to the gift of God,
you might have been serviceable; but you have been unfaithful,
and a cloud is come over you, and you are laid aside as useless.

I was altogether a stranger to the state of the priest, nor had I heard anything of him,
nor indeed of the state of the inhabitants of the island, but what I heard afterwards,
mostly from Mary Starbuck.
As we walked from the priest`'s house towards our quarters,
she said everything she now met with did confirm her in the Truth;
for she knew this was indeed the state of the priest, as I had said,
being acquainted with him in his best state,
and then he had fine openings and a living ministry among them,
but of late a cloud was come over him, and, as I said, he was laid by and useless.
She also put me in mind of something I had said in the meeting about election,
which as near as I can remember was thus: I had endeavored to make one in the election,
and one born again, much the same;
for I had laid waste all claim to election without being born again;
for as Christ was the chosen or elect of God, who never fell,
could such who were in the fall be the branches of Christ, the pure heavenly vine?
Or such who were found in the impure state, and in the degeneracy,
by reason of sin and wicked works?
Or would Christ be married to a people, and become as their husband,
who were in an unconverted state?
Could this be the true church of Christ?
Could this be the Lamb`'s bride, who had departed from his spirit,
and was in the pollutions of the world through lust,
and running after the pleasures and fineries of the world, depending upon ceremonies,
and outside things and elements, which appear not to be essential to our salvation,
neither do we find life in them, nor conversion through them?
I was of the apostle`'s mind,
that "`Neither circumcision nor uncircumcision avails anything,
but a new creature:`" and what man in the world can say, that water,
although he may have been baptized or dipped into the same, has converted him,
or changed his state from a natural to a spiritual,
or from a dead to a living state in Christ?
Or, who that have gone through the most celebrated ceremonies, as some may account them,
had thereby got dominion over sin and Satan?

Having thus treated of these things among them, I said to Mary,
that she warred and strove against the testimony for a time: and as nearly as I remember,
she said their principle was, That such who believed once in Christ, were always in him,
without a possibility of falling away; and whom he had once loved, he loved to the end:
it was a distinction they had given to their church, to be called Electarians;
and as I said, or near it, she had no mind to be pulled out of her strong hold.
But when she saw the glory of Christ and the true church,
as the queen of the south saw Solomon`'s, and the glory of his house;
and as she had her questions and doubts answered, she had no more spirit in her,
or doubts or questions, but openly acknowledged, This is the Truth,
this is the glory I have heard so much of:
that spirit of doubting and questioning was swallowed up now,
by hearing and beholding for herself this greater than Solomon, his wisdom and glory,
and the great house that he had built.
The servants, the attendance, the excellent order, with the ascent to the house of God,
which were all wonderful in Solomon`'s house,
carried in them a lively resemblance of Christ, his power, glory and wisdom,
as also that order and mien which is seen among his faithful servants,
his church and people,
even such as our spiritual Solomon rules in and over by his spirit and power.
Here is Solomon or Man of Peace, elsewhere called the Prince of Peace;
and as Solomon ruled in Jerusalem, formerly called Salem, or City of Peace,
and indeed over all Judah, and over all his tribes,
so does Christ in his kingdom everywhere upon the face of the whole earth.
Learn this, see and know in and for yourself,
that you are truly translated out of the kingdom
of death and darkness into the kingdom of Christ,
which is a kingdom of power, life, light, peace and joy in the Holy Ghost.
I was much bowed down in my spirit, and in weakness, fasting, and in much fear,
for the more Truth appears, the more it brings the creature into self-abasement.

A passage is here revived to my mind, which was thus: After a large Yearly Meeting,
where were many able ministers, worthy William Penn, who was one of them,
taking me aside, said,
"`The main part of the service of this day`'s work went on your side, and we saw it,
and were willing and easy to give way to the Truth, though it was through you,
who appears but like a shrub;
and it is but reasonable the Lord should make use of whom he pleases: now,
I think you may be cheerful.`"
From which I gathered, that he thought I was too much inclined to be cast down;
therefore I gave him this true answer, I endeavor to keep in a medium,
out of all extremes, as believing it to be most agreeable to my station;
with this remark, the worst of my times rather embitter the best to me.
William shook his head, and said with much respect,
There are many who steer in this course besides you,
and it is the safest path for us to walk in;
with several other expressions which bespoke affection.

This worthy man, and minister of the Gospel,
notwithstanding his great endowments and excellent qualifications,
yet thought it his place to give way to the Truth,
and let the holy testimony go through whom it might
please the Lord to empower and employ in his work,
although it might be through contemptible instruments.
I sincerely desire this may prove profitable to those whom it may concern,
and into whose hands it may come, that the Lord`'s work maybe truly minded,
and given way to, when it is opened; for seeing no man can open it,
let not any strive in the man`'s part to shut the same.
I have at times seen something of this, which has not been altogether to my satisfaction.
A word to the wise may serve, I hope, and be sufficient for a caution,
for what I have written is in the love of God,
and under a concern that has been upon my mind at times, for some years,
to leave behind me a gentle caution to my tender friends of both sexes,
to have a special care in all things to recommend not only their gifts,
but their demeanor in them, as also their conduct after them,
to every man`'s conscience in the sight of God; so that you may build up the Lord`'s house,
and always have a great care,
that nothing you say or do may in any way tend to the hindrance of the Lord`'s work,
or to discourage the weakest in the flock of Christ, but labor to fasten every stake,
and strengthen every cord of Zion, and as much as you are capable,
build up the tabernacle in Jerusalem.
As God is a spirit, and the soul of man is a spiritual existence,
and as the soul and body of man become sanctified and prepared,
as a temple for the Lord by his Holy Spirit to tabernacle in,
the Lord is to such as a sanctuary to flee to, and rest in, from heats and from storms:
here is the Rock of the true church, and her place of defense, that is,
the name and power of the mighty God.
Oh! that all the inhabitants of the earth were acquainted with this name,
and rock of defense! they would not then be so much overcome, as they are,
with the power of the enemy of the soul, but would live above his region,
which is in the earth, or rather in the earthly hearts of men.
All you who have escaped the pollutions of the world, keep in your tents,
until the Lord moves and leads forward, and opens the way, sometimes as in a wilderness.

Read and understand from which these things have their rise,
for there is the church`'s safety, and its comeliness too in abiding in the Truth.
This is your place of safety, where the enemy has no power,
where the wiles of Satan and inventions of man cannot reach;
no enchantment has power over these,
renowned be the great name of the Lord now and forever.

How comfortable, how easy and pleasant are even all the books and testimonies,
and exhortations, that are given forth in the spirit, love and life of Christ! yes,
the very company and conduct of such who are preserved in the life,
becomes a sweet savor of Divine life to the living.
There is comfort and consolation,
a strengthening and building up one of another in the most holy and precious faith,
so that I find the truly quickened soul takes great delight to resort to,
and as much as may be,
converse with the awakened and truly quickened
souls who take up the cross of Christ daily,
and follow him in the way of self-denial,
although it be a way that is much spoken against,
by such who know not the nature and discipline of the holy cross,
and despise those who are the true followers of Christ.
To feel this essential virtue, seed or leaven of the kingdom, or salt of the covenant,
Christ, to work so effectually to the restoring of the powers and faculties of the soul,
into the first rectitude and purity, that all the malignity may be thoroughly purged out,
with all the dross or tin, which defiles the man,
and makes him unfit for the kingdom and for the service of God, is a great work.
Neither is the vessel preserved clean, when it is in degree cleansed,
but through great care, watchfulness,
and diligence in attending upon the Lord with great devotedness,
and resignation to his mind and will in all things.
Experience has taught us, as well as what we read in the Holy Scriptures,
that there are many combats to go through for such as are engaged in this warfare,
before the above-said states, deliverance from sin and Satan,
and a sabbatical or peaceful rest in Christ, can be obtained to the soul.

Come, you that love the light, and bring your deeds to the light,
and believe in the light, and have your body full of light,
by keeping your eye single to God,
and in and to all things that may tend to his glory and your duty;
you will become a child of the light, and receive the whole armor of light.
This is that which will arm you on the right hand and on the left.
Put off your own righteousness,
with which it may be your breast has been too much possessed,
and put on Christ`'s righteousness as a breast plate,
for it much emboldens in imminent dangers, and also at approaching death.
Wait upon him who has power,
that your feet may be shod with the preparation of the Gospel of peace;
so that as the Gospel power and Gospel ministry all tend to
gather into the ways of the Gospel and of virtue,
you may not fail to be a preacher of righteousness in
your walking and in your whole manner of life;
for this is one of the good ends for which the
Gospel power has reached and visited your soul,
namely, to purge it, and make it clean.
Take care to have upon your head the helmet of salvation,
which will be a strength and as a crown to you, not only in the many encounters,
but more especially m your last encounter with death;
and that you may have faith as a shield to put on, that you may overcome the world;
and above all things, take to yourself the sword of the spirit, which is the word of God,
that through this excellent armor of proof,
you may be able to quench all the fiery darts and temptations of the devil.

If you are a soldier of Christ, this is your armor;
these are your accoutrements which fit you for your vocation,
as a follower of the Lamb through many encounters with your enemies,
which armor will give you the victory, and bring you through many tribulations,
which is the way to the kingdom of heaven.

Now leaving the eastern parts of New England,
and these tender people on Nantucket Island,
with fervent supplications and prayers to the Lord of heaven and earth, that:
he will prosper his blessed work of conversion which he has begun amongst them,
and in all such upon the face of the whole earth; in the next place I came to Lynn,
to Samuel Collings`', where I had not been long before I met with an unusual exercise,
which I had expected for some time would fall upon me.

Having heard of George Keith`'s intention of being at Lynn Monthly Meeting the next day,
which as near as I remember, lies between Salem and Boston, the evening coming on,
as I was writing to some Friends in Old England,
one came in haste to desire me to come down, for George Keith was come to the door,
and a great number of people and a priest with him,
and was railing against Friends exceedingly.
I said, "`Inasmuch as I understand this Lynn meeting is, although large,
mostly a newly convinced people, I advise you to be swift to hear, but slow to speak,
for George Keith has a life in argument; and let us, as a people,
seek unto and cry mightily to the Lord, to look down upon us,
and help us for his name`'s sake, for our preservation, that none may be hurt.`"

The country was much alarmed; for, as Friends said,
George Keith had given notice two weeks beforehand,
that he intended to be at this Monthly Meeting,
and the people were in great expectation to hear the Quakers run down,
for George Keith had boasted much of what he would prove against Friends.
Soon after some pause, retirement,
and fervent seeking to the Lord for direction and counsel in this important affair,
I went to the rails, and leaned my arms on them near George Keith`'s horse`'s head,
as he sat on his back, and many people were with him; but the few Friends who were come,
stood with me in the yard.
My fervent prayers were to the Lord, that if he gave me anything to speak to George,
it might go forth in that power and wisdom which was
able to wound that wicked spirit in which he appeared,
and boasted over Friends after the following manner, crying,
"`Is here a man that is a scholar?
Is here a man that understands the languages amongst you, If so,
I will dispute with him.`"
I told him,
it was probable the English tongue was most generally
understood and used amongst that people,
and therefore I thought it was the best to keep to it.
He went on and said that he was come in the Queen`'s
name to gather the Quakers from Quakerism,
to the mother church, the good old Church of England,
and that he intended to exhibit in our meeting
on the morrow these charges following against us,
which, he said, he could prove we were guilty of out of our Friends`' books, namely,
Errors, heresies, damnable doctrines and blasphemies: Look, said he,
to answer for yourselves, for if you do not,
the auditory will conclude that what I exhibit against you is true.

I was roused up in my spirit in a holy zeal against his
wicked insults and great threatenings,
and said to him, That it was the fruit of malice and envy,
and that he was to us but as a heathen man and a publican.
Then he began to cast what odium he could upon Friends,
with such bitter invectives as his malice could invent.
I stood with an attentive ear and a watchful mind; for as I stood leaning upon the rails,
with no small concern upon my mind, I felt the Lord`'s power arise,
and by it my strength was renewed in the inner man, and faith, wisdom,
and courage with it, so that the fear of man,
with all his parts and learning was taken from me;
and in this state George Keith appeared to me but as a little child, or as nothing:
renowned be the most excellent name of the Lord, now and forever.
But this great champion, Goliath like, at least in his mind,
I supposed feared not any there; he overlooked us all,
and in the pride of his heart disdained us;
but the Lord of heaven and earth looked down upon us in a very acceptable time,
and helped us for his name`'s sake, and covered our heads in the day of battle:
glorified be his great name forever.

I have sometimes thought to omit some part of this account concerning George Keith,
but remember it opened clearly in my mind then, and I said to him,
That the hand of the Lord was against him,
and that he would pour forth contempt upon him for his disobedience and wickedness.

But to return to his reflections:
he said the Quakers pretend to be against all ceremonies,
but he could prove that they used many ceremonies, as taking one another by the hand,
and men saluting one another, and women doing so to one another, and he said,
that women did salute men; yes, they had done it to him;
as it was generally understood by those who heard him,
which I thought not worthy my notice.
He went on and said, the Quakers pretended to be against all persecution,
but they were not clear,
for the Quakers in Pennsylvania and the Jerseys had persecuted him,
and would have hanged him, but that there was some alteration in the government.

Then came out one of my arrows, which cut and wounded him deeply: I said,
"`George, that is not true.`"
Upon that the priest drew near, and appeared very brisk,
and said I had as good as charged Mr. Keith, as he called him, with a lie.
I replied, "`Give me time, and I will prove that which George said, is not true,
and then you and he may take your advantage to rescue him from that epithet of a liar,
if you can.`"
The priest said I knew not Mr. Keith: I replied, "`If you knew him as well as I did,
you would be ashamed to be there as an abettor of him.`"
The priest got away,
and troubled me no more in all the engagements that George and I had afterwards,
although the said priest was with him.
Then I demanded of George, what way our friends proceeded against him,
and what measures they took, as he would insinuate, to bring him to the gallows.
But I perceived fear began to surprise the hypocrite,
and he thinking by my boldness I was an inhabitant in those parts,
and knew his abuse to Friends in these provinces,
and their peaceable behavior towards him, was willing to let the matter drop,
and demanded my name, which was told him.
I then asked how he could dare urge such a notorious untruth
in the view of that people who were much strangers to,
and ignorant of the troubles and differences, chiefly created by him,
among Friends in these parts.

The members of this meeting being generally newly convinced of the truth,
I urged him to come to the particulars of Friends`' proceedings against him,
that among those strangers he would set forth as far as he could in truth,
the steps Friends had taken in persecuting him, as he pretended;
but he would not meddle in the least with it.
Then I showed him, and the people, the falsity of his charge,
and the wickedness of his spirit, and the peaceableness of Friends`' behavior towards him,
and what great affronts and provocations they had put up with at his hand,
as I had it from those who were eye and ear witnesses of it.
For, as I showed George Keith, I had searched into the bottom of these matters,
and heard that when he stood before governors
and assembly-men in their courts of judicature,
when they were met about the affairs of the three provinces,
he had torn open his buttons and told them, His back tickled for a whipping,
and could they not cut him into collops, and fry and eat them with salt;
and that he scorned they should wipe his shoes: all which, with much more,
I told him I could prove against him.
And when he saw he could not provoke Friends to give him some condign punishment,
which I thought, as I said to him, none but Friends would have spared,
especially when his back tickled so much for a whipping; but they,
like men of peace and religion, overlooked it all; he, like a man full of malice,
rather than go without something to slur and blacken Friends with, wrote a letter,
I know not where, but dated it from Bridlington prison, in West Jersey.
It must have been dated on the outside of the prison, the doors being locked,
so that he could not get into it; yet this went current far off,
that George Keith was in prison; consequently by Friends`' procurement,
they being chiefly at the helm of government in those three provinces.

I asked what he had to say to all this, for it was all provable:
he did not object one word against what I had said,
but vainly hoping for better success in Old England, relating to his undertaking,
and finding me, as he might suppose, so well versed in the American affairs, hoped,
no doubt, that I had been more ignorant of the affairs of Britain: but, poor man,
he sped as illy there also.
For he boastingly said,
that since it pleased God to open his eyes to see into the worst of the Quakers`' errors,
although, he said,
charity did oblige him to construe everything at the best while in fellowship with them,
but since they were so opened; he had been instrumental to bring from Quakerism,
to the good old mother church, in Old England, five hundred people.
I replied, that is not true: if he rightly considered what he had done in Old England,
he had little cause to boast; for, I said,
I thought about as many persons as he spoke of hundreds, would make up the number there;
and if there was occasion, I could name all or most of them; and told him,
that some of those few, while amongst us,
were grown to be neither honorable nor comfortable to us.
I urged George, if he could, to name or make appear more in number than I had mentioned,
that he had so gathered, as he had falsely said.
This was a very great stroke, and put him to a stand.
He then began to ask of my country, and from where I came;
with the account of which I humored him; yet I put him in mind of his great brag,
and importuned him to make something appear towards
that great matter he had done in Old England;
for I was ashamed for him, that a man of his learning, abilities, and pretensions,
should so expose himself; but he went no further about it.
Then I showed the people what sort of a man he was, as they themselves could not but see,
who were impartial, and that he was not worthy of our notice,
for he cared not what he said, so that he could but calumniate and abuse us.

By this time he appeared somewhat glutted with
the sharp sword and keen arrow the Lord gave me,
which cut and wounded deeply, so that I did not find in our after encounters,
he appeared at any time so bold and desperately hardy, but rather expressed himself,
though very wickedly, yet in a softer tone.
He was now for being gone, threatening us with what he would do on the morrow;
but I reminded him, that he was to us as a heathen man or a publican,
and that what he exhibited against us, being but the fruits of wrath and envy,
as such we slighted and trod it under our feet as dirt,
and rather desired his absence than his company: so away he went, only telling us,
he would be with us in the morning.
We understood by it, that he intended to be with us at the Friend`'s house,
the meeting-house being about a quarter of a mile from our lodgings.

The evening coming on,
the neighboring Presbyterian women fell hard
upon our women Friends about their saluting men,
which George Keith had charged upon them, as was generally understood in the plural,
and this appeared as a confirmation, as they alleged, because when charged,
I made no reply to it, as I had done to all or most other charges,
and had overthrown Mr. Keith, as they said, so that he was not able to stand before me.
They ought to have said, before the Lord in the first place.
But how the women might clear themselves of that reflection was the present business.
I said I thought it would be the best, at a suitable time in the morning,
when George Keith was come, that by handsomely bringing the matter over him,
they might learn what women they were who saluted him,
and so clear themselves from the reflection cast upon them; for, I said,
perhaps he will limit it to some of his near kindred, as wife, mother, sister, daughter,
which may serve him for a salvo in this present case;
for I did not know of any such general practice in and place where I had been,
and I had visited most of the meetings in England, Scotland, and Wales.
So in the morning, when George, with two priests, and many people were come,
with some Friends, who filled the house, a woman Friend stood up,
and brought the matter discreetly over George Keith.
But when she put the question in the plural, women, he shifted the term, and said,
He did not say women.
I desired the Friend to call to her neighbors who heard
what George Keith had said the last evening,
and were now present, how they understood the word.
One, like a wise and just man, said, He would do justice to every man;
and he understood that George said women; and many said to the same purpose,
but none to the contrary.
The Friends asked me, How I understood the word: as being a north countryman,
I might know better the north or Scotch dialect than they.
I replied, "`They had a broad way of expressing the word woman,
rather sounding it like the plural, but I understood it women,
as the above-mentioned discreet man had said.`"

The next question she put to him was, "`What woman?`"
He answered, "`A good old motherly woman that was gone to heaven many years ago.`"
Then she asked, "`What countrywoman?`"
He replied, "`A Scotch woman.`"
The Friend said, "`It was very well that he had cleared all the world of that fault,
if it might be so termed, but Scotland, and one woman dead many years ago.`"
The women Friends were greatly satisfied,
and glad they were so finely discharged of that which some counted a reflection,
and especially before their zealous neighbors the Presbyterians; who,
as the Friends said, might probably have twitted them with it,
whether the matter was true or false, if it had not been cleared up; but,
as I said to George, it was a reflection for reflection`'s sake:
for I was willing to set everything that was wrong, as far as I was capable,
in its proper light, that Friends and others, of all persuasions who were present,
might see things as they really were, and not be deceived;
and I had much satisfaction in so doing.
As I was engaged in the defense of the truth,
it appeared most clear to me to load him with his own lies, mistakes, and wickedness,
and to do what we did, as much as in us lay, in the Lord`'s mighty power;
for he appeared to me like the angels who kept not their first state.

Matters being thus far gone through, and the meeting time drawing on,
I was in some concern of mind,
lest any should be hurt by either hearing or answering George Keith,
he having a great propensity to jangling;
it therefore opened in my mind to ask him a question,
reminding him that he was but to us as a heathen man or a publican, yet he might,
if he pleased, answer me the question, which was,
Whether he was always sound in the fundamental doctrines of Christianity, yes or no.
Upon which he sat a considerable time in silence, of which I was truly glad,
my spirit being much bowed under the apprehension I had of the
weighty exercise that was likely to attend the approaching meeting.
But before we parted, George stood up, and taking his staff in his hand by the middle,
said, while he was a Quaker, he thought as Paul thought, that he had the Spirit of God,
and when he had the Spirit of God, then he wrote sound things, but when he had it not,
then he wrote unsound things.
I asked, whether these unsound things he wrote were in fundamentals, yes or no:
if not in fundamentals, then my question remained firm and untouched.
He would have gone from the matter, but I reminded him of it again,
as I supposed he foresaw that he could not answer it,
but by bringing a stroke upon himself, for if he had acknowledged his being unsound,
I had it under his own hand, in a book written after he left Friends,
that he was always sound, etc.
And if he had said, he was always sound in the fundamentals, as before,
then I intended to have asked, why he left us:
for he advocated the same orthodox principles which we believed and taught;
but we ended quietly, and prepared to go to the great meeting,
for by this time many Friends and people were come, and coming from every quarter,
to see and hear how matters would go between the poor Quakers,
and this great champion in his heart, George Keith,
for I thought he most resembled the great Goliath of Gath,
who defied the armies of the living God, of any I had seen in all my travels,
in a religious respect.

Now to the meeting we went; George Keith,
with two priests and a great many people of several
professions and qualities gathered together into one body,
and Friends and some friendly people into another body;
and as we came near to the meeting-house, I stood still, and took a view of the people,
and it appeared to me as if two armies were going to engage in battle.
There appeared with George Keith men of considerable estates, parts, and learning,
and we appeared like poor shrubs; and, under a sense of our present state,
I had like to have been dismayed, and my faith even to have failed me.
But I cried mightily to the God and Fountain of all our tender mercies,
that he would look down upon us, and help us in this time of great exercise,
which was not hid from him; but his penetrating eye saw,
and his watchful providence attended us, blessed be his name forever.
I continued my fervent prayers and intercessions to the Lord of Hosts,
that he would arise for his great name`'s sake, and work for us that day,
that the enemies of truth might not triumph or vaunt over us,
and that none of these tender plants,
whom he had brought to the saving knowledge of the Truth, might be hurt.

I had no sooner thus heartily sought the Lord, but I felt renewed strength come upon me,
and the fear of man was taken away from me,
and I saw evidently that Truth would have the victory that day,
and my faith and confidence were greatly strengthened in the Lord.
These breathings forth of my spirit to the Lord were in secret,
without words to be heard by men,
but the Lord hears and knows the distress and language of the spirit.

Being thus encouraged in myself,
it arose in my heart to speak to Friends before we went into the meeting-house;
and I advised them to be swift to hear, and slow to speak,
that what was spoken might be in the Lord`'s power, for that wounds George the most,
and slays that wicked and ranting spirit in him,
more than all the wisdom of words without it:
let us maintain our testimony of denial against him,
and endeavor to get together into one body,
that we may be a help and strength one to another; and let every one who knows the Lord,
cry mightily to him, that his living power and presence may be amongst us,
and I believe the Lord will not allow any to be hurt.
So the meeting gathered, and immediately after, George stood up to tell us, as before,
that he was come in the Queen`'s name, to gather Quakers from Quakerism,
to the good old mother church, the Church of England, as he called it,
and that he could prove out of our own books, that we held errors, heresies,
damnable doctrines, and blasphemies; with a threat to look to ourselves to answer,
or else the auditory would conclude, that what he exhibited against us was true.
I expected some of the elder Friends would say something to him, but none did;
and having a deep concern upon my mind, lest Truth, or the friends of Truth,
should suffer through our mismanagement,
and such as waited for occasion might have it administered by us against ourselves;
under this concern I stood up,
and signified to the people what manner of man George Keith was.
Notwithstanding he had walked many years amongst us,
yet towards the latter end of his so walking with us, he grew very troublesome,
by reason of a contentious spirit which did possess him;
and after much labor and exercising of patience, and extending of love towards him,
in order to recover and reclaim him,
all that labor of love and much forbearance would not avail,
but he still persisted in the work of contention and disturbance;
then he was publicly disowned, and testified against by us,
as a person with whom we had no unity or fellowship.
Being thus cast out, he became to us, agreeably to the sayings of Jesus Christ,
as a heathen man or a publican; and did what lay in his power,
to expose us to all sorts of people, printing against us; wherein he has much abused us,
in leaving out the explanatory parts of sentences,
and coining words to make the meaning appear different from what was designed,
and indeed, from what was most fair and genuine.
Therefore, some of our Friends found themselves concerned to follow him in print,
for the clearing us from what he, through envy, would have willingly fastened upon us,
and to return his self-contradictions, misinterpretations,
and misapplications of our writings upon himself, and to clear our own innocency,
and manifest the perverseness and wickedness of his spirit.
Neither do we, as a people,
hold ourselves under any obligation to follow him into foreign parts of the world,
to answer his charges,
not being conscious that we hold anything contrary to sound and orthodox doctrine.
And knowing that what he exhibits against us, is the fruit of envy and malice,
as such we reject it, and trample it under our feet; and were it not for your sakes,
who are strangers to these things, we should take no further notice of George Keith,
than to slight and reject him as a man that cares not what he says,
nor is he worthy of our notice.

Then pausing a little, George being quiet, a Friend stood up with a short,
but living testimony, and then my companion; all this in much weight,
and with good demonstration.
After them it pleased the Lord to open my mouth, I think in as much strength,
clearness and demonstration as ever, beginning with the following words:
In that way you call heresy do we worship the God of our fathers,
believing all things that are written concerning Jesus Christ,
both as to his Godhead and manhood; giving a summary account of his birth,
working of miracles, some of his doctrine, sufferings and death,
ascension and glorification, the coming of the Spirit of Truth, or Comforter,
to lead all those who receive, believe and obey it, into all truth:
having great openings concerning the law and prophets, and the beginning,
service and end of the ministration of John the Baptist.
The people appeared very attentive,
for the Lord`'s heavenly baptizing power was amongst us that day:
it was thought many were there who had not been at any of our meetings of worship before,
and the presence of the priests there, opened a door for all the rest.
Being clear, I left them to the grace of God, and to their free teacher Christ,
whose heavenly power in the appearance of his Spirit, the last and lasting dispensation,
was exalted that day above all the shadowy and
typical things that ever had been in the world:
a good meeting it was,
and Friends were mutually comforted and edified in the eternal presence of the Lord.

The priest of this place, whose name was Sheppard,
before my mouth was opened in testimony, made preparation to write;
and when I began to speak, he had his hat upon his knee, and his paper upon its crown,
and pen and ink in his hands, and made many motions to write, but wrote nothing;
as he began so he ended, without writing at all.
As Friends entered the meeting-house, the Lord`'s power,
even that power which cut Rahab and wounded the Dragon, which had been at work,
kept down in a good degree the wrong spirit in George, for he appeared much down;
but this busy priest called to him several times to make his reply to what I had spoken.
After some time, I said to the priest, on behalf of the meeting,
That he might have liberty to make reply.
He proposed to have another day appointed for a dispute; to which I said,
if he did make a voluntary challenge, which he should not say we put him upon, we,
or some of us, meaning Friends, if a day and place were agreed upon,
should find it our concern to answer him as well as we could.
He said he would have Mr. Keith to be with him.
I told him if he should, and meddled in the dispute, if I was there,
I should reject him for reasons before assigned.
When the priest had said this and somewhat more,
an elder of the Presbyterian congregation clapped him on the shoulder,
and bid him sit down; so he was quiet, and then stood up George Keith,
and acknowledged he had been refreshed amongst us that day,
and had heard a great many sound truths, with some errors,
but that it was not the common doctrine which the Quakers preached.

I then stood up and said,
I had something to say to obviate what George Keith would insinuate;
for his drift was to infuse an opinion into them,
that the Quakers did not commonly preach up faith in the manhood of Christ,
as I had done that day.
I appealed to the auditory,
whether any thought there was a necessity frequently to
press a matter so universally received among Christians,
as faith in the manhood of Christ was: yet we, as a people,
had so often and clearly demonstrated our faith in the manhood of Christ,
both in our testimonies and writings, as might satisfy any unbiased person,
or such who were not prejudiced against us;
and we know not of any people who believe more
scripturally in the manhood of Christ than we do.
But inasmuch as the grace, light, and Holy Spirit,
is highly concerned in the work of man`'s salvation,
as well as what Christ did for us without us,
and this being yet much a mystery to many called Christians, it pleases God to open,
in the course of our ministry, into the meaning and mystery thereof,
and to press the latter more than the former.
To which George made no reply, but began to exhibit his charges against us,
and said he could prove them out of our Friends`' books,
naming George Fox and Edward Burrough, etc.
He had in a paper a great many quotations out of Friends`' books,
and a young man with him had many books in a bag, out of which,
he said he would prove the charges he was about to exhibit against us.

He was now crowded up into the gallery between me and the rail, with a paper in his hand;
and I standing over him, and being taller, could see his quotations,
and his paraphrases upon them, on which I told him loudly,
that all the meeting might hear,
That he offered violence to that sense and understanding which God had given him,
and he knew in his conscience, we were not that people,
neither were our Friends`' writings either damnable or blasphemous,
as he through envy endeavored to make the world believe,
and that he would not have peace in so doing,
but trouble from the Lord in his conscience.
I spoke in the Lord`'s dreadful power,
and George trembled so much as I seldom ever saw any man do.
I pitied him in my heart, yet as Moses said once concerning Israel,
I felt the wrath of the Lord go forth against him.
George said, "`Do not judge me;`" I replied,
"`The Lord judges, and all who are truly one in spirit with the Lord, cannot but judge you.`"
So he gave over, and it appearing a suitable time to break up the meeting,
Friends parted in great love, tenderness, and brokenness of heart;
for the Lord`'s mighty power had been in and over the
meeting from the beginning to the end thereof;
glorified and renowned be his most excellent name, now and forever,
for his mercies are many to those that love and fear him,
who is the fulness of all good.

This meeting was not only for worship, but also for business,
as I said to the people at our parting; it was Friends`' Monthly Meeting,
in which their poor, fatherless and widows, were taken care of,
and such other things as concern them as a people.
Two Friends were desired to stay, to hear what George had to say to them who remained,
which said two Friends gave us an account,
that George said to the people after we were gone,
the Quakers had left none to dispute with him but an ass and a fool; when I heard it,
I said, "`could you not have replied,
'`An ass was once made sufficient to reprove the madness of the prophet.`'`"

George called to see me the next day, and said, "`You had the advantage of me yesterday,
for you persuaded me to be quiet until you had finished,
and then you would not stay to hear me;`" neither
indeed were we under any obligation so to do.
I told him I hoped that Truth would always have the advantage over those who opposed it;
and so we parted, but met again upon Rhode Island; the governor of which place,
who was a friendly man, having heard of my intention of coming there,
ordered the deputy-governor, when I came, to bring me to him, which he did.
When he saw me at the door, and after inquiry heard my name, he took me by the hand,
and led me like a brother, or rather more like a tender father, into a room,
setting me down by him, and then began to say, I have heard much of you,
and I desired to see you long, and am glad you are here.
Finding him near me in spirit, I was very open in my mind to him,
and answered him with much clearness and satisfaction.
I remember he asked,
whether I thought the sourness in the minds of the Presbyterians against us,
was not rather abated?
I told him, I did believe it was; and if our Friends did but observe to walk wisely,
and live up to what they professed, they would overcome it all.
He said that was the way, and there was not another comparable to it; and as he said,
and I believe it was so, he had no other view in sending for me,
but to manifest his respect to me, and to do me any service that lay in his power.
I told him I was sensible of his love,
and wished I could be capable of returning that
which in gratitude his kindness to me called for:
he said he desired no more than when I came that way, I would visit him,
if he was living.
I told him I intended so to do, if it was my lot to come there again.
I then desired he would be at the meeting next day, George Keith proposing to be there,
in all likelihood it would be very large; which he promised he would,
and accordingly came.

George made little disturbance in the beginning of the meeting,
but commanded the governor to quiet the Quakers.
A priest said, "`Mr. Keith, you ought not to command the governor,
but entreat him;`" well then, he entreated the governor to quiet the Quakers,
that he might be heard; whereupon the governor, like a man of justice and wisdom,
stood up and said it was not in his power to quiet the Quakers;
inasmuch as the house is theirs, and they have appointed the meeting,
it is but reasonable they should have their liberty,
and if they be willing when they have done,
you have your liberty to say what you have to say to those who will stay to hear you:
so the governor being next me, leaned his hand upon me, and went away in a sober manner.
George was quiet, and we had a good meeting, and so parted.

After most of the Friends were gone, a Friend and I went to the meeting-house door,
to hear what George said: he held his Bible in his hand,
and said it was promised that the Gospel should
be preached unto every creature under heaven;
but if it was truly translated, it would be in every creature, not in every creature,
as horse, cow, etc., but in every rational creature of mankind:
and then their meeting broke up in confusion.

My next remove was to Long Island, where I met with Thomas Story and John Rodman;
John desired Thomas and me to be assistant to
him in preparing a writing against George Keith,
when he came to Flushing meeting upon the aforesaid island,
which writing was to this effect:

Colonel West, an inhabitant in these parts, who died and made Miles Forster a trustee,
gave by Will a considerable sum of money to poor Friends of London,
which money was ordered by the testator to be put into the
hands of some faithful Friends of the aforesaid city of London,
to distribute as above.`"
A true copy of which Will we obtained,
and at the meeting made it fairly appear to George Keith`'s face,
that he had wronged the poor in receiving fifty
pounds of the aforesaid money of Miles Forster,
as appeared under Miles`'s own hand;
which George did not deny when he was charged with it in the meeting,
as knowingly to have robbed the poor; it being made fairly to appear,
that George Keith had no right to meddle with the money, neither as a faithful Friend,
nor yet as a poor Friend of London, because he was then in America.
And what made him more incapable of claiming any part of it,
was his being got into the spirit of strife and enmity against Friends, and therefore,
before they could hear his charges, he ought first to lay down the money,
or give such security as Friends approved of; neither of which he was capable of doing.
He was slighted by all or most of the people, as well as by Friends,
and this blocked up his way so much that we had little
or no trouble with him in that part of the world.
The Lord wrought for his name`'s sake, and the preservation of his tender people,
praises and honor be given to his great name, now and forever.
Thus ended this engagement between a poor servant of Christ, and a grand apostate,
who appeared to fight against reason, sense and conscience.

Think not, my friends, the account too long, for it has seemed to me, for some time,
a debt due to my brethren, and a piece of justice due to the memory of George Keith,
for his wickedness, revolting and sad apostasy.
Few there are who can believe how great the power of
darkness and wickedness of that mind and spirit was,
which possessed and breathed through him; so great it was,
that even the considerate and sober people said they did not think that
George Keith had been so wicked a man as they found he was upon trial.
Courteous friend and reader, hold fast that which you have received,
that none may take your crown, for it is laid up in store for the righteous only,
and such who hold out to the end, in the same pure righteousness which is of Christ,
wrought and continued in man, by the operation and indwelling of his Holy Spirit,
as man abides in subjection and obedience to the leadings and dictates thereof.

I told George, that I was much ashamed of his complimenting great people;
for I observed he sometimes said thee and thou, and sometimes you and sir;
sometimes put his hat off, and sometimes kept it on,
and that before I would be so unhandy, if I intended to be ceremonious,
I would go to school a while, and not shame myself as he had done.
If I have not written the very words, in all my accounts in the preceding pages,
I have the substance: and for a conclusion, I had to say to George Keith,
the hand of the Lord was against him, and would follow him, unless he repented.

This account carries in it an admonition to us, and to Friends in future ages,
into whose hands it may come, to beware of letting in the spirit of envy,
prejudice and pride of heart, which I clearly saw was that which,
with too much leaning to his natural abilities and learning, was his overthrow,
he not keeping to the Lord`'s Holy Spirit, the life and strength of his faithful people,
and the key of true knowledge, the good remembrance, and leader into all truth,
which the Lord sees fit in his wisdom to open and lead us into.
Without the help of this anointing and Holy Spirit,
we are apt to be cold and forgetful in our duties towards God,
and also in our love and duties one to another;
but as the measure of this spirit is faithfully kept to and improved,
we grow more and more fruitful in every good work and word,
to the glory of God and comfort of our souls, and, as the salt of the earth,
help to season those who are not seasoned.

When I was in the Yearly Meeting upon Rhode Island,
there was a query concerning what Friends should do,
in case there should be a tax laid upon the inhabitants for building fortifications,
and to provide men and arms for the security of the island;
such a thing being then in agitation.
One of the chief Friends concerned in church affairs,
would have me give an account what we did in the like case in England;
for he said they looked upon themselves as the daughter,
and Friends in Old England as their mother,
and they were willing to act consistently with us as far as they could,
and would know whether we could pay that tax which was
for carrying on a vigorous war against France.
I was unwilling to meddle with it, as I said;
but the meeting waited a considerable time for my answer, as one told me,
and was not willing to go forward without it.
At last, when I could not well do otherwise, I signified to that large meeting,
that I had heard the matter debated both in superior and inferior meetings,
and privately, and the most general result was this;
Friends did not see an effectual door opened to avoid the thing,
that tax being mixed with the other taxes;
although many Friends are not so easy as they could desire:
neither have we any further sway in the government,
than only giving our voices for such as are concerned therein; therefore,
as things appear to me,
there is a great disparity between our circumstances and yours here;
for you have a great interest and share in the government,
and perhaps may put such a thing by in voting, considering the body of Friends,
and such as are friendly, whom you have an interest in;
therefore look not for help from the mother,
wherein she is not capable of helping herself, and thereby neglect your own business;
but mind your own way in the Truth, and look not out.
Friends appeared well satisfied with these distinctions, and it gave me some ease,
in that I had not hurt any.

During my stay in one of the Jerseys, a great weight, more than usual,
seized upon my spirit as I sat in a meeting,
and under a sense of the same my cries ascended unto the Lord,
the fountain of all tender mercies,
that he would please to show me what was the cause of that
great power of darkness which did so oppress my spirit.
And it pleased the Lord to show me,
that a man there had been guilty of some gross wickedness;
and when it clearly appeared to be required of me to express it publicly,
it became a very great exercise to me,
and I had some reasonings before I gave up to make it public
to that large meeting of Friends and other people.
I labored under it till towards the conclusion of the meeting,
but finding my peace concerned very nearly in the matter,
I stood up in the gallery and said,
"`Under a sense of some gross wickedness committed by some person not far from me,
has my spirit been borne down:
which wickedness will in a short time break forth to the dishonor of Truth,
and grief of Friends.`"
A great man who sat in the gallery by me,
started up and seated himself upon the rail of the gallery, with his eyes fixed on me,
and in the Lord`'s dread, I fastened my eyes on him, and said,
"`We have a common maxim in Old England, touch a galled horse`'s back, and he will kick;
and I am of the opinion, he that kicks is not clear.`"
He got down as fast as he could out of my way,
for he not only prevented me from the view of the meeting by sitting there,
but his uncleanness stood much in the way of my service.

After the meeting was over,
several worthy Friends expressed to me the great concern they were under,
lest he should either by money, or subtlety, conceal the wickedness,
if such was committed; for I found there was a great jealousy in the minds of Friends,
that something was wrong with the man,
but I was till then altogether a stranger to their thoughts, and to the state of the man;
yet I advised that Friends should have a watchful eye over him and his family,
for I told Friends, my spirit was easy in what I had delivered,
and I believed the evil would not be concealed.
On my return, I heard his wickedness had been made manifest, which he did not deny.
Friends then asked me, what they should do in the case; I said,
"`Let the judgment of Truth go forth against all manifest wickedness,
without respect of persons, that the ever blessed Truth, and such as live in it,
may be kept clear and in good esteem before all men as much as may be.`"

Something of the like exercise I met with in a meeting in Pennsylvania,
repeating several times what oppression my spirit was under,
because of some yet hidden wickedness, which in a short time would be brought to light,
to the blemish of the Truth, and great trouble to Friends.
That very evening, after the meeting,
a woman little thought by Friends to be guilty of such a crime,
went to a worthy Friend and told him,
she was the woman who had done that great wickedness I had complained of,
and had borne such a great load because of; and, as the honest Friend said,
she wept bitterly, even in the very anguish of her soul.
He came twelve miles the next day to Philadelphia to acquaint me with the matter,
and ask my advice, which I gave to this effect: If Friends find upon inquiry,
in the proper season, that the woman continues heartily sorry,
and truly penitent for what she has done, for godly sorrow works repentance,
and if from such a hearty and penitent sense, which is to be felt beyond words,
she gave forth a paper against her wicked doings,
not so much to ingratiate herself into favor, as for the clearing of Truth and Friends,
and for the ease and peace of her own mind, and took the blame and shame to herself,
then Friends may pass it by; if not.
Friends must set the judgment of Truth over manifest wickedness, as before mentioned.

I went to visit a meeting in that part called North Wales,
which had not been long planted, where there was a fine tender people;
but few understanding English, Rowland Ellis was my interpreter; we had a good meeting,
and truth was over all.
Some expressed their great satisfaction with our visit to that meeting,
which before then had not been considered as Friends,
but since that time they have been taken notice of,
and grown into good esteem with the body of Friends.

I found it much my work to be engaged in the discipline of the church,
which was very low in many places,
yet there was a willingness in Friends`' minds to be helped in that needful concern,
for surely it is a good fence, and a help to keep the righteous in,
and hurtful and wicked things and doings out,
if the same be rightly handled and extended as it ought to be,
in the love and wisdom of God.

When I was in Rhode Island, one Rogers came there to offer his gift, as he said,
in the Yearly Meeting amongst Friends; but they appeared in a great strait about him,
although he had written on behalf of Truth`'s principles, suffered imprisonment,
and the taking away his wife from him,
and was not so much as permitted to converse with his own son,
but under a guard or watch which was set over him, to hear what passed between them,
as he told me and some other Friends, which Friends said was true;
yet under the consideration of the matter, and clearness of the man`'s conduct,
Friends remained in a strait what to do.
And they desired that I would reason the case with him,
to try if I could persuade him to be easy, and not insist upon any such thing,
as a promise to receive his gift: for otherwise,
he said he would go where it would be received.
I showed him that it was a thing impracticable amongst us, and in itself unreasonable,
that we should be by any pre-engagement obliged
to receive that which he might call a gift,
before we heard it.
If he believed he had a gift, he might speak, and, as the apostle said, we might judge.
It was not impossible but he, who was a scholar, and a wise man, and had a strong memory,
might have gathered certain passages out of the Bible or other books,
with what other interpretations he might have stored up, and speak of,
and call it a gift, but which we could not receive as a real gift of the ministry,
which stands in the Spirit, and in the power,
and if it be such it will make way for itself, if not, we cannot receive it.
So he went away, and troubled Friends no more that I heard of.

I was at William Penn`'s country house, called Pennsbury, in Pennsylvania,
where I stayed two or three days, on one of which I was at a meeting and a marriage.
Much of the other part of the time I spent in seeing, to my satisfaction,
William Penn and many of the Indians, not the least of them,
in council concerning their former covenants,
now again revived upon William Penn`'s going away for England;
all which was done in much calmness of temper, and in an amicable way.
To pass by several particulars, I may mention the following:
They never first broke covenant with any people; for, as one of them said,
smiting his hand upon his head three times, they did not make them there in their heads,
but smiting his hand three times on his breast, said,
they made them (i.e. their covenants) there in their hearts.
When they had ended the most weighty parts for which they held their council,
William Penn gave them match coats and some other things;
which the speaker for the Indians advised to be put
into the hands of one of their cassacks or kings,
for he knew best how to order them.
I observed, and also heard the like from others, that they did not speak two at a time,
nor interfere in the least one with another that way in their councils.
Their eating and drinking was also in much stillness.

I desire that Christians, whether they may be such in reality or profession only,
may imitate these people in those things which are commendable,
which may be a means to prevent loss of time and expedite business; as much as may be,
endeavoring to prevent above one speaking at a
time in meetings of conference and of business.

When these matters were nearly gone through,
I put William Penn in mind to inquire of the interpreter,
if he could find some terms intelligible to them,
by which he might reach the understandings of the natives,
and inculcate a sense of the principles of Truth,
such as Christ`'s manifesting himself to the inward senses of the soul, by his light,
grace, or Holy Spirit, with the manner of its operations in the hearts of men,
and how it reproves for evil,
and ministers peace and comfort to the soul in obedience and well-doing; or,
as nearly as he could, come to the substance of this in their own language.
William Penn pressed the matter much upon the interpreter to do his best,
but he would not, either because, as he alleged, of a lack of terms,
or his unwillingness to meddle in religious matters, which, I know not;
but I rather think the latter was the main reason.

William Penn said, he understood they acknowledged a superior power,
and asked the interpreter, what their notion was of God in their own way.
The interpreter showed, by making several circles on the ground with his staff,
till he reduced the last into a small circumference, and placed, as he said,
by way of representation, the great man, as they termed him, in the middle circle,
so that he could see over all the other circles, which included all the earth.
We queried what they acknowledged as to eternity, or a future state;
the interpreter said, they believed when such died as were guilty of theft, swearing,
lying, murder, etc., they went into a very cold country,
where they had neither good fat venison, nor match coats,
which is what they use instead of clothes to cover themselves,
being of one piece in the form of a blanket or bed-covering.
But those who died clear of the aforesaid sins, go into a fine warm country,
where they had good fat venison and good match coats; things much valued by the natives.
I thought, as these poor creatures had not the knowledge of God by the Scriptures,
as we have who are called Christians,
that what knowledge they had of the Supreme Being must be by an inward sensation,
by contemplating the works of God in the creation,
or probably from some tradition handed down from father to son, by which it appears,
they acknowledged a future state of rewards and punishments;
the former of which they express by warmth, good clothing and food,
and the latter by nakedness, pining hunger, and piercing cold.

I have often thought and said, when I was amongst them,
that generally my spirit was very easy,
and I did not feel that power of darkness to oppress me,
as I had done in many places among the people called Christians.

After William Penn and they had expressed their satisfaction,
both for themselves and their people, in keeping all their former articles inviolate,
and agreed that if any differences happened amongst any of their people,
they should not be an occasion of fomenting or creating
any war between William Penn`'s people and the Indians,
but justice should be done in all such cases,
that all animosities might be prevented on all sides forever;
they went out of the house into an open place not far from it, to perform their worship,
which was done thus: First, they made a small fire,
and the men without the women sat down about it in a ring,
and whatsoever object they severally fixed their eyes on,
I did not see them move them in all that part of their worship,
while they sang a very melodious hymn,
which affected and tendered the hearts of many who were spectators.
When they had thus done, they began to beat upon the ground with little sticks,
or make some motion with something in their hands, and pause a little,
till one of the elder sort sets forth his hymn,
followed by the company for a few minutes, and then a pause;
and the like was done by another, and so by a third,
and followed by the company as at the first;
which seemed exceedingly to affect them and others.
Having done, they rose up and danced a little about the fire,
and parted with some shouting like triumph or rejoicing.

I leave Pennsbury, but intend, before I leave the Indians,
to say something more concerning that people,
which I met with near Caleb Puscy`'s house in Pennsylvania.
Walking in the wood, I espied several wigwams or houses of the Indians,
and drew towards them, but could not converse with them;
but looking over them in the love of God, I found it to be my way, as I apprehended,
to look for an interpreter, and go to them again, which I did.
I signified to them that I was come from a far country,
with a message from the great man above, as they called God,
and my message was to endeavor to persuade them, that they should not be drunkards,
nor steal, nor kill one another, nor fight, nor commit adultery,
nor put away their wives, especially for small faults, which, as I understood,
is usual with them to do; for if they did those things,
the great and good man above would be angry with them, and would not prosper them,
but bring trouble on them; but if they were careful to refrain from these evils,
then would God love them and prosper them, and speak peace to them;
or very nearly these words.
When the interpreter expressed these things to them in their own language they wept,
and tears ran down their naked bodies, and they smote their hands upon their breasts,
and I perceived said something to the interpreter.
I asked what they said:
he told me they said that all that I had delivered to them was good,
and except the great man had sent me, I could not have told them those things.
I desired the interpreter to ask them, how they knew what I had said to them was good:
they replied, and smote their hands on their breasts, the good man here,
meaning in their hearts, told them what I had said was all good.
They manifested much love to me in their way, and I believe the love of God is to them,
and to all people in the day of their visitation.

Having left them, I came to a Friend`'s house in the lower part of Pennsylvania,
who was in the office of a justice of peace,
and had been convinced not long before by Thomas Story.
When I came into the house the man`'s wife was very uneasy, and called me a deceiver,
and wrung her hands and said, "`Woe is me!
I am undone, my husband is deceived; and more deceivers are come!`"
O how she lamented!
I was somewhat struck with the passion the poor woman was in; however, I said little,
but sat down, and after some time it rose in my mind to ask her,
in what her husband was deceived: whether he was, since he came amongst us,
any worse husband to her; if he was, it was a bad sign; or,
was he a worse father to his children; or a worse neighbor;
or in any particular thing which she could name, changed from better to worse,
since he was convinced of the Truth?
If not, she had no great reason to complain.
But if he had turned drunkard, railer, fighter, or become a vicious man,
she would have had reason to complain.
She honestly acknowledged, she had nothing to charge him with.
He sat by me and heard all our discourse, but said nothing.
I told her, she had made a lamentable outcry about her husband`'s being deceived,
but had not convinced me of any cause she had received for her sore complaint.

Being weary, having rode a great way that day,
I with my companion Richard Orm took leave of her husband, and went to our rest,
and saw him no more till the next day in the evening.
When he came, I asked him, for what reason he left us so long,
as he knew how uneasy his wife was about us, and that we had a great need of him.
He said he had been giving notice of the meeting twenty miles one way,
and two men had given notice as far, each man his way;
that was six score miles in and out.

Our landlady, before we rose in the morning, had got another woman, a justice`'s wife,
to help her to dispute with us, and overthrow us, as she hoped, but in vain,
for Truth proved too hard for them; although the other woman charged high in the morning,
and said we were no Christians.
I said it was easier to charge than to prove; how do you prove it?
Because; said they, you deny +++[+++water baptism,]
the precious ordinance of Jesus Christ.
I asked if they could prove it to be such: they said they did not question but they could.
I said they should do it from plain texts of Scripture, verbatim as it lies,
without any inferences, consequences, or comments upon the places they insisted upon;
and they agreed to it.
But I told them, in case they should fail and not prove, as they thought they could,
that ordinance to be so appointed by Christ,
I hoped then they would allow us to be Christians,
notwithstanding what they had charged to the contrary; and they said they would.

I then repeated all the preliminaries,
and asked them if they would agree to each particular: they said they would.
I desired Richard Orm to mind them, and imprint them in his memory,
for it was like enough we should have occasion
to call them in question before we had done;
which came to pass not long after we began.
They urged the twenty-eighth of Matthew in defense of water-baptism,
where Christ said to his disciples, "`Go you therefore and teach all nations,
baptizing them in the name of the Father, and of the Son, and of the Holy Ghost;
teaching them to observe all things whatsoever I have commanded you:
and lo I am with you always, even unto the end of the world.`"
Water not being mentioned, the disputants were at a stand, and said it must be implied.
I showed them, that by their agreement to the preliminaries,
there were to be no inferences, but plain Scripture.
I told them,
it was an unreasonable thing declare a great
body of religious people to be non-christian,
merely by a few inferences, which might be true, or not true.
When they had searched the New Testament a great while,
they could not find what they desired,
although they urged what Peter said in a certain case, "`Who can forbid water,
that these should not be baptized, who have received the Holy Ghost as well as we?`"
I showed them, that there was a great disparity between a servant`'s question,
and a master`'s command.
When they were weary with searching,
and could not find a positive ordination by Christ for water baptism, they gave it over,
and I asked them,
if they had not fallen short of the proof of what they
had so boldly charged upon us in the morning.
My landlady confessed they had fallen short of their expectation;
but the other was in the mind, as she said that it might be proved.
I told her she would not prove it from any plain text of Scripture.

My passionate landlady became more meek and friendly,
and received the Truth in the love of it: we had a good meeting the next day,
and she said if I would stay that night, I should be as welcome as her own children;
but if not, she blessed the Lord for my company,
and the good she had already received by me,
and parted with me in much brokenness of heart;
and I heard she lived and died in good unity with Friends.
But, oh! how glad was her husband to see that great and
sudden change wrought in her! it was the Lord`'s doings;
to him be the praise now and forever, for he alone is worthy.

I had many comfortable meetings in my travels through these provinces, and good service.
We were at a Yearly Meeting at Tredhaven in Maryland, upon the eastern shore,
to which meeting for worship, came William Penn, Lord Baltimore and his lady,
with their retinue, but it was late when they came,
and the strength and glory of the heavenly power
of the Lord was going off from the meeting.
The lady was much disappointed, as I understood by William Penn, for she told him,
she did not need to hear him, and such as he, for he was a scholar and a wise man,
and she did not question but he could preach;
but she wanted to hear some of our mechanics preach, as husbandmen, shoemakers,
and such like rustics; for she thought they could not preach to any purpose.
William Penn told her, some of these were rather the best preachers we had amongst us;
or nearly these words.
I was a little in their company, and I thought the lady to be a notable wife,
and a courteously carriaged woman.
I was also in company with the governor of Virginia, at our friend Richard John`'s house,
upon the west cliffs in Maryland, for we both lodged there one night,
and I heard that he had been studious in a book against Friends, called the Snake,
and Friends desired he might have the answer, called the Switch,
but knew not how to be so free with him as to offer it to him;
I told Friends I would endeavor to make way for it.
Although he seemed to be a man of few words, yet at a suitable interval I said to him,
I had heard that he had seen a book called the Snake in the Grass; he confessed he had.
I desired he would accept of the answer,
and be as studious in it as he had been in the Snake; which he promised he would,
and took the book.

There happened a passage worthy of note either in this
or the preceding governor`'s time in Virginia,
as I was credibly informed, which was thus:
The governor needed a cooper to mend his wine, cider and ale casks,
and some told him there was a workman near, but he was a Quaker;
he said if he was a workman, he made no matter what he professed; so the Quaker,
such as he was, was sent for, and came with his hat under his arm:
the governor was somewhat at a stand to see the man come in after that manner,
and asked if he was the cooper he had sent for: he said, "`Yes.`"
"`Well,`" said the governor, "`are not you a Quaker?`"
"`Yes,`" replied the man, "`I am so called, but I have not been faithful.`"
He then asked, "`How long have you been called a Quaker?
The poor man said, "`About twenty years.`"
"`Alas for you, poor man,`" said the governor, "`I am sorry for you!`"

By this we may clearly see, that such who walk up to what they profess,
are in most esteem among the more thinking and religious people;
and the unfaithful and libertine professors of the Truth are slighted,
and I believe will be more and more cast out as the unsavory salt,
which is good for naught in religion, and is indeed trodden under the feet of men;
for a great part of the world have such an understanding as to know
what we profess,`" and what we should do and be in many things.
Let us therefore walk wisely before all, and not be an occasion of stumbling,
nor give offense either to Jew or Gentile, nor to the church of God,
that so we may indeed be "`as a city set upon a hill, which cannot be hid;`" no,
that may not desire to be hid,
but rather that the inhabitants of the earth may see our good works,
and have an occasion from there administered, to glorify the Father which is in heaven.

Having it on my mind to visit a meeting up the river called Perquimons,
on the west side of the river Choptank, and being on the east side,
Henry Hosier and some more Friends set forward with me in a small boat,
not in good condition, with only one small sail.
We set out, as we thought, in good time to reach our desired port,
but when we were upon the great river, which is ten miles over the shortest way,
according to my recollection, though the manner of our crossing it made it more,
the wind veered much against us, being then within about four points of our course.
It rained hard, and was very dark, so that we could scarcely see one another,
and the water broke so into the boat, that it was one man`'s work to heave it out,
and all our company were discouraged, and most of them very sea sick.
Henry Hosier, of whom I had the most hope for help,
said that he could not steer the boat any longer.
Notwithstanding the extreme darkness, the roughness of the waves,
boisterousness of the wind and hard rain, unwell as I was,
I was obliged to undertake the steering of the boat,
and not without some conflicts of mind, having no certainty, from any outward rule,
what way we went.
Having no fire, and the boat being open, we could not have any light to see our compass,
but my faith was in the Lord, that he would bring us to shore;
and I kept the boat as near the wind as she would sail,
and told my poor sick and helpless company, I believed that we should not perish,
although we might miss of our port.
The like imminent danger, I think, I was never in before upon any water;
but renowned over all be the great name of the Lord forever,
we put into the mouth of our desired river Perquimons,
as though we had seen it in the day, or steered by a compass,
neither of which we had the benefit of for several hours.

Here we went on shore and made a great fire under the river`'s cliff,
and about midnight the moon rose, it cleared up and froze, and was very cold.
My companions falling asleep, I turned them over,
and pulled them from the fire as it increased, and put them nearer as it failed,
but could not keep them awake.
I sought logs of wood, and carried them to and minded the fire,
which was work enough for the remaining part of the night; but morning being come,
we got into our cold icy boat, and sailed away towards the meeting.
When we were come among Friends, notice was given of a stranger being there,
and a heavenly and sweet meeting it was,
so that we thought we had a good reward for all our trouble;
blessed be the name of the Lord now and forever, for he is worthy;
although he may see good to try us, sometimes one way and sometimes another.
How should we know that we have any faith, if it be not tried?
How shall we know that we have any true love to God, if it never be proved.
The trial of the true believer`'s faith is more precious than gold.
The excellent sayings of Job came into my mind, "`Behold, I go forward,
but he is not there; and backward, but I cannot perceive him: On the left hand,
where he does work, but I cannot behold him: He hides himself on the right hand,
that I cannot see him.`"
And then in verse the tenth, he, like a man in the true faith, says,
"`The Lord knows the way that I take; and when he has tried me,
I shall come forth as gold:`" and the more vehement the fire is,
the more it destroys the dross, and the more pure and weighty the gold is.
Read you, and understand this, that can.

I had a meeting, when in Virginia, at a Friend`'s house, whose name was Matthew Jordan,
and something that I said in the meeting, offended a young woman, a Presbyterian;
and not having, as she said, a suitable opportunity while I was there,
to discourse with me, being busy in her master`'s affairs,
for she was the Friend`'s housekeeper,
she desired liberty of her master to go to the next meeting,
that there she might ease her mind to me about the offense I had given her.
It was something about election, and they told me what it was, but not writing it down,
it went from me.
Accordingly she came to the meeting, where the Lord`'s mighty power broke in upon us,
to the tendering of many hearts, to Friends`' mutual satisfaction,
and it proved a good day to this young woman.
Her heart was as if it had melted within her; she shed many tears,
and I am satisfied went from the meeting in fear and in great joy; in fear,
how to walk so as not to offend Christ the Elect, whom before she could talk of,
but now she had met with, and he had opened her state to her: and joy,
that she had met with the Messiah, the Elect of the Father, his choice and beloved Son;
so that she could now say.
Where is the wise?
Where is the scribe?
Where is the disputer of this world?
All her brisk talkative qualities were swallowed up in the feeling of the internal,
enlightening presence of Christ.
When she returned to her master`'s house, he asked her if she had got satisfaction:
meaning, had she had any discourse with me, and was satisfied.
She replied, she was satisfied.
Some time after I met with her in Philadelphia, plain and Truth-like,
but knew not who she was at the first.
The manner of the working of the Truth is to humble the creature,
and bring it into contrition, tenderness and fear, with true self-denial.

When we were crossing James river to attend a Yearly Meeting in Virginia,
there were five horses and nine people in the boat; among whom were Jane Pleasants,
a public Friend, and her man-servant, who rode before her upon a great horse,
and high in flesh.
About the midst of the river, which was two miles over, he rose upon his hind feet,
and threw himself upon the gunnel of the boat, half into the river;
the fall of the horse, and the motion of the other horses,
caused the boat to make such sallies that it took in water, and was very likely to sink.
Before he could have time to rise again, I took several young men by the shoulders,
and threw them upon his neck to keep him down, and told them, as fast as I could,
why I did so.
The ferryman, who was about to strip for swimming, said we should all be drowned;
but for his part he could swim; and was about to leap into the river, for,
he said the boat would either break or sink.
I told him it was soon enough for him to swim, when he saw the boat either break or sink,
and if he would not row, I would.
With much entreaty he took the oar again, and rowed us to the shore.
But in our imminent danger I looked over my tender friends, for so they appeared to me,
and thought what a pity it would be, if all these were drowned!
Yet the thought of my own drowning never entered my mind, until I was got over the river,
which was a mercy to me, and a great means to keep out confusion,
which commonly attends sudden surprises and frights,
or makes people fainthearted and almost senseless.

I had now occasion to observe, as well as in some imminent dangers I had seen before,
that it is an excellent thing to be, as much as we can, always ready,
and by frequently thinking upon death, it is not so surprising when it does come.
It is a point of true wisdom, to number our days so as to remember our latter end.
The failure to contemplate what preparation we have made to look death in the face,
and to appear before the great Judge of quick and dead, was the cause of the complaint,
"`Oh that my people were wise! that they understood this,
that they would consider their latter end!`"
The great remissness of such considerations among people,
bespeaks folly and great insensibility,
and that the heart is hardened through a habit of sinning.
O that I might prevail with the children of men to awake.
Arise, you that sleep in sin, and are at ease therein,
that you may come to hear inwardly the call of the Son of God,
that your souls may not only live here to serve God,
but also may live eternally in bliss with him,
is the desire of my soul for the whole bulk of mankind;
for my life has often appeared not to be dear to me,
in comparison of the saving of the souls of the children of men.

I have often thought of Moses, how far he went for saving Israel,
and how far Paul went for the saving of his kinsfolk after the flesh.
It was a demonstration that they had great faith and interest in the Lord,
and a very great love to his people.
Those whose eyes are truly opened, cannot but see it is the love of God,
and love to the souls of men, that constrains us thus to take our lives as in our hands,
and labor through many weary steps, in many perils by sea and by land,
and in the wilderness; sometimes in tumults and noises,
sometimes in watchings and fastings, and we have been sometimes made spectacles to men;
but the Lord has given us faith and patience to bear and overcome all,
as we have singly stood in his heavenly counsel,
and been truly devoted to his will in all things.

Something which I have before omitted now occurs to my memory:
when I was in that part of Virginia towards North Carolina, to visit Friends,
a very great mist arose, and we went wrong, until the guides were so far lost,
that they confessed, they knew not east from west,
nor on which hand we had left the road, although it was in the forepart of the day,
neither wind nor sun was to be felt or seen.
I told them I would try what I could do,
if they did but know what quarter we should go to:
they said we should go towards the south:
then I brought out my little compass which I had made before I left England,
and steered by it till we came into the road.
The inward sense I had persuaded me, that we were to the westward of the road,
so leaning a little to the eastward of the south point, we came right,
and the guides rejoiced,
and said I was fitter to be guide in a wilderness country than they.
My compass was not so big as a tailor`'s thimble, but had often been of use to me,
and others with me.

Now the time came on for my leaving all my near and dear friends in these parts,
and I embarked for the islands the 6th of the ninth month, 1702,
with my companion James Bates, on board of a sloop, Samuel Salter, master, for Barbados,
and we put into Bermudas in our way.
Soon after we landed, being on the 21st of the same month,
we were sent for by Governor Bennett to come before him, and being near his door,
a man came and clapped me on the shoulder, as we were walking on our way,
and said roughly to us.
You must go before the governor, and seemed to hasten us.
I replied meekly, I am willing to go as fast as I can, but I have been very sea sick,
and can go but weakly.
The man fell from his roughness, bid us take time, and carried himself very civilly,
and put us by a man who was keeping sentry at
the governor`'s door with his musket on his arm.
When we were come into a large room the man left us, and we wailed a while.
I began to reason in myself.
What if the governor should be a rigid man, and severe to us,
and either confine or punish us?
But I said in my heart.
Lord, you that know all things, know that I have not only offered up my liberty,
but life also, for your name and Gospel`'s sake;
and immediately all fear and reasonings about human power were taken away from me.

Being unwell, and weary with walking from the ship, I sat down to rest myself unbidden,
when there came a friendly well carriaged young woman, who I supposed to be a servant,
and spoke kindly to us.
I desired her to do as much for us as to give us something to drink,
for we were very thirsty, and had been much out of health,
and were not well recovered since we came from the sea, having had rough weather.
She brought us wine and water, and taking most of a glass of water,
and a very little wine poured into it, I drank and was very well refreshed.
By this time the governor called us into an upper room,
and as I came near to the top of the stairs, going but faintly, for reasons before given,
the governor put forth his hand and reached to take hold of mine,
and like a tender father drew me up, and led me along towards a great window,
and stood and looked on me and said he believed he knew what I was, and my business too.
I replied it might be so, and asked if he was the governor of that place: he said he was,
and bowed his head.
I then spoke to him in the love of God and said, "`Thy countenance bespeaks moderation,
and the apostle said, '`Let your moderation appear to all men,
for the Lord is at hand.`'`" And it was with me to say to him,
"`The Lord of heaven and earth bless you and all yours.`"
He bade us sit down, and gave us each a glass of wine, and inquired from where we came.
I told him my home was in Old England, but it was long since I was there;
my companion`'s was in Virginia.
He wanting to know the affairs in Europe,
I told him there was a merchant belonging to the same ship that we did,
was lately come from Europe, and I thought was a man of parts and memory,
and well versed in the affairs of those parts of the world,
and when we came into this place he was with us.
The governor sent for him, and when he came,
he answered his expectation in resolving all or most of his questions,
for the knowledge of the news appeared to me to be the young man`'s talent.
Having dismissed him, he said he must now have some discourse with us:
then rose up all the great men who were with the governor,
to make way that I might come near him.
I said if it was the governor`'s mind, I had rather sit where I was, for I sat in the air,
and that suited well with my present weakness.
So he bade them all sit down, and they did so.

Now, said he, I want to know the reasons why you, as a people,
do not assist the king and country with men and arms,
for their and your own defense and safety, against all that may attempt your hurt.
I replied, the most convincing reasons I have to offer to the governor are,
we have neither precept nor example from Christ, or his apostles,
to use the sword to hurt one another with.
No, said he, what then means that saying of our Savior,
when he bade him that had no sword, sell his cloak or coat and buy one?
I replied, one of his disciples answered and said, "`Lord, here are two!`"
Christ said, "`It is enough.`"
Now how two swords can be enough to answer for a general precept,
I leave the governor and all these men to judge.
So after a little pause he said,
In case you were assaulted by robbers that would break your house,
and take what they could get from you, or upon the highway,
and would take your purse or horse, what would you do in that case?
I replied, I could not directly answer what I should do in such a case,
because through the Lord`'s mercy I was never yet so assaulted;
but it appears most likely, that I should endeavor to keep my house from being broken up,
and yet be tender of men`'s lives; and as to the other assault,
inasmuch as it is well known I do not provide any outward weapon for my defense,
neither sword, pistol, nor any such like weapon,
therefore I must rely upon the Lord for protection and help,
who is able to rescue me out of the hands of all such ungodly men: or if he does not,
I must endeavor to bear what the Lord allows such to do to me.
The governor said, "`You say well:
for inasmuch as you have not provided anything for your defense,
you have nothing to fly to but the Lord;
you say very well;`" and said he hoped what he had offered had not given any offense.
I replied, it was so far from that, we were glad he was so free with us;
yet if he pleased to dismiss us, we should be willing to be going, for night came on.
He said, there were some of our friends would be glad to see us.
I replied, I understood there were some further on the island that did acknowledge us,
but how much they were of us I could not tell, for I had not seen any of them.
He asked, whether we had a mind to go by water or by land, for he had a boat,
and a couple of hands should carry us where we would; or if we had a desire to ride,
he had two horses, we might take them and keep them as long as we stayed upon the island.
I endeavored to persuade him to let us go without troubling himself any further,
for I was sensible of his good will and love to us, and having his countenance,
was more than we expected, and as much as we desired.
He still urging to know, after what manner we would choose to go: I told him,
I was very sensible of his generosity to us who were strangers,
and if he would be easy and let us pass, we had means to defray our necessary charges,
either by water or land, as would answer best with our convenience.
He pressed upon us to accept of his offer,
for he said he did not do it in compliment to us.
Seeing no way but to accept of his generous offer,
I said riding at present would be much more acceptable to me,
considering how I had been lately fatigued at sea, of which I was not yet well.
He immediately gave orders for the horses to be brought to the door, which being done,
and we having notice thereof, I rose up and made an offer to go,
and the governor likewise rose up and came and took me by the hand,
and we went down into the great room where we
first entered in the Lord`'s dread and holy fear.
I had resigned my life and all to the Lord who gave it, and my life at that time,
as at many others, was not dear to me for Christ`'s sake; and being thus resigned,
I felt the love of God, and a measure of that life was manifest,
in which I had dominion over men, bonds, and over death, and the powers of darkness;
blessed be the Lord forever.

Coming to take horse, I looked out at the door, and saw two horses.
The one next to the door, which I supposed I was to ride on,
had a saddle set about with three rows of shining silver lace,
I thought about two inches broad on each; the governor holding me by the hand,
and looking in my face, said,
I am apt to think you are not used to ride upon such a saddle as this.
I told him, if he could let me have one more like myself, plain, without much trouble,
I should like it better, but if not, I could ride on it, I thought,
without much straitness, in case of necessity.
He answered, he could not, for horses and saddles were scarce on that island;
one was that which he rode on, and the other was for his man;
but he said he would tell me how to prevent all this.
If, said he, you get over the inlet of water, though he questioned it,
because the wind blew very strong in the mouth or inlet of the river,
and should come to Richard Stafford`'s, an old judge of life and death,
we might ask there for the cover of his saddle,
which ties on with little straps at each corner and hides all this,
and then it will be like yourself.
But if the ferryman says he cannot carry the horses over, what man soever you meet,
white or black, if capable, tell him he must bring me my horses,
he dares do no other but bring them; and be sure you take no further thought for them:
and if we met with anything that troubled us, let him know and he would help it,
if it lay in his power.

So with his blessing on us, we took leave of him, and came to the water-side,
but could not get the horses over, therefore we sent them back again,
and intended to stay at the ferryhouse all night,
but the boat was about going over as we alighted; and notice being got to the judge,
that there were two strangers on the other side of the water,
he sent a boat and a couple of men for us, who said, we must go,
for the judge said he could not sleep until we came.
So we went, after asking,
if they at the ferry-house had been at any cost
or trouble on our account in providing supper,
for as yet we had not eaten anything since we landed; the people said no,
they had not done anything which we should pay for.
It grew dark and very stormy, and the sea broke over the boat,
so that some of us were forced to hold our coat
laps one to touch another on the weather-side,
to keep out the breakers, that they might not fill the boat.
We came safe over to the judge`'s house,
and no sooner got into the passage but his friendly wife met us,
and asked us if we were the strangers her husband had sent for, I said, we are strangers.
She bid us follow her to the judge, and we did so.
When we came to him he rose up, and took the candle in his hand and said,
"`Are you the strangers I sent for?`"
I said, "`Who you may expect I know not, but we are strangers.`"
When he had looked well in my face, he set down the candle, and said,
"`What a mercy is this, that the Lord should send men from I know not where,
in his love to visit me!`"
And he took me in his arms and kissed me; and I said to him,
"`The Lord of heaven and earth bless you;`" and we shed many tears and wept together.

As I entered the house, I felt the love of God, and his glory, I thought,
shone in and filled every room as I passed through them, and I said,
peace be to this place, and I felt it was so.
He inquired of our travels, and from where we came, of which we gave him a brief account;
he also asked, if I knew anything of the family of Staffords, at Lahorn,
near Haverford-west, in South Wales.
I told him all I knew about them, both of the dead and of the living;
with which he was pleased, and said, he had not heard of them for many years,
and that family were his near kindred.

I found his usual bed time drew near,
and I made an offer to go away lest I should incommode him,
yet he appeared unwilling to part with us; but considering his own ailments,
and our early rising in the morning, he at length consented.
Before we parted, his wife asked leave of him to go with us on the morrow to the meeting,
to which he readily assented, if he was not worse of his distemper,
and then ordered how we should ride, and which negro should go,
not only to help his wife but us also, and take our horses when there was occasion,
and do anything he could for us; and indeed so he did,
and appeared to me to run on foot without much trouble, being a lively young man.

I omitted before, that the judge asked, if we had seen the governor,
and if he was kind to us.
I told him he was very friendly to us,
and said if we met with any trouble that he could help us in,
only let him know and he would right us.
The judge said it was very well, and he was glad of it.
I perceived the judge was rather a moderator of the governor,
he being an ancient wise man, and had lived long as a judge upon the island,
and understood, it is likely, more fully the state of things here than the governor,
he being but a young man, although he appeared to be a wise man, and,
as William Penn said, came of an ancient and honorable family in England,
which he knew very well, whose name was Bennett.
Afterwards I told William Penn how it had fared with us on that island;
and especially the kindness of the two chief men in power there, and William Penn wept,
and said, he had not heard any account of this nature,
that he had been so much affected with, as he remembered, these many years.

We left the judge until the morning, and got some refreshment, it being late,
and I had been faint for several hours for lack of food,
but the Lord`'s heavenly power bore me up over all,
so that at times I felt no lack of anything:
Oh! renowned over all be the name of the mighty God, now and forever.
We went to bed, and when morning came, I and my companion were stirring early,
having eight miles to the meeting, and it being in the latter end of the ninth month,
we were willing to be in time, that we might give some notice to the people.
I was walking in our lodging room early, and the judge`'s wife came to the door and asked,
if she might speak with us; I said she might:
then she came in and said she had a message from her husband to us.
I queried, what it was;
she said he desired we would come and pray for him before we went away.
I desired she would favor us so much as to lay
before her husband something which I had to say,
and she promised she would: Well then, tell the judge,
that if he will allow us to come into his room, and sit down and wait upon the Lord,
as our manner is in such a case as this,
if it please the Lord to move us by his Holy Spirit to pray, we may; but if not,
let not the judge take it amiss,
for we are willing to be at the Lord`'s disposing in all things.
She went, and I believe, as she said, laid the matter before him,
as I had delivered it to her; for she was a woman of a good understanding,
and came back again to us in a very little time.
I asked what the judge said; she replied, he said, let the men take their own way,
and whether they pray for me or not, I believe they are men of God.
So after some little respite, being brought to the judge`'s bedside,
we sat down and waited upon the Lord, who was pleased in his love,
and by his mighty power to break in upon us,
and also opened my mouth in his gift of grace and of supplication,
in which gift ardent and fervent cries went up to the Lord of heaven and earth,
that he would send health and salvation to the judge, and also to all his family,
and to all people far and near, that all everywhere might repent,
and come to the knowledge of the Truth and be saved.
The judge wept aloud, and a mighty visitation it was to his family,
and especially to himself and his tender wife.
We left the judge in a fine frame of spirit, and no doubt near the kingdom,
having his blessing and earnest request,
that when we could reach his house we would not fail to come to it,
for we were very welcome; and I found and felt it so, and it was mostly our lodgings.
His wife and foot page went with us to all the meetings, except one,
while we were on the island, which was about two weeks,
in which time we had many good opportunities among a soberly behaved people,
amongst whom we met with no opposition, but had large quiet meetings.

When we were clear, as we thought, of the island,
we went to take our solid leave of the governor,
acknowledging his civility and generosity to us.
I told him and the judge,
that they would not lack their reward for what they had done to us,
and to such who should take their lives as in their hands,
and come in the love of God to visit those remote parts of the world,
which we dared not have undertaken if we had not
believed it required of us by the Almighty,
and our peace concerned in it, as also the glory of God,
and the good of the children of men;
these are the motives to those our great undertakings, or words to that purpose.
So we parted in much love, with these great men, especially the judge,
with tears on his face, as also his tender and friendly wife,
who had been very serviceable to us in ordering meetings, and making way for us.
There was none like her in all the island, that we met with,
being given up to that service,
for encouraging Truth and Friends in what she was capable of.

Being invited to a Friend`'s house to dine one day, when we had sat down at the table,
the woman of the house desired that one of us would say grace;
from which I took occasion to show her and several more in the company,
who appeared not much more grown in the Truth than she, that since we had been a people,
we had both believed, and accordingly practiced,
that true prayer was not performed without the help of the Holy Spirit of God,
and no man could pray aright and acceptably without it;
nor was it in man`'s power to have it when he pleased.
Therefore it is man`'s place to wait upon the
Lord for the pouring forth of this gift upon him,
and also to know whether it be required of him to pray so as to be heard by man,
or only to pray secretly, so as to be heard of God, as did Hannah,
and as many more have done; which, as they do aright, no doubt,
but as Christ said to his disciples, their Father will hear them in secret,
and reward them openly; or to this effect; with which they all appeared satisfied.

We then went on board our vessel, and set sail with a fair wind for Barbados;
but soon after we got out to the mouth of that inlet where we arrived first,
the wind came full against us, and we put in there again; and the master,
although not called one of us, said, in a friendly manner, What is the matter now?
This is because of you, Mr. Richardson, as he was pleased to call me,
although I often showed my dislike to it, you have something to do yet upon the island.
I said I know not of anything; but he seemed positive, and said,
if the wind came fair at midnight he would call, if I was willing, if not,
he would stay as long as I pleased.
I said I knew not of anything to hinder, but he might call as soon as the wind came fair.
So we parted, only telling him we intended to go to the judge`'s house.
It was late in the evening when we got there and the judge was gone to bed;
but his wife was up, who lifted up her hands with more than ordinary surprise,
and much joy, and said she was always glad to see me, but never more than now: I said,
why so?
She then began to tell, that since I went away, there had been a man with the judge,
who had incensed him against me all that he could, and said he knew me in England,
and that I was broken, and came into those parts to preach for a living.
I asked what her husband said to all that?
She said his answer to the man was, that he believed I was no such person,
but an honest man; yet the accuser seemed very positive.
I said it would be well if this man could be brought with me to the judge`'s face,
that he might be convinced, not only of the man`'s ignorance of us as a people,
but of me in particular, and his envy against me be made known.
I opened to her the nature of such journeys and services, how we proceeded,
and how the meetings were constituted in which we did so proceed,
and from where we had certificates, namely, from Monthly and Quarterly Meetings,
or meetings of ministers to which we belonged,
and from Friends in the several provinces and islands where we traveled,
if we desired them, many of which I could show the judge, if time would permit.
She said, lest we should be called away in haste,
she craved to see some of those certificates.
I showed her them, beginning at the first, wherein Friends of Kelk, now Bridlington,
Monthly Meeting in Yorkshire, to Friends in America,
declared not only their full unity with my present journey,
but also with my service for the Truth, and manner of life in the same,
where I had lived and traveled;
and that I had settled my outward affairs to Friends`' satisfaction,
under many hands variously written.

When this great and wise woman saw this, she said it was enough:
but I showed her other certificates from diverse places,
wherein Friends had signified sufficiently their unity and satisfaction with me.
I likewise informed her, that in case any man, not approved by us as a minister,
attempted to impose his preaching upon any who were strangers to him, such as knew him,
took care to acquaint the churches therewith, if his intentions could be known,
that no impostor might do any hurt.
All which she admired, and said she had never heard so much before,
neither did she think there had been such excellent order amongst any people.

Having thus acquainted her with our order and discipline,
and afterwards informed her of the cause of our unexpected return,
I renewed my proposal of having my accuser before the judge.
She told me, she had good place with her husband, and would endeavor to obtain it;
and accordingly, after talking with him, she let me know,
that the judge expressed his readiness to do me any service which lay in his power,
and was of opinion my accuser dared not face either him or me in that affair.
If the wind continued against us, he would try to find him out, and bring him,
which might be of service; but if the wind favored, she thought I might be easy to go;
as indeed I was, and the more so, considering that our captain, Salter,
who lived near the judge on the same island,
had showed a great deal of patience and good disposition to us, for about two weeks,
yet would gladly be gone.
About midnight we were called to go on board the ship, for the wind was fair,
if we were ready.
I replied, we come quickly: and so we did, and took leave of all we saw of the family,
and remembered our dear love, with grateful acknowledgments, to the judge,
for all his civility and kindnesses to us, with reasons why we could not see him,
for he had been afflicted some time with the gout, and was now fallen into some rest,
and we going away very early, were not at our own disposal.
I admired the Lord`'s good providence in all this,
and there was something from the same watchful Providence,
to order that to be put into my certificate which did so fully
remove the slur this enemy would have fastened upon me,
i.e. That I had broken in England, and could not pay my debts,
and therefore had come into these remote parts of the world, where I was unknown,
to preach for a livelihood.
But it fully appeared, that I was known, and well beloved too,
and had effects to discharge any just demand upon me,
blessed be the worthy name of the Lord now and forever.

Now I may say something of our affairs upon the sea in this voyage.
When Captain Salter had taken us in passengers at Philadelphia for Barbados,
it being a time of war, and people somewhat afraid of shipping goods, he said,
he was to have two honest Quakers passengers,
and he did not fear being taken by privateers, or pirates.
I was troubled at his confidence in us, and told him so,
and that it was much if the Lord did not allow us to be taken,
that he might see men were not to be depended upon,
but that we ought to depend upon the Lord alone for protection and deliverance; however,
in much less time than we expected, goods came, and we were loaded and gone.
We had rough weather before we came to Barbados;
especially about the tropic of Cancer we had very high winds,
and I was extremely sea-sick, and so was my companion, and I could eat little,
but was treated with remarkable civilities by the captain.
About that latitude there are fish not unlike herring, which fly from wave to wave,
and by dipping their fins or wings in the water, they will fly a great way,
especially when they are chased by fishes of prey,
and almost every morning there were some of those fish on the ship`'s deck.
The captain often said, as his manner was, Mr. Richardson, these are sent for you,
or for your breakfast, and seeing it is so, I will dress them myself,
for I know my cook is so greasy you can hardly eat of his cookery.
This was very true, and therefore he would wash his hands,
and lay a clean napkin on his arm,
and tell me he would dress me my breakfast in the best fashion he could.
I asked him why he would put himself to so much trouble;
he said he never wailed on a man in all his life with so much pleasure,
and if I were going into any country where he was going,
I should not pay anything for my passage; so much respect he showed me.

It happened in the course of this voyage, when we were within a few leagues of Barbados,
one morning early, as soon as day appeared, he that was aloft,
upon the watch to look out, as the manner of mariners is,
especially in the time of wars and danger, espied a ship,
which he and the rest of our most knowing men supposed to be a Turkish frigate,
of considerable strength; however, it was a great vessel, and appeared to have many guns;
and when we first saw her, she seemed to be within gun shot.
But oh, what a surprise and fright our ship`'s crew were in!
I had not often seen the like.
Our vessel being deeply loaded, although a good sailor,
was less than that which chased us,
and to run for it appeared the only way for us to escape,
hauling as close to the wind as we could, to keep the sails full.
The vessel being stiff with its great burden, endured sail well,
and they crowded so much,
that I told them I feared they would bring the rigging by the board.
Thus we labored until noon,
and then our captain having lost all his confidence in the Quakers, said,
we shall be taken, for the ship has gained upon us for several hours;
we have done what we can, and are all spent.
I walked upon the main deck under no small concern of mind, and Truth rose,
and I found it open in the Truth, that we should not be taken; the captain said,
binding it with some asseverations.
We shall certainly be taken.
I said, No, we shall not, unless by our mismanagement.
Alas, said he, you are such a man as I never met with.
Do you not see the frigate, or Salleeman, for so he called her,
is just going to fire a broadside at us, opening the gun-ports,
and laying the ship broadside upon us, and leveling at her as well as they can.
Although our captain was a stout man, he appeared very ghostly and dead-hearted,
and said to me in a tone which bespoke both affliction and trouble, Go into my cabin,
or somewhere under the deck, for they will fire immediately;
and where I walked I could hardly escape either the shot or the rigging falling upon me.
I said, they will not fire; and desired him to be easy,
for we should come to no damage by that ship.
Well then, he asked, what they should do, for the enemy was just upon us.
I said I would fetch them a bottle or two, or more of my best brandy,
and they should take as much as might do them good, but have a care of more,
and ply away awhile, and you will see they will fall back and we shall leave them.
The captain said, although there was no human probability of escaping, yet, for my sake,
they would try; and to work they went.
I think I never saw men on board of any ship work like them for some hours,
and we soon perceived that we outsailed them, and by the time it began to be dark,
we had left them considerably.

Now all fire and light was forbidden, except what could not be avoided, and all noise,
and a council was held, to consult what way to steer,
whether the nearest or most common way for the island, or about;
for it was reasonable to conclude the adversary would waylay us, if he could,
before we came to the island.
The captain said, what I said in the case should be done; after some deliberation,
I told him, I was most easy in steering the nearest course, which we did,
and saw our adversary no more.

We came to the island next day in much joy, that we had escaped so imminent a danger,
but I was very ill of a fever when I landed,
which had been growing upon me for several days, this being the sixth day of the week,
and 18th of the tenth month.
I was so poorly, that several thought I must die;
but I stood resigned in the will of God, whether to die or live.
The first-day being come, I went to the meeting, though with great difficulty,
being very weak, where I sat under more than usual exercise, reasonings,
and conflict of spirit for some time, about my present condition, which was weak and low,
and in my own apprehension, unlikely to be of any service.
Notwithstanding all the troubles and hazards of the sea, and robbers,
and other jeopardies in coming here, I was now disabled and laid by as useless.
These things occasioned me to consider,
whether I had not missed my way in something or other.
Many particulars were brought to my mind,
whether I had discharged myself faithfully where I had been.
When I looked back,
and took a view of my travels and services in the work
of the ministry and discipline of the church,
my conduct and whole manner of living,
I saw nothing but that I was clear of the blood of all men;
as also clear and well satisfied both as to the time and my coming to this island.
There appeared yet two things in my way; first, if this place should be my grave,
such as might not watch over me with the best eye may say,
if he had gone at the Lord`'s command, no doubt he would have brought him back again;
and secondly, as I had two little children in England, if I finished my course here,
they would be left fatherless and motherless.
And I said before the Lord, let not my end bring dishonor to your great name,
nor any blemish to the Truth which I have loved and labored for the promotion of,
from my childhood.

When I had thus appealed to the Lord, I felt great quietness and resignation of mind.
As I sat, a Friend well thought of by several, began to speak in the meeting,
and it opened in my mind,
that he was not wholly redeemed from having some thoughts that
elementary water had not yet ended its service;
I mean in point of dipping.
I would have shut it out, for the man appeared a wise, zealous man;
and being altogether a stranger, I could not remember that I had heard his name,
yet the matter continued, and I thought, for my own satisfaction,
I might ask him the question.
If he was a right spirited Friend, he would not be hurt; if he was not,
he stood in need of help,
or at least it was high time for Friends to have a more perfect knowledge of him.

During my sitting, as before, under much weakness of body, yet quiet in mind,
the living virtue or heavenly power of Christ
sprung up in my inward man like healing oil,
which so effectually helped me every way, that I could say feelingly and experimentally,
miracles are not ceased.
I was raised beyond my own expectation, and all others who knew my weak state,
to give testimony to the glorious coming and manifestation of Christ in power,
and spirit, for the help and salvation of all the children of men who receive,
believe in, and obey his spiritual reproofs and heavenly calls in the soul,
without any lessening to his humanity.
Great cause have I, with all the living, to love, honor,
and reverence the great and mighty name of Him who has helped and healed,
by sending his eternal word of living power into our hearts.

Returning with other Friends to my quarters from this good meeting,
not to be forgotten by me, the before-mentioned Friend came to see me.
Having, as I told him, a desire to speak privately with him, he replied,
there were none there but his good friends, and I might speak my mind.
I told him, what I had to say related chiefly to himself,
and in such a matter as he might not be willing to have exposed; but he would not hear,
and said I might speak it there.
I desired he would not take offense at what I had to say,
for I did suppose it to be a secret to all there but himself.
Then I said, the matter is, when you were speaking in the meeting,
it sounded in the ear of my soul as if one had said, this man, meaning you,
is not wholly redeemed out of a belief in John`'s ministration of water,
as not having done its work.
Now the matter is before you, you know whether what I received be true or false:
in the first place I inquire for my own satisfaction.
His answer, if it may be called one, was as follows: he said, The disciples of Christ,
when they baptized with water,
knew that it was the mind of their great Master that they should so baptize.
I said, I know not that any of the apostles did ever say so much as you would insinuate;
for both by what Peter and Paul say, it appears very natural to be the mind of Christ,
only to condescend to so much as was done by the apostles in that of water,
because of the people`'s weakness;
and no question but the Jews were very much settled in the belief of
John the Baptist`'s dispensation of water to repentance,
and also of the circumcision, and purifying,
and many other things used amongst that people.
When the converts were grown stronger in the faith and in the grace of God,
Peter told them, "`It is not the putting away the filth of the flesh,
but the answer of a good conscience towards God,
by the resurrection of Jesus Christ;`" and Paul,
although he did once in condescension circumcise Timothy,
yet told the people at another time,
that "`Neither circumcision nor uncircumcision avails anything,
but a new creature;`" and that if they were circumcised,
Christ would profit them nothing.
He also thanks God, he baptized no more than Crispus and Gaius,
and the household of Stephanas; besides these,
he knew not that he had baptized any other, for Christ sent him not to baptize,
but to preach the Gospel.
I said to the Friend, I am of the prophet`'s mind, when he said,
The elements should melt as with fervent heat;
if the Gospel power be not this fervent heat, I know not what is,
nor what is able to melt away the elements.
But I further said, if he was a Baptist,
he should deal plainly and honestly with Friends, and tell them what he was,
and not preach one thing, and keep such reserves to himself.

Friends admired, and said,
they had not the least thought of any such thing respecting him;
so he said he would not fall out with me.
I told him, I was as much for peace as he was,
but at the same time I would have us to mind that we were sound in the faith,
and preachers of the Gospel, and not go back again to the beggarly elements,
for what is all in comparison of the love of God in Christ Jesus?

I had good service and great satisfaction upon this island,
although I found Truth so low, that it might then be truly said as formerly,
By whom shall Jacob, or the true seed, arise, which is in our apprehension but small,
and much pressed down with many things that are hurtful, especially by the love of money,
pride, and forgetfulness of God?

I was invited on board a great transport ship, whereof one Reed was master,
who remembered me when I was but young, and was traveling to or near Scarborough;
he was loving to me, and several Friends who were with me,
and I had good service on board.

There was also on board a French Protestant,
now a captain of the English transport soldiers, bound for Jamaica.
He lodged at John Groves`', and was a very civil man,
and said if I would go with Captain Reed, who offered to carry me to Jamaica for free,
he would wait on me if I was sick, or ailed anything;
and would gladly have had my company.
I acknowledged both their generosity and civility to me, and took leave of them,
and of the noble Captain Salter, who I have had occasion both to mention and to love.
He took his solid leave of me, wept like a child, and said openly in the hearing of many,
that he never loved a man so well before, and though he did not lack business, yet,
for my sake, he would serve my friends what lay in his power; or nearly those words.

I find, as we live and walk in the Truth,
there is an inward witness which God has placed in the hearts of men that is reachable,
except in such who have arrived to a great degree of hardness and insensibility,
and so have little sense or perception of good, either in themselves or in others,
which is a deplorable state.
Oh, what grief of heart it has been to me, to hear and see the wickedness of some!
If such wickedness was as great a trouble to them who acted it, as it was to me,
I have thought they would soon grow weary of it.

I embarked on board a ship, John Griffith master, bound for Bristol, in Old England,
and went to sea with some East India ships that had put in at Barbados,
having a ship of war or two for their convoy.
After we had got to sea,
they had so much drinking and carousing that we grew weary of staying with them,
and after some consideration, the captain, who was a Friend, left them,
and came safe to England.

In our passage we had some rough weather near the tropic, which I mentioned before,
and the men and captain being much disordered with watching and hard labor,
as I remember, for eight and forty hours night and day, a calm ensuing,
the captain desired me to take his place for his watch, and mind the helmsman,
and see that he made straight steerage; but he was so sleepy,
that it was next to impossible to keep him awake.
I walked on the deck, and had overmuch work to mind the compass and the helmsman too,
for a fine breeze of wind came on, and all of a sudden a very unusual fear fell on me;
I looked into the sea, and beheld it appeared to turn blue,
and as far as I could discern to windward, I saw white caps, or the water-freckle;
on seeing which, through fear, more than any great skill,
I stamped with my foot as though I would have broke the deck.
Out came the captain,
but what with fear and sleep he could scarcely hit the door out of the cabin.
When he got upon the deck, he stamped, and called out all his hands,
and bid them lower and furl the sails with speed, or else we were all dead men,
for here is a hurricane just upon us.
No sooner was all made snug as well as could be, as the seamen phrase it,
but the wind blew so, that we thought it would have turned the bottom of the ship upward:
the like I never saw; and, as the captain said,
we had not one minute to spare of being cast away, according to all human probability.
As the seamen term it, it was such hurry-durry thick weather,
that we could scarcely see anything a hundred yards.
It held for about an hour, in which time we drove by a vessel, and were so near her,
that I thought I could have flung a stone aboard.
Our ship`'s crew were sorely afraid, and looked upon her to be a robber;
her rudder was lashed or tied up, and the men were all gone off the deck,
but our mariners were so affrighted,
that they thought they would set some sail and follow us.
No sooner were we past this ship but the weather grew better,
and away we ran in hazard of bringing the masts by the board;
but through the Divine Providence of him who is Lord over all, both sea and land,
we escaped, and came safe into Cork in Ireland, where the master lived;
we rode there some time, and then weighed for Bristol,
intending for the Yearly Meeting there.

We had rough weather in crossing the channel, before we came into the Severn,
where our sailors, afraid of being pressed, launched the boat,
and ran away into Cornwall, leaving but four on board to bring the ship up the river.
We saw a pinnace, having in it a lieutenant with a crew of pressed men,
intending to press more if they could find them.
Our master called on me, desired I would put on my best clothes, and come to him,
which I did, and he set me on his right hand.
By this time the lieutenant came up and asked for my men, taking me for the master.
I told him, they had launched the long-boat and were gone, and we could not hinder them,
they being the strongest party; at which he appeared very much enraged,
and seemed as though he would have struck at me.
I told him calmly, he had more need to pity than be angry with us,
for if there should be a gale of wind,
we were in great danger of all perishing for lack of hands.
I showed him what force we had, namely: James Bates,
whom I did not then call my companion, John Griffith captain, the cabin-boy and myself,
who were all the men on board.
He asked, what for a man that was who sat beside me?
I told him, he was a man sufficiently secured against the press.
Then the rough man fell, and said I looked like an honest man,
and he would take my word and not search for men.

I write not this as a thing I approved, but disliked; but being taken at unawares,
had not time to shun it, unless I had exposed my friend, the master of the ship;
although I neither said nor did, that I know of,
anything worse than what you see here written; I told the captain,
I thought he was a great coward, and had exposed me to danger to save himself.

Wind and weather favored us, and we came in due time to Bristol Yearly Meeting,
where I met with William Edmundson, and was truly glad to see him,
with many more at that place.
My companion falling sick, I was made willing to leave him,
and traveled to London with John Watson of Ireland, a sweet spirited man.
We got to London Yearly Meeting, where I discharged myself of what I had upon my mind,
and came away in peace, and in the feeling of the love of God.

John Haydock and I came from London together,
and had meetings in our way to York Yearly Meeting,
where I was glad to see my home-friends,
and to enjoy the love of God once more with them.
This is our principal crown and kingdom, in this world,
to enjoy the favorable countenance of the Lord,
and one another in his living and internal presence.
When I looked back upon all the mercies and deliverances I had
received from the mighty God of heaven and earth,
seas, and rivers of water, whose hand made all,
and whose eye and watchful providence attends all, and is over all,
my soul was filled with thanks and praises to the great
and most excellent name of Him who lives forever,
and has helped my soul to overcome many strong temptations,
and has borne up my head under many deep afflictions and tribulations;
renowned forever be his holy name.

I came home the 18th of the fourth month, 1703, and found my children well;
and now I was under a thoughtfulness how to walk and demean myself,
so that I might be preserved near the Lord, and in reverence and true fear before him;
that as I found there was something of holiness unto
the Lord engraved upon the fleshly table of my heart,
I might not lose the savor, relish and sensation of heavenly things,
now when I was not so particularly and immediately
concerned in the like daily travel on Truth`'s account.
Some will read me here,
in this short survey I have been taking of my thoughtfulness and present state,
that if I could not make it better, I might not make it worse,
either in doing or not doing anything that would prove a hurl to me;
for a vessel had better be laid by, if it can be spared, than used to its hurt.
In this careful and watchful frame of mind,
I have found preservation from time to time to this day,
by retaining the salt of the kingdom in the soul or the inward man,
which is of a preserving quality, with which the vessel is,
and can only be kept fit for the Master`'s use; if we lose this,
the creature soon grows unfit for his use.
Read and consider these things in time, while you have the prize in your hand,
and time to do, and receive good at the hand of Him who is truly full of good,
and is all good: to Him be the offerings of praise and renown now and forever.

While I remained at home, as my usual manner was, I attended first-day, week-day,
Monthly, Quarterly, and other meetings, and visited many meetings in the country,
and had much satisfaction in being given up to the service of Truth.
I did not see it convenient, as my children were well placed, to settle to keep a family,
until my way appeared clear to marry, which now drew on,
and after I had been nearly seven years a widower, I married Anne Robinson,
who descended of a substantial family at Hutton-in-the-Hole, in the parish of Lestingham,
not far from Kirbymoorside, in Yorkshire.

We had not been married much above two years,
before my wife began to appear in the public work of the ministry,
very acceptably to Friends;
and she grew in understanding of the discipline of the church of Christ,
and also in further knowledge in the work of the living ministry.
About that time it came upon me to visit Friends in
most parts of the northern counties in England;
and a short time after my return,
I had a concern to visit Friends in several parts of the southern counties.
Thomas Beedal, being my companion, he grew in the Truth, and also in the ministry:
and we had many good meetings in that journey, good service and great satisfaction,
and I returned home in peace.

Now I may say with sorrow of heart,
the time drew on quickly when my virtuous wife and I must part,
and be no longer help-mates to one another, which we truly were,
and never had either evil word or evil thought against each other, I am fully satisfied;
but lived in peace and true love one with another,
and were glad when we could serve Truth and Friends: therefore I find it on my mind,
in this place, to insert the following relation concerning her:

She was descended of an honest and considerable family of the Robinsons,
and was convinced in her young years, and received the Truth in the love of it.
It became precious to her above all things in this world;
and through the blessed operation of the grace and Holy Spirit of God,
she was weaned from the world`'s pleasures, vanities and recreations,
and from taking any delight in them.
Through the virtuous and most precious blood of Christ,
she came to witness her heart sprinkled from an evil conscience,
and in a good degree made able to serve the living God.
She bore a faithful testimony against the needless and
superfluous dresses and fashions of the world,
as also against the corrupt language thereof.
She came to be a great lover of virtue and purity,
and had much satisfaction in being in Friends`' company, and at meetings,
and in retirement and waiting upon the Lord.
In great mercy and condescension to the desire of his handmaid,
he gave her a large share, not only of the enjoyment of his power and internal presence,
but also a knowledge and clear sight into those
things that appertain to life and salvation.
After Truth thus prevailed over her,
and brought every thought into the obedience of Christ,
and subjected her will to the will of God, which is a great work,
without which there is no regeneration; and without being born again,
there is no entering into the kingdom of heaven;
it was evident through the remaining part of her time,
that she was much preserved under the influence and
guidance of the meek and quiet spirit of Jesus Christ,
and grew daily more and more in the favor and love of God.
She was much beloved of God`'s people, and of her relations, neighbors and acquaintance,
who were not of her persuasion; and walked so wisely and prudently,
that she sought not her own honor and interest, but the honor of the Lord,
and peace with him, to which she had a regard in all her undertakings.
Even such who sought for an occasion against Truth and the professors of it,
had nothing to say against her, for she was generally beloved and spoken well of,
and many were sorrowfully affected to part with her, both Friends and others;
and not without cause.
For she was a woman of an upright life, and exemplary conduct,
and gave no offense to Jew or Gentile, nor to the church of Christ:
charitable to the poor, a true sympathizer with such as were in affliction and distress,
whether in body or in mind, which was manifested in her frequent visits to such,
and by other means.
She was endued with great patience, and with a quiet and serene mind,
well qualified and fitted to her husband`'s circumstances,
whose lot it was to be often abroad in the service of the Truth,
an honorable and a faithful wife,
willing to give up all for Christ and the Gospel`'s sake,
counting nothing in this world too near or dear to part with for the glory of God,
and advancement of the ever blessed Truth, the peace and salvation of her own soul,
and the good of others.

One thing I insert as follows, that others in the like case may not barely imitate her,
but feelingly come up in her heavenly practice and experience, under the influence,
light and help of God`'s holy and blessed spirit:
When that worthy servant of Jesus Christ, John Bowstead,
returned from London Yearly Meeting to York, and so home with me,
not long before my wife was taken away; having some discourse with her,
he asked her about her husband being so much from home; and she gave him this answer,
that as she gave up her husband cheerfully and freely to serve the Lord,
and to be serviceable to the church of Christ,
she did not only sympathize and feel with him in his adverse and low state,
but partook with him in his enjoyments,
when the power of Truth prevailed over its enemies; although I am then far from him,
yet I partake of the spoil,
or the shedding abroad of the good things of God among his people,
as my heart goes along with the work of the Lord, and such as are engaged in it;
and in all my husband`'s afflictions I am afflicted with him:
and one of my main concerns is, that neither I, nor anything in this world,
may detain my husband from doing what the Lord calls for at his hand;
for if anything hurt him as to the Truth, what good can I expect of him?
This John much admired,
with the deep and weighty reasons she gave about the Christian discipline of the church,
and concerning the ministry.
She was a woman of few words, and expressed much in a little compass.

She was very clear in her understanding, had a penetrating and discerning eye,
a sense of the state of a meeting, as also of the several particular states in it.
She was an affectionate and tender mother to her children,
yet corrected them when occasion required, without passion,
or the least appearance of disorder of mind, and had them in great subjection;
at which I often admired, and thought, surely she is come,
by the workings of the Holy Spirit,
to a greater dominion over her own spirit than many who appeared to be her equals.
She was a true Christian, a loving and dutiful child to her parents, a good neighbor,
a faithful wife, tender-hearted toward her servants, and overcame them with love,
and was much beloved and feared by them;
and they were very unwilling to disoblige or offend her.

She behaved herself as became a sanctified vessel,
that was in a good degree fitted for the great Master`'s use,
and often appeared as one that had communion with Jesus Christ in spirit,
where his glory had shone in her soul,
not only because of the gravity of her countenance, but also the tenderness,
humility and sweetness of her spirit, weightiness of her conduct,
edification of her advice, and soundness of her judgment.
Her heart was often filled with the love of God,
and enabled to speak a word in season to states and conditions,
whether in her own family, amongst her neighbors, or in the church of Christ,
in testimony to matters relating to the worship of God, or to the discipline,
especially in the meetings of her own sex.
She had a great care upon her for the good education of
our youth in plainness of habit and language,
and that they might be preserved out of the corruptions of the world.
Her watchful and solid sitting in our meetings for worship was remarkable,
and her appearance in the ministry was with the wise,
and in the language of the Holy Spirit;
which was a clear demonstration that the work was the Lord`'s,
and by his Spirit and power;
which gave her a great place in the minds of faithful Friends and brethren.
But she is gone in the prime and flower of her age! which sets before us a memento,
to show us the uncertainty of our time here, and to prepare for one certain to come,
that death may not overtake us at unawares, before we are prepared for it.

During the time of her long weakness, she was preserved in great patience,
steadiness and resignation to the will of God, even to the end.
She enjoyed much heavenly comfort and consolation to her immortal soul,
in the presence of the Lord, so that when she was asked,
whether she thought she might recover or not; she mildly replied,
she was afraid to desire to live;
because I believe if it please the Lord to take me away now, it will be well with me,
for I find nothing lies as a burden upon my spirit.
At another time she said, "`As to that little testimony I have been concerned in,
this is my comfort and satisfaction,
that I can truly say I did not kindle any strange fire,
and therefore could not warm myself at the sparks thereof:
but what I did in that matter was in the constrainings of the love of God;
and when my cup was full, I a little emptied myself among the Lord`'s people,
yet very sensible of my own weakness and poverty,
and often thought myself unworthy of the least of the Lord`'s mercies.`"

She spoke many savory expressions that were not written then,
and therefore could not be remembered; having some hopes of her recovery,
it rather caused an omission; although she was heard to say not long before her sickness,
she thought her time would not be long in this world.
I never heard an unbecoming or unsavory word come from her,
let the provocation thereto be what it would, no, not in the time of her health;
and in her weakness,
she was much swallowed up in the luminous and internal
presence of her Lord and Savior Jesus Christ,
and often sang praises to his worthy name,
and appeared as one wholly redeemed from this world, whose heart was set upon,
and earnestly engaged in the pursuit after heaven and heavenly things.
Blessed be the Lord, she had witnessed a part in the first resurrection,
and over such the second death has no power;
no doubt she lived and believed in Jesus Christ, even to the end of her time,
and passed away without any appearance of struggling or sorrow,
I believe into a mansion of glory,
where her soul shall sing hallelujah to the Lord God and the Lamb forever,
with all those who have overcome the world, the beast and false prophet,
and everything the Lord`'s controversy is with,
and who have not loved their lives unto death,
but given up that life they had in any wrong thing whatsoever.

She departed this life the 18th of twelfth month, 1711, aged about thirty-three years.
Not long after the departure of my wife,
it came upon me to visit the southern parts of England, and some parts of Wales,
and I had good service and great satisfaction; I was also at London,
John Adam being my companion, who was an innocent, clean spirited man.

Again, I found it required of me to visit the south-west parts of England,
in the year 1717, and I traveled through the west part of Yorkshire, into Westmoreland,
Lancashire, Cheshire, to Bristol, and as far as Cornwall, and had many good meetings;
although I traveled alone, yet the Lord in whom I put my trust and depended upon,
helped me, and bore up my head through and over all,
renowned be his most honorable name now and forever.
