== Chapter III

[.chapter-subtitle--blurb]
Other Experiences Travelling in America

When I was in the Yearly Meeting upon Rhode Island,
there was a query concerning what Friends should do,
in case there should be a tax laid upon the inhabitants for building fortifications,
and to provide men and arms for the security of the island;
such a thing being then in agitation.
One of the chief Friends concerned in church affairs,
would have me give an account what we did in the like case in England;
for he said they looked upon themselves as the daughter,
and Friends in Old England as their mother,
and they were willing to act consistently with us as far as they could,
and would know whether we could pay that tax which
was for carrying on a vigorous war against France.
I was unwilling to meddle with it, as I said;
but the meeting waited a considerable time for my answer, as one told me,
and was not willing to go forward without it.
At last, when I could not well do otherwise, I signified to that large meeting,
that I had heard the matter debated both in superior and inferior meetings,
and privately, and the most general result was this;
Friends did not see an effectual door opened to avoid the thing,
that tax being mixed with the other taxes;
although many Friends are not so easy as they could desire:
neither have we any further sway in the government,
than only giving our voices for such as are concerned therein; therefore,
as things appear to me,
there is a great disparity between our circumstances and yours here;
for you have a great interest and share in the government,
and perhaps may put such a thing by in voting, considering the body of Friends,
and such as are friendly, whom you have an interest in;
therefore look not for help from the mother wherein she is not capable of helping herself,
and thereby neglect your own business; but mind your own way in the Truth,
and look not out.
Friends appeared well satisfied with these distinctions, and it gave me some ease,
in that I had not hurt any.

During my stay in one of the Jerseys, a great weight, more than usual,
seized upon my spirit as I sat in a meeting,
and under a sense of the same my cries ascended unto the Lord,
the fountain of all tender mercies,
that he would please to show me what was the cause of that
great power of darkness which did so oppress my spirit.
And it pleased the Lord to show me,
that a man there had been guilty of some gross wickedness;
and when it clearly appeared to be required of me to express it publicly,
it became a very great exercise to me,
and I had some reasonings before I gave up to make it public
to that large meeting of Friends and other people.
I laboured under it till towards the conclusion of the meeting,
but finding my peace concerned very nearly in the matter,
I stood up in the gallery and said,
Under a sense of some gross wickedness committed by some person not far from me,
has my spirit been borne down:
which wickedness will in a short time break forth to the dishonour of Truth,
and grief of Friends: A great man who sat in the gallery by me,
started up and seated himself upon the rail of the gallery, with his eyes fixed on me,
and in the Lord`'s dread, I fastened my eyes on him, and said,
We have a common maxim in Old England, touch a galled horse`'s back, and he will kick;
and I am of the opinion, he that kicks is not clear.
He got down as fast as he could out of my way,
for he not only prevented me from the view of the meeting by sitting there,
but his uncleanness stood much in the way of my service.

After the meeting was over,
several worthy Friends expressed to me the great concern they were under,
lest he should either by money, or subtlety, conceal the wickedness,
if such was committed; for I found there was a great jealousy in the minds of Friends,
that something was wrong with the man,
but I was till then altogether a stranger to their thoughts, and to the state of the man;
yet I advised that Friends should have a watchful eye over him and his family,
for I told Friends, my spirit was easy in what I had delivered,
and I believed the evil would not be concealed.
On my return, I heard his wickedness had been made manifest, which he did not deny.
-- Friends then asked me, what they should do in the case; I said,
let the judgment of Truth go forth against all manifest wickedness,
without respect of persons, that the ever blessed Truth, and such as live in it,
may be kept clear and in good esteem before all men as much as may be.

Something of the like exercise I met with in a meeting in Pennsylvania,
repeating several times what oppression my spirit was under,
because of some yet hidden wickedness, which in a short time would be brought to light,
to the blemish of the Truth, and great trouble to Friends.
That very evening, after the meeting,
a woman little thought by Friends to be guilty of such a crime,
went to a worthy Friend and told him,
she was the woman who had done that great wickedness I had complained of,
and had borne such a great load because of; and, as the honest Friend said,
she wept bitterly, even in the very anguish of her soul.
He came twelve miles the next day to Philadelphia to acquaint me with the matter,
and ask my advice, which I gave to this effect: If Friends find upon inquiry,
in the proper season, that the woman continues heartily sorry,
and truly penitent for what she has done, for godly sorrow works repentance,
and if from such a hearty and penitent sense, which is to be felt beyond words,
she gave forth a paper against her wicked doings,
not so much to ingratiate herself into favour, as for the clearing of Truth and Friends,
and for the ease and peace of her own mind, and took the blame and shame to herself,
then Friends may pass it by; if not.
Friends must set the judgment of Truth over manifest wickedness, as before mentioned.

I went to visit a meeting in that part called North Wales,
which had not been long planted, where there was a fine tender people;
but few understanding English, Rowland Ellis was my interpreter; we had a good meeting,
and truth was over all.
Some expressed their great satisfaction with our visit to that meeting,
which heretofore had not been considered as Friends,
but since that time they have been taken notice of,
and grown into good esteem with the body of Friends.

I found it much my work to be engaged in the discipline of the church,
which was very low in many places,
yet there was a willingness in Friends`' minds to be helped in that needful concern,
for surely it is a good fence, and a help to keep the righteous in,
and hurtful and wicked things and doings out,
if the same be rightly handled and extended as it ought to be,
in the love and wisdom of God.

When I was in Rhode Island, one Rogers came there to offer his gift, as he said,
in the Yearly Meeting among Friends; but they appeared in a great strait about him,
although he had written on behalf of Truth`'s principles, suffered imprisonment,
and the taking away his wife from him,
and was not so much as permitted to converse with his own son,
but under a guard or watch which was set over him, to hear what passed between them,
as he told me and some other Friends, which Friends said was true;
yet under the consideration of the matter, and clearness of the man`'s conduct,
Friends remained in a strait what to do.
And they desired that I would reason the case with him,
to try if I could persuade him to be easy, and not insist upon any such thing,
as a promise to receive his gift: for otherwise, he said,
he would go where it would be received.
I showed him, That it was a thing impracticable among us, and in itself unreasonable,
that we should be by any pre-engagement obliged to
receive that which he might call a gift,
before we heard it.
If he believed he had a gift, he might speak, and, as the apostle said, we might judge.
It was not impossible but he, who was a scholar, and a wise man, and had a strong memory,
might have gathered certain passages out of the Bible or other books,
with what other interpretations he might have stored up, and speak of,
and call it a gift, but which we could not receive as a real gift of the ministry,
which stands in the Spirit, and in the power,
and if it be such it will make way for itself, if not, we cannot receive it.
So he went away, and troubled Friends no more that I heard of.

I was at William Penn`'s country house, called Pennsbury, in Pennsylvania,
where I stayed two or three days, on one of which I was at a meeting and a marriage.
Much of the other part of the time I spent in seeing, to my satisfaction,
William Penn and many of the Indians, not the least of them,
in council concerning their former covenants,
now again revived upon William Penn`'s going away for England;
all which was done in much calmness of temper, and in an amicable way.
To pass by several particulars, I may mention the following:
They never first broke covenant with any people; for, as one of them said,
smiting his hand upon his head three times, they did not make them there in their heads,
but smiting his hand three times on his breast, said,
they made them (i. e. their covenants) there in their hearts.
When they had ended the most weighty parts for which they held their council,
William Penn gave them match coats and some other things;
which the speaker for the Indians advised to be put
into the hands of one of their cassacks or kings,
for he knew best how to order them.
I observed, and also heard the like from others, that they did not speak two at a time,
nor interfere in the least one with another that way in their councils.
Their eating and drinking was also in much stillness.

I desire that Christians, whether they may be such in reality or profession only,
may imitate these people in those things which are commendable,
which may be a means to prevent loss of time and expedite business; as much as may be,
endeavouring to prevent above one speaking at a time
in meetings of conference and of business.

When these matters were nearly gone through,
I put William Penn in mind to inquire of the interpreter,
if he could find some terms intelligible to them,
by which he might reach the understandings of the natives,
and inculcate a sense of the principles of Truth,
such as Christ`'s manifesting himself to the inward senses of the soul, by his light,
grace, or Holy Spirit, with the manner of its operations in the hearts of men,
and how it reproves for evil,
and ministers peace and comfort to the soul in obedience and well-doing; or,
as nearly as he could, come to the substance of this in their own language.
William Penn pressed the matter much upon the interpreter to do his best,
but he would not, either because, as he alleged, of a lack of terms,
or his unwillingness to meddle in religious matters, which, I know not;
but I rather think the latter was the main reason.

William Penn said, he understood they owned a superior power, and asked the interpreter,
what their notion was of God in their own way.
The interpreter showed, by making several circles on the ground with his staff,
till he reduced the last into a small circumference, and placed, as he said,
by way of representation, the great man, as they termed him, in the middle circle,
so that he could see over all the other circles, which included all the earth.
We queried what they owned as to eternity, or a future state; the interpreter said,
they believed when such died as were guilty of theft, swearing, lying, murder, etc.,
they went into a very cold country, where they had neither good fat venison,
nor match coats, which is what they use instead of clothes to cover themselves,
being of one piece in the form of a blanket or bed-covering.
But those who died clear of the aforesaid sins, go into a fine warm country,
where they had good fat venison and good match coats; things much valued by the natives.
I thought, as these poor creatures had not the knowledge of God by the Scriptures,
as we have who are called Christians,
that what knowledge they had of the Supreme Being must be by an inward sensation,
by contemplating the works of God in the creation,
or probably from some tradition handed down from father to son, by which it appears,
they acknowledged a future state of rewards and punishments;
the former of which they express by warmth, good clothing and food,
and the latter by nakedness, pining hunger, and piercing cold.

I have often thought and said, when I was among them,
that generally my spirit was very easy,
and I did not feel that power of darkness to oppress me,
as I had done in many places among the people called Christians.

After William Penn and they had expressed their satisfaction,
both for themselves and their people, in keeping all their former articles inviolate,
and agreed that if any differences happened among any of their people,
they should not be an occasion of fomenting or creating
any war between William Penn`'s people and the Indians,
but justice should be done in all such cases,
that all animosities might be prevented on all sides forever;
they went out of the house into an open place not far from it, to perform their worship,
which was done thus: First, they made a small fire,
and the men without the women sat down about it in a ring,
and whatsoever object they severally fixed their eyes on,
I did not see them move them in all that part of their worship,
while they sang a very melodious hymn,
which affected and tendered the hearts of many who were spectators.
When they had thus done, they began to beat upon the ground with little sticks,
or make some motion with something in their hands, and pause a little,
till one of the elder sort sets forth his hymn,
followed by the company for a few minutes, and then a pause;
and the like was done by another, and so by a third,
and followed by the company as at the first;
which seemed exceedingly to affect them and others.
Having done, they rose up and danced a little about the fire,
and parted with some shouting like triumph or rejoicing.

I leave Pennsbury, but intend, before I leave the Indians,
to say something more concerning that people,
which I met with near Caleb Pusey`'s house in Pennsylvania.
Walking in the wood, I caught sight of several wigwams or houses of the Indians,
and drew towards them, but could not converse with them;
but looking over them in the love of God, I found it to be my way, as I apprehended,
to look for an interpreter, and go to them again, which I did.
I signified to them that I was come from a far country,
with a message from the great man above, as they called God,
and my message was to endeavour to persuade them, that they should not be drunkards,
nor steal, nor kill one another, nor fight, nor commit adultery,
nor put away their wives, especially for small faults, which, as I understood,
is usual with them to do; for if they did those things,
the great and good man above would be angry with them, and would not prosper them,
but bring trouble on them; but if they were careful to refrain from these evils,
then would God love them and prosper them, and speak peace to them;
or very nearly these words.
When the interpreter expressed these things to them in their own language they wept,
and tears ran down their naked bodies, and they smote their hands upon their breasts,
and I perceived said something to the interpreter.
I asked what they said: he told me they said, all that I had delivered to them was good,
and except the great man had sent me, I could not have told them those things.
I desired the interpreter to ask them, how they knew what I had said to them was good:
they replied, and smote their hands on their breasts, the good man here,
meaning in their hearts, told them what I had said was all good.
They manifested much love to me in their way, and I believe the love of God is to them,
and to all people in the day of their visitation.

Having left them, I came to a Friend`'s house in the lower part of Pennsylvania,
who was in the office of a justice of peace,
and had been convinced not long before by Thomas Story.
When I came into the house the man`'s wife was very uneasy, and called me a deceiver,
and wrung her hands and said, Woe is me!
I am undone, my husband is deceived; and more deceivers are come!
O how she lamented!
I was somewhat struck with the passion the poor woman was in; however, I said little,
but sat down, and after some time it rose in my mind to ask her,
in what her husband was deceived: whether he was, since he came among us,
any worse husband to her; if he was, it was a bad sign; or,
was he a worse father to his children; or a worse neighbour;
or in any particular thing which she could name, changed from better to worse,
since he was convinced of the Truth?
If not, she had no great reason to complain.
But if he had turned drunkard, railer, fighter, or become a vicious man,
she would have had reason to complain.
She honestly owned, she had nothing to charge him with.
He sat by me and heard all our discourse, but said nothing.
I told her, she had made a lamentable outcry about her husband`'s being deceived,
but had not convinced me of any cause she had received for her sore complaint.

Being weary, having rode a great way that day,
I with my companion Richard Orm took leave of her husband, and went to our rest,
and saw him no more till the next day in the evening.
When he came, I asked him, for what reason he left us so long,
as he knew how uneasy his wife was about us, and that we had a great need of him.
He said he had been giving notice of the meeting twenty miles one way,
and two men had given notice as far, each man his way;
that was six score miles in and out.

Our landlady, against we rose in the morning, had got another woman, a justice`'s wife,
to help her to dispute with us, and overthrow us, as she hoped, but in vain,
for Truth proved too hard for them; although the other woman charged high in the morning,
and said we were no Christians.
I said it was easier to charge than to prove; how do you prove it?
Because; said they, you deny +++[+++water baptism,]
the precious ordinance of Jesus Christ.
I asked if they could prove it to be such: they said they did not question but they could.
I said they should do it from plain texts of Scripture, verbatim as it lies,
without any inferences, consequences, or comments upon the places they insisted upon;
and they agreed to it.
But I told them, in case they should fail and not prove, as they thought they could,
that ordinance to be so appointed by Christ,
I hoped then they would allow us to be Christians,
notwithstanding what they had charged to the contrary; and they said they would.

I then repeated all the preliminaries,
and asked them if they would agree to each particular: they said they would.
I desired Richard Orm to mind them, and imprint them in his memory,
for it was like enough we should have occasion to
call them in question before we had done;
which came to pass not long after we began.
They urged the twenty-eighth of Matthew in defence of water-baptism,
where Christ said to his disciples, "`Go therefore and teach all nations,
baptizing them in the name of the Father, and of the Son, and of the Holy Spirit;
teaching them to observe all things whatsoever I have commanded you:
and lo I am with you alway, even unto the end of the world.`"
Water not being mentioned, the disputants were at a stand, and said it must be implied.
I showed them, that by their agreement to the preliminaries,
there were to be no inferences, but plain Scripture.
I told them,
it was an unreasonable thing to undertake to unchristian
a great body of religious people by a few inferences,
which might be true, or not true.
When they had searched the New Testament a great while,
they could not find what they desired,
although they urged what Peter said in a certain case, "`Who can forbid water,
that these should not be baptized, who have received the Holy Spirit as well as we?`"
I showed them, that there was a great disparity between a servant`'s question,
and a master`'s command.
When they were weary with searching,
and could not find a positive ordination by Christ for water baptism, they gave it over,
and I asked them,
if they had not fallen short of the proof of what
they had so boldly charged upon us in the morning.
My landlady confessed they had fallen short of their expectation;
but the other was in the mind, as she said, that it might be proved:
I told her she would not prove it from any plain text of Scripture.

My passionate landlady became more meek and friendly,
and received the Truth in the love of it: we had a good meeting the next day,
and she said if I would stay that night, I should be as welcome as her own children;
but if not, she blessed the Lord for my company,
and the good she had already received by me,
and parted with me in much brokenness of heart;
and I heard she lived and died in good unity with Friends.
But, oh! how glad was her husband to see that great and sudden
change wrought in her! it was the Lord`'s doings;
to him be the praise now and forever, for he alone is worthy.

I had many comfortable meetings in my travels through these provinces, and good service.
We were at a Yearly Meeting at Tredhaven in Maryland, upon the eastern shore,
to which meeting for worship, came William Penn, Lord Baltimore and his lady,
with their retinue, but it was late when they came,
and the strength and glory of the heavenly power
of the Lord was going off from the meeting.
The lady was much disappointed, as I understood by William Penn, for she told him,
she did not want to hear him, and such as he, for he was a scholar and a wise man,
and she did not question but he could preach;
but she wanted to hear some of our tradesmen preach, such as farmers, shoemakers,
and such like rustics; for she thought they could not preach to any purpose.
William Penn told her, some of these were rather the best preachers we had among us;
or nearly these words.
I was a little in their company, and I thought the lady to be a notable wife,
and a courteously carriaged woman.
I was also in company with the governor of Virginia, at our friend Richard John`'s house,
upon the west cliffs in Maryland, for we both lodged there one night,
and I heard that he had been studious in a book against Friends, called the Snake,
and Friends desired he might have the answer, called the Switch,
but knew not how to be so free with him as to offer it to him;
I told Friends I would endeavour to make way for it.
Although he seemed to be a man of few words, yet at a suitable interval I said to him,
I had heard that he had seen a book called the Snake in the Grass; he confessed he had.
I desired he would accept of the answer,
and be as studious in it as he had been in the Snake; which he promised he would,
and took the book.

There happened a passage worthy of note either in
this or the preceding governor`'s time in Virginia,
as I was credibly informed, which was thus:
The governor needed a cooper to mend his wine, cider and ale casks,
and some told him there was a workman near, but he was a Quaker;
he said if he was a workman, he made no matter what he professed; so the Quaker,
such as he was, was sent for, and came with his hat under his arm:
the governor was somewhat at a stand to see the man come in after that manner,
and asked if he was the cooper he had sent for: he said, yes.
Well, said the governor, are not you a Quaker?
Yes, replied the man, I am so called, but I have not been faithful.
He then asked, how long have you been called a Quaker?
The poor man said, about twenty years.
Alas for you, poor man, said the governor, I am sorry for you!

By this we may clearly see, that such who walk up to what they profess,
are in most esteem among the more thinking and religious people;
and the unfaithful and libertine professors of the Truth are slighted,
and I believe will be more and more cast out as the unsavoury salt,
which is good for naught in religion, and is indeed trodden under the feet of men;
for a great part of the world have such an understanding as to
know what we profess,`" and what we should do and be in many things.
Let us therefore walk wisely before all, and not be an occasion of stumbling,
nor give offence either to Jew or Gentile, nor to the church of God,
that so we may indeed be "`as a city set upon a hill, which cannot be hid;`" no,
that may not desire to be hid,
but rather that the inhabitants of the earth may see our good works,
and have an occasion from there administered, to glorify the Father which is in heaven.

Having it on my mind to visit a meeting up the river called Perquimons,
on the west side of the river Choptank, and being on the east side,
Henry Hosier and some more Friends set forward with me in a small boat,
not in good condition, with only one small sail.
We set out, as we thought, in good time to reach our desired port,
but when we were upon the great river, which is ten miles over the shortest way,
according to my recollection, though the manner of our crossing it made it more,
the wind veered much against us, being then within about four points of our course.
It rained hard, and was very dark, so that we could scarcely see one another,
and the water broke so into the boat, that it was one man`'s work to heave it out,
and all our company were discouraged, and most of them very sea sick.
Henry Hosier, of whom I had the most hope for help,
said that he could not steer the boat any longer.
Notwithstanding the extreme darkness, the roughness of the waves,
boisterousness of the wind and hard rain, unwell as I was,
I was obliged to undertake the steering of the boat,
and not without some conflicts of mind, having no certainty, from any outward rule,
what way we went.
Having no fire, and the boat being open, we could not have any light to see our compass,
but my faith was in the Lord, that he would bring us to shore;
and I kept the boat as near the wind as she would sail,
and told my poor sick and helpless company, I believed that we should not perish,
although we might miss of our port.
The like imminent danger, I think, I was never in before upon any water;
but renowned over all be the great name of the Lord forever,
we put into the mouth of our desired river Perquimons,
as though we had seen it in the day, or steered by a compass,
neither of which we had the benefit of for several hours.

Here we went on shore and made a great fire under the river`'s cliff,
and about midnight the moon rose, it cleared up and froze, and was very cold.
My companions falling asleep, I turned them over,
and pulled them from the fire as it increased, and put them nearer as it failed,
but could not keep them awake.
I sought logs of wood, and carried them to and minded the fire,
which was work enough for the remaining part of the night; but morning being come,
we got into our cold icy boat, and sailed away towards the meeting.
When we were come among Friends, notice was given of a stranger being there,
and a heavenly and sweet meeting it was,
so that we thought we had a good reward for all our trouble;
blessed be the name of the Lord now and forever, for he is worthy;
although he may see good to try us, sometimes one way and sometimes another.
How should we know that we have any faith, if it be not tried?
How shall we know that we have any true love to God, if it never be proved?
The trial of the true believer`'s faith is more precious than gold.
The excellent sayings of Job came into my mind, "`Behold, I go forward,
but be is not there; and backward, but I cannot perceive him: On the left hand,
where he does work, but I cannot behold him: He hides himself on the right hand,
that I cannot see him.`"
And then in verse the tenth, he, like a man in the true faith, says,
"`The Lord knows the way that I take; and when he has tried me,
I shall come forth as gold:`" and the more vehement the fire is,
the more it destroys the dross, and the more pure and weighty the gold is.
Read and understand this, you that can.

I had a meeting, when in Virginia, at a Friend`'s house, whose name was Matthew Jordan,
and something that I said in the meeting, offended a young woman, a Presbyterian;
and not having, as she said, a suitable opportunity while I was there,
to discourse with me, being busy in her master`'s affairs,
for she was the Friend`'s housekeeper,
she desired liberty of her master to go to the next meeting,
that there she might ease her mind to me about the offence I had given her.
It was something about election, and they told me what it was, but not writing it down,
it went from me.
Accordingly she came to the meeting, where the Lord`'s mighty power broke in upon us,
to the tendering of many hearts, to Friends`' mutual satisfaction,
and it proved a good day to this young woman.
Her heart was as if it had melted within her; she shed many tears,
and I am satisfied went from the meeting in fear and in great joy; in fear,
how to walk so as not to offend Christ the Elect, whom before she could talk of,
but now she had met with, and he had opened her state to her: and joy,
that she had met with the Messiah, the Elect of the Father, his choice and beloved Son;
so that she could now say, Where is the wise?
Where is the scribe?
Where is the disputer of this world?
All her brisk talkative qualities were swallowed up in the feeling of the internal,
enlightening presence of Christ.

When she returned to her master`'s house, he asked her if she had got satisfaction:
meaning, had she had any discourse with me, and was satisfied.
She replied, she was satisfied.
Some time after I met with her in Philadelphia, plain and Truth-like,
but knew not who she was at the first.
The manner of the working of the Truth is to humble the creature,
and bring it into contrition, tenderness and fear, with true self-denial.

When we were crossing James river to attend a Yearly Meeting in Virginia,
there were five horses and nine people in the boat; among whom were Jane Pleasants,
a public Friend, and her man-servant, who rode before her upon a great horse,
and high in flesh.
About the midst of the river, which was two miles over, he rose upon his hind feet,
and threw himself upon the gunnel of the boat, half into the river;
the fall of the horse, and the motion of the other horses,
caused the boat to make such sallies that it took in water, and was very likely to sink.
Before he could have time to rise again, I took several young men by the shoulders,
and threw them upon his neck to keep him down, and told them, as fast as I could,
why I did so.
The ferryman, who was about to strip for swimming, said we should all be drowned;
but for his part he could swim; and was about to leap into the river, for,
he said the boat would either break or sink.
I told him it was soon enough for him to swim, when he saw the boat either break or sink,
and if he would not row, I would.
With much entreaty he took the oar again, and rowed us to the shore.
But in our imminent danger I looked over my tender friends, for so they appeared to me,
and thought what a pity it would be,
if all these were drowned! yet the thought of my own drowning never entered my mind,
until I was got over the river, which was a mercy to me,
and a great means to keep out confusion,
which commonly attends sudden surprises and frights,
or makes people fainthearted and almost senseless.

I had now occasion to observe, as well as in some imminent dangers I had seen before,
that it is an excellent thing to be, as much as we can, always ready,
and by frequently thinking upon death, it is not so surprising when it does come.
It is a point of true wisdom, to number our days so as to remember our latter end.
The lack of thus contemplating what preparation we are in to look death in the face,
and to appear before the great Judge of quick and dead, was the cause of the complaint,
"`Oh that my people were wise! that they understood this,
that they would consider their latter end!`"
The great remissness of such considerations among people,
bespeaks folly and great insensibility,
and that the heart is hardened through a habit of sinning.
O that I might prevail with the children of men to awake.
Arise, you that sleep in sin, and are at ease therein,
that you may come to hear inwardly the call of the Son of God,
that your souls may not only live here to serve God,
but also may live eternally in bliss with him,
is the desire of my soul for the whole bulk of mankind;
for my life has often appeared not to be dear to me,
in comparison of the saving of the souls of the children of men.

I have often thought of Moses, how far he went for saving Israel,
and how far Paul went for the saving of his kinsfolk after the flesh.
It was a demonstration that they had great faith and interest in the Lord,
and a very great love to his people.
Those whose eyes are truly opened, cannot but see it is the love of God,
and love to the souls of men, that constrains us thus to take our lives as in our hands,
and labour through many weary steps, in many perils by sea and by land,
and in the wilderness; sometimes in tumults and noises,
sometimes in watchings and fastings, and we have been sometimes made spectacles to men;
but the Lord has given us faith and patience to bear and overcome all,
as we have singly stood in his heavenly counsel,
and been truly devoted to his will in all things.

Something which I have before omitted now occurs to my memory:
when I was in that part of Virginia towards North Carolina, to visit Friends,
a very great mist arose, and we went wrong, until the guides were so far lost,
that they confessed, they knew not east from west,
nor on which hand we had left the road, although it was in the forepart of the day,
neither wind nor sun was to be felt or seen.
I told them I would try what I could do,
if they did but know what quarter we should go to:
they said we should go towards the south:
then I brought out my little compass which I had made before I left England,
and steered by it till we came into the road.
The inward sense I had persuaded me, that we were to the westward of the road,
so leaning a little to the eastward of the south point, we came right,
and the guides rejoiced,
and said I was fitter to be guide in a wilderness country than they.
My compass was not so big as a tailor`'s thimble, but had often been of use to me,
and others with me.

Now the time came on for my leaving all my near and dear friends in these parts,
and I embarked for the islands the 6th of the ninth month, 1702,
with my companion James Bates, on board of a sloop, Samuel Salter, master, for Barbados,
and we put into Bermudas in our way.
Soon after we landed, being on the 21st of the same month,
we were sent for by Governor Bennett to come before him, and being near his door,
a man came and clapped me on the shoulder, as we were walking on our way,
and said roughly to us.
You must go before the governor, and seemed to hasten us.
I replied meekly, I am willing to go as fast as I can, but I have been very sea sick,
and can go but weakly.
The man fell from his roughness, bid us take time, and carried himself very civilly,
and put us by a man who was keeping sentry at the
governor`'s door with his musket on his arm.
When we were come into a large room the man left us, and we wailed a while.
I began to reason in myself.
What if the governor should be a rigid man, and severe to us,
and either confine or punish us?
But I said in my heart.
Lord, you that know all things, know that I have not only offered up my liberty,
but life also, for your name and Gospel`'s sake;
and immediately all fear and reasonings about human power were taken away from me.

Being unwell, and weary with walking from the ship, I sat down to rest myself unbidden,
when there came a friendly well-carriaged young woman, who I supposed to be a servant,
and spoke kindly to us.
I desired her to do as much for us as to give us something to drink,
for we were very thirsty, and had been much out of health,
and were not well recovered since we came from the sea, having had rough weather.
She brought us wine and water, and taking most of a glass of water,
and a very little wine poured into it, I drank and was very well refreshed.
By this time the governor called us into an upper room,
and as I came near to the top of the stairs, going but faintly, for reasons before given,
the governor put forth his hand and reached to take hold of mine,
and like a tender father drew me up, and led me along towards a great window,
and stood and looked on me and said, he believed he knew what I was, and my business too.
I replied it might be so, and asked if he was the governor of that place: he said he was,
and bowed his head.
I then spoke to him in the love of God and said, Your countenance bespeaks moderation,
and the apostle said, "`Let your moderation appear to all men,
for the Lord is at hand:`" and it was with me to say to him,
The Lord of heaven and earth bless you and all yours.
He bade us sit down, and gave us each a glass of wine, and inquired from where we came.
I told him my home was in Old England, but it was long since I was there;
my companion`'s was in Virginia.
He wanting to know the affairs in Europe,
I told him there was a merchant belonging to the same ship that we did,
was lately come from Europe, and I thought was a man of talents and memory,
and well versed in the affairs of those parts of the world,
and when we came into this place he was with us.
The governor sent for him, and when he came,
he answered his expectation in resolving all or most of his questions,
for the knowledge of the news appeared to me to be the young man`'s talent.
Having dismissed him, he said he must now have some discourse with us:
then rose up all the great men who were with the governor,
to make way that I might come near him.
I said if it was the governor`'s mind, I had rather sit where I was,
for I sat in the air, and that suited well with my present weakness.
So he bade them all sit down, and they did so.

Now, said he, I want to know the reasons why you, as a people,
do not assist the king and country with men and arms,
for their and your own defence and safety, against all that may attempt your hurt.
I replied, the most convincing reasons I have to offer to the governor are,
we have neither precept nor example from Christ, or his apostles,
to use the sword to hurt one another with.
No, said he, what then means that saying of our Saviour,
when he bade him that had no sword, sell his cloak or coat and buy one?
I replied, one of his disciples answered and said, Lord, here are two; Christ said,
It is enough.
Now how two swords can be enough to answer for a general precept,
I leave the governor and all these men to judge.
So after a little pause he said,
In case you were assaulted by robbers that would break your house,
and take what they could get from you, or upon the highway,
and would take your purse or horse, what would you do in that case?
I replied, I could not directly answer what I should do in such a case,
because through the Lord`'s mercy I was never yet so assaulted;
but it appears most likely,
that I should endeavour to keep my house from being broken up,
and yet seek to be tender of men`'s lives; and as to the other assault,
inasmuch as it is well known I do not provide any outward weapon for my defence,
neither sword, pistol, nor any such like weapon,
therefore I must rely upon the Lord for protection and help,
who is able to rescue me out of the hands of all such ungodly men: or if he does not,
I must endeavour to bear what the Lord permits such to do to me.
The governor said, You say well:
for inasmuch as you have not provided anything for your defence,
you have nothing to fly to but the Lord; you say very well; and said,
he hoped what he had offered had not given any offence.
I replied, it was so far from that, we were glad he was so free with us;
yet if he pleased to dismiss us, we should be willing to be going, for night came on.
He said, there were some of our friends would be glad to see us.
I replied, I understood there were some further on the island that did own us,
but how much they were of us I could not tell, for I had not seen any of them.
He asked, whether we had a mind to go by water or by land, for he had a boat,
and a couple of hands should carry us where we would; or if we had a desire to ride,
he had two horses, we might take them and keep them as long as we stayed upon the island.
I endeavoured to persuade him to let us go without troubling himself any further,
for I was sensible of his good will and love to us, and having his countenance,
was more than we expected, and as much as we desired.
He still urging to know, after what manner we would choose to go: I told him,
I was very sensible of his generosity to us who were strangers,
and if he would be easy and let us pass,
we had sufficient money as to defray our necessary charges, either by water or land,
as would answer best with our conveniency.

He pressed upon us to accept of his offer,
for he said he did not do it in compliment to us.
Seeing no way but to accept of his generous offer,
I said riding at present would be much more acceptable to me,
considering how I had been lately fatigued at sea, of which I was not yet well.
He immediately gave orders for the horses to be brought to the door, which being done,
and we having notice thereof, I rose up and made an offer to go,
and the governor likewise rose up and came and took me by the hand,
and we went down into the great room where we first
entered in the Lord`'s dread and holy fear.
I had resigned my life and all to the Lord who gave it, and my life at that time,
as at many others, was not dear to me for Christ`'s sake; and being thus resigned,
I felt the love of God, and a measure of that life was manifest,
in which I had dominion over men, bonds, and over death, and the powers of darkness;
blessed be the Lord forever.

Coming to take horse, I looked out at the door, and saw two horses.
The one next the door, which I supposed I was to ride on,
had a saddle set about with three rows of shining silver lace,
I thought about two inches broad on each; the governor holding me by the hand,
and looking in my face, said,
I am apt to think you are not used to ride upon such a saddle as this.
I told him, if he could let me have one more like myself, plain, without much trouble,
I should like it better, but if not, I could ride on it, I thought,
without much straitness, in case of necessity.
He answered, he could not, for horses and saddles were scarce on that island;
one was that which he rode on, and the other was for his man;
but he said he would tell me how to prevent all this.
If, said he, you get over the inlet of water, though he questioned it,
because the wind blew very strong in the mouth or inlet of the river,
and should come to Richard Stafford`'s, an old judge of life and death,
we might ask there for the cover of his saddle,
which ties on with little straps at each corner and hides all this,
and then it will be like yourself.
But if the ferryman says he cannot carry the horses over, what man soever you meet,
white or black, if capable, tell him he must bring me my horses,
he dares do no other but bring them; and be sure you take no further thought for them:
and if we met with anything that troubled us, let him know and he would help it,
if it lay in his power.

So with his blessing on us, we took leave of him, and came to the water-side,
but could not get the horses over, therefore we sent them back again,
and intended to stay at the ferry house all night,
but the boat was about going over as we alighted; and notice being got to the judge,
that there were two strangers on the other side of the water,
he sent a boat and a couple of men for us, who said, we must go,
for the judge said he could not sleep until we came.
So we went, after asking,
if they at the ferry-house had been at any cost or
trouble on our account in providing supper,
for as yet we had not eaten anything since we landed; the people said no,
they had not done anything which we should pay for.
It grew dark and very stormy, and the sea broke over the boat,
so that some of us were forced to hold our coat laps one to touch another on the weather-side,
to keep out the breakers, that they might not fill the boat.
We came safe over to the judge`'s house,
and no sooner got into the passage but his friendly wife met us,
and asked us if we were the strangers her husband had sent for?
I said, we are strangers.
She bid us follow her to the judge, and we did so.
When we came to him he rose up, and took the candle in his hand and said,
Are you the strangers I sent for?
I said, who you may expect I know not, but we are strangers.
When he had looked well in my face, he set down the candle, and said,
What a mercy is this, that the Lord should send men from I know not where,
in his love to visit me! and took me in his arms and kissed me; and I said to him,
The Lord of heaven and earth bless you; and we shed many tears and wept together.

As I entered the house, I felt the love of God, and his glory, I thought,
shone in and filled every room as I passed through them, and I said,
peace be to this place, and I felt it was so.
He inquired of our travels, and from where we came, of which we gave him a brief account;
he also asked, if I knew anything of the family of Staffords, at Lahorn,
near Haverford-west, in South Wales.
I told him all I knew about them, both of the dead and of the living;
with which he was pleased, and said, he had not heard of them for many years,
and that family were his near kindred.

I found his usual bed time drew near,
and I made an offer to go away lest I should incommode him,
yet he appeared unwilling to part with us; but considering his own ailments,
and our early rising in the morning, he at length consented.
Before we parted, his wife asked leave of him to go with us on the morrow to the meeting,
to which he readily assented, if he was not worse of his distemper,
and then ordered how we should ride, and which negro should go,
not only to help his wife but us also, and take our horses when there was occasion,
and do anything he could for us; and indeed so he did,
and appeared to me to run on foot without much trouble, being a lively young man.

I omitted before, that the judge asked, if we had seen the governor,
and if he was kind to us.
I told him he was very friendly to us,
and said if we met with any trouble that he could help us in,
only let him know and he would right us.
The judge said it was very well, and he was glad of it.
I perceived the judge was rather a moderator of the governor,
he being an ancient wise man, and had lived long as a judge upon the island,
and understood, it is likely, more fully the state of things here than the governor,
he being but a young man, although he appeared to be a wise man, and,
as William Penn said, came of an ancient and honourable family in England,
which he knew very well, whose name was Bennett.
Afterwards I told William Penn how it had fared with us on that island;
and especially the kindness of the two chief men in power there, and William Penn wept,
and said, he had not heard any account of this nature,
that he had been so much affected with, as he remembered, these many years.

We left the judge until the morning, and got some refreshment, it being late,
and I had been faint for several hours for lack of eating,
but the Lord`'s heavenly power bore me up over all,
so that at times I felt no lack of anything:
Oh! renowned over all be the name of the mighty God, now and forever.
We went to bed, and when morning came, I and my companion were stirring early,
having eight miles to the meeting, and it being in the latter end of the ninth month,
we were willing to be in time, that we might give some notice to the people.
I was walking in our lodging room early,
and the judge`'s wife came to the door and asked, if she might speak with us;
I said she might: then she came in and said she had a message from her husband to us.
I queried, what it was;
she said he desired we would come and pray for him before we went away.
I desired she would favour us so much as to lay before
her husband something which I had to say,
and she promised she would: Well then, tell the judge,
that if he will allow us to come into his room, and sit down and wait upon the Lord,
as our manner is in such a case as this,
if it please the Lord to move us by his Holy Spirit to pray, we may; but if not,
let not the judge take it amiss,
for we are willing to be at the Lord`'s disposing in all things.
She went, and I believe, as she said, laid the matter before him,
as I had delivered it to her; for she was a woman of a good understanding,
and came back again to us in a very little time.
I asked what the judge said; she replied, he said, let the men take their own way,
and whether they pray for me or not, I believe they are men of God.
So after some little respite, being brought to the judge`'s bedside,
we sat down and waited upon the Lord, who was pleased in his love,
and by his mighty power to break in upon us,
and also opened my mouth in his gift of grace and of supplication,
in which gift ardent and fervent cries went up to the Lord of heaven and earth,
that he would send health and salvation to the judge, and also to all his family,
and to all people far and near, that all everywhere might repent,
and come to the knowledge of the Truth and be saved.
The judge wept aloud, and a mighty visitation it was to his family,
and especially to himself and his tender wife.
We left the judge in a fine frame of spirit, and no doubt near the kingdom,
having his blessing and earnest request,
that when we could reach his house we would not fail to come to it,
for we were very welcome; and I found and felt it so, and it was mostly our lodgings.
His wife and foot page went with us to all the meetings, except one,
while we were on the island, which was about two weeks,
in which time we had many good opportunities among a soberly behaved people,
among whom we met with no opposition, but had large quiet meetings.

When we were clear, as we thought, of the island,
we went to take our solid leave of the governor,
acknowledging his civility and generosity to us.
I told him and the judge,
that they would not lose their reward for what they had done to us,
and to such who should take their lives as in their hands,
and come in the love of God to visit those remote parts of the world,
which we dared not have undertaken if we had not believed it required of us by the Almighty,
and our peace concerned in it, as also the glory of God,
and the good of the children of men;
these are the motives to those our great undertakings, or words to that purpose.
So we parted in much love, with these great men, especially the judge,
with tears on his face, as also his tender and friendly wife,
who had been very serviceable to us in ordering meetings, and making way for us.
There was none like her in all the island, that we met with,
being given up to that service,
for encouraging Truth and Friends in what she was capable of.

Being invited to a Friend`'s house to dine one day, when we were sat down at the table,
the woman of the house desired that one of us would say grace;
from which I took occasion to show her and several more in the company,
who appeared not much more grown in the Truth than she, that since we had been a people,
we had both believed, and accordingly practised,
that true prayer was not performed without the help of the Holy Spirit of God,
and no man could pray aright and acceptably without it;
nor was it in man`'s power to have it when he pleased.
Therefore it is man`'s place to wait upon the Lord
for the pouring forth of this gift upon him,
and also to know whether it be required of him to pray so as to be heard by man,
or only to pray secretly, so as to be heard of God, as did Hannah,
and as many more have done; which, as they do aright, no doubt,
but as Christ said to his disciples, their Father will hear them in secret,
and reward them openly; or to this effect; with which they all appeared satisfied.

We then went on board our vessel, and set sail with a fair wind for Barbados;
but soon after we got out to the mouth of that inlet where we arrived first,
the wind came full against us, and we put in there again; and the master,
although not called one of us, said, in a friendly manner, What is the matter now?
This is because of you, Mr. Richardson, as he was pleased to call me,
although I often showed my dislike to it, you have something to do yet upon the island.
I said I know not of anything; but he seemed positive, and said,
if the wind came fair at midnight he would call, if I was willing, if not,
he would stay as long as I pleased.
I said I knew not of anything to hinder, but he might call as soon as the wind came fair.
So we parted, only telling him we intended to go for the judge`'s house.
It was late in the evening when we got there, and the judge was gone to bed;
but his wife was up, who lifted up her hands with more than ordinary surprise,
and much joy, and said she was always glad to see me, but never more than now: I said,
why so?
She then began to tell, that since I went away, there had been a man with the judge,
who had incensed him against me all that he could, and said he knew me in England,
and that I was broken, and came into those parts to preach for a living.
I asked what her husband said to all that?
She said his answer to the man was, that he believed I was no such person,
but an honest man; yet the accuser seemed very positive.
I said it would be well if this man could be brought with me to the judge`'s face,
that he might be convinced, not only of the man`'s ignorance of us as a people,
but of me in particular, and his envy against me be made known.
I opened to her the nature of such journeys and services, how we proceeded,
and how the meetings were constituted in which we did so proceed,
and from which we had certificates, namely: from Monthly and Quarterly Meetings,
or meetings of ministers to which we belonged,
and from Friends in the several provinces and islands where we travelled,
if we desired them, many of which I could show the judge, if time would admit.
She said, lest we should be called away in haste,
she craved to see some of those certificates.
I showed her them, beginning at the first, wherein Friends of Kelk, now Bridlington,
Monthly Meeting in Yorkshire, to Friends in America,
declared not only their full unity with my present journey,
but also with my service for the Truth, and conduct in the same,
where I had lived and travelled;
and that I had settled my outward affairs to Friends`' satisfaction,
under many hands variously written.

When this great and wise woman saw this, she said it was enough:
but I showed her other certificates from various places,
wherein Friends had signified sufficiently their unity and satisfaction with me.
I likewise informed her, that in case any man, not approved by us as a minister,
attempted to impose his preaching upon any who were strangers to him, such as knew him,
took care to acquaint the churches therewith, if his intentions could be known,
that no impostor might do any hurt.
All which she admired, and said she had never heard so much before,
neither did she think there had been such excellent order among any people.

Having thus acquainted her with our order and discipline,
and afterwards informed her of the cause of our unexpected return,
I renewed my proposal of having my accuser before the judge.
She told me, she had good place with her husband, and would endeavour to obtain it;
and accordingly, after talking with him, she let me know,
that the judge expressed his readiness to do me any service which lay in his power,
and was of opinion my accuser dared not face either him or me in that affair.
If the wind continued against us, he would try to find him out, and bring him,
which might be of service; but if the wind favoured, she thought I might be easy to go;
as indeed I was, and the more so, considering that our captain, Salter,
who lived near the judge on the same island,
had showed a great deal of patience and good disposition to us, for about two weeks,
yet would gladly be gone.
About midnight we were called to go on board the ship, for the wind was fair,
if we were ready.
I replied, we come quickly: and so we did, and took leave of all we saw of the family,
and remembered our dear love, with grateful acknowledgments, to the judge,
for all his civility and kindnesses to us, with reasons why we could not see him,
for he had been afflicted some time with the gout, and was now fallen into some rest,
and we going away very early, were not at our own disposal.

I admired the Lord`'s good providence in all this,
and there was something from the same watchful Providence,
to order that to be put into my certificate which did so fully
remove the slur this enemy would have fastened upon me, i. e.
That I had broken in England, and could not pay my debts,
and therefore had come into these remote parts of the world, where I was unknown,
to preach for a livelihood.
But it fully appeared, that I was known, and well beloved too,
and had effects to discharge any just demand upon me,
blessed be the worthy name of the Lord now and forever.
