== Chapter V

[.chapter-subtitle--blurb]
An Account of His Visit to Friends in Ireland.

In the year 1722, it was renewed upon me to go into Ireland;
the thoughts of it had been long upon my mind,
but the time seemed now to be fully come to pay the visit; and Joseph Bunting,
of Cumberland, being my companion, we went from Kendal Yearly Meeting,
which was a large and good meeting, passed along to Whitehaven,
and took shipping for Dublin.
We stayed their Half-year`'s Meeting, which was large,
and in which the living power and presence of the Lord was felt among us;
exalted over all be the mighty name of the Lord, for those and all his mercies.

I had many good meetings, and also some hard ones,
as is the lot of such who are called to this vocation, and the best way I have found,
when I meet with such, is first to regard our call,
then to mind the daily steps we take in that vocation into which we are called,
and take special care to have along with us the company
and counsel of Him that has so called us.
This is the way fully and truly to discharge ourselves
of that trust the Lord has reposed in us,
to the comfort and edification of the churches of Christ,
and to the peace and consolation of our own souls.

It is now with me to write the following remarks respecting Ireland,
which will not be remote to the state of Friends in many other places.
Where there is a sound living ministry preserved, and good discipline exercised,
which mostly go together.
Truth and Friends are kept in good esteem, and also thriving.
But where these fail, especially the discipline, undue liberty,
and the fashions of the world, with many corrupting things,
creep in among the professors of Truth, to the reproach thereof,
and the scandal of those who are so prevailed upon;
and the hearty sorrow of such as feel the hurt of these things.
Oh! what a hindrance this is to the progress of the ever blessed Truth in the earth;
and it has impressed my mind,
that the main work of our day is to search into the churches,
and endeavour to bring them to such a condition, that it may once more be said,
Follow Christ as you have us for examples; not only here and there one,
but the believers in general.
It will be so, when we as a people all speak the same thing, as well in our practice,
so often recommended, as in faith and doctrine;
for I have ever understood example to be more prevalent than precept.
But if any among Friends grow so insensible, as to prefer foolish fashions,
which to me appear to be shameful and indecent,
it is an evident demonstration that they are departed from the
principles and practices of our worthy elders in the Truth;
which I fear is the case of too many, both in that nation and in England.

Let not any say that I smite in the dark, and do not tell what I mean;
some particulars I intend to mention for the ease of my mind.
I have seen several changes of fashions in forty years time;
our first Friends and promoters of Truth came out in the Lord`'s work and heavenly power,
plain, and generally continued so for their time;
but alas! how soon there appeared an alteration, in some men especially,
when the weight of suffering was over.
It then began to appear, and from time to time has continued to increase ever since,
among some professing Truth with us, not only in extravagant wigs,
with much powder in them, but also in cross-pockets, needless capes,
and various cuts and shapes in their clothing,
in conformity to the prevailing fashions of the times,
as well as in setting up their hats;
all which appear to me more likely to lead those who follow them, into Egypt,
or the world again, than into the heavenly country, or Canaan,
which we profess to be pressing after, and hope to obtain in the end.

I well remember in my younger years, especially in great towns and cities,
I have met with females who professed Truth with us,
who had but very little covering on their heads,
and others who had more set up at a considerable distance above their foreheads,
and both these sorts perhaps bare-necked.
When I have met with such, I have said,
What a fair or beautiful daughter of Zion would you be,
if you would put on Truth and Christ`'s righteousness,
and put away all these foolish fashions?
When I have asked some, what they could say for these dresses, and being so naked,
both neck and shoulders, I received this answer, or something like it,
that it was good for their health, to keep their temples cool, and to learn to be hardy,
by exposing themselves thus to the air in their youth.
But if that was the true reason, I added this caution to them; to consider duly,
if religion did not, yet the modesty of their sex should reclaim them from it.
Sometimes, with the dislike I showed to these things, I advised them,
that they should cover their naked skin,
and no more expose themselves to the vain speculation of the worst,
and great trouble of their best friends; and worse than all,
to the great hurt of themselves,
and in a manner destroying all reasonable claim to Christ.
For how can our love to, and faith in him be true and sound,
when our practice is so reverse to the practice and example of Christ and his apostles,
which they thus inculcated?
"`Be not conformed to this world, but be transformed by the renewing of your mind,
that you may prove what is that good and acceptable, and perfect will of God.`"
"`Whose adorning, let it not be that outward adorning of plaiting the hair,
and of wearing of gold, or of putting on of apparel;
but let it be the hidden man of the heart, in that which is not corruptible,
even the ornament of a meek and quiet spirit,
which is in the sight of God of great price: for after this manner in the old time,
the holy women also who trusted in God adorned themselves,
being in subjection unto their own husbands.`"
Alas!
Woe is me, for the hurt of the daughter of Zion,
when I consider with regret from where such are fallen,
if they were ever restored out of the fall.

If we as a people should follow such examples as I have touched upon,
certainly we shall become a hissing and a by-word to all nations round about,
who have heard of us,
and what great things the Lord of hosts has done for us since we became a people,
as may be seen by the examples and writings of our faithful Friends and brethren,
promulgators of truth and righteousness, in their unwearied labours,
faith and sufferings for the cause and testimony of Jesus Christ;
and what also was not less remarkable by their exemplary lives of plainness, humility,
sincerity and self-denial, with works of charity.

Now you that read this, beware that you do not let in any wrong mind,
and in that begin to judge me instead of judging yourself; for as far as I know,
I have but done my duty: see first, that you do yours before you begins to judge me.
Bear this caution from your friend, you that God have endued with his Spirit,
and wait till this Holy Spirit of Truth is upon you as a spirit of judgment.
As you abide under these qualifications, you are fit to sit in judgment,
and judge wrong things in yourself first, next in your family,
and then in the church of Christ; and be unwearied in your labours to preserve,
as well as to restore, from all wrong ways and things,
what you are capable of in the church of Christ; for if corruption and slackness come in,
and prevail over the leader,
as well as over those whom God has raised you up to be a help unto,
then will the Lord deal with both you and them some other way.
I am satisfied the Lord will turn his hand upon his people in these days,
as he did upon Israel formerly, saying by his prophet, he would purge away her dross,
and take away all her tin; not only all gross evils,
but also that which in appearance may be like Truth, but is not Truth:
this was and will be the way to restore judges as at the first,
and counsellors as at the beginning.
Oh! "`then shall the Gentiles see your righteousness,
and all kings your glory,`" says the prophet.

Although there is great occasion for an amendment in many,
yet there is a bright and heavenly-minded remnant in England,
Ireland and many other parts of the world,
against whom I find not anything to press upon my mind to complain of.
A word of encouragement springs in the life, in the love and good will of God,
to press and persuade you to a steady perseverance in the true faith,
and in an exemplary and pious life, and I never saw more need of this than now,
according to my view of the state of things; that when the Lord, the righteous Judge,
shall bring every work into judgment with every secret thing,
these may be found clear of the blood of all men, seeing that they have warned them,
when they have seen any danger, or an enemy approach nigh to them.

Here is work for those whom God has set as watchmen over his people,
to see that they do not go in by-ways, who profess Truth,
and leave the way of Truth unoccupied.
Here is work for the true judges, who have the spirit of judgment upon them;
notwithstanding some here and there,
who may be found in the faithful discharge of that trust the Lord has reposed in them,
may meet with opposition from the unfaithful,
who are not willing to be bounded by the Truth,
no not so much as to an outward conformity to the plainness and decency,
so frequently recommended by writings, public testimonies,
and also in our meetings for discipline.
It is a considerable branch of our meetings for discipline to inspect into,
and take care that Friends walk orderly as becomes our holy profession;
and where wrong ways are gone into, and liberty taken by any who profess with us,
that such may be dealt with, and the evil, as also the bad consequence thereof,
laid before them, and they be laboured with, and not left.
Although it may be but a small appearance of a leprosy, which is apt to spread,
unless proper applications, in due time too, be made in the wisdom and love of God;
yet if any prefer their own wills, and so far love that life they have in those things,
that are not only evil in themselves, but also of evil consequence by their bad example,
more than they love Truth and the unity of the brethren,
such had better for Truth`'s sake and for the reputation of the testimony thereof,
be dealt with, for the relief of the minds of the faithful,
who suffer under the sense they frequently have of a cloud of darkness and oppression,
wrong ways and wrong things.

It may not be amiss to give a hint here,
at what door many have gone out into various evils; first,
by being brought by custom to love strong drink, and keeping loose company.
Such have been a means to corrupt,
and in time to draw away the mind from that simplicity
and purity the Lord`'s people ought to live in,
until a cloud has come over the understanding,
and the sense of the virtue and heavenly savour of the precious Truth is lost.
Then the old inhabitants of the land, figuratively speaking, crowd in again, as pride,
passion, lust, envy, loose conduct, open drunkenness;
no some worse spirits than ever had possessed them before,
have now entered their minds with the former,
that were once measurably overcome and cast out; it is therefore certain,
that the end of these will be miserable,
except the Lord grants them a place of repentance while here.

Now my tender and well beloved friends, watch against,
and strive to keep out the enemy that he enter not;
for what way soever he enters and gets footing, he defiles God`'s temple.
And before you witness the Lord to destroy him and cast him out again,
you must have many a sore combat, and some warfare, perhaps more than you are aware of,
before you gain all the ground you have lost,
by giving way to the adversary of your soul.
Therefore keep upon your watch tower, and watch unto the end.
Watch and pray continually, that you enter not into temptation,
said our great Lord to his followers.
I have found by experience, that it is harder to gain what we have lost,
than to keep it while we had it;
and to improve our talents is not only the way to have them continued,
but also to have them more abundantly added unto;
but such as do not improve what is given unto them,
even that with which they have been entrusted shall be taken from them.
Oh how desolate and miserable such will be in the day of account, when Christ,
like a great shepherd,
divides the sheep from the goats,--between the slothful and the
faithful servants,--between the wise and the foolish virgins,
and between all those who adhered to, obeyed,
and followed him according to the measure of light and knowledge received,
and those who have rejected and disobeyed the strivings
and convictions of God`'s holy light and blessed spirit,
placed in the hearts of the children of men to enlighten, instruct, reprove,
comfort and guide, according to the slate of every individual,
as it is conformable or disobedient to inward convictions.
So is this holy gift a witness for, or against, to accuse, or excuse in your conscience,
according as your good or evil doings prevail in your heart.
This is a digression from the historical part of my travels,
and as I mentioned my going into Ireland,
I shall now say something more particularly thereof.

We journeyed from Dublin towards Cork, and had several meetings in our way,
as at Ballicane, Cooladine, Wexford, Lambstown, Waterford, Clonmel, Cashel, Youghall,
Cork, and stayed their province meetmg for Munster, which was a good and large meeting.
I was much disordered here, by a fever and ague which held me several days,
and was not without some reasonings for a time, at being out of my native country,
but the Lord who is mighty in power, helped me and raised me again,
and gave me ability to discharge myself of that service I was called to;
honoured forever be the great name of the Lord for this and all his mercies.

Next we came to Charleville, Limerick, Ross, and from there to John Ashton`'s, Birr,
James Hutchinson`'s, Montrath, Mountmelick, Henry Ridgway`'s,
and from Balinakil to Montrath again, and were at their six-weeks`' meeting,
which was a heavenly and good meeting, there being a living remnant here:
then we came to Kilconner, Carlow, Ballitore, John Stephenson`'s, Timahoe, Edenderry,
and went to see my good friend Thomas Wilson, who was sorely troubled with the gravel.
I was much afflicted, and truly sympathized with him in my spirit, and John Barcroft,
that true man, and I, did what we could for our afflicted brother,
and so left him and his family in the love of God, and went to Lismoiny,
and many other meetings to the province meeting, which was held at Ballinderry,
and so to Dublin, the 29th of the fifth month, 1722, and stayed there some meetings.
There is a living remnant in that city, but it is a rich place;
the mighty God of heaven and earth keep his people low,
and truly humble there and everywhere else,
is the earnest desire of my soul to the Lord; for I know there is a considerable remnant,
whose labour and daily travail is to have the church kept
clean from all defilement both of flesh and spirit,
so that she may be presented unto God the Father without spot or wrinkle,
or any such thing,
in the day when she must appear before the great Judge of all the earth,
who will do right unto every one, according as their works are found to be good or evil.

Being clear of Dublin and the whole nation,
I took shipping for Whitehaven--had a short passage but a very rough one,
and had some meetings in my way home, to which I got on the 21st of the sixth month,
1722,
and found my children recovered from the fever and
ague in which I left them when I took my journey,
which distemper had so far prevailed over them,
that they were sometimes scarcely sensible.
It had been upon them for a considerable time,
and proved a trial for me to leave them in that very weak state;
but one day as I sought the Lord in the fervency of my heart,
to know whether I should leave these my two poor weak children or not,
as also my house-keeper much in the same case, who were all my constant family,
it sprang in my heart livingly, as though it had been spoken with a man`'s voice,
Leave them, and I will take care of them: I said, "`You oh Lord have never failed me,
I will leave them to You; do what seems good in your eye with them.`"
I looked then no more behind me, neither at them nor anything else I had left,
but became as if I had not anything in the world.
For thus it behooves all the servants of Christ to do,
even the married as if they were not married; and those that buy anything,
as if they did not possess it.
This liberty which many are strangers unto, is wrought by the finger of God;
it is the work of God`'s heavenly power to loosen man thus from the things of this world:
at the same time we are most bound unto Christ,
yet enjoy a comfortable and heavenly freedom in our spirits in Christ,
by our faith and obedience to him, in and through all trials, provings and adversities.
Dear friends, the greater the cross,
the greater is the crown and reward which all those possess,
who do all things with a single mind and an upright heart to the Lord at all times.

Thus the children of the Bridegroom are or ought to be espoused or married to Christ,
and truly devoted to him, that so they may stand, as much as may be,
disentangled from all mutable things,
and cleave to and follow him when and wheresoever he calls and leads,
and be in subjection to him, as a virtuous wife is not only bound,
but willingly subject to her virtuous husband.
Thus we may know Christ to become our holy Head; and that we may hold unto him,
and so walk and live, that he may take delight in his church, the body,
to rule in and over it,
as we have the state of the true church and Christ represented
in the most excellent and sacred writings of the holy Scriptures.
May we likewise know the marriage of the Lamb to be come, and as of old,
make ourselves ready,
put off the sins and corruptions of the world that are through lust,
and put on the Lord Jesus Christ and his pure righteousness.
This is the fine linen, the righteousness of the saints; this is the wedding garment;
without which preparations, and true Bride`'s attire,
I cannot see how any can expect an admittance into the Bridegroom`'s chamber.
Therefore I entreat all such as do not find themselves in preparation,
and have not their peace assured to them,
still lacking the evidence of the Spirit of the Lord that they are his,
not to slumber away their precious time until the midnight,
lest unexpectedly the cry be heard to sound with terror in your ears.
Arise, trim your lamp, for behold the Bridegroom comes,
who has in times past exercised mercy and lovingkindness towards you,
and has sought various ways to win you to love him.
He has at times reproved you for evil,
and at other times has set before you the comforts and happiness you should possess,
if you would obey and follow him; no, he has wooed you as a young man does a virgin,
and if you had devoted yourself to him, he would have gathered and saved you,
and rejoiced over you as a bridegroom does over his bride.
But if you turn your back upon all his reproofs, entreaties and endearments,
as in the parable of the five foolish virgins, in the time when he, the Bridegroom,
calls to an account,`" he will not know you otherwise
than to shut you out of his presence and favour,
notwithstanding whatever you may have heard, received or done,
if you continue to work wickedness, and are not reclaimed therefrom.
These things sprang in my mind as a warning for all,
to flee from every destructive thing, before the Lord overtakes them,
when they cannot escape his hand of justice; and also,
that the faithful may be encouraged in well-doing,
and to a faithful perseverance to the end.
Amen.

Some things which have been omitted, I think proper to insert here,
as worthy of observation.
As I was travelling towards Lincoln, and passing through Brig,
Friends gave me notice that there were two great disputants, a non-conformist minister,
and a doctor of medicine, who were likely to go all or most of the way with me,
as the court sessions were coming on, and would be at me with arguments about religion,
which I soon found true.
We no sooner got into a suitable way but they began with me,
which I endeavoured to prevent by telling them,
I did not look upon myself to be qualified for disputes; and observed,
that sometimes disputants ended in a worse understanding
one of another than when they began,
except they minded well to keep good government;
and now as we appeared free and friendly, how we might be when we had ended our dispute,
was a question, therefore I had rather they would forbear.
But they turned the deaf ear to all I said, and nothing would do with them,
but a dispute we must have.
I then asked them, what they would say, They queried,
whether all men were placed in a station capable of salvation, yes or no.
I replied, if I should give my positive thoughts to your question,
we shall have occasion to go back to treat of the nature,
not only of the upright state man was in before he fell, but also how he fell;
and also in the fall, how he stands as in relation to his restoration,
which brings us to the question.
Although this be not the usual way of disputants, yet if you will submit to it,
it will either answer your question, or set it in a clearer light for an answer.
They asked, how could that be; I replied, if it did not, they might say so.
They then so far condescended as to hear me.
I said, first, we all agree in this, that man was made upright; secondly,
that he fell from that uprightness; the question then is.
How? Ans.
By the offence or disobedience of the first man Adam, sin entered,
and condemnation came upon all who have sinned.
I then queried of the disputants,
whether they believed that Adam`'s fall did affect all those who did not hear of it,
as well as those who did; for, I said, there were some of opinion,
that those who had not the explicit or outward knowledge
of the promised seed or coming of Christ,
had not the benefit of his coming; and except they would first allow,
that all were affected or hurt by Adam`'s fall, then such as were not,
remained in paradise to this day,
except they would make the remedy less than the disease, the plaster less than the sore,
and Christ`'s coming less extensive than Adam`'s fall.
I argued, that upon the foot of reason, as well as what we had in plain Scripture,
+++[+++the effect of]
Christ`'s coming was as extensive as the fall of Adam, for, by the obedience of Christ,
the gift of God came upon all unto justification.

Now I think, said I, your question is set in a clear light for an answer,
or else answered; so take it at what end you will, laying aside all quibbling,
I intend to join issue with you,
and prove that all men are placed in a station capable of salvation,
or otherwise you will leave a great part of the world in paradise,
or make the coming of Christ less extensive than the fall of Adam.
I then queried, what they said to all this; they answered,
they never heard the like before, and they would not meddle with me,
I was too great a scholar for them.
I said, there was little of scholarship in it.
I offered, I thought, nothing but plain Scripture and sound reason: and I told them,
I had now as good as answered their question,
and had given several reasons to back my answer, and as they appeared wise,
well-read men, and as far as I had gathered,
had been principled against the universal +++[+++offer of]
salvation and universal grace, for them now to drop the matter so slenderly,
before me who appeared but like a child to them, was very surprising: but they replied,
they would not meddle with me.

I commended them for their good temper and civility,
for they were civil to me beyond what I could expect;
and invited me to the burial of one of their deceased friends, but I could not go,
for I was in haste to get to Lincoln, having some business there that hastened me.
At parting with them, my soul magnified the Lord, under a sense of his goodness to me,
in that he had opened my way, and helped me through this difficulty,
with many other trials and afflictions I had met with.

I had at another time some reasonings with a Papist who was my neighbour,
about their church and transubstantiation, with several other things.
As to the first, I showed him, that the true church fled into the wilderness,
where she was for times, time, and half a time;
in this state we do not read she had any outward character as a visible church;
and if they derived their descent, it was from some false church,
and not through the true one.
As to the other, they took too much upon them,
more than they could justify from Scripture,
or clearly demonstrate from Christ or his apostles;
for Christ never gave any of them such a commission,
as to convert bread and wine into real flesh and blood, and then to call it Christ.
You, said I, by these notions,
deceive yourselves and your adherents for Christ spoke unto such as you by parables,
because they were carnal,
and did not understand the meaning of his sayings in this
case any more than the Jews understood what Christ meant,
when he spoke of destroying this temple, meaning his body,
which they understood was of that temple at Jerusalem, which they made a great wonder at,
and said, How can this be, that he can destroy this temple,
and raise it up again in three days, when it was forty-eight years in building?
Thus they reasoned carnally, as Nicodemus, though a ruler of the Jews,
did concerning regeneration or the new birth; and as the woman of Samaria did,
when she asked from where Christ should get that living water, which he spoke of,
that should be in man as a well of living water, springing up unto everlasting life;
and as the Jews did, when Christ said, "`Except you eat the flesh of the Son of man,
and drink his blood, you have no life in you;`" they said, How can this be,
that he can give us his flesh to eat, and his blood to drink?
But this is a spiritual eating and drinking; even as Christ said,
"`Out of the belly of him that believes,
shall flow rivers of living waters;`" which he spoke of the Spirit.
In like manner it is said in the Revelation, "`Behold I stand at the door and knock,
if any man hear my voice, and open unto me, I will come in and sup with him,
and he with me.`"
Here is a union of spirit between Christ and his faithful children,
and here is an inward eating and drinking of the heavenly, spiritual,
and mystical flesh and blood of Christ, which carnal men cannot eat of,
neither can the carnal eye discern Christ`'s spiritual body,
with which he feeds his living and spiritual church.
When I had reasoned with the man to this effect, he went away seemingly not pleased,
but would not from that time ever meddle with me any more.

I need not say much here about Christ`'s being come; having showed,
in a conference in New England,
how he is come to answer his eating and drinking
the passover and last supper with his disciples,
saying.
He would drink no more of the fruit of the vine,
until he drank it new with them in his Father`'s kingdom.
Now he that has experienced what this eating and drinking is,
is come beyond the outward eating and drinking, into the kingdom which is within,
which comes not with outward observations, eating, drinking, or carnal ordinances,
but the kingdom of heaven consists in righteousness, peace and joy in the Holy Spirit.

Read this you that can, and learn to understand between the thing that points,
and the thing which is pointed at, and between the thing signifying,
and the thing signified, and mistake not the shadow for the substance any longer;
for it is possible a man may do all the outward parts,
and yet be ignorant of the cross of Christ, and of the heavenly substance.
But if he is come to the end of these outside things, to the Holy of Holies,
such will know what it is to minister before the Lord in his temple,
and to serve and wait at the holy altar, and live,
and have that pure spiritual life preserved.
We read not of any tithes that appertain to this spiritual priesthood,
or Gospel ministry; and what their outward maintenance was to be, is showed by Christ,
beyond contradiction, who sent them forth: where they were received,
(mark that well,) they might eat such things as were set before them,
but were not to take anything from them by force,
for that is out of the doctrine and practice of Christ and his apostles.

Why do people call the Scripture their rule of faith and manners,
when at the same time they believe and act contrary thereto?
When I had, some years before, a debate with the priest of our parish,
we meeting at Sponton, being there upon some occasion, and several people met together,
the priest demanded my reasons, why I did not pay him his tithe.
I used some persuasive arguments to put him off,
not being willing at that time to enter into a debate with him;
but the more I showed my unwillingness to it, the more urgent he was upon me.
So when I could not see how to avoid entering into some close debate with him,
I desired he would not be angry, and he said he would not.
I then showed in several particulars, why I could not pay him tithes,
because I believed if he was a minister of Jesus Christ, he ought not to claim any; for,
as there was a change of the priesthood,
there also must be of necessity a change of the law, as we see in Heb. 7:12,
and to pretend to draw any command or example from Christ or his apostles,
out of the New Testament, for that purpose, appears to me weak and inconsistent.

We had some farther discourse upon the ground of his right to tithes,
whether __jure divino__, as they used to be formerly claimed; or __jure humano__, that is,
by human law, as most of the modern priests seem to choose to fix their title.
I bid him fix his right for tithes on which claim he`' pleased,
and I would endeavour to answer him as well as I could;
but he seemed not to fix upon either.
Whereupon I told him, there was no Scripture settlement of tithes upon Gospel ministers;
and also offered to prove, that he was neither in the practice of the Levites,
to whom tithes were directed to be paid,
nor yet in the practice of those ministers whom Christ qualified,
ordained and sent forth.
First, not in the practice of the Levites; because the tithes due to them,
were for their punctual performance of their part of the ceremonial law, Num. 18:21,
which if any now claimed, it seemed to me,
that he subjected himself to the practice of burnt-offerings and sacrifices,
circumcision, Jewish habits, washings, etc., besides which,
the law which appointed the tithe to the Levites,
expressly forbids them to have any share or inheritance in the land,
as appears from Num. 18:20,23,24. and Duet. 18:1-2.;
which the modern claimers of tithe would be unwilling to be compelled to practice;
not to insist on the law of the third year`'s tithe, of which the widow, the fatherless,
and the stranger within their gates,
were to receive a considerable part as their allotted portion, Duet. 14:28-29.
Secondly,
not in the practice of those ministers whom Christ qualified and sent forth;
for these went out by an especial command from him, without gold, silver,
or brass in their purses, and without two coats;
and so intent were they to be in the execution of
their great duty of preaching the Gospel,
that they were to salute no man by the way,
but to go forward on the great errand they had received in commission:
and when they returned to their Lord, he asked them, if they lacked anything:
and they said nothing.
Not because they had forced a maintenance from any,
but that the effect of their ministry among their hearers had been so prevalent,
that those who had been convinced by their doctrine,
and turned to the effectual power of Christ in themselves,
had from there known their hearts so opened,
as to administer to all their immediate necessities; and these, thus sent,
only eat such things as were set before them, as they were appointed;
and where they had sown spirituals,
had only reaped of the temporals of their converts for their immediate subsistence.
But though you sow not to me of your spirituals,
nor do I believe you to be one who have anything spiritual,
which can be of any benefit to my spiritual part;
and though you esteem me as a heathen man and a publican,
and I am excommunicated and cut off from any church fellowship with you,
not for any evil, but as far as I can understand,
for not coming to what you call the church, yet you expect to reap of my temporals,
because the law of the land has given you that power;
which disposition to reap where you have not sown,
and to gather where you have not strewn, is far from manifesting a Christian spirit.

The priest farther urged some passages out of the New Testament,
in vindication of the payment of tithes, alluding to that of the apostle, 1 Cor. 9:7,
about sowing of spiritual things unto us;
that it was but a small thing if such received of our carnal things;
and that of feeding a flock, and partaking of the milk of the flock;
and of planting a vineyard, and eating the fruit thereof:
all which I endeavoured to obviate, by showing, that he did not sow his spirituals to us,
so that he might be entitled to our carnal things;
neither were we of that flock which he should partake of the milk of;
neither were we a vineyard which he had planted,
that he might eat of the fruit thereof Furthermore I said, I am a stranger,
and an excommunicated person, and not of your children; the apostles, if they had needs,
or were in any strait for necessaries, did not apply to strangers for help,
but to such of their children in whom they had been instrumental
in the hand of God to plant the true faith,
and sow the seed of the kingdom.
These who were thus convinced, and by the work of God`'s power converted,
were such who knew spiritual things sown in them,
who I believed were very free to distribute, where need was, of their temporal things,
especially to such who had been instrumental in the Lord`'s
hand to their coming to the saving knowledge of Jesus Christ.
But I showed the priest, that all this carried no analogy to what was between him and me,
for I being excommunicated, was but to him as a heathen man and a publican,
and as we never came to hear him, we could not owe him any acknowledgment,
nor could he expect anything as a freewill offering on that account.

The priest was a strong-spirited man, of considerable talents and learning;
and a neighbouring justice of the peace told me,
he was fearful would be very severe with me; yet to his commendation be it spoken,
he was ever after this conference very loving,
and never gave me any trouble for what he called his dues.

I may add one observation or two not mentioned in our debate, which were,
that if the maintenance of the priests was to be wholly withdrawn,
or left to the freedom and generosity of the people, many of them would come to poverty,
and be forced to labour with their hands, which would distract,
or at least impede their studies.
I answered, that with such ministers as they were, this might be the case:
but if all would come truly and rightly to wait on the great Teacher,
the anointing in themselves, it would greatly tend to the advantage of Christendom.
For the Almighty,
who by his good Spirit is alone able to raise up and qualify Gospel ministers,
as he knows the needs of his people, and their faith and trust in him,
would no doubt raise up from among them faithful ministers; who, being humble,
meek and low in heart, like him of whom they had learned,
would be content to live in moderation on a little,
and to labour in their respective callings, such as fishermen, collectors of customs,
and like the apostle Paul, that great minister of the Gentiles,
working with their hands that their ministry might not be chargeable.
Their ministry being not their own,
but received immediately from the great Shepherd of the sheep,
would not require time and study to pen it down,
but coming from the Spirit of Truth immediately moving upon the ministers`' hearts,
it would be more effectual to reach the witness of Truth in the hearts of their hearers,
than all the laboured discourses of the most subtle priest,
though the product of much pains and study.
Neither have I found in all my travels, from any observation I have made,
that ever the faithful ministers of Christ became
any great burden or charge to the churches;
for I have seen the Divine Providence attend the Lord`'s faithful servants,
who thereby have been enabled to order their affairs with discretion,
so as to need little.
