[quote.epigraph, , Luke 10:16]
____
He that heareth you, heareth me; and he that despiseth you, despiseth me;
and he that despiseth me, despiseth him that sent me.
____

== Chapter 1

[.chapter-subtitle--blurb]
An Account of the Early Life of John Richardson,
Introduced with a Brief Relation Concerning His Father, William Richardson.

It has been repeatedly revived in my mind,
to leave the following account concerning my dear father, William Richardson,
having seen something of his own in manuscript, concerning his convincement,
with remarks on some other things; but I being young when he died,
did not then much heed it, and when I would gladly have seen it for my own satisfaction,
I could not, nor as yet can meet with it.

As my father was early convinced of the Truth, a sufferer for it,
and bore a public testimony to it, I found it my duty,
as nearly as I could remember the contents thereof,
to leave this short account concerning him.

He was born at North Cave, in the eastern part of Yorkshire, in the year 1624,
of honest parents, and of good repute, and was educated in the Episcopal way,
being soberly inclined from his childhood; a lover and seeker after purity and virtue.
I have heard him say he gave his mind much to retirement, reading the Holy Scriptures,
and seeking after the Lord, especially in the fields, being by calling a shepherd;
and it pleased the Lord to open his understanding so clearly,
that he saw and longed for a more excellent dispensation to come.
He also saw that the priests were wrong, and generally proud and covetous,
so that he was weary of following them, and much weaned from them and all company,
except two or three men who met with him,
and spoke one to another concerning their inward conditions,
and what they had experienced of the Lord`'s dealings with them.
This was before they had heard of the name Quaker,
as it was in a short time after given to a people which the Lord
raised up to give testimony of the notable and ancient,
yet newly revived and blessed, dispensation of Christ`'s coming,
and manifestation by the Holy Spirit in the hearts of the children of men,
in order to enlighten, quicken, sanctify, and save them from darkness, death,
ignorance and sin, that they might be made capable of obeying,
worshipping and glorifying the great God and sanctifier of them.

As my father was thus waiting and looking for a more
general breaking forth of this glorious,
powerful, and Gospel day, which had in a good degree sprung up in his heart, he had not,
as yet, seen that worthy and good man, George Fox,
although he passed through those parts about that time;
but soon after came William Dewsbury, and at the sound of his voice,
I have heard my father say, he was exceedingly glad,
in hearing him declare the way to find the lost piece of silver,
the pearl of great price within, a Saviour near,
who had been held forth by men to be at a distance.
But having left the dark watchmen, of whom they used to inquire,
they now met with their beloved at home, in their own bosoms;
renowned be the name of the Lord, now and forever.

Thus the hearing and receiving the ever blessed Truth, was as the seed,
or word of the kingdom, sown in the good ground, or honest hearts of men,
which took root downward and sprang upward, and brought forth fruit, in some thirty,
in some sixty, and in others an hundred fold,
to the praise of the great and good Husbandman.

My father was early raised to bear a public testimony,
which was living and acceptable to Friends,
but was so much attended with weakness of body for many years,
that he went little abroad in the work of the ministry.
He suffered patiently the spoiling of his goods, and imprisonment of his weakly body,
in the great and more general imprisonment; and not only believed in Jesus Christ,
but suffered for him.
He was a good neighbour, a loving husband, and a tender father over all that was good,
but severe to all that which was wrong, and was for judgment, without respect of persons,
and spared not even his own children; especially he was much concerned for me,
for he said, I was the wildest of them.
As he lived well, and believed in Jesus Christ,
I doubt not that he has finished his course in the love and favour of God,
is entered into a mansion of glory, and is at rest with all the faithful,
who "`loved not their lives unto death,`" but rather hated them in comparison
of that endeared and unfeigned love they bore to God the Father,
and to Jesus Christ his dear and well-beloved Son, who died for them,
and also for the whole world.

He departed this life in 1679, aged about fifty-five years,
and was decently buried in Friends`' burying-place at Hotham, near Cave,
where he was born.

Having given the foregoing account of my father,
it remains with me to leave to posterity some remarks on my convincement,
with an account of sundry transactions, travels, healings,
and deliverances I have met with, from my youth to this day,
with some advice and openings in the Spirit of Truth.

I was not above thirteen years of age when my father died,
yet the Lord was at work by his light, grace, and Holy Spirit in my heart;
but I knew not then what it was which inwardly disquieted my mind,
when any thing which was evil prevailed over the good in me, which it oftentimes did,
for want of taking heed to the spirit of God in my heart.
I desired ease and peace some other way,
without taking up the cross of Christ to my own corrupt will, and strove for some time,
as no doubt many do, to make merry over the just witness,
until for a season the converting and true witness of God seemed to be slain,
or disappeared.
Then I took liberty, but not in gross evils which many ran into,
being preserved religiously inclined, seeking after professors, and inquiring of them,
for my information and satisfaction, to find, if I could,
any thing that was safe to rest in,
or any true and solid comfort to my poor disconsolate and bewildered soul.
But I was afraid I should be deceived,
or take up a false rest in any thing that was wronger unsafe;
which fear was of the great love and mercy of God to me.

After many searches and inquiries among those who
were but in the letter and outward court,
where the veil is over the understanding,
and the eye of the mind is not truly opened to see
into things that are hid from all carnal-minded men;
so my state and afflictions were hid from them, and all the deceitful workings of Satan,
and the strong temptations which I met with, these blind guides could not see,
nor did they know how to direct me to the true Shepherd of Israel,
the Law-giver coming out of Zion, that turns away ungodliness from Jacob,
and transgression from Israel;
not having truly experienced deliverance wrought in themselves out of this cloudy,
bewildered, and tempted state which I was in.
Oh! that people would come to him that hath the eye-salve,
with which if the eye be truly anointed, it will see things clearly as they are,
and not darkly, mistaking trees for men, and things terrestrial for things celestial;
and that they would buy gold, tried by the fire of him who is called the Tried Stone,
elect and precious, laid in Zion for a foundation.
This is Christ whom the true church believes in and builds upon,
and is enriched with his love, power, and virtue, which is belter than gold outwardly:
this is the unction, which the true church hath, and receives from Christ, the Holy One;
and such as do truly put on his righteousness, purity, and holiness,
their clothing is better than that of fine linen outwardly.
Oh! that all the inhabitants of the earth might be thus anointed, enriched,
and truly clothed,
that no more inward blindness or poverty may be found in the children of men,
nor the shame of their nakedness be any more seen.

Receive and learn these things, you that can,
of him that is the faithful and true witness,
who always witnesseth against the evil in man, but always giveth witness to the Father,
for the good in men which they say and think.
This is the Spirit of him that was dead, and is alive,
no more to be known after the flesh, as the apostle gave testimony,
but is to be known inwardly and spiritually by the children of men,
to open the blind eye, and unstop the deaf ear,
and pierce into the soul that hath been clouded and captivated, imprisoned,
and misguided, and even in a wilderness, and sees no way for deliverance;
like Israel in the land of Egypt, when the Lord Jehovah sent Moses,
a lively type of Christ, and employed him in that great work of pleading with,
and plaguing Pharaoh and the Egyptians.
For a time their burdens were increased, and their exercises more embittered,
until their deliverance was in a good degree accomplished;
and which was not wrought until the first-born of man, and of beast, was slain,
throughout all the land of Egypt.

The clear opening I had in the light,
of what is to be understood and gathered from hence,
is not the slaying of the outward man, but a putting off,
or slaying the body of the sins of the flesh, crucifying,
or putting off the old man with his deeds; and as to the beast, all cruelty, lust,
pushing, tearing, devouring, and savageness, is to be slain or put away;
and the corrupt or strong will of man, as well as what is bestial,
must be slain before man can come from under the power of
him who is called the Prince of the power of the air,
the spirit that rules in the hearts of the children of disobedience.
These things must be experienced,
before the children of men can go forth rightly qualified to glorify God,
and follow his dear Son,
whom he hath appointed to be a leader and a commander of his people.
This is he, as Moses declares, who is to be heard in all things,
under the penalty of being cut off from the people;
or of having their names blotted out of the book of life;
or being deprived of the comforts of the Lord`'s holy presence.
Read this, you who have heard and understood what the Spirit saith unto the churches.
These things I saw, after the true witness arose or revived in me,
and the light shone which had disappeared or been clouded.

After much searching without, amongst those who proved to me physicians of no value,
and miserable comforters, I betook myself to a lonesome and retired life,
breathing after, and seeking the Lord in the fields and private places, beseeching him,
that he would bring me to the saving knowledge of his truth;
and blessed be the name of the Lord now and forever,
I had not sought him long with all my heart,
before I met with his inward appearance to me, in and by his Holy Spirit,
light and grace.
But when the true Light did begin to shine more clearly,
and the living witness arose in my inward man, oh! then my undone, bewildered,
and miserable condition began to appear,
and great and unutterable were my conflicts and distress.
I thought no man`'s condition upon the face of the earth was like mine.
I thought I was not fit to die, neither did I know how to live.
I thought in the evening, "`Oh that it was morning!`" and in the morning,
"`that it was evening!`"
I had many solitary walks in the fields, and other places,
in which I poured out my complaints and cries before the Lord,
with fervent supplications to him,
that he would look upon my affliction and the strong temptations I was under,
and that he would rebuke the adversary of my soul, and deliver it,
for I even thought it was in the jaws of a devouring lion, and amongst the fiery spirits,
and, as it were, under the weight of the mountains.

Read and understand the afflictions of thy brother,
thou that hast come through great tribulations,
and hast washed and made thy garments white in the blood of the Lamb.
This is the beginning of that baptism which doth save,
and of that washing of regeneration and renewing of the Holy Ghost,
which the Lord sheds upon the believers in abundance.
This is the blood which sprinkleth the heart from an evil conscience,
that the children of men, thus changed, may serve the living and true God;
this is the life which converts the world, even as many as are converted;
this is the virtue, life, and blood, which maketh clean the saints`' garments,
and inwardly washeth them from all filthiness, both of flesh and spirit.
I found this was and is He of whom it is said, "`By him were all things made,
and he is Lord of all;`" a man ought to be servant to him,
and all things in man subservient to him, who commands and comprehends all things,
in whom all the types and shadows end, or are fulfilled.
Read this, thou virgin daughter, or clean church of Christ, the rock of thy strength,
whose name to thee is as precious ointment poured forth,
and because of the savour thereof, the virgins love him,
and are under great obligations to obey and follow the Lamb of God,
wheresoever he leadeth.

Although I had seen many things, and had divers openings, yet great were my trials,
and many were the temptations I met with in those days,
for I lived at a distance from Friends and meetings, which made my exercise the harder,
as will more fully appear hereafter,
in the course of my travels and pilgrimage in this vale of tears and troubles,
and some of them not very common; but the Lord helped me through them all,
blessed be his name forever.

I now came to witness that Scripture to be fulfilled which saith,
that "`When the Lord`'s judgments are in the earth,`" or earthly hearts of men,
"`the inhabitants learn righteousness:`" and notwithstanding there was
an aversion in my wild nature to the people in scorn called Quakers,
as also to the name itself,
yet when the afflicting hand of the Lord was upon me for my disobedience, and when,
like Ephraim and Judah, I saw in the light my hurt and my wound, I bemoaned myself,
and mourned over that just principle of light and grace in me,
which I had pierced with my sins and disobedience.
Although that ministration of condemnation was glorious in its time,
yet great were my troubles, which humbled my mind,
and made me willing to deny myself of everything;
which the light made known in me to be evil, I being in great distress,
and wanting peace and assurance of the love of God to my soul;
the weight of which so humbled my mind, that I knew not of any calling, people, practice,
or principle, that was lawful and right, which I could not embrace, or fall in with.
This was surely like the day of Jacob`'s troubles, and David`'s fears.
I saw that the filth of Zion was to be purged away
by the Spirit of judgment and of burning;
this is the way of the deliverance and recovery of poor men out of the fall,
and the time of the restoration of the kingdom to God`'s true Israel.
Read ye that can, and understand.
This was the day of my baptism into the love of God, and true faith in his beloved Son,
as also into a feeling of, or sympathy with him in his sufferings,
which were unutterable, and I found that ministration changed;
that which had been unto death, was now unto life;
and the ministration which was of condemnation unto the first birth, when that was slain,
and in a good degree nailed or fastened to the cross of Christ, the power of God,
then the good prevailed over the evil, and working out the evil in the mind,
and also in the members, made all good or holy.
The Lord`'s living power, and consuming word, when it works and prevails,
brings into subjection, and maketh holy the very heart or ground in men.

As there had been an aversion in me to the people called in scorn Quakers,
and also to their strict living, and demeanour, plainness of habit and language,
so I learned none of these from them; for when the Lord changed my heart,
he also changed my thoughts, words, and ways, and there became an aversion in me to vice,
sin, and vanity, as there had been to the ways of virtue.
Having tasted of the terrors and judgments of God because of sin,
I was warned to flee from such things as occasioned
Christ`'s coming not to bring peace upon the earth,
but a sword; a sword indeed, yea, his heart-penetrating, searching word,
which is sharper than any two-edged sword,
that pierceth to the dividing asunder between flesh and spirit, joints and marrow.
As I came thus to see and abhor the evil in myself,
when such who had been my companions in vanity reviled me, or came in my way,
I was often moved to warn and reprove them.
Having tasted of the terrors of the Lord for sin,
I could not well forbear to warn others to flee such things as I had been judged for.
Now I came clearly to be convinced about hat-honour, bowing the knee,
and the corrupt language, as well as finery in habit; all which, for conscience-sake,
and the peace thereof, I came to deny, and take up the cross to,
and had great peace in so doing.

Notwithstanding the blessed truth thus prevailed in me,
I was not without great conflicts of spirit, temptations, and trials of divers kinds;
yet my mind was resigned to the Lord, and my fervent prayers were to him, and he kept me,
and opened my understanding, for I was afraid of being misled in any thing,
especially relating to my salvation.
I came to be weaned from all my companions and lovers in whom I had taken delight,
and all things in this world were little to me,
my mind being much redeemed out of the world, not only the corrupt and evil part thereof,
but even from the lawful part; so that I became much given up to seek the Lord,
waiting upon him to feel his presence, and peace, and to know his will,
and receive power to do the same.

As my mind came to be thus brought into a dependant and waiting frame upon the Lord,
and to be stayed in the light,
and experimentally and feelingly to partake of his love and grace,
which helped me against my infirmities, blessed be his name,
I found it sufficient for me, as I kept to it, in all trials and temptations.
Then I came to see,
that all outward performances in matters of religion
did not avail nor render man acceptable to God,
but as the heart came to be truly given up to him,
that he might not only purge it from defilement,
but keep it clean through the indwelling of his Holy Spirit.
As nearly as I remember,
I saw clearly through these things before the sixteenth year of my age.
Between the death of my father and this time,
I took liberty to go among what people I would, my mother giving us great liberty,
although she was a woman well accounted of among all who knew her, and not undeservedly,
for her industry and fair dealing concerning the things of this world.

After this time I attended the meetings of the Lord`'s people called Quakers,
as diligently as my circumstances would well admit.
My mother being left with five children,
the youngest about three years old when my father died,
and he leaving but little of this world to bring us up,
though my parents always had as much as kept them above contempt,
and nobody lost by them;
I found myself under a necessity to work hard for my own support, the help of my mother,
and education of my brothers, more especially as my only sister died soon after.

Being left on a grazing farm, part of which was tilled,
we did well as to the things of this world,
yet I cannot well omit mentioning one thing which became a great exercise to me,
which was thus: My mother married one who was zealous for the Presbytery,
and being much against it, I showed my dislike to the marriage, and told my mother,
I was afraid that she had too much an eye to what he had,
for he was counted rich as to this world;
but if she thought to augment our portion in so marrying,
the hand of the Lord would be against her,
and a blasting or mildew would come upon even that
which we had got through industry and hard labour,
and what the Lord had intended to bless to us, if we kept faithful to the truth,
and contented ourselves with our present condition.
My mother confessed, that as to the worldly enjoyments,
it had not been better with her than now.
I must write with great caution; she was my mother, and a tender mother over me,
loath to offend me, and had promised, as far as she well durst,
not to marry with any one with whom I was not satisfied.
Of their procedure in courtship, and marriage, from this time I was entirely ignorant,
until it was accomplished.
But when my poor mother was married, her cry was, "`My son,
how shall I ever be able to look him in the face any more,
it will be such a trouble to him! he that hath not
at any time disobliged me--but if I bid him go,
he ran; and if I bid him do any thing, he did it with all his might;`" or to that effect,
as several told me who heard her.
She being married, what we had was mixed with my step-father`'s goods;
my mother died first, and our father married again, made his will, and dying,
left me five shillings for all my part,
which was of right to descend from my own parents upon me.
I gave his executors a receipt in full, and there was an end of all,
except some small matter given to my youngest brother,
for the rest of my brothers and sisters were dead.
As nearly as I remember, this marriage was in the eighteenth year of my age,
so that what I foresaw about the blast and mildew, came to pass.

To return to my account concerning the troubles that attended
me while I was in my step-father and mother`'s house;
after marriage, we, and what we had, were removed to his house,
except part of the stock left in the ground.
I foresaw that I was likely to come to a great trial,
and was brought very low about the marriage,
and exercise of mind concerning my own condition, having many conflicts of spirit,
so that I was almost in despair.

Had not the Lord, in whom I believed, risen in his power,
and rebuked the adversary of my soul, I had been overthrown,
and swallowed up in the floods of temptation that
were cast out of the mouth of the dragon after me,
in this day of great trouble and travail; but the God of love and pity saw me,
and helped me in my distress, in an acceptable time.
He that heard poor Ishmael when he cried from under the shrub,
and gave relief to him and his mother, who had gone from Abraham`'s house,
saw me in this great strait.
When I came to my father`'s house, he being a man much given to family duties,
saying grace, etc. before and after meat, I could comply with none of them,
except I felt evidently the Spirit of Truth to attend therein,
and open the heart and mouth into such duties.
The first day I came to the house,
being called to the table with all or most of the family, I thought,
"`Is it now come to this?
I must either displease my heavenly or earthly father:`" but, oh! the awfulness,
or deep exercise, which was upon my spirit,
and strong cries that ascended to the Lord for help
and preservation that I might not offend him.
My step-father sat with his hat partly off, with his eyes fixed on me,
as mine were on him in much fear;
so we continued as long or longer than he used to be in saying grace, as they call it,
but said nothing that we heard.
At length he put on his hat again, to the wonder of the family: neither did he then,
nor ever after, ask me why I did not put off my hat;
neither did he perform that ceremony all the time I stayed with him,
which was above one year: thus the Lord helped me,
renowned be his great name now and forever.
My father might seem for age, spirit, and understanding,
to be much more than a match for me, a poor shrub; but the Lord,
who caused the pillar of cloud to be bright and give light to Israel,
and brought darkness upon the Egyptians, and fought against them, and for Israel,
I believe smote my poor father,
that he could not rise up against the power with which the Lord helped me;
for it was not mine but the Lord`'s doing, to him be given the attributes of praise,
salvation, and strength, now and forever.
I saw clearly, that there could not be any true and acceptable worship performed to God,
but what was in the Spirit, and in the Truth; neither could any pray aright,
but as the Spirit helped them, which teacheth how to pray, and what to pray for,
and rightly prepares the mind,
and guides it in the performance of every service
which the Lord calls for from his children.

I found my step-father was much displeased with my going to meetings,
yet I could not see what way to appease his displeasure,
except in being very diligent in his business, which I was, rather beyond my ability,
working very hard.
It is almost incredible what my poor little weak body went through in those days,
but all would not gain his love, for the longer I stayed with him,
themore his love declined from me;
although I told him he need not be uneasy about my wages,
for I would leave that to himself.
I could not see what he could have against me, except my going to meetings;
however that was all he alleged.
When his former stratagems would not do, he offered me a horse to ride on,
if I would go with him to his place of worship.
I met with many a snib and sour countenance from him, in my return on foot from meetings,
although as seasonably as my body was capable of performing.
On the first-day mornings my father commonly sent
me into the fields a mile or two on foot,
and as far upon a common to look at beasts, horses and sheep,
I thought with a design to weary and make me incapable of going to meetings;
all which I bore patiently, neither ever said, that I remember, this is hard usage:
after this, to the great grief of my poor mother, I had to go two, three, four, five,
and sometimes six miles, to Friends`' meetings.
After I had walked fast, and ran sometimes with my shoes under my arms for want of time,
I have seen many Friends weep,
and could not forbear when they saw me come into
the meeting very hot and in a great sweat,
they being in part sensible of the hard task I had to undergo.

There is one thing somewhat remarkable, which was thus: One first-day morning,
when I was about going to the meeting, my father said,
if I would ride upon such a young mare, as he mentioned, I might;
she was one of the greatest of ten or twelve horses that he kept, about four years old,
and had not been ridden before.
I thought his design was more to hinder me of the meeting than any good to me,
or any expectation of getting his mare rightly broken; but I accepted his offer,
only asking how I might catch her.
Having got help to answer that, she being abroad, I put on the bridle,
and mounted the topping beast, and upon her first resistance, down she came;
for that was my way: and if the first or second fall did not,
the third mostly cured them from striving to throw the rider.
I commonly fell upon my feet,
and endeavoured so to free my legs that she might not fall upon them,
and then sprang up on her back while down, and made her rise with me; so away we went,
and came in due time to the meeting.
I rode to meetings two or three times, and my father asked me,
if the mare did not carry me soberly: I replied, she did; then I must have her no more,
he would make her his saddlemare; so I took to my feet again,
except some other such turn came.
The Lord`'s mighty power bore me up, and he gave me as it were hinds`' feet,
and enabled me to go through these exercises,
and to bear the burden in the heat of the day of my trials, inwardly and outwardly,
which were many and various.

Now the last stratagem my father used to hinder my going to meetings was thus:
He took me in his arms in great show of kindness, saying, If I would be as a son to him,
I should find he would be a father to me,
expressing something about his having no near kindred,
and more to the same effect he said to my brother Daniel, who was an innocent, wise,
and clean spirited lad.
I replied to him, If in thus making me thy son,
thou intends to hinder me from going to meetings,
or to oblige me to go with thee to the Presbyterian meetings,
or any thing that is against my conscience, I cannot upon this bottom be thy son; and,
for the same reasons, I refused to be his hired servant,
although he offered to hire me and give me wages.
Now when he saw that neither frowns, threatenings, hardships,
nor great promises of kindness could prevail with me, he told me bluntly and roughly,
I should stay no longer in his house.
I innocently answered, I could not help it if it must be so,
as all I could do would not give him content, without hurting my conscience,
and the peace of my mind, which I valued above all mutable things of this world.
My poor mother heard my pleading with him,
and how I offered to do the best for him I was capable of by night or day,
as I always had done, if he would be easy, and let me have his countenance.

But this was the sentence: No, I should not stay in the house.
That troubled my mother so, that I was forced to leave my father,
and go to endeavour to mitigate her great trouble by telling her,
that if I was but faithful, the Lord, I believed,
would take care of me that I should not want; and the more fully to discharge myself,
I reminded her, that as she had entered into marriage covenants with her husband,
she should endeavour to perform them,
and in everything faithfully to discharge herself as a wife ought to do to a husband,
and leave me and all, and cleave to him, and to make her life as easy as she could.
I also told her, never to send me any thing that my father knew not of,
for I was not free to receive it; although what we had was in his hand,
and all sunk there, as I mentioned before.

I write this partly, that all who marry,
may take special heed that it be done with great caution, and under due consideration,
and the Lord sought to in it, that it may be done in his counsel, and not only nominally,
but truly in his fear, and then no doubt that it will be well with both husband and wife.
Being equally yoked,
such will not only be true helpers in all things belonging to this life,
but more especially in things appertaining to the world that is to come,
and the good of the immortal soul,
which to the faithful people of the Lord is of great value.
Oh! how happily and peaceably do such live together in the Lord,
as they keep to that which thus joined them: there is more in it,
both as to the parents and their posterity, than it is to be feared many think of,
as is apparent in the many forward and unequal marriages of which I have made observation.

One remarkable passage occurs, which happened thus:
My father having been at the Presbyterian meeting, and come home, he, as his manner was,
put me or my brother upon reading the priest`'s text, which had been that day in Daniel,
concerning his being cast into the den of lions, for not regarding the king`'s decree,
but on the contrary,
he prayed to the God of heaven with his windows open toward Jerusalem,
after his wonted manner.
My father made his observations as my brother read, and very much magnified Daniel,
and said, the Spirit of God was in him, but that there were none such as him in our days.
I owned that he was indeed an extraordinary man,
but in that there were none endowed with a measure of the same spirit in any degree,
I dissented from him,
and gave my father a brief account of the many sufferings of our Friends,
some of which were past,
and some then under sufferings for the word of God and the testimony of Jesus,
which they bore for him,
and especially the great sufferings of our dear Friends in New England, viz:
hard imprisonnments, cruel whippings, cutting off ears,
and banishment if they returned into New England anymore.
I showed him likewise, how they put to death Marmaduke Stevenson, William Robinson,
William Leddra and Mary Dyer,
for no other cause but labouring to turn people from darkness to light,
and from the power of Satan to the living power of God, to his light,
grace and Holy Spirit in their hearts,
and labouring to bring the people from persecution, pride, and every evil work and way,
to live a self-denying, humble life, a life agreeably to the Christianity they professed.
This was the service they were called to, and so deeply suffered for:
from whence I inferred,
there was somewhat of the Spirit of God in man in these days as there was in Daniel,
and many more formerly, which helped and bore them up in their great sufferings.
My father confessed, it was true some suffered for good, and some for evil; and said,
he had now lived to the age of about sixty-five years,
and although he heard us telling of a principle, or light within,
yet he knew not what it was.
I replied very meekly, If he would hear me, I would tell him what it was;
which I did in the following words:
When at any time thou hast been under a temptation to put forth thy hand to steal,
or to lie for advantage, or by provocation to swear, or any evil work or word,
hast thou not found something in thee,
that hath showed thee thou oughtest not to say or do so, which,
if thou hast taken heed to, and not said or done wrong,
hast thou not found great peace and inward comfort in thy mind?
But if thou hast said or done wrong,
hast thou not found great disquietness and trouble of mind?
This is the inward principle, light, or grace,
that God hath placed in man to help and direct him,
which we the people of God called Quakers, do hold agreeably to the Holy Scriptures.
My father smote his hands together, and confessed it was true.

There was one thing worthy of notice,
which may be duly considered by all who read or hear it.
When I mentioned Marmaduke Stevenson, that good man,
and great sufferer in the cause of Christ, my mother said, it was true;
for she lived a servant with Edward Wilberfoss, an honest Quaker in Skipton,
where Marmaduke Stevenson was a day labourer,
about the time he had his call to go to New England.
+++[+++See the account of New England judged, not by man as man,
but by the Spirit of the living God, written by George Bishop.]
If I remember right she said, He was such a man as she never before knew,
for his very countenance was a terror to them,
and he had a great check upon all the family;
if at any time any of the servants had been wild, or any way out of the truth,
if they did but see him, or hear him coming, they were struck with fear,
and were all quiet and still:
if one of the children came into the house where he laboured,
and he would not have it to come, these were his words.
Go thy way; or.
Go home, lest I whip thee; and they were subject and quiet.
This account, I thought had some reach upon my father, however, it much affected my mind.
Oh! that we the professors of the same holy Truth, may so live in it,
as to reign over every wrong thing in ourselves and in others,
especially in our children.

Some little time before the marriage of my mother,
I was brought into the public work of the ministry,
concerning which I had many reasonings, being young, scarcely eighteen years old,
and naturally of a stammering tongue, which I could not overcome;
although I used what endeavours lay in my power as a man,
considering my years and education, all would not do until the Truth helped me.
But after my many conflicts, troubles and temptations, the worst I ever met with,
and the most piercing sorrow I had been in since
I came to the knowledge of the blessed Truth was,
when through reasonings, disobedience,
and an unwillingness to comply with the Lord`'s requirings,
he in displeasure took away from me the comfort of
his holy presence for several months together.
Oh! the tribulations I met with in this condition!
No tongue is able to express,
nor any creature to conceive the depth of the heart-piercing sorrows I was in.
I thought my state was as bad as Jonah`'s, for surely if there be a hell upon earth,
I was in it.
What greater hell can be here to a quickened soul, and an enlightened understanding,
who hath tasted of the goodness of God, and in degree of the powers of the world to come,
than to be deprived thereof, and think they are fallen away from this state?
I could scarcely believe I should ever have repentance granted to me,
or be restored to the love and favour of God, when I found that river of life dried up,
as to me, which did before, not only make me, but even the whole city of God truly glad.
Being left under an apprehension of the Lord`'s displeasure,
and in part a partaker of the terrors of his wrath, oh!
I thought surely the very mountains and the hills, were not sufficient,
if they could have been put into the balance,
to have weighed against my troubles and afflictions they were so great.
But as the Lord by his judgments had brought me in
a good degree from the vice and vanity of this world,
now by his judgments he made me willing to give up to answer his requirings in part,
and in my obedience to him I began to feel some comfort
of love and fellowship of the Spirit of the Lord in myself,
and in his people, who were partakers of the like fellowship.

Now I return to the matter about my being turned out of my father`'s house,
which I mentioned before, but was willing to keep this solemn account entire,
with desires it may be a caution to all,
in whom the Lord is at Work in the same manner not to reason or gainsay as I did,
but to give up freely and cheerfully to the will of God.
When I saw I must turn out,
I thought it expedient to acquaint some worthy Friends with it,
lest any undue reflections should be cast upon the Truth, or Friends, or myself,
that if so, these Friends might be able to contradict them.
So I acquainted Sebastian Ellethorp, and that worthy minister of the Gospel,
Benjamin Padley, two of the chief Friends in Ellington Monthly Meeting;
they came to my father`'s house, and inquired the reasons why I went away;
if my father had any thing against me concerning the business he employed me in;
and whether I was not faithful and diligent in all his affairs he sent me about:
he confessed I was; and thought none could exceed me.
They said, Well then,
what is the reason of that misunderstanding which is between thee and thy son-in-law?
Is it about his going to meetings?
When they understood his reasons, which it was not hard to do,
they expressed pity towards me that I could have no more liberty; and they thought,
as I was so diligent in his business,
if he would give me a little more liberty to go to meetings,
it would be more encouragement to me.
At which he took offence, gave the good men rough language, and asked,
what they had to do with him and his son; and bid them go home,
and mind their own business; which they were troubled at, especially for my sake,
and wondered how I had lived with him so long; for he said in short,
that there was no abiding for me there.
But Sebastian Ellethorp told me, which was mightily to my comfort,
that my father had nothing against me, save concerning the law of my God.
This is the sense, if not the words, of these wise and good men,
which passed between them and my father, as they expressed them to me;
for I was not there when they were together.

Notwithstanding I pleaded with my father to let me stay until I could hear of a place,
he would not, though I was scarcely fit for service, being almost like an anatomy,
as the saying is, so that most who knew me, said, I would pine away in a consumption;
but turn out I must, and did, though I was weak, poor and low in body, mind,
pocket and clothes; for I think I had but twelve pence in my pocket,
and very ordinary clothes upon my back.
Thus I took my solemn leave of the family, with my heart full,
but I kept inward to the Lord, and under Truth`'s government.
Many tears were shed, especially by my poor mother, when I left them;
my father said little, but appeared like one struck with wonder,
to see so much love manifested towards me by the family,
and so much wishing that I might not go away.
I came out upon the great common afore- mentioned, where I had had many solitary walks,
but none like this, for this reason, that I knew not where to go.
I then thought of Abraham, who was called out of Ur in the land of the Chaldeans,
as it is briefly mentioned by Stephen; but this was the difference between us,
he was called, I was forced out.
Although I had many friends, I could not be free to go to them,
unless I had known they had business for me, being not of a forward,
but rather backward and shy disposition.

As I was walking upon the common, the sense of my weak condition,
not knowing whither to go, nor where to lay my head, came over me to that degree,
that it appeared to me as though my way was hedged up on every side,
inwardly and outwardly.
I thought myself like a pelican in the wilderness, or as an owl in the desert,
there appearing to me scarcely a man in all the earth in my condition,
every way considered;
and in the sense and deep consideration of my present wilderness state,
I felt myself under a great oppression of spirit, and my heart seemed full,
like a bottle that wanted vent.
I looked round about me to see that none were near to see my tears, nor hear my cries,
and in the very anguish and bitterness of my soul I poured forth my complaints,
cries and tears, to the Judge of all the earth,
who spoke to me and comforted me in this my deplorable state,
which was worse than Jacob`'s when he lay upon the ground,
and had a stone for his pillow.
He had his near kindred to go to, who he might expect would receive him gladly,
I had none to go to but such as rather reviled me, and gave me hard language;
but the Lord said unto me, as if a man had spoke.
Seek first the kingdom of heaven, and the righteousness thereof,
and all these things that thou standest in need of shall be given unto thee.
I then desired he would be pleased to show me the place I should go to;
and the Lord opened my way, and showed me the house I should go to,
and abide in for a time.
I said, Good is the word of the Lord: I believed,
and it was a great means to stay my mind, and settle it in the Truth,
with full purpose of heart to follow the Lord and obey his requirings,
according to the knowledge and ability given me; yet reasonings attended me.
Soon after I came to the Friend`'s house in South-Cliff, viz: William Allon by name,
I bound myself to him to learn his trade of a weaver, and after I was bound,
I found this good man loved me, and I loved him to the day of his death; he often said,
he was blessed for my sake, and all that appertained to him; for he was very poor,
but increased very considerably after I went to live with him.

Three things stood in my way of answering the Lord`'s
commands as fully as sometimes I should have done;
first, a violent humour fell into one of my legs soon after I was bound apprentice,
which I with others thought was much occasioned by hard usage, heats and colds,
and many surfeits, even from my infancy.
The lameness held me about two years, and it much discouraged and disabled me.
The second hindrance was, my low circumstances in the world, which very few knew of,
because the common fame was, and not without some truth, that I had rich parents.
Few knew the straits I met with; yet my truly religious master,
if he understood any thing was upon my mind to go to visit any meeting or meetings,
would say, take my mare and go thy way, and be not uneasy,
neither about the mare nor business; and do not hasten thyself.
These kindnesses made me often thoughtful how I might return suitable acknowledgments,
and be duly grateful for the same.
I was diligent in my master`'s business, not serving him with eye service,
but faithfully; believing it good and acceptable in the sight of God,
and I had great peace in it; my master never found fault with me for doing too little,
but often for doing too much, and would sometimes say,
I think thou wilt cleave to the beam;
come off and let us walk into the fields and see how things are there.
The healing of my leg, I attribute to the great and good providence of God;
for in a short time after I gave up freely and cheerfully to answer the Lord`'s requirings,
the Lord healed me of my lameness.

As to the third hindrance, when I cried unto him,
that he would also heal my tongue of its stammering,
believing that the Lord was able to take away this impediment,
as he was to stop the violence of the humour in my body:
notwithstanding several men had given their advice, and had showed their skill,
which all proved ineffectual, until I came to believe in Jesus Christ,
and to press through all to him, and to touch the skirt,
or lowest appearance of his blessed truth and power,
in which I found true healing virtue to my soul, and also to my body, and to my tongue,
even to my admiration;
so that I did not only speak plain in the testimony the Lord gave me to bear,
but also spoke plain in my common intercourse with men.

I was likewise in these days under the dispensation of openings and visions,
and thought myself as it were upon Mount Pisgah, and saw into the holy land,
into things relating to God and his heavenly kingdom,
and into his work and way of bringing man out of the fall and alienation,
to himself again, and into a heavenly state in Christ,
as man yields true obedience to the leadings and operation
of his blessed grace and Holy Spirit in the heart.
But under such dispensations it is of absolute necessity,
that man be brought into true self-denial, into a depending frame of mind,
and resignation of his will to the will of God, and a daily sitting as in the dust,
as to the motions and workings of the creature; for all that is of man`'s working,
does but hinder the spiritual work of God in the heart.
And we must come truly to know all fleshly motions,
and the workings in man`'s own will and spirit, to be silenced,
in order to hear the voice of God, which is a still small voice,
and not to be heard in the noise and hurries of the world;
neither when the mind is busied with things agreeable
to our own corrupt wills and depraved nature.

Although I had clear sights into many heavenly things,
and also at times had comfortable enjoyments of the living presence of God,
yet I wanted to be more established in the unchangeable Truth,
of which I had some comfortable feeling.
In crying to the Lord, I found he inclined unto me, and, as David said,
he heard my cries, and plucked my feet out of the mire and clay,
and set them upon a rock, that was higher than I, and in part, established my goings,
and put a new song into my mouth,
even high praises unto the Lord for all his tender mercies to me in these trying times.
And now being more crucified to the world, and the spirit of it,
I witnessed a more constant indwelling of his heavenly power and living presence,
light and grace; I came to be brought into stillness,
and it was most agreeable to my condition to keep much in silence,
and wait upon the Lord for the renewing of strength,
that thereby I might surmount all temptations and trials with which I might be tried,
which were not a few.

These things are worthy of commemoration,
and proved great confirmations to me in the Truth,
in these days of my tribulations and great trials: read and believe, thou that canst,
for they are faithful and true sayings.
After the Lord had healed me, he sent me forth in the work of the ministry,
and the first journey I took was southward into Lincolnshire, Nottinghamshire,
and through Coventry, and so to Warwick, to see William Dewsbury.
One thing is remarkable;
in giving him an account of the particular towns and places I had passed through,
in answer to his inquiry what way I came, I mentioned Coventry,
which was the last and the worst; for some of the rude people flung stones at me,
with great violence, as I was speaking in the meeting,
so that had the Lord suffered them to hit me, they must have spoiled me;
but my faith in the Lord, and the strength of the Truth,
bore up my mind above the fear of what wicked men could do to me.
After William had heard my account, he fixed his eyes on me, and said,
thou must go back again to Coventry.
I appeared unwilling, for two reasons: first,
because I thought I had cleared myself of that people: secondly,
I thought it not safe to run into the danger of suffering,
unless I was satisfied the Lord required it of me.
But William was positive, and said I must go, for there was a service for me to do there.
Upon a deliberate consideration of the matter,
and seeking to the Lord to know his will in it, I found my way clear to go,
and I had some service and good satisfaction,
and left Friends nearer to one another than when I first met with them;
for there had been a misunderstanding amongst some Friends in that city.
I came from thence to Tamworth, where there was a difference,
especially between two Friends;
both of whom had made some considerable figure among Friends.
I felt it upon me to go to one of them, and warn him of the spirit of prejudice and envy,
for if he gave way to it, it would eat out his love to Friends and Truth,
and he would decline meetings and come to naught, and turn his back on the Truth;
which came to be fulfilled, as I afterwards heard; for he became a loose man,
and listed himself to be a soldier.
I was zealous for the name of the Lord,
and had a great concern upon my mind for the promulgation of the Truth,
and where I met with loose professors of the Truth, it was a great exercise to me.

When I returned home from this, and indeed from all my journeys,
I took care so far as my weak body was capable, to fall into business,
and not to loiter away my time, neither abroad nor at home.
My weak constitution would not well bear the weaving trade,
therefore I left it much against my will; but I wrought upon clock and watch work,
and many other things, which supplied my necessities,
the Lord allowing me as much time at home as put me in a condition fit for travelling,
and then I was inclined to go to visit Friends.
Many things I omit, because I am not willing to swell my account too much.
I travelled through most parts of England four times,
and twice through most parts of Wales,
between the twentieth and twenty-eighth year of my age.

After the Lord had opened my heart, and I came in part to understand the Holy Scriptures,
and to have a feeling of that Holy Spirit in which the holy penmen wrote them,
and a sympathy with the spirits and exercises of the righteous therein mentioned,
I took great delight in reading them, and having a good memory,
could thereby the better deal with priests, and with professors.
I had many disputes and reasonings with persons of several denominations,
both in Yorkshire and other parts in my travels, so that through these disputes,
and much reading, my mind was rather too much in the letter,
and not altogether so much in spirit and in power, as it should have been;
for which I met with a gentle caution from the Lord, which was thus:
I heard a voice from the Lord, as plain as if one had spoken to my outward ear,
"`the fowls of the air lodge in the branches.`"
This being repeated to me,
I besought the Lord to show me what was the meaning of that voice which I heard;
and the Lord, the mighty God, showed me, in his condescending love, that the Scriptures,
even all of them which were written as the holy men were moved of the Holy Ghost,
sprung from the living root; yet those who rested only in the letter,
and came not to be acquainted with, and live in, and minister from the same Holy Spirit,
are outward, dead, dry, airy, and foolish.
This gentle check was of great service to me;
not so as to make me decline reading the Scriptures,
but that I should not have overmuch dependency on them;
and to caution me against the neglect of waiting for the help of the Holy Spirit,
the root and pure spring of the right and living ministry,
which reaches the heart and carries the true evidence with it to the believers,
that it is of God;
which that of the letter cannot do of itself I tenderly
desire that all concerned in this great work of the ministry,
may not be ministers of the letter only, but of the spirit also,
and may speak in the demonstration of the spirit and of power.
Let him that speaketh, speak as the oracle of God, and he that ministereth,
do it as of the ability that God giveth.
This is the last and lasting ministry, which is after the order of Melchisedeck,
and not after the order of Aaron, but in Jesus Christ, the high priest, the one offering,
which makes perfect forever all who come to him through the drawings of the Father.
He is the one Lord, and there is but one true faith in him,
and but one true and saving baptism into him, or into the likeness of his death;
that as Christ died for sin, we may truly die to sin;
and as he was raised by the glory of the Father, so we may walk in newness of life.
He is the heavenly High Priest, holy, harmless, separate from sinners; who was tempted,
and knows how to succour such as are tempted; he is the Advocate with the Father,
the Propitiation for the sins of all, the true Guide and Comforter,
the Leader of them into all truth who obey and follow him;
although to the world a Reprover and a swift Witness
against all ungodliness and unrighteousness of men.

My writing thus, from this gentle check, concerning the fowls and the branches,
is not with the least intention either to lessen the Holy Scriptures,
or discourage any from reading them;
for I would have all true Christians encouraged to be more conversant in them;
yet with this advice, kind reader, from thy well-wisher and true friend, to breathe to,
and truly seek after the Lord for a measure of his holy and blessed Spirit,
the only key and best expositor to open and truly expound them to thee,
as by the same Holy Spirit,
thy mind and understanding comes to be fitted and enlightened.
Indeed,
the whole vessel must be brought into a preparation to hold the heavenly treasure,
and not to mix the pure with the corrupt and impure: for without this enlightening,
preparing, opening, and sanctifying gift of God`'s holy grace and spirit,
man can neither know the heavenly power of God, nor yet the Holy Scriptures aright,
as he ought to know them.
And for this reason it hath seemed good to God to hide these things from the learned,
wise, and prudent of this world, that they should not pry into,
nor find out the mysteries contained therein, unless they are sanctified,
and called of God thereto; as no man knows the things of a man,
save the spirit of a man that is in him;
likewise the things of God are not perceivable by man,
without the help of the Holy Spirit of God in man.

Thus the Lord opened to me the true meaning of the parable of the mustard-seed,
in this the time of my infancy as to the ministry,
with which he sent me forth into the world, that my faith might stand in the Lord alone,
the author and finisher, as well as giver of the true and saving faith,
even that faith which works by love, and gives victory over the world.
It was by and through the power and efficacy of true faith, which is the gift of God,
that the elders in former ages obtained, and now obtain a good report;
it was through this gift, that worthy Abel with his offering was accepted of God,
although he was envied of his evil-minded brother Cain, and also by him slain.
The ever memorable Enoch, through the virtue of this holy gift, walked with God,
as himself gave witness that Enoch pleased him;
he walked so in faith and obedience even to the end,
that he died not as men in common do, but was translated,
or changed in a peculiar manner.
Come, read, thou that canst, and understand,
thou that art redeemed out of the power of the first nature, and hast overcome the flesh,
the world and the devil, in a great measure;
for thou knowest that it is by the operation of this gift that
the dead in old Adam are raised to a new life and way of living,
in the new man, and through this heavenly Adam,
that is known to these to be a quickening spirit, agreeably to holy writ.
Through faith the violence of fire was quenched, the mouths of lions stopped,
the sword turned backward, and armies put to flight,
even such as were aliens or strangers,
who outwardly fought against the Lord`'s people which sets before us, as in a glass,
how and what we are to overcome in this Gospel-day,
in which we are not to fight with men, but with our lusts, and to overcome sin and Satan;
which is as great a victory as he obtained who overcame the rampant lions,
that had dominion over the wicked,
as sin and Satan have power and dominion over the wicked and ungodly to this day.

Consider now in time, thou that readest these lines,
whether Christ or antichrist doth predominate in thee;
whether grace or sin most abound in thy mortal body; whether the- Spirit of Truth,
that leads into all truth, or the spirit of error, that leads into all error and untruth,
is the most prevalent, and hath the greatest place in thy heart.
For to him to whom thou art the most subject, and yields thy members servants,
his servant thou art; and to him to whom thou givest way and subjects thyself,
his servant thou wilt altogether come to be in time,
and the wages due to his servants thou shalt have given to thee at the end of thy work.
Therefore consider in duo time, while the day of thy visitation is continued unto thee,
and the Lord is following and calling thee by his secret checks and reproofs,
by which he disquiets thy mind,
that although thou mayest take some pleasure in vanity and wrong ways,
when thou canst get over the just witness of God in thy own soul,
yet while it strives with thee to convert and gather
thee out of earthly and fading pleasures,
to have thy mind set upon heavenly things and take pleasure in them,
thou wilt have no solid comfort in all thy lower enjoyments,
but condemnation and anguish of soul will attend thee,
until thou either gets over the witness, or leaves the evil.
This is the experience of the Lord`'s people,
who have been acquainted with the true inward warfare,
and also with the saints`' victory.
Learn to follow Christ by the footsteps of the flocks of his companions;
although it be through great tribulations,
it is the way to have thy garments washed and made white
in the mystical blood of the immaculate Lamb of God.
This is he, as John the Baptist said, that taketh away the sins of the world.
Happy is every one that truly putteth on his lamb-like nature, his humility,
righteousness, and purity, and is covered with his Holy Spirit,
and lives and walks in and under the influence and conduct thereof to the end of time.

When I had travelled much of the time between my going forth,
which was from about the nineteenth to the twenty-seventh year of my age;
finding some little respite from the weight of that service,
I inclined to settle a little closer to business,
but had little to begin any calling with.
I had been a sojourner some time at Whitby, Scarborough, and Bridlington;
but upon seeking to the Lord to know what place I might now settle in,
though my great inclination was for Whitby, yet it sounded in my ear, Bridlington,
Bridlington is the place to settle in; and in the cross I repaired thither,
and settled for some time, keeping a little shop, and mending clocks and watches,
as I had done for several years past at times.
My settling there was of good service, for the Lord began to work mightily,
especially amongst the young Friends,
so that in a few years many had their mouths opened in testimony for the Lord,
and a fine spring of heavenly ministry was in that Monthly Meeting,
the like I have not known in the same bounds, for it is but a small Monthly Meeting,
and hath been so ever since I knew it.
Truth did mightily prosper, and Friends grew go in the ministry,
that it became a proverb, that Bridlington was become a school of prophets.
This mighty work of the Lord, in these days,
is worthy to be chronicled and remembered among his worthy and noble acts;
we had many heavenly and good meetings,
praised and renowned be the worthy name of the Lord, now and forever.

We had but little discipline when I first settled in that place,
but afterwards many Friends`' hearts were stirred up in a holy zeal for the Lord,
to promote meetings for worship, and also for good discipline in the church,
for they began to see a necessity of coming up more
in the practice of this very needful work.
Although some said, They could see no need of such close order and discipline,
I found it to be my way in the truth to bear with such,
if they were not irregular in their conversations; but if they were disorderly,
we dealt with them as the Lord opened our way in the wisdom of truth;
and thus bearing with the indifference of some on the one hand,
and encouraging the faithful and zealous on the other, way was made,
beyond my expectation, for the spreading of the truth, its testimony,
and the discipline thereof in those parts.

I had now travelled and laboured much in the Lord`'s
work at home and abroad for about ten years,
but had not in all that time found my way clear to marry,
although not without some likely opportunity,
and with such as were a great deal richer than she was whom I did marry.
But I was afraid in this weighty affair to miss my way,
knowing the great difference there is between those who only profess,
and they who possess the truth; those who are only in the first and unregenerated state,
strictly speaking, but the sons and daughters of men, and such who are born again,
not of flesh and blood,
but of that incorruptible Seed and living word of God which leads into a lively hope,
and brings forth a new and heavenly birth in man,
that takes delight to please and obey the Lord in all things, and so become sons,
or children of God, in a more spiritual and nearer relation than that of creation only;
that is in and through this great work of renovation, and being born again.
As such live up to that Holy Seed and regenerating principle,
and as the same doth predominate and rule in man, in this state man cannot sin,
as the apostle said, with this reason annexed, because His Seed (to wit,
the Seed of God) remaineth in him.
Thus walking in the light, and living in the Seed, Grace, or Holy Spirit,
for although the terms of it differ, the virtue and nature of it are indivisible;
such come to be gathered to walk with, and truly love Christ, the bridegroom of the soul,
and are brought into a greater nearness, truer sympathy, and unity of spirit,
than the world knows of I believe, and therefore truly speak it,
the Lord gave me such a wife as really feared him, loved truth and righteousness,
and all such as she thought loved, and especially such as lived in the truth;
her name was Priscilla Canaby, daughter of James Canaby.
She was descended of an honest family in the eastern part of Yorkshire,
the only child her parents left; they gave her a commendable education,
though they did not leave her any great portion; she was under the care of her uncle,
Charles Canaby, of Bridlington, an honest Friend,
who left something behind him in manuscript concerning his convincement of the Truth,
and sufferings for the same; he was convinced early, lived to a great age,
and was a man of great service in those parts where he lived.

I was in the twenty-eighth year of my age when I married my wife,
who was a woman of an excellent temper, very affectionate, sober and prudent,
loved retirement much, and waiting upon the Lord, and the enjoyment of his presence,
especially with the Lord`'s people,
that they might also be made partakers with her of the like favour;
this was as her crown and kingdom while in this world, even from her childhood;
and to see Friends prosper in the truth was matter of great rejoicing to her.
When we had been married scarcely three years,
the Lord raised her up to bear a public testimony amongst Friends,
which was very comfortable to them; she had also the Spirit of grace and supplication,
measurably poured upon her,
so that many with me did believe she had access to the throne of God,
and to that river which maketh truly glad the city of God.
She always freely gave me up to answer the service I believed the Lord called for of me.
She was taken from me when we had been married about five years,
in the twenty-eighth year of her age, and died in a sweet frame of mind,
and was sensible to the last.
Her last words were, "`He is come, he is come, whom my soul loves;
and my soul rejoices in God my Saviour,
and my spirit magnifies him;`" and so passed away like a lamb,
I believe into a mansion of glory,
where her innocent soul will forever sing hallelujah to the Lord God and the Lamb,
who is worthy of glory, honour, salvation, and strength, now and forever.

I might enlarge much upon her virtue and worthiness, but in this, as in other matters,
it is my desire to avoid prolixity,
yet I would notice the most remarkable occurrences that
have happened to me in the course of my pilgrimage.
I have been much pressed by some of my faithful brethren, and I believe it to be my duty,
to leave some accounts for the encouragement and
comfort of others in the way and work of the Lord.
One thing is worthy here to be inserted, which had an astonishing effect upon my mind,
which was thus:

As I was walking in a plain field in the forepart of the day, not far from the sea,
betwixt Bridlington and Broynton, my soul was in a deep concern,
and at that time exercised in meditation on the things of God,
and also in fervent prayer to him for preservation from every hurtful thing:
my mind was then brought into a heavenly frame, I neither saw cloud over my mind,
nor yet any in the firmament, for it appeared to me a morning without clouds,
though I had passed under many.
Soon after my mind was brought into this heavenly frame,
and as it were swallowed up in the heavenly and internal presence of the Lord,
I thought a bright cloud covered me, or caught me up into it: whether I was standing,
walking, or set upon the ground, or carried up into the cloud in the body,
or out of the body, I know not to this day; yet fear and reverence with bowing of soul,
did possess me before the great Majesty,
at the glory of whose countenance men and angels fled and gave way,
and could not steadfastly behold the brightness and
glory of the countenance of the Son of tho Highest,
with the mighty God and Father, which are one in power, greatness, goodness, and glory,
who was before all things, made all things,
and upholds and fills all things that are good, with that which is truly good,
or at least is for a good end.
Read this mystery, thou that canst,
and learn to fear him that hath power over both soul and body,
to kill and to cast into hell, for at one time or another he will make thee fear him,
when he brings thy sins to judgment, whether it be now or hereafter.
The time hath been, is, or will be, in which the Lord, the Judge of both quick and dead,
hath, doth, or will plead with thee and all flesh, as in the valley of Jehoshaphat;
therefore beware, lest thou make him wroth, as he was upon mount Perlzim,
but be thou subject to the Lord, as faithful Moses was upon Mount Horeb,
or the Mount of God, when he obeyed his voice, and put off his shoes; do thou obey,
if it be to the putting away of the glory and wisdom of Egypt, or learning,
or what else is required of thee.
Oh, then thou art in the way to further service, and wilt be enabled,
as thou continuest faithful, to go through all to God`'s glory,
and thy unspeakable peace in the end.

Now as to the last part of the vision,
when I was swallowed up in the luminous presence of Him that is first and last,
the Alpha and Omega, I heard a voice,
very intelligible to that sensation I had then given me, saying,
"`Dost thou see how pride and wickedness abound in the nation?`"
I answered in much fear.
"`Lord, I do see it:`" the next words which I heard in the voice and in the cloud were,
"`The people are too many, I will thin them, I will thin them, I will thin them.`"
I desired of the Lord to show me whether it was his
mind I should publish this in any part of the nation?
The south was set before, with this caution, "`Where this is opened to thee in my power,
there speak of it, and not otherwise.`"
I gave up to answer the heavenly vision, and visited most parts of the southern counties,
as also the northern parts, and Scotland;
and where the Lord opened my mouth to speak of what I had heard, as before,
by way of prophecy, I gave up, but did not so much insist upon that matter,
as to suffer it to be a means to mislead me from that work
of the ministry I was chiefly concerned in.
I would that all, who are concerned in the like manner,
may be cautious in this great affair, and look well to the rise and original,
whence they receive this gift, and how; and also what frame of mind they are in,
that nothing of the warmth of their own spirits be set to work,
either by the sight of the eye, hearing or reading,
but that the mind may be redeemed from all workings
which arise from these and the like grounds,
and purely purged, and fitted to receive this gift of prophecy:
and also be sure to be very careful to be guidable in the gift,
or otherwise thou mayest miss, as to time and place, etc.
I intend not to dwell long upon it,
as there are other services included in this of prophecy, as edification and comfort,
etc., but what I have been upon relates to foretelling something that is to come; and,
as a worthy elder once said to me, when I was young in the ministry,
"`It is a great thing to know what, where,
and when;`" and I have found it true to this day.
Learn of Him that is meek and low of heart, and be not discouraged,
but persevere in faith and sincerity, and look not too much at the difficulty,
but look over all to him who hath called thee,
and in some measure has revealed his Son through the Spirit in thee.
Although I know, from some experience,
what it is to be exercised in the matter of prophecy,
for in the journey touched of before, I was concerned to tell Friends at Kinmuck,
in Scotland, especially, that the Lord would take many of them away:
which in a short time came to pass, for many died before that time twelvemonth,
it being a time of scarcity of corn, and it was thought many died for want of bread,
the year ensuing my being there.
I had good service for the Lord, and great satisfaction in these my long travels,
as I had in the like before, in divers of which some were convinced of the Truth.

At Cromer, in Norfolk, one Elizabeth Horry, when my mouth was opened, despised my youth,
as she confessed afterwards; but what I had to say so reached her condition,
that she shed many tears upon her fine silks, and before the meeting broke up, confessed,
so that all might hear, in these words,
"`All that ever I have done hath been told me this day,
and this is the everlasting truth.`"
As I passed along from that meeting, not far from Cromer, with some other Friends,
it rose in my heart to say aloud, so that a man who was watering his horse might hear,
looking and pointing my hand towards him--That man will be a Friend before he dies; and,
as he owned after, he was so struck with it,
that he had no rest till he came among Friends, though he was then afar off,
but he came to be a serviceable man among us,
and his wife was also convinced of the truth, and was a serviceable woman.
Samuel Hunt, of Nottingham, was first reached at Leicester,
by the testimony I had given me to bear in that meeting at that time,
as he acknowledged afterwards; but I always gave God the glory,
and laid the creature as in the dust, that man might not be too much accounted of.

After my hearing the voice, as before mentioned, I had many deep and heavenly openings,
some of which it may not be amiss to mention here,
inasmuch as I had now a more clear sight into a translated state than ever I had before.
I came, through a Divine sense and participation, to have great sympathy and dear unity,
not only with the ever memorable Enoch,
whose walking was such that the Lord gave testimony that he pleased him;
the ground of which witness was from hence, that he lived near to, and loved God,
and walked in the ways of virtue, and abhorred vice: but also with the apostle,
having this seal, that God knoweth who are his:
and with some other of the servants of Christ in former ages who could say,
as some now can say, from true experience,
that the Spirit of the Lord beareth witness with our spirits, that we are his, to wit,
the Lord`'s children, so long as we do well; which last words are of large extent,
to do well, think well, speak well, and believe well; for he that hath no faith,
or that believes ill, cannot do well.
He that eats, drinks, or wears that which he knows he ought not, doth not well;
but what is done well, is done in a pure mind and clean conscience,
for so is true faith held, and all acceptable work to God performed.

I had great openings into the removal of Moses, and taking up of Elijah,
that great and worthy prophet, from the earth into heaven,
and I have seen things not fit to be uttered; neither can the world yet believe them.
I saw far into the mystery of the transfiguration of Christ,
and the appearance of Moses and Elias with him upon the mount;
and the voice which was heard from the excellent glory, "`This is my beloved Son,
hear him;`" not Moses nor Elias in comparison of him, for the law pointed to him,
and was as a school-master to bring to him.
The holy prophets foresaw and prophesied of his coming, and John the Baptist saw Christ,
and baptized him, and bore witness of him as the Light, and said,
"`Behold the Lamb of God, that taketh away the sin of the world;`" he also said,
"`He is the bridegroom that hath the bride,`" the church.
He spoke of his own decrease, and unworthiness in comparison of Christ,
though called by Christ himself, as great a prophet as was ever born of a woman.
He was also called Elias, which must first come and is already come; in respect of power,
knowledge, boldness, and faithfulness, he was as Elias,
yet the least in the kingdom of Christ was greater than he,
because the power and glorious kingdom and Gospel dispensation
was not fully brought in and restored to Israel,
or those who should believe in him until his ascension.
But now these great agents all passed away, with their figurative, prophetical,
and elementary dispensations, and gave place to the Son and Heir of all things,
the Messiah, the Great Prophet, Bishop, Shepherd, King, and Law-giver.

Read these things, and learn truly to understand how Moses past away,
and Elias past away, and Christ is left,
who is able alone to perfect the work of man`'s redemption,
who trod the wine-press alone, and amongst all the sons of men,
none were with him or helped him.
He came who was the anti-type of all types gone before: he, Christ,
is come to remove the covenant made before,
because of the weakness and imperfection thereof;
which covenant made not the comers thereto perfect,
but the better hope brought in by Christ did.
This covenant is abundantly more excellent and established
upon better promises than that was or could be,
by the blood of bulls, goats, and the ashes of an heifer, which reached the outside only.
But in the second or new covenant,
there is the blood which sprinkleth the heart from an evil conscience,
so that such may be fitted and qualified to serve the living God,
not in the works of the old covenant, but in the newness of the Holy Spirit.
This is he that, as to his divinity and eternity, was before the hills were settled,
and the seas and foundations were made, that took delight to dwell with the sons of men,
or in the habitable parts of the earth.
As he is a spirit, or word uncreated, he dwelt measurably in Abel, Seth, Enoch, and Noah,
before the flood;
for by his Spirit God strove with the old world to reclaim them from their wickedness,
when it was great.
It was by this Spirit Noah was made a preacher of righteousness,
and instructed how to build the ark.
This is he who was with Shem and Japheth, Abraham, Isaac, Jacob, and Joseph,
and all the faithful fathers after the flood, the foundation of all the righteous,
prophets, apostles, and martyrs, such as loved and believed in him,
and suffered for his name`'s sake, and the testimony which they held.
This is he that despised the glory of this world,
and is lifted up as a standard to the people, and an ensign to the nations;
unto him shall the Gentiles seek, and his rest shall be glorious.
He hath lifted up a greater rod than that of Moses, sometimes called the rod of iron,
by which he hath, and, I believe will, break to pieces many people as a potter`'s vessel,
when the sin and iniquity of the people is come to the height.
It was he that turned the waters of Egypt into blood;
it was he that slew the first-born throughout all the land of Egypt:
he overthrew the Egyptians, and brought forth Israel by a strong hand,
and an outstretched arm.
After he had marked the dwellings of his people,
and spared them in the time of this great slaughter,
which was executed both upon man and beast, to wit, the first-born in Egypt,
then he became Israel`'s passover.
These things that were done typically and in an outward way,
read inwardly and in thine own experience, that thou mayest say, and that truly,
Christ is my passover, after he hath mitigated thy sore bondage,
and in degree given thee faith in his great name,
and caused thee to love him and made thee willing to follow him,
although it be through the sea of troubles, and sometimes as through the wilderness.
Here is an eating of the heavenly passover, or paschal Lamb,
under the influence of the pure love of God, that is spread over the soul like a canopy,
or banner; here is the heavenly manna, the true body to feed on,
that yields true nourishment and solid comfort to thy soul,
in thy travel towards the heavenly country;
here the substance of the scape goat is known, that beareth away the sins of the people,
for he bore our iniquities, and through his stripes we were healed.
On his part there wants nothing, but on man`'s, faith in and obedience to Christ.
He is the substance or antitype of the brazen serpent,
which was lifted up in the wilderness to cure the people`'s ailments,
occasioned by the serpents; he is the advocate with the Father, as John said,
to encourage little children in that time,
which I think may very well be applied to all in
that state until time here shall be no more.
Happy is every one that heareth, obeyeth, and reverenceth the Son and Heir of all things,
in his spiritual appearance in the heart,
where he speaks to the conditions of the children of men, as never man spoke,
and to much better purpose than ever man could do.
This is he that spoke to the fathers by the prophets,
who in these times doth speak to us in or by his Spirit;
so take heed to his spiritual appearance in the heart,
for there must the work of our salvation be perfected, after sin is purged out,
and the guilt thereof taken away.
To such death is easy, where sin, the sting of death, is taken away,
having a part in Christ, the firstborn of many brethren,
the resurrection from the dead--a part in Him that
is the resurrection indeed and the life;
over such the second death,
which is a perpetual separation from the heavenly presence of God,
and the company of holy angels, shall have no power.
I now leave this digression, and return to the historical part.

In my young years, I was very much afflicted upon taking cold, with a sore throat,
that I could scarcely speak so as to be heard,
and had much trouble at times to swallow any thing which nature required.
In a journey northward, in Truth`'s service, coming to Hawkshead,
and sitting in the meeting under no small exercise with the trouble aforesaid,
not without some reasonings and conflicts of spirit, having left all, as I believed,
to do what the Lord required of me, and yet I apprehended myself,
by means of this affliction, not likely to be of any service; after some reasonings,
and a fervent seeking to the Lord to know the cause,
and to bring my mind to a true resignation to the will of God in this,
and in all the trials he might see good in his wisdom to exercise me in;
I had not been long brought into this resigned state
to be and do what the Lord would have me do,
but oh!
I felt of the virtue of Christ as a sweet and living spring, by which I was healed.
I was, and am to this day, when I remember the Lord`'s kind dealings with me,
very thankful to him.

It has been frequently observable, that the Lord leads his servants through many states,
that having the experience thereof,
they may be the more capable of helping others in the like straits;
it is an excellent thing to love and truly believe in Jesus Christ,
and keep self down as in the dust forever.
