== Chapter IV.

[.chapter-subtitle--blurb]
Travels to Barbados, Jamaica, and Return to England

Now I may say something of our affairs upon the sea in this voyage.
When Captain Salter had taken us in passengers at Philadelphia for Barbados,
it being a time of war, and people somewhat afraid of shipping goods, he said,
he was to have two honest Quakers passengers,
and he did not fear being taken by privateers, or pirates.
I was troubled at his confidence in us, and told him so,
and that it was much if the Lord did not suffer us to be taken,
that he might see men were not to be depended upon,
but that we ought to depend upon the Lord alone for protection and deliverance; however,
in much less time than we expected, goods came, and we were loaded and gone.
We had rough weather before we came to Barbados;
especially about the tropic of Cancer we had very high winds,
and I was extremely sea-sick, and so was my companion, and I could eat little,
but was treated with remarkable civilities by the captain.
About that latitude there are fish not unlike herring, which fly from wave to wave,
and by dipping their fins or wings in the water, they will fly a great way,
especially when they are chased by fishes of prey,
and almost every morning there were some of those fish on the ship`'s deck.
The captain often said, as his manner was, Mr. Richardson, these are sent for you,
or for your breakfast, and seeing it is so, I will dress them myself,
for I know my cook is so greasy you can hardly eat of his cookery.
This was very true, and therefore he would wash his hands,
and lay a clean napkin on his arm,
and tell me he would dress me my breakfast in the best fashion he could.
I asked him why he would put himself to so much trouble;
he said he never waited on a man in all his life with so much pleasure,
and if I were going into any country where he was going,
I should not pay any thing for my passage; so much respect he showed me.

It happened in the course of this voyage, when we were within a few leagues of Barbados,
one morning early, as soon as day appeared, he that was aloft,
upon the watch to look out, as the manner of mariners is,
especially in the time of wars and danger, espied a ship,
which he and the rest of our most knowing men supposed to be a Turkish frigate,
of considerable strength; however, it was a great vessel, and appeared to have many guns;
and when we first saw her, she seemed to be within gun shot.
But oh, what a surprise and fright our ship`'s crew were in!
I had not often seen the like.
Our vessel being deeply loaded, although a good sailer,
was less than that which chased us,
and to run for it appeared the only way for us to escape,
hauling as close to the wind as we could, to keep the sails full.
The vessel being stiff with its great burden, endured sail well,
and they crowded so much,
that I told them I feared they would bring the rigging by the board.
Thus we laboured until noon,
and then our captain having lost all his confidence in the Quakers, said,
we shall be taken, for the ship has gained upon us for several hours;
we have done what we can, and are all spent.
I walked upon the main deck under no small concern of mind, and Truth rose,
and I found it open in the Truth, that we should not be taken; the captain said,
binding it with some asseverations.
We shall certainly be taken.
I said, No, we shall not, unless by our mismanagement.
Alas, said he, you are such a man as I never met with.
Do you not see the frigate, or Salleeman, for so he called her,
is just going to fire a broadside at us, opening the gun-ports,
and laying the ship broadside upon us, and levelling at her as well as they can?
Although our captain was a stout man, he appeared very ghostly and dead-hearted,
and said to me in a tone which bespoke both affliction and trouble,
Go into my cabin, or somewhere under the deck, for they will fire immediately;
and where I walked I could hardly escape either the shot or the rigging falling upon me.
I said, they will not fire; and desired him to be easy,
for we should come to no damage by that ship.
Well then, he asked, what they should do, for the enemy was just upon us.
I said I would fetch them a bottle or two, or more of my best brandy,
and they should take as much as might do them good, but have a care of more,
and ply away awhile, and you will see they will fall back and we shall leave them.
The captain said, although there was no human probability of escaping, yet, for my sake,
they would try; and to work they went.
I think I never saw men on board of any ship work like them for some hours,
and we soon perceived that we outsailed them, and by the time it began to be dark,
we had left them considerably.

Now all fire and light was forbidden, except what could not be avoided, and all noise,
and a council was held, to consult what way to steer,
whether the nearest or most common way for the island, or about;
for it was reasonable to conclude the adversary would waylay us, if he could,
before we came to the island.
The captain said, what I said in the case should be done; after some deliberation,
I told him, I was most easy in steering the nearest course, which we did,
and saw our adversary no more.

We came to the island next day in much joy, that we had escaped so imminent a danger,
but I was very ill of a fever when I landed,
which had been growing upon me for several days, this being the sixth day of the week,
and 18th of the tenth month.
I was so poorly, that several thought I must die;
but I stood resigned in the will of God, whether to die or live.
The first-day being come, I went to the meeting, though with great difficulty,
being very weak, where I sat under more than usual exercise, reasonings,
and conflict of spirit for some time, about my present condition, which was weak and low,
and in my own apprehension, unlikely to be of any service.
Notwithstanding all the troubles and hazards of the sea, and robbers,
and other jeopardies in coming here, I was now disabled and laid by as useless.
These things occasioned me to consider,
whether I had not missed my way in something or other.
Many particulars were brought to my mind,
whether I had discharged myself faithfully where I had been.
When I looked back,
and took a view of my travels and services in the
work of the ministry and discipline of the church,
my conduct and whole conversation,
I saw nothing but that I was clear of the blood of all men;
as also clear and well satisfied both as to the time and my coming to this island.
There appeared yet two things in my way; first, if this place should be my grave,
such as might not watch over me with the best eye may say,
if he had gone at the Lord`'s command, no doubt he would have brought him back again;
and secondly, as I had two little children in England, if I finished my course here,
they would be left fatherless and motherless.
And I said before the Lord, let not my end bring dishonour to thy great name,
nor any blemish to the Truth which I have loved and laboured for the promotion of,
from my childhood.

When I had thus appealed to the Lord, I felt great quietness and resignation of mind.
As I sat, a Friend well thought of by several, began to speak in the meeting,
and it opened in my mind,
that he was not wholly redeemed from having some thoughts
that elementary water had not yet ended its service;
I mean in point of dipping.
I would have shut it out, for the man appeared a wise, zealous man;
and being altogether a stranger, I could not remember that I had heard his name,
yet the matter continued, and I thought, for my own satisfaction,
I might ask him the question.
If he was a right spirited Friend, he would not be hurt; if he was not,
he stood in need of help,
or at least it was high time for Friends to have a more perfect knowledge of him.

During my sitting, as before, under much weakness of body, yet quiet in mind,
the living virtue or heavenly power of Christ sprung
up in my inward man like healing oil,
which so effectually helped me every way, that I could say feelingly and experimentally,
miracles are not ceased.
I was raised beyond my own expectation, and all others who knew my weak state,
to give testimony to the glorious coming and manifestation of Christ in power,
and spirit, for the help and salvation of all the children of men who receive,
believe in, and obey his spiritual reproofs and heavenly calls in the soul,
without any lessening to his humanity.
Great cause have I, with all the living, to love, honour,
and reverence the great and mighty name of Him who hath helped and healed,
by sending his eternal word of living power into our hearts.

Returning with other Friends to my quarters from this good meeting,
not to be forgotten by me, the before-mentioned Friend came to see me.
Having, as I told him, a desire to speak privately with him, he replied,
there were none there but his good friends, and I might speak my mind.
I told him, what I had to say related chiefly to himself,
and in such a matter as he might not be willing to have exposed; but he would not hear,
and said I might speak it there.
I desired he would not take offence at what I had to say,
for I did suppose it to be a secret to all there but himself.
Then I said, the matter is, when thou wast speaking in the meeting,
it sounded in the ear of my soul as if one had said, this man, meaning thee,
is not wholly redeemed out of a belief in John`'s ministration of water,
as not having done its work.
Now the matter is before thee, thou knowest whether what I received be true or false:
in the first place I inquire for my own satisfaction.
His answer, if it may be called one, was as follows: he said, The disciples of Christ,
when they baptized with water,
knew that it was the mind of their great Master that they should so baptize.
I said,
I know not that any of the apostles did ever say so much as thou wouldest insinuate;
for both by what Peter and Paul say, it appears very natural to be the mind of Christ,
only to condescend to so much as was done by the apostles in that of water,
because of the people`'s weakness;
and no question but the Jews were very much settled in the belief
of John the Baptist`'s dispensation of water to repentance,
and also of the circumcision, and purifying,
and many other things used amongst that people.
When the converts were grown stronger in the faith and in the grace of God,
Peter told them, "`It is not the putting away the filth of the flesh,
but the answer of a good conscience towards God,
by the resurrection of Jesus Christ;`" and Paul,
although he did once in condescension circumcise Timothy,
yet told the people at another time,
that "`Neither circumcision nor uncircumcision availeth any thing,
but a new creature;`" and that if they were circumcised,
Christ would profit them nothing.
He also thanks God, he baptized no more than Crispus and Gaius,
and the household of Stephanas; besides these,
he knew not that he had baptized any other, for Christ sent him not to baptize,
but to preach the Gospel.
I said to the Friend, I am of the prophet`'s mind, when he said,
The elements should melt as with fervent heat;
if the Gospel power be not this fervent heat, I know not what is,
nor what is able to melt away the elements.
But I further said, if he was a Baptist,
he should deal plainly and honestly with Friends, and tell them what he was,
and not preach one thing, and keep such reserves to himself.

Friends admired, and said,
they had not the least thought of any such thing respecting him;
so he said he would not fall out with me.
I told him, I was as much for peace as he was,
but at the same time I would have us to mind that we were sound in the faith,
and preachers of the Gospel, and not go back again to the beggarly elements,
for what is all in comparison of the love of God in Christ Jesus?

I had good service and great satisfaction upon this island,
although I found Truth so low, that it might then be truly said as formerly,
By whom shall Jacob, or the true seed, arise, which is in our apprehension but small,
and much pressed down with many things that are hurtful, especially by the love of money,
pride, and forgetfulness of God?

I was invited on board a great transport ship, whereof one Reed was master,
who remembered me when I was but young, and was travelling to or near Scarborough;
he was loving to me, and several Friends who were with me,
and I had good service on board.

There was also on board a French Protestant,
now a captain of the English transport soldiers, bound for Jamaica.
He lodged at John Groves`', and was a very civil man, and said,
if I would go with Captain Reed, who offered, if I was going,
to carry me to Jamaica free, he would wait on me if I was sick, or ailed any thing;
and would gladly have had my company.
I acknowledged both their generosity and civility to me, and took leave of them,
and of the noble Captain Salter, who I have had occasion both to mention and to love.
He took his solid leave of me, wept like a child, and said openly in the hearing of many,
that he never loved a man so well before, and though he did not want business, yet,
for my sake, he would serve my friends what lay in his power; or nearly those words.

I find, as we live and walk in the Truth,
there is an inward witness which God hath placed in the hearts of men that is reachable,
except in such who have arrived to a great degree of hardness and insensibility,
and so have little sense or perception of good, either in themselves or in others,
which is a deplorable state.
Oh, what grief of heart it hath been to me, to hear and see the wickedness of some!
If such wickedness was as great a trouble to them who acted it, as it was to me,
I have thought they would soon grow weary of it.

I embarked on board a ship, John Griffith master, bound for Bristol, in Old England,
and went to sea with some East India ships that had put in at Barbados,
having a ship of war or two for their convoy.
After we were got to sea,
they had so much drinking and carousing that we grew weary of staying with them,
and after some consideration, the captain, who was a Friend, left them,
and came safe to England.

In our passage we had some rough weather near the tropic, which I mentioned before,
and the men and captain being much disordered with watching and hard labour,
as I remember, for eight and forty hours night and day, a calm ensuing,
the captain desired me to take his place for his watch, and mind the helmsman,
and see that he made straight steerage; but he was so sleepy,
that it was next to impossible to keep him awake.
I walked on the deck, and had overmuch work to mind the compass and the helmsman too,
for a fine breeze of wind came on, and all of a sudden a very unusual fear fell on me;
I looked into the sea, and beheld it appeared to turn blue,
and as far as I could discern to windward, I saw white caps, or the water-freckle;
on seeing which, through fear, more than any great skill,
I stamped with my foot as though I would have broke the deck.
Out came the captain,
but what with fear and sleep he could scarcely hit the door out of the cabin.
When he got upon the deck, he stamped, and called out all his hands,
and bid them lower and furl the sails with speed, or else we were all dead men,
for here is a hurricane just upon us.
No sooner was all made snug as well as could be, as the seamen phrase it,
but the wind blew so, that we thought it would have turned the bottom of the ship upward:
the like I never saw; and, as the captain said,
we had not one minute to spare of being cast away, according to all human probability.
As the seamen term it, it was such hurry-durry thick weather,
that we could scarcely see any thing a hundred yards.
It held for about an hour, in which time we drove by a vessel, and were so near her,
that I thought I could have flung a stone aboard.
Our ship`'s crew were sorely afraid, and looked upon her to be a robber;
her rudder was lashed or tied up, and the men were all gone off the deck,
but our mariners were so affrighted,
that they thought they would set some sail and follow us.
No sooner were we past this ship but the weather grew better,
and away we ran in hazard of bringing the masts by the board;
but through the Divine Providence of him who is Lord over all, both sea and land,
we escaped, and came safe into Cork in Ireland, where the master lived;
we rode there some time, and then weighed for Bristol,
intending for the Yearly Meeting there.

We had rough weather in crossing the channel, before we came into the Severn,
where our sailors, afraid of being pressed, launched the boat,
and ran away into Cornwall, leaving but four on board to bring the ship up the river.
We saw a pinnace, having in it a lieutenant with a crew of pressed men,
intending to press more if they could find them.
Our master called on me, desired I would put on my best clothes, and come to him,
which I did, and he set me on his right hand.
By this time the lieutenant came up and asked for my men, taking me for the master.
I told him, they had launched the long-boat and were gone, and we could not hinder them,
they being the strongest party; at which he appeared very much enraged,
and seemed as though he would have struck at me.
I told him calmly, he had more need to pity than be angry with us,
for if there should be a gale of wind,
we were in great danger of all perishing for want of hands.
I showed him what force we had, viz: James Bates, whom I did not then call my companion,
John Griffith captain, the cabin-boy and myself, who were all the men on board.
He asked, what for a man that was who sat beside me?
I told him, he was a man sufficiently secured against the press.
Then the rough man fell, and said, I looked like an honest man,
and he would take my word and not search for men.

I write not this as a thing I approved, but disliked; but being taken at unawares,
had not time to shun it, unless I had exposed my friend, the master of the ship;
although I neither said nor did, that I know of,
any thing worse than what thou seest here written; I told the captain,
I thought he was a great coward, and had exposed me to danger to save himself.

Wind and weather favoured us, and we came in due time to Bristol Yearly Meeting,
where I met with William Edmundson, and was truly glad to see him,
with many more at that place.
My companion falling sick, I was made willing to leave him,
and travelled to London with John Watson of Ireland, a sweet spirited man.
We got to London Yearly Meeting, where I discharged myself of what I had upon my mind,
and came away in peace, and in the feeling of the love of God.

John Haydock and I came from London together,
and had meetings in our way to York Yearly Meeting,
where I was glad to see my home-friends,
and to enjoy the love of God once more with them.
This is our principal crown and kingdom, in this world,
to enjoy the favourable countenance of the Lord,
and one another in his living and internal presence.
When I looked back upon all the mercies and deliverances
I had received from the mighty God of heaven and earth,
seas, and rivers of water, whose hand made all,
and whose eye and watchful providence attends all, and is over all,
my soul was filled with thanks and praises to the great
and most excellent name of Him who lives forever,
and hath helped my soul to overcome many strong temptations,
and hath borne up my head under many deep afflictions and tribulations;
renowned forever be his holy name.

I came home the 18th of the fourth month, 1703, and found my children well;
and now I was under a thoughtfulness how to walk and demean myself,
so that I might be preserved near the Lord, and in reverence and true fear before him;
that as I found there was something of holiness unto
the Lord engraven upon the fleshly table of my heart,
I might not lose the savour, relish and sensation of heavenly things,
now when I was not so particularly and immediately
concerned in the like daily travel on Truth`'s account.
Some will read me here,
in this short survey I have been taking of my thoughtfulness and present state,
that if I could not make it better, I might not make it worse,
either in doing or not doing any thing that would prove a hurt to me;
for a vessel had better be laid by, if it can be spared, than used to its hurt.
In this careful and watchful frame of mind,
I have found preservation from time to time to this day,
by retaining the salt of the kingdom in the soul or the inward man,
which is of a preserving quality, with which the vessel is,
and can only be kept fit for the Master`'s use; if we lose this,
the creature soon grows unfit for his use.
Read and consider these things in time, whilst thou hast the prize in thine hand,
and time to do, and receive good at the hand of Him who is truly full of good,
and is all good: to Him be the offerings of praise and renown now and forever.

Whilst I remained at home, as my usual manner was, I attended first-day, week-day,
Monthly, Quarterly, and other meetings, and visited many meetings in the country,
and had much satisfaction in being given up to the service of Truth.
I did not see it convenient, as my children were well placed, to settle to keep a family,
until my way appeared clear to marry, which now drew on,
and after I had been nearly seven years a widower, I married Anne Robinson,
who descended of a substantial family at Hutton-in-the-Hole, in the parish of Lestingham,
not far from Kirbymoorside, in Yorkshire.

We had not been married much above two years,
before my wife began to appear in the public work of the ministry,
very acceptably to Friends;
and she grew in understanding of the discipline of the church of Christ,
and also in further knowledge in the work of the living ministry.
About that time it came upon me to visit Friends
in most parts of the northern counties in England;
and a short time after my return,
I had a concern to visit Friends in several parts of the southern counties.
Thomas Beedal, being my companion, he grew in the Truth, and also in the ministry:
and we had many good meetings in that journey, good service and great satisfaction,
and I returned home in peace.

Now I may say with sorrow of heart,
the time drew on apace when my virtuous wife and I must part,
and be no longer meet-helps to one another, which we truly were,
and never had either evil word or evil thought against each other, I am fully satisfied;
but lived in peace and true love one with another,
and were glad when we could serve Truth and Friends: therefore I find it on my mind,
in this place, to insert the following relation concerning her, viz:

[.embedded-content-document.testimony]
--

She was descended of an honest and considerable family of the Robinsons,
and was convinced in her young years, and received the Truth in the love of it.
It became precious to her above all things in this world;
and through the blessed operation of the grace and Holy Spirit of God,
she was weaned from the world`'s pleasures, vanities and recreations,
and from taking any delight in them.
Through the virtuous and most precious blood of Christ,
she came to witness her heart sprinkled from an evil conscience,
and in a good degree made able to serve the living God.
She bore a faithful testimony against the needless
and superfluous dresses and fashions of the world,
as also against the corrupt language thereof.
She came to be a great lover of virtue and purity,
and had much satisfaction in being in Friends`' company, and at meetings,
and in retirement and waiting upon the Lord.
In great mercy and condescension to the desire of his handmaid,
he gave her a large share, not only of the enjoyment of his power and internal presence,
but also a knowledge and clear sight into those things
that appertain to life and salvation.

After Truth thus prevailed over her,
and brought every thought into the obedience of Christ,
and subjected her will to the will of God, which is a great work,
without which there is no regeneration; and without being born again,
there is no entering into the kingdom of heaven;
it was evident through the remaining part of her time,
that she was much preserved under the influence and
guidance of the meek and quiet spirit of Jesus Christ,
and grew daily more and more in the favour and love of God.
She was much beloved of God`'s people, and of her relations, neighbours and acquaintance,
who were not of her persuasion; and walked so wisely and prudently,
that she sought not her own honour and interest, but the honour of the Lord,
and peace with him, to which she had a regard in all her undertakings.
Even such who sought for an occasion against Truth and the professors of it,
had nothing to say against her, for she was generally beloved and spoken well of,
and many were sorrowfully affected to part with her, both Friends and others;
and not without cause.
For she was a woman of an upright life, and exemplary conversation,
and gave no offence to Jew or Gentile, nor to the church of Christ:
charitable to the poor, a true sympathizer with such as were in affliction and distress,
whether in body or in mind, which was manifested in her frequent visits to such,
and by other means.
She was endued with great patience, and with a quiet and serene mind,
well qualified and fitted to her husband`'s circumstances,
whose lot it was to be often abroad in the service of the Truth,
an honourable and a faithful wife,
willing to give up all for Christ and the Gospel`'s sake,
counting nothing in this world too near or dear to part with for the glory of God,
and advancement of the ever blessed Truth, the peace and salvation of her own soul,
and the good of others.

One thing I insert as follows, that others in the like case may not barely imitate her,
but feelingly come up in her heavenly practice and experience, under the influence,
light and help of God`'s holy and blessed spirit, viz:
When that worthy servant of Jesus Christ, John Bowstead,
returned from London Yearly Meeting to York, and so home with me,
not long before my wife was taken away; having some discourse with her,
he asked her about her husband being so much from home; and she gave him this answer,
that as she gave up her husband cheerfully and freely to serve the Lord,
and to be serviceable to the church of Christ,
she did not only sympathize and feel with him in his adverse and low state,
but partook with him in his enjoyments,
when the power of Truth prevailed over its enemies; although I am then far from him,
yet I partake of the spoil,
or the shedding abroad of the good things of God among his people,
as my heart goes along with the work of the Lord, and such as are engaged in it;
and in all my husband`'s afflictions I am afflicted with him:
and one of my main concerns is, that neither I, nor any thing in this world,
may detain my husband from doing what the Lord calls for at his hand;
for if any thing hurt him as to the Truth, what good can I expect of him?
This John much admired,
with the deep and weighty reasons she gave about the Christian discipline of the church,
and concerning the ministry.
She was a woman of few words, and expressed much in a little compass.

She was very clear in her understanding, had a penetrating and discerning eye,
a sense of the state of a meeting, as also of the several particular states in it.
She was an affectionate and tender mother to her children,
yet corrected them when occasion required, without passion,
or the least appearance of disorder of mind, and had them in great subjection;
at which I often admired, and thought, surely she is come,
by the workings of the Holy Spirit,
to a greater dominion over her own spirit than many who appeared to be her equals.
She was a true Christian, a loving and dutiful child to her parents, a good neighbour,
a faithful wife, tender-hearted toward her servants, and overcame them with love,
and was much beloved and feared by them;
and they were very unwilling to disoblige or offend her.

She behaved herself as became a sanctified vessel,
that was in a good degree fitted for the great Master`'s use,
and often appeared as one that had intercourse with Jesus Christ in spirit,
where his glory had shone in her soul,
not only because of the gravity of her countenance, but also the tenderness,
humility and sweetness of her spirit, weightiness of her conversation,
edification of her advice, and soundness of her judgment.
Her heart was often filled with the love of God,
and enabled to speak a word in season to states and conditions,
whether in her own family, amongst her neighbours, or in the church of Christ,
in testimony to matters relating to the worship of God, or to the discipline,
especially in the meetings of her own sex.
She had a great care upon her for the good education
of our youth in plainness of habit and language,
and that they might be preserved out of the corruptions of the world.
Her watchful and solid sitting in our meetings for worship was remarkable,
and her appearance in the ministry was with the wise,
and in the language of the Holy Spirit;
which was a clear demonstration that the work was the Lord`'s,
and by his Spirit and power;
which gave her a great place in the minds of faithful Friends and brethren.
But she is gone in the prime and flower of her age! which sets before us a memento,
to show us the uncertainty of our time here, and to prepare fur one certain to come,
that death may not overtake us at unawares, before we are prepared for it.

During the time of her long weakness, she was preserved in great patience,
steadiness and resignation to the will of God, even to the end.
She enjoyed much heavenly comfort and consolation to her immortal soul,
in the presence of the Lord, so that when she was asked,
whether she thought she might recover or not; she mildly replied,
she was afraid to desire to live;
because I believe if it please the Lord to take me away now, it will be well with me,
for I find nothing lies as a burden upon my spirit.
At another time she said, As to that little testimony I have been concerned in,
this is my comfort and satisfaction,
that I can truly say I did not kindle any strange fire,
and therefore could not warm myself at the sparks thereof:
but what I did in that matter was in the constrainings of the love of God;
and when my cup was full, I a little emptied myself among the Lord`'s people,
yet very sensible of my own weakness and poverty,
and often thought myself unworthy of the least of the Lord`'s mercies.

She spoke many savoury expressions that were not written then,
and therefore could not be remembered; having some hopes of her recovery,
it rather caused an omission; although she was heard to say not long before her sickness,
she thought her time would not be long in this world.
I never heard an unbecoming or unsavoury word come from her,
let the provocation thereto be what it would, no, not in the time of her health;
and in her weakness,
she was much swallowed up in the luminous and internal
presence of her Lord and Saviour Jesus Christ,
and often sang praises to his worthy name,
and appeared as one wholly redeemed from this world, whose heart was set upon,
and earnestly engaged in the pursuit after heaven and heavenly things.
Blessed be the Lord, she had witnessed a part in the first resurrection,
and over such the second death hath no power;
no doubt she lived and believed in Jesus Christ, even to the end of her time,
and passed away without any appearance of struggling or sorrow,
I believe into a mansion of glory,
where her soul shall sing hallelujah to the Lord God and the Lamb forever,
with all those who have overcome the world, the beast and false prophet,
and everything the Lord`'s controversy is with,
and who have not loved their lives unto death,
but given up that life they had in any wrong thing whatsoever.

She departed this life the 18th of twelfth month, 1711, aged about thirty-three years.

--

Not long after the departure of my wife,
it came upon me to visit the southern parts of England, and some parts of Wales,
and I had good service and great satisfaction; I was also at London,
John Adam being my companion, who was an innocent, clean spirited man.

Again, I found it required of me to visit the south-west parts of England,
in the year 1717, and I travelled through the west part of Yorkshire, into Westmoreland,
Lancashire, Cheshire, to Bristol, and as far as Cornwall, and had many good meetings;
although I travelled alone, yet the Lord in whom I put my trust and depended upon,
helped me, and bore up my head through and over all,
renowned be his most honourable name now and forever.
