== Chapter VI.

An Account of Hy Second visit to Friends in America.

Having had drawings in my mind for sometime,
once more to visit Friends in several parts of America, and as I believed it was my duty,
and what the Lord required me to give up to, I was resigned,
after some reasonings about my age, and declining as to outward strength,
concerning which I met with some inward conflicts and combatings,
which brought me very low for a time.
But the Lord helped me through these difficulties,
and caused his Truth to spring comfortably in my heart,
and I witnessed his heavenly presence at times to
refresh my soul in these exercises unknown to many.
The time being come for my preparing for the journey, on the 15th of the third month,
1731, I set forward from Hutton-in-the-Hole to Scarborough,
where I took shipping with George Widget, for London,
and came thither the first day of the Yearly Meeting,
with which I was very well satisfied,
and on the 25th day of the fourth month went on board of a vessel bound for Philadelphia,
in America, John Wilcox master, who was very civil and kind to me.

On the 27th of the said month we set sail, and had a good passage in the main,
excepting one very great storm, in which we were in danger of being lost;
our bowsprit was broken, and the masts were in danger of coming down,
yet we were preserved.
In about eleven weeks, being the 12th of the seventh month, I landed near Philadelphia,
to the great satisfaction of Friends as well as myself;
renowned be the great name of the Lord forever.

I have many times considered,
that although it was my place to leave my very near and dear friends,
children and relations, who were much concerned for me, and I for them,
yet I met with many tender-hearted Friends in my travels,
who were very near to me in the blessed Truth.
This does not fail those who trust in the Lord, and are faithful,
according to the ability and understanding which he gives to the children of men,
and are devoted to follow the guidance of his Holy Spirit, and willing to bear the cross,
burden, or yoke, which he sees good to lay upon his servants and handmaids.
I entreat all who are called to the Lord`'s great work,
to give up cheerfully and not grudgingly, and not to look back at what is behind,
so as to hasten or hinder themselves in that work they are called to,
lest they fall short of the penny or crown,
which the faithful will receive in the end of all their labour.

The Yearly Meeting at Philadelphia was nigh when we landed, which was large,
and a good meeting, many Friends from several parts being at it.
Here I met with Henry Frankland, and we were truly glad to see each other,
and went in company together southward towards Maryland, Virginia and North Carolina,
and returned to Pennsylvania; and in a short time after we parted: he came for England,
and I travelled for New England through the Jerseys, Long Island,
Rhode Island and Nantucket, having Richard Walne, of Pennsylvania, for my companion,
an innocent good man; we passed through all,
or the most part of the aforesaid provinces and islands, and had very large meetings,
and great attention there was in many to hear the testimony of Truth,
and an open door both of utterance, and in many places of entrance,
for what was delivered; yet not without opposition in some places.

I had some discourse with a Baptist, a justice of peace, in one of the Jerseys,
a man whom I truly loved; he told me, that some of his children went to our meetings,
and he did not hinder them: he appeared a tender-spirited man,
was of good repute in these parts where he lived, and very serviceable in his post.
What we had most in debate, was touching water-baptism.
I endeavoured to show him the use and end of all the shadowy things,
all which were ended in Christ the substance, or antitype;
and that such outward materials or elements pertained not to his kingdom,
or inward and spiritual administration;
nor could they take away the root or cause of sin,
which is only effected by the Holy Ghost and fire,
to the cleansing and purifying the hearts of the children of men,
as is the nature of material fire to cleanse what it is properly applied unto.

I met with the same justice afterwards at Burlington, in West Jersey,
he was glad to see me, and so was I to see him, for he was very loving and friendly.
I likewise met with a man who was a school-master upon Long Island,
that appeared offended at something I had said in a meeting where he had been,
and he followed me to a Friend`'s house,
and appeared so full of Scriptures in vindication, as he thought, of water-baptism,
that what with his reading many passages in the Scriptures, and paraphrasing upon them,
he would not hear me for some time.
But when he was quiet, I said to him, Thou hast not treated me like a fair disputant,
to run on so long and not to give me time to make my objections;
if thou hadst pitched upon any particular Scripture,
and given me liberty to have answered, it would have been civil and reasonable.
He owned, he had not done fairly by me;
but I desired to know what church he pretended to belong to?
He answered to the Episcopal church.
I then requested he would answer me one question
before we entered into any farther debate,
and he promised he would if he understood it.

I told him, I heard he was a scholar, and no doubt understood how to answer it,
if he did but consider the matter; the query was this,
Whether the sprinkling a little water in a child`'s face would bear the name baptism,
yea or nay?
He said it would not.
I answered, thou hast made a great noise about little or nothing;
for by thy own confession thy church has no baptism at all,
for I know not of any other way they use but sprinkling.
He would not enter into any farther discourse about it,
but made use of the words of Gamaliel,
in favour of the work the apostles were concerned in, saying,
If this work be of God it could not be overthrown,
but if it was of man it would come to naught.
I told him, I was of his mind; and the Lord hath supported me in this and the like work,
now between forty and fifty years, and if I continued faithful,
I had no doubt at all in my mind, but he would support and stand by me to the end.
And when we parted, he said, The Lord of heaven and earth bless you,
for I believe you are an honest man.

By this we may see, that Truth sometimes comes over men,
the witness which God hath placed in men is reached,
and Truth prevails many times beyond our expectation;
therefore it is good to keep to the guidance of the Spirit of Truth,
for it is a blessed remembrancer, instructor,
and true comforter to all such as truly depend upon Him,
who sent the Spirit of Truth into the hearts of the children of men,
to guide them into all the necessary truths which we are to know and practise,
and consequently out of all untruth.

When we had gone through this island, and visited Friends there, and in Rhode Island,
and had some meetings in our way, we went to Nantucket,
where we met with many innocent plain Friends; also on Rhode Island,
and in many places in these parts of the country, we found great openness; in Boston,
beyond expectation, and there was some convincement in that town.
We travelled to Dover, and visited Friends thereabout,
which are the most remote parts inhabited by Friends in that quarter of New England.
Here I met with a Presbyterian priest;
what his design was in coming to the Friend`'s house I know not,
but thought it was to speak with me, for he soon began to ask me questions; first,
whether I was not brought up a scholar,
and had been in some of the colleges where I had my education?
Also, whether I had not put on the canonical gown,
and preached according to the manner of the church of England?
I replied, I had not received my education in any college,
neither ever put on the canonical gown,
nor preached after the manner of the church of England.
He told me, I had been so represented to him: and said,
he supposed I had been at some schools.
I told him, I had been at several to learn when I was young;
but I did not know that I had given occasion at any time, by what I had said,
for any man to judge me to be a scholar.
He understood I came from Old England, and asked several questions,
as whether our Friends increased or decreased: I answered, I could not positively tell;
I thought there was no great alteration in my time as to number,
for their decrease in one part of the nation might be made up by their increase in another.
He asked, how the Episcopal ministers dealt with us about their tithes;
My answer was thus: As to that part called the Prsedial tithes,
they commonly either gather them themselves or family, or let them to tenants,
who take care to fetch them away before us,
knowing that we cannot be free to leave them on the ground, as hay and corn, etc.
And as to small tithes, there is an act of parliament,
called An Act for the more easy recovery of small tithes,^
footnote:[The 7th and 8th of William III, chap. 6. is the
Act for recovery of small tithes or offerings,
etc. not amounting to above the yearly value of forty shillings,
which is common for all people, the cost not exceeding ten shillings,
before two or more justices of the peace, not to go back above two years.
The 7th and 8th of William III, chap. 34, which is our Affirmation Act,
is the act for the recovery of tithes and church rates,
for any sum not exceeding ten pounds from Quakers only,
before two justices of the peace, without any limitation of time.
And by the Statute of the 1st of George I., chap. 6. sect. 2.,
limited to ten shillings cost. See the Statutes at large.]
for any sum not exceeding forty shillings, and ten shillings cost;
which is by justices`' warrants.
This is mostly thought to be intended to prevent their procedure by Exchequer process,
through which great havoc and spoil has been made of Friends`' goods,
and sometimes their bodies cast into prison, where some have lain a long time.
He asked, how our Friends did in Scotland, if they increased there?
I told him, I heard that they did not increase,
but some of the Presbyterians in Scotland were kind
to our Friends and would come to our meetings,
especially if strangers were at them.

I also told him,
that persecution in our part of the world was become hateful amongst sober people.
He said, it was very well; and likewise mentioned, that we were refined,
and not the people we had been.
I asked him, wherein he thought we were refined?
He answered, in our principles.
I desired him to name one: and he said, George Fox denied the resurrection of the dead.
I told him, George Fox did own a resurrection according to Scripture, as we do;
but because he and our Friends thought it not safe to recede from plain Scripture,
nor to comply with the way many people have of expressing it,
which we think to be too gross and carnal, viz: that the same body shall rise,
therefore they have asserted we deny the resurrection.
The apostle saith, "`That which thou sowest, thou sowest not that body that shall be,
for it is sown in corruption, raised in incorruption, sown a natural,
raised a spiritual body;`" with much more that might be added:
and how much such a change maketh a difference between
the present and the future in the resurrection,
between the natural and spiritual, corruption and incorruption,
I know not of any finite creature that is able truly to determine;
and therefore I think it is not consistent with charity, nor true wisdom,
to differ about such things which exceed our comprehension.
He allowed it to be better to let them alone.

We parted very friendly, and Friends were glad of the opportunity,
he having the character of being a great scholar and a wise man;
but from all that passed, they believed he gained no advantage; however he behaved well.
Before we parted, I told him,
I thought the greatest reason why some think us refined was this;
formerly people were so prejudiced, that whatever was printed or said against us,
our principles, practice or doctrines, was generally received and believed,
though covered with such dresses as to render us more odious,
and were by many taken for the standard of our belief and practice.
Of late the light hath more appeared, many are grown better disposed towards us,
and like wise men, not willing to be imposed upon,
have searched for themselves into the state of the controversy between us and our opposers.
Our writings, upon perusal,
appearing so clear and different from what the books
of those who opposed us charged upon us,
caused many who read them with a good design and willingness to be set right, to say,
we were reformed, and not the people we had been.
The priest said, he thought there might be much owing to that.
I told him, it was undeniable,
that there must be a great difference between our principles,
doctrines and conversations, truly stated and set forth in their proper light,
and when they were misrepresented,
sometimes with all the art and implacable malice that men were capable of:
and this has been the way our adversaries have treated us,
almost in everything we have believed, said, or written;
although it was very agreeable to the Holy Scriptures of the Old and New Testament.

We returned back to Salem, Lynn and Boston, and visited Friends in our way,
and at Rhode Island, Long Island and New York; and had many good meetings and some large,
in the Jerseys,
where I had some discourse with a justice of the peace about water baptism,
but he did not hold it long before he gave up.
I had another at Allentown with a Presbyterian, which held for some hours,
about water baptism, and concerning election and reprobation.
He soon gave up the first; but when he began upon election and reprobation,
I said I thought it was the most pernicious doctrine that was ever broached in the world,
it so opposed the very nature of God, and his design of creating man, whom,
with all his other works, he pronounced good and blessed; and that man,
as the crown and glory of all his works which he had created,
should be designed for the most miserable end, was unaccountable.
I urged many Scriptures against that doctrine,
as also the confusion they were in about it,
as in their Westminster Confession of Faith they say,
"`The decree is so certain and definite,
that one cannot be added to the number of the elect,
or diminished from the number of the reprobate,`" and yet you tell us,
that God has ordained the means to effect his ends.
I then said, this supposition of a decree for the means, as well as the end,
seems intended to make the priests and their service necessary;
but yet if they cannot alter the decree,
what benefit or advantage can there be to men by their services or performance?
I hope none will think that it is a service to mankind,
to strengthen or confirm the decree, if it were in their power to do it,
which I am satisfied it is not; because no such decree was made, or is in being,
the opposite appearing by plain Scripture, which he owned when I urged it, to wit,
that the fall of Adam did affect all; and upon the parity of reason,
the coming of Christ did reach as far; because, as in Adam all die,
so in Christ shall all be made alive; he tasted death for every man,
was a propitiation for the sins of all;
and where then wilt thou find a people that is not included?
But if thou canst find in, and prove by plain Scripture,
that there is such a people not included in these general assertions,
that Christ came to save, show me who they are.
These and much more I urged against that doctrine,
and he with many others appeared much satisfied, and we parted friendly.
He came next day several miles to a meeting which I had appointed;
the man was counted a wise and sober man, and was under some convincement,
and behaved well.

From thence we went to Pennsylvania, and had many good meetings in that province,
and being clear and willing to return,
I took leave of Friends in a loving and tender frame of spirit,
and embarked on board a ship, whereof Samuel Flower was master,
the 1st of the third month, 1733, at Philadelphia,
and arrived at Bristol the 18th of the fourth month following,
and was glad we got safe to England, having been seven weeks in our passage.
I got home on the 6th of the sixth month, and was truly thankful to the Lord,
who had preserved me in these long travels and labours of love,
through many difficulties;
but the Lord`'s power is sufficient to bear up and carry through all;
renowned be his worthy name over all, now and forever.
Amen.

A remarkable deliverance which happened to me, being omitted in its proper place,
I think fit to insert here, which was as follows:

In the year 1718, and the twelfth month,
when John Dodgson was visiting Friends in our parts, he lodged with me,
and I went with him and his brother-in-law, Peter Buck, to be their guide to Whitby.
I stayed their first-day`'s meeting, and second-day`'s Preparative Meeting;
and on the third-day went on with Friends towards Scarborough,
to have the better road home,
there having fallen a great deal of snow while we were at Whitby,
so that it was looked upon impracticable for me to return the same way home that I came,
it being a moorish bad way.
In our way back, within a mile or little more from Scarborough, we came to a brook,
which by reason of the excessive rain and snow was higher than ever I had seen it,
so that when we came to ride through it, Henry Levins, our guide, first adventured in,
being mounted upon a very strong large horse, and got over with some difficulty,
and I followed him; but when I came about the middle of the fording place,
it took my mare off her feet, and something being in the way,
it turned her upon her broadside,
so that I was dismounted and carried away by the rapidity of the stream.
There being a footbridge a little below, about knee-deep under water,
and no rail either to be a guide or to lay a hand on,
and the water reduced to a narrow compass, hurried me violently along,
and drove me with my breast against the bridge with such force,
that it very nearly knocked the breath out of me.
Before I touched the bridge I happened to hold up my hand,
and John Dodgson seeing the danger I was in, jumped off his horse, and ran at a venture,
seeing the water ripple, to hit the bridge, and just caught hold of my fingers,
and held my head above water, until Henry Levins, who had got over,
came to his assistance.

By the weight of the water in my boot tops, they being large,
and a nail in the timber under the bridge, catching hold of my great coat,
which held me fast, it was impossible for one man to free me,
and not without some difficulty for them both to get me out,
the nail holding so fast that it tore out a great piece of my coat, lining and all.
Upon Henry`'s dismounting, his horse ran away to Scarborough,
and mine swam back to the company, and when they had got me out,
Henry ran on foot to gel his horse,
and found him at the stable door where he used to stand,
and in the mean time John Dodgson kept me in motion by dragging me along,
having very little and sometimes no hopes of my recovery.
When the horse returned, they got me back to Scarborough, but I was not sensible how,
and they had me to Dorothy Jaques`' house.
When there, they could perceive my lips move, but could not hear what I said,
until one laid an ear close to my mouth, and so understood that I said,
if they gave me any thing that was strong, it would carry me off;
which made them very cautious: however, they stripped me, changed my shirt,
put me into a warm bed, and applied warm flannel to my feet for three hours together,
which I knew nothing of, being then altogether senseless.

Isaac Skelton, who had been my companion in the service of the Truth,
through several counties, hearing of this accident,
came immediately and got into bed to me, and kept me close in his bosom,
which many thought was a great means to preserve my life.
John Dodgson, though he intended for the Monthly Meeting,
expressed so great a concern for me, that he said,
he would either see me in a way of recovery or die, before he left me.
It pleased the Lord, of his infinite mercy, so wonderfully to raise me up again,
as to enable me to be at the meeting next day, and also to bear some testimony,
which was very acceptable and comfortable to Friends,
as it was also beyond their expectation to see me there;
but yet I was much troubled with pain,
the fleshy part of my shoulder being rent by the violent hauling me out of the water.

In gratitude,
my soul can do no less than praise and magnify the Lord for this great deliverance,
and all his other mercies, who alone is worthy.
And I cannot but take notice of Friends`' kindness and good will to me,
in doing whatsoever they could for me, but more especially my worthy friend John Dodgson,
who hazarded his life to save mine.
