== Testimonies of John Richardson

[.chapter-subtitle--blurb]
The Testimony of Friends belonging to Gisbrough Monthly Meeting,
concerning our worthy friend John Richardson,
who departed this life near Hutton-in-the-Hole, the 2nd of the Fourth month, 1753,
in the eighty-seventh year of his age,
and was buried in Friends`' burying-ground at Kirby-moorside.

As many of our elders are removed,
and but few left who had personal knowledge of '`this Friend
in his younger years and early part of his service,
we cannot give so full an account thereof as otherwise might have been done.

By accounts transmitted to us, we have cause to believe he was much devoted,
and given up to walk in the way of his duty,
and therein was of great service to the churches where his lot was cast;
and an instrument in the Divine hand in turning many to righteousness.

As to the latter part of his life, we have this testimony to give of him;
that he was a lover of discipline and good order in the church,
diligent in attending meetings for worship and Truth`'s service, whilst of ability;
a good example therein, by sitting in a still and unaffected manner in silence,
and when raised up to bear a public testimony, was comfortable and acceptable to Friends.

And when his natural faculties were somewhat impaired,
and he confined at home through old age and infirmities,
he appeared more and more heavenly-minded, and seemed to grow in the life of religion,
that we hope he is now at rest in the fruition of that happiness,
prepared for such as hold on to the end in well-doing.

[.small-break]
'''

Signed on behalf of the said meeting, held at Castleton, on the 22nd of the third month,
1754.

[.blurb]
=== The Testimony of Friends from the Quarterly Meeting held at York.

On reading the testimony given from the Monthly Meeting of Gisbrough,
concerning our late ancient and worthy friend John Richardson, deceased,
of which we approve, we find ourselves under an engagement to add this short testimony;
from certain experience of the service he had amongst us in a fresh and lively ministry,
and in exercising the discipline of the church in a Gospel spirit,
whereby many received comfort and edification;
some of us having knowledge of him from his early appearance in the ministry,
remember that he was acceptable to Friends, being sound in doctrine,
reaching the witness of God in those to whom he ministered.
He was a diligent and faithful labourer,
travelling several times through most parts of this nation,
and visited Friends meetings in Scotland and Ireland,
also twice the English plantations in America, leaving many seals of his ministry,
having had the approbation and unity of Friends with his service both at home and abroad.
He was a tender nursing father, in the church, over the youth whom God had visited,
to encourage and strengthen the newly convinced, to whom also he was a good example;
and though of a sweet and courteous disposition, yet careful in the spirit of wisdom,
to caution and guard such against the deceitful workings
and false representations of the spirit of error.
To divers of us who visited him towards the close of his time,
he appeared in a heavenly frame of mind, to our great comfort,
evidencing a preparation for that eternal bliss whereinto, we doubt not, he is entered,
and now reaps the fruits of his labours.

[.small-break]
'''

Signed in and on behalf of our Quarterly Meeting, held at York,
the 27th and 28th of the third month, 1754.
